Repository rabbitmq/rabbitmq-server, pull requests merged in 2020-04, with the labels that each got.

#2301 Ensure randomized_startup_delay_range custom value is used
  src/rabbit_peer_discovery.erl
  test/peer_discovery_classic_config_SUITE.erl
Labels: bug, effort-low

#2311 Add docs for check_if_node_is_mirror_sync_critical and check_if_node_…
  docs/rabbitmq-diagnostics.8
  docs/rabbitmq-queues.8
Labels: doc, effort-tiny, enhancement

#2316 Fix schema sync for parameters
  src/rabbit_definitions.erl
Labels: bug, effort-low

#2277 Always handle config files with Cuttlefish
  apps/rabbitmq_prelaunch/src/rabbit_prelaunch_conf.erl
  src/rabbit_config.erl
Labels: enhancement
