Repository rabbitmq/rabbitmq-server, pull requests merged in 2021-12, with the labels that each got.

#3804 QQ: remove decoded properties before storing messages
  deps/rabbit/src/rabbit_quorum_queue.erl
Labels: backport-v3.9.x

#3820 Remove flaky assertion
  deps/rabbit/test/quorum_queue_SUITE.erl
Labels: backport-v3.9.x

#3822 Initial 3.9.11 release notes
  release-notes/3.9.10.md
  release-notes/3.9.11.md
Labels: backport-v3.9.x

#3825 Match help box to correct item
  deps/rabbitmq_management/priv/www/js/tmpl/policies.ejs
Labels: backport-v3.9.x, backport-v3.8.x

#3835 Extend log.file.rotation.date parser
  deps/rabbit/apps/rabbitmq_prelaunch/src/rabbit_logger_std_h.erl
  deps/rabbit/apps/rabbitmq_prelaunch/test/rabbit_logger_std_h_SUITE.erl
Labels: backport-v3.9.x

#3838 Add compress option for file rotation
  deps/rabbit/priv/schema/rabbit.schema
  deps/rabbit/src/rabbit_prelaunch_logging.erl
Labels: backport-v3.9.x

#3861 Adopt latest rabbitmq-server-buildenv:linux-erlang-23.3 for RBE
  WORKSPACE.bazel
Labels: bazel, backport-v3.9.x, backport-v3.8.x

#3862 Adopt latest rabbitmq-server-buildenv:linux-erlang-24.1 for RBE
  WORKSPACE.bazel
Labels: bazel, backport-v3.9.x, backport-v3.8.x

#3879 Return appropriate response when stream leader not available
  deps/rabbitmq_stream/src/rabbit_stream_manager.erl
  deps/rabbitmq_stream/src/rabbit_stream_reader.erl
  deps/rabbitmq_stream/test/rabbit_stream_SUITE_data/pom.xml
  deps/rabbitmq_stream/test/rabbit_stream_SUITE_data/src/test/java/com/rabbitmq/stream/ClusterSizeTest.java
  deps/rabbitmq_stream/test/rabbit_stream_SUITE_data/src/test/java/com/rabbitmq/stream/FailureTest.java
  deps/rabbitmq_stream/test/rabbit_stream_SUITE_data/src/test/java/com/rabbitmq/stream/LeaderLocatorTest.java
  deps/rabbitmq_stream/test/rabbit_stream_SUITE_data/src/test/java/com/rabbitmq/stream/TestUtils.java
  deps/rabbitmq_stream/test/rabbit_stream_manager_SUITE.erl
  deps/rabbitmq_stream_management/test/http_SUITE_data/pom.xml
Labels: backport-v3.9.x

#3894 Optimise user declare/update/import by reducing the number of operations
  deps/rabbit/src/rabbit_auth_backend_internal.erl
Labels: backport-v3.9.x, backport-v3.8.x

#3908 Stream coordinator: avoid mnesia update process crashing after delete
  deps/rabbit/src/rabbit_stream_coordinator.erl
Labels: backport-v3.9.x

#3905 Make health checks less resource intensive
  deps/rabbit/src/rabbit_health_check.erl
Labels: backport-v3.9.x, backport-v3.8.x

#3907 Fix log level when halting the VM
  deps/rabbit/src/rabbit.erl
Labels: backport-v3.9.x, backport-v3.8.x

#3906 Fix win32 memory leak by using `raw` file operations
  deps/rabbit/src/rabbit_file.erl
Labels: backport-v3.9.x, backport-v3.8.x

#3887 OAuth 2 plugin improvements
  deps/rabbitmq_auth_backend_oauth2/README.md
  deps/rabbitmq_auth_backend_oauth2/priv/schema/rabbitmq_auth_backend_oauth2.schema
  deps/rabbitmq_auth_backend_oauth2/src/uaa_jwks.erl
  deps/rabbitmq_auth_backend_oauth2/src/uaa_jwt.erl
  deps/rabbitmq_auth_backend_oauth2/src/uaa_jwt_jwt.erl
  deps/rabbitmq_auth_backend_oauth2/test/config_schema_SUITE_data/rabbitmq_auth_backend_oauth2.snippets
  deps/rabbitmq_auth_backend_oauth2/test/jwks_SUITE.erl
  deps/rabbitmq_auth_backend_oauth2/test/jwks_http_app.erl
  deps/rabbitmq_auth_backend_oauth2/test/rabbit_auth_backend_oauth2_test_util.erl
Labels: backport-v3.9.x

#3903 Wrap authentication calls in try catch to avoid leaking error
  deps/rabbit/src/rabbit_access_control.erl
Labels: backport-v3.9.x

#3930 Import definitions: support user limits
  deps/rabbit/src/rabbit_auth_backend_internal.erl
  deps/rabbit/src/rabbit_osiris_metrics.erl
  deps/rabbit/test/definition_import_SUITE.erl
  deps/rabbit/test/definition_import_SUITE_data/case18.json
  deps/rabbit/test/definition_import_SUITE_data/failing_case19.json
Labels: backport-v3.9.x
