Repository rabbitmq/rabbitmq-server, pull requests merged in 2021-11, with the labels that each got.

#3553 Use inter-node TLS conf to enable Osiris TLS replication
  deps/rabbit/apps/rabbitmq_prelaunch/BUILD.bazel
  deps/rabbit/apps/rabbitmq_prelaunch/src/rabbit_prelaunch_conf.erl
Labels: bazel

#3633 Use hex values in RabbitMQ Streams protocol description
  deps/rabbitmq_stream/docs/PROTOCOL.adoc
Labels: backport-v3.9.x

#3636 Adopt otp 24.1.4 for OCI workflow
  packaging/docker-image/otp-versions/otp-max.yaml
Labels: backport-v3.9.x, backport-v3.8.x

#3635 Introduce a target cluster size hint setting
  deps/rabbit/priv/schema/rabbit.schema
  deps/rabbit/src/rabbit_nodes.erl
  deps/rabbit/test/config_schema_SUITE_data/rabbit.snippets
Labels: backport-v3.9.x, backport-v3.8.x

#3631 Use erlang:system_info(creation) as GUID
  deps/rabbit/src/rabbit_amqqueue.erl
  deps/rabbit/src/rabbit_node_monitor.erl
Labels: backport-v3.9.x, backport-v3.8.x

#3643 Turn down logging from queue rebalancing
  deps/rabbit/src/rabbit_amqqueue.erl
Labels: backport-v3.9.x, backport-v3.8.x

#3646 Adopt latest bazel-erlang
  WORKSPACE.bazel
Labels: bazel

#3647 Comment-out code_reload
  erlang_ls.config
Labels: backport-v3.9.x

#3649 Tweak more erlang_ls settings
  erlang_ls.config
Labels: backport-v3.9.x

#3615 rabbit_msg_store: Accept duplicate writes from the same queue
  deps/rabbit/src/rabbit_msg_store.erl
Labels: backport-v3.9.x

#3652 Adopt latest bazel-erlang
  WORKSPACE.bazel
Labels: bazel

#3653 Remove pacemaker OCF RA agent for RabbitMQ
  scripts/rabbitmq-server-ha.ocf
Labels: backport-v3.9.x, backport-v3.8.x

#3658 Update link in comment
  deps/rabbitmq_auth_backend_ldap/src/rabbit_auth_backend_ldap_app.erl
  deps/rabbitmq_auth_mechanism_ssl/src/rabbit_auth_mechanism_ssl_app.erl
  deps/rabbitmq_federation/src/rabbit_federation_app.erl
  deps/rabbitmq_web_mqtt/src/rabbit_web_mqtt_app.erl
  deps/rabbitmq_web_mqtt_examples/src/rabbit_web_mqtt_examples_app.erl
  deps/rabbitmq_web_stomp_examples/src/rabbit_web_stomp_examples_app.erl
Labels: backport-v3.9.x

#3657 Adopt the new buildbuddy remote execution url
  .bazelrc
  .github/workflows/perform-bazel-execution-comparison.yaml
  .github/workflows/rabbitmq_peer_discovery_aws.yaml
  .github/workflows/test-erlang-git.yaml
  .github/workflows/test-mixed-versions.yaml
  .github/workflows/test.yaml
Labels: backport-v3.9.x, backport-v3.8.x

#3667 Increase some buildbuddy rbe timeouts
  .bazelrc
Labels: backport-v3.9.x, backport-v3.8.x

#3628 QQ: stability and channel side improvements
  deps/rabbit/src/rabbit_amqqueue.erl
  deps/rabbit/src/rabbit_channel.erl
  deps/rabbit/src/rabbit_fifo_client.erl
  deps/rabbit/src/rabbit_queue_type.erl
  deps/rabbit/src/rabbit_quorum_queue.erl
  deps/rabbit/test/quorum_queue_SUITE.erl
Labels: make, backport-v3.9.x

#3672 Ra v2.0.2
  deps/rabbitmq_stream/BUILD.bazel
  deps/rabbitmq_stream/test/rabbit_stream_SUITE.erl
  rabbitmq-components.mk
  workspace_helpers.bzl
Labels: bazel, make

#3673 update osiris to 1.2.3
  BUILD.osiris
  deps/rabbit/Makefile
  workspace_helpers.bzl
Labels: bazel, make

#3677 3.9.9 release notes
  release-notes/3.9.9.md
Labels: backport-v3.9.x

#3680 Grammar
  deps/rabbit_common/src/rabbit_nodes_common.erl
Labels: backport-v3.9.x, backport-v3.8.x

#3689 Use a for loop here because IE 11 does not support lambdas
  deps/rabbitmq_management/priv/www/js/dispatcher.js
Labels: backport-v3.9.x, backport-v3.8.x

#3587 Pre-render prometheus labels
  deps/rabbitmq_prometheus/src/collectors/prometheus_rabbitmq_core_metrics_collector.erl
  rabbitmq-components.mk
  workspace_helpers.bzl
Labels: bazel, make, backport-v3.9.x, backport-v3.8.x

#3552 Improve consuming from a stream using AMQP 1.0
  deps/amqp10_client/src/amqp10_client_connection.erl
  deps/amqp10_client/src/amqp10_client_session.erl
  deps/rabbitmq_amqp1_0/src/rabbit_amqp1_0_message.erl
  deps/rabbitmq_amqp1_0/src/rabbit_amqp1_0_outgoing_link.erl
  deps/rabbitmq_amqp1_0/src/rabbit_amqp1_0_session_process.erl
  deps/rabbitmq_amqp1_0/test/system_SUITE.erl
  deps/rabbitmq_amqp1_0/test/system_SUITE_data/fsharp-tests/Program.fs
Labels: rabbitmq-amqp1.0

#3700 Add --remote_download_toplevel to the bazel config
  .bazelrc
Labels: backport-v3.9.x, backport-v3.8.x

#3699 Adopt otp 24.1.5 for OCI workflow
  packaging/docker-image/otp-versions/otp-max.yaml
Labels: backport-v3.9.x, backport-v3.8.x

#3676 Avoid slow mnesia transaction on QQ init
  deps/rabbit/src/rabbit_amqqueue.erl
  deps/rabbit/src/rabbit_quorum_queue.erl
Labels: make, backport-v3.9.x

#3656 Expose pending enqueues in quorum queue overview
  deps/rabbit/src/rabbit_fifo.erl
  deps/rabbit/src/rabbit_fifo_client.erl
Labels: backport-v3.9.x

#3710 Generate the rabbitmqadmin cli under bazel
  deps/rabbitmq_management/BUILD.bazel
  rabbitmq.bzl
Labels: bazel, backport-v3.9.x, backport-v3.8.x

#3683 Use externailzed rbe config in bazel
  .bazelrc
  .github/workflows/perform-bazel-execution-comparison.yaml
  .github/workflows/rabbitmq_peer_discovery_aws.yaml
  .github/workflows/test-erlang-git.yaml
  .github/workflows/test-mixed-versions.yaml
  .github/workflows/test.yaml
  BUILD.bazel
  WORKSPACE.bazel
Labels: bazel, backport-v3.9.x, backport-v3.8.x

#3716 Stream coordinator: reset reply_to for delete_stream command
  deps/rabbit/src/rabbit_stream_coordinator.erl
Labels: backport-v3.9.x

#3714 Prevent crash logs when mqtt user is missing permissions
  deps/rabbitmq_mqtt/src/rabbit_mqtt_processor.erl
  deps/rabbitmq_mqtt/test/auth_SUITE.erl
Labels: backport-v3.9.x

#3723 Fix description of "deliver" command in RabbitMQ Streams protocol documentation
  deps/rabbitmq_stream/docs/PROTOCOL.adoc
Labels: backport-v3.9.x

#3722 Use externailzed rbe config in bazel
  .bazelrc
  .github/workflows/perform-bazel-execution-comparison.yaml
  .github/workflows/rabbitmq_peer_discovery_aws.yaml
  .github/workflows/test-erlang-git.yaml
  .github/workflows/update-rbe-images.yaml
  BUILD.bazel
  WORKSPACE.bazel
  user-template.bazelrc
Labels: bazel, backport-v3.9.x, backport-v3.8.x

#3735 Use --remote_download_minimal and Actions Cache
  .bazelrc
  .github/workflows/rabbitmq_peer_discovery_aws.yaml
  .github/workflows/test-erlang-git.yaml
  .github/workflows/test-mixed-versions.yaml
  .github/workflows/test.yaml
Labels: backport-v3.9.x, backport-v3.8.x

#3731 Stream coordinator: only update amqqueue record if stream id matches
  deps/rabbit/src/rabbit_stream_coordinator.erl
  deps/rabbit/src/rabbit_stream_queue.erl
  deps/rabbit/test/rabbit_stream_queue_SUITE.erl
Labels: backport-v3.9.x

#3738 Fixup the "Failed to symlink private_log directory." error in bazel
  deps/rabbitmq_ct_helpers/src/rabbit_ct_helpers.erl
Labels: backport-v3.9.x, backport-v3.8.x

#3740 Distribution listener settings support in rabbitmq.conf
  deps/rabbit/priv/schema/rabbit.schema
  deps/rabbit/test/config_schema_SUITE_data/rabbit.snippets
Labels: backport-v3.9.x

#3759 Fix rabbitmq.conf translation rule for OAuth2 signing keys
  deps/rabbitmq_auth_backend_oauth2/priv/schema/rabbitmq_auth_backend_oauth2.schema
  deps/rabbitmq_auth_backend_oauth2/test/config_schema_SUITE_data/rabbitmq_auth_backend_oauth2.snippets
Labels: backport-v3.9.x, backport-v3.8.x

#3752 Stream flake fixes
  deps/rabbit/src/rabbit_stream_coordinator.erl
Labels: backport-v3.9.x

#3755 Adopt latest bazel-erlang
  WORKSPACE.bazel
Labels: bazel

#3764 Use bazel-erlang 1.4.0
  BAZEL.md
  WORKSPACE.bazel
  deps/rabbitmq_cli/rabbitmqctl.bzl
  deps/rabbitmq_ct_helpers/BUILD.bazel
  deps/rabbitmq_ct_helpers/src/rabbit_ct_helpers.erl
  deps/rabbitmq_ct_helpers/tools/tls-certs/BUILD.bazel
  deps/rabbitmq_stomp/BUILD.bazel
  deps/rabbitmq_web_dispatch/BUILD.bazel
  deps/rabbitmq_web_dispatch/test/rabbit_web_dispatch_SUITE.erl
  deps/rabbitmq_web_mqtt/BUILD.bazel
  rabbitmq.bzl
Labels: bazel, backport-v3.8.x

#3763 Add the bazel target :package-generic-unix
  BUILD.bazel
  WORKSPACE.bazel
  deps/rabbit/BUILD.bazel
  deps/rabbitmq_web_dispatch/BUILD.bazel
  dist.bzl
  rabbitmq.bzl
  rabbitmq_home.bzl
Labels: bazel, backport-v3.9.x, backport-v3.8.x

#3733 Adopt latest rabbitmq-server-buildenv:linux-erlang-23.3 for RBE
  WORKSPACE.bazel
Labels: bazel, backport-v3.9.x, backport-v3.8.x

#3734 Adopt latest rabbitmq-server-buildenv:linux-erlang-24.1 for RBE
  WORKSPACE.bazel
Labels: bazel, backport-v3.9.x, backport-v3.8.x

#3770 Add systemd hardening parameters in rabbitmq-server.service.example
  deps/rabbit/docs/rabbitmq-server.service.example
Labels: backport-v3.9.x

#3779 Add optional metrics for vhost and exchange count
  deps/rabbitmq_prometheus/metrics-detailed.md
  deps/rabbitmq_prometheus/src/collectors/prometheus_rabbitmq_core_metrics_collector.erl
  deps/rabbitmq_prometheus/test/rabbit_prometheus_http_SUITE.erl
Labels: backport-v3.9.x

#3798 Link to most recent description of Osiris chunk format
  deps/rabbitmq_stream/docs/PROTOCOL.adoc
Labels: backport-v3.9.x

#3746 Fix case where quorum queue consumer is cancelled while message is about to be delivered
  deps/rabbit/src/rabbit_fifo_client.erl
  deps/rabbit/test/quorum_queue_SUITE.erl
Labels: backport-v3.9.x

#3800 To stop collect_statistics when rabbitmq_management_agent has been disabled
  deps/rabbitmq_management_agent/src/rabbit_mgmt_db_handler.erl
Labels: backport-v3.9.x

#3781 Adopt latest bazel-erlang
  WORKSPACE.bazel
Labels: bazel

#3806 tcp_listener: avoid logging listener arguments on shutdown
  deps/rabbit/src/tcp_listener.erl
Labels: backport-v3.9.x

#3805 To deactivate limit of all QPids when the limiter has been changed from 'limit' to 'unlimit'.
  deps/rabbit/src/rabbit_amqqueue.erl
  deps/rabbit/src/rabbit_amqqueue_process.erl
  deps/rabbit/src/rabbit_channel.erl
  deps/rabbit/src/rabbit_queue_consumers.erl
Labels: backport-v3.9.x

#3815 Introduce a new CLI tool (scope), rabbitmq-tanzu
  Makefile
  deps/rabbit/docs/rabbitmq-diagnostics.8
  deps/rabbit/docs/rabbitmq-echopid.8
  deps/rabbit/docs/rabbitmq-env.conf.5
  deps/rabbit/docs/rabbitmq-plugins.8
  deps/rabbit/docs/rabbitmq-queues.8
  deps/rabbit/docs/rabbitmq-server.8
  deps/rabbit/docs/rabbitmq-service.8
  deps/rabbit/docs/rabbitmq-upgrade.8
  deps/rabbit/docs/rabbitmqctl.8
  deps/rabbit/scripts/rabbitmq-tanzu
  deps/rabbit/scripts/rabbitmq-tanzu.bat
  deps/rabbitmq_cli/Makefile
  deps/rabbitmq_cli/lib/rabbitmq/cli/ctl/commands/help_command.ex
  deps/rabbitmq_cli/test/ctl/clear_global_parameter_command_test.exs
  deps/rabbitmq_cli/test/ctl/clear_policy_command_test.exs
  deps/rabbitmq_mqtt/test/java_SUITE_data/src/test/java/com/rabbitmq/mqtt/test/MqttTest.java
  deps/rabbitmq_peer_discovery_etcd/test/config_schema_SUITE_data/rabbitmq_peer_discovery_etcd.snippets
  deps/rabbitmq_peer_discovery_k8s/test/config_schema_SUITE_data/rabbitmq_peer_discovery_k8s.snippets
  dist.bzl
  rabbitmq_home.bzl
Labels: bazel, make

#3814 Query total number of messages on stream leader on queue.declare
  deps/rabbit/src/rabbit_stream_queue.erl
  deps/rabbit/test/rabbit_stream_queue_SUITE.erl
Labels: backport-v3.9.x
