Repository rabbitmq/rabbitmq-server, pull requests merged in 2021-07, with the labels that each got.

#3203 Remove project maturity warning
  deps/rabbitmq_stream/README.adoc
  deps/rabbitmq_stream/docs/PROTOCOL.adoc
Labels: backport-pending

#3213 Fix accept dependency in rabbitmq_prometheus
  deps/rabbitmq_prometheus/Makefile
Labels: bug, effort-tiny, rabbitmq-prometheus

#3250 Publish RabbitMQ-Stream dashboard to grafana.com
  deps/rabbitmq_prometheus/.dockerignore
  deps/rabbitmq_prometheus/Dockerfile
  deps/rabbitmq_prometheus/Makefile
  deps/rabbitmq_prometheus/docker/docker-compose-dist-metrics.yml
  deps/rabbitmq_prometheus/docker/docker-compose-dist-tls.yml
  deps/rabbitmq_prometheus/docker/docker-compose-metrics.yml
  deps/rabbitmq_prometheus/docker/docker-compose-overview.yml
  deps/rabbitmq_prometheus/docker/docker-compose-qq.yml
  deps/rabbitmq_prometheus/docker/grafana/dashboards/RabbitMQ-Overview.json
  deps/rabbitmq_prometheus/docker/grafana/dashboards/RabbitMQ-Stream.json
  deps/rabbitmq_prometheus/docker/grafana/publish/rabbitmq-stream-14798.md
  deps/rabbitmq_prometheus/docker/grafana/publish/rabbitmq-stream-bottom-2021-07-29-original.png
  deps/rabbitmq_prometheus/docker/grafana/publish/rabbitmq-stream-bottom-2021-07-29.jpg
  deps/rabbitmq_prometheus/docker/grafana/publish/rabbitmq-stream-logo-2021-07-29-original.jpg
  deps/rabbitmq_prometheus/docker/grafana/publish/rabbitmq-stream-top-2021-07-29-original.png
  deps/rabbitmq_prometheus/docker/grafana/publish/rabbitmq-stream-top-2021-07-29.jpg
Labels: backport v3.9.x
