Repository rabbitmq/rabbitmq-server, pull requests merged in 2022-12, with the labels that each got.

#6538 rabbit_runtime_parameters: Fix event when clearing a global runtime parameter
  deps/rabbit/src/rabbit_runtime_parameters.erl
Labels: backport-v3.9.x, backport-v3.10.x, backport-v3.11.x

#6544 Fix rabbit_misc:hexify/1 when called with a list
  deps/rabbit_common/BUILD.bazel
  deps/rabbit_common/src/rabbit_core_metrics.erl
  deps/rabbit_common/src/rabbit_data_coercion.erl
  deps/rabbit_common/src/rabbit_date_time.erl
  deps/rabbit_common/src/rabbit_env.erl
  deps/rabbit_common/src/rabbit_json.erl
  deps/rabbit_common/src/rabbit_misc.erl
  deps/rabbit_common/src/rabbit_writer.erl
  deps/rabbit_common/test/unit_SUITE.erl
  deps/rabbitmq_auth_backend_cache/BUILD.bazel
  deps/rabbitmq_auth_backend_cache/src/rabbit_auth_backend_cache_app.erl
  deps/rabbitmq_auth_backend_cache/src/rabbit_auth_cache.erl
  deps/rabbitmq_auth_backend_cache/src/rabbit_auth_cache_dict.erl
  deps/rabbitmq_auth_backend_cache/src/rabbit_auth_cache_ets.erl
  deps/rabbitmq_auth_backend_cache/src/rabbit_auth_cache_ets_segmented.erl
  deps/rabbitmq_auth_backend_cache/src/rabbit_auth_cache_ets_segmented_stateless.erl
  deps/rabbitmq_auth_backend_http/src/rabbit_auth_backend_http.erl
  deps/rabbitmq_auth_backend_ldap/src/rabbit_auth_backend_ldap.erl
  deps/rabbitmq_auth_backend_ldap/src/rabbit_auth_backend_ldap_app.erl
  deps/rabbitmq_ct_client_helpers/src/rabbit_ct_client_helpers.erl
  deps/rabbitmq_event_exchange/BUILD.bazel
  deps/rabbitmq_event_exchange/src/rabbit_exchange_type_event.erl
  deps/rabbitmq_peer_discovery_common/BUILD.bazel
  deps/rabbitmq_peer_discovery_common/src/rabbit_peer_discovery_httpc.erl
  deps/rabbitmq_peer_discovery_common/src/rabbit_peer_discovery_util.erl
  deps/rabbitmq_tracing/BUILD.bazel
  deps/rabbitmq_tracing/src/rabbit_tracing_consumer.erl
  deps/rabbitmq_tracing/src/rabbit_tracing_sup.erl
  deps/rabbitmq_trust_store/BUILD.bazel
  deps/rabbitmq_trust_store/src/rabbit_trust_store.erl
  deps/rabbitmq_trust_store/src/rabbit_trust_store_http_provider.erl
  deps/rabbitmq_web_stomp/BUILD.bazel
  deps/rabbitmq_web_stomp/src/rabbit_web_stomp_handler.erl
  deps/rabbitmq_web_stomp/src/rabbit_web_stomp_internal_event_handler.erl
  deps/rabbitmq_web_stomp/src/rabbit_web_stomp_listener.erl
Labels: bazel, backport-v3.9.x, backport-v3.10.x, backport-v3.11.x

#6560 3.10.13 release notes
  release-notes/3.10.13.md
Labels: backport-v3.10.x, backport-v3.11.x

#6563 3.11.5 release notes
  release-notes/3.11.5.md
Labels: backport-v3.11.x

#6569 Update 3.11.5 and 3.10.13 release notes
  release-notes/3.10.13.md
  release-notes/3.11.5.md
Labels: backport-v3.11.x

#6574 Adopt otp 25.1.2
  MODULE.bazel
Labels: bazel, backport-v3.10.x, backport-v3.11.x

#6571 Adopt otp 24.3.4.6
  MODULE.bazel
Labels: bazel, backport-v3.9.x

#6583 Modify rabbit_sharding_exchange_decorator boot requirements
  deps/rabbitmq_sharding/src/rabbit_sharding_exchange_decorator.erl
Labels: backport-v3.10.x, backport-v3.11.x

#6586 Copy rather than symlink rabbitmqctl in bazel
  BUILD.bazel
  dist.bzl
  rabbitmq_home.bzl
Labels: bazel, backport-v3.9.x, backport-v3.10.x, backport-v3.11.x

#6600 Consistently expose default queue functionality in management UI
  deps/rabbitmq_management/priv/www/js/global.js
  deps/rabbitmq_management/priv/www/js/main.js
  deps/rabbitmq_management/priv/www/js/tmpl/queues.ejs
  deps/rabbitmq_management/priv/www/js/tmpl/vhost.ejs
  deps/rabbitmq_management/priv/www/js/tmpl/vhosts.ejs
Labels: backport-v3.11.x

#6601 Fix error filtering and printing in queue grow/shrink commands
  deps/rabbitmq_cli/lib/rabbitmq/cli/queues/commands/grow_command.ex
  deps/rabbitmq_cli/lib/rabbitmq/cli/queues/commands/shrink_command.ex
Labels: backport-v3.10.x, backport-v3.11.x

#6598 Make rabbitmqctl with no command (implicit "help") behave more like with "help"
  deps/rabbitmq_cli/lib/rabbitmq/cli/core/command_modules.ex
  deps/rabbitmq_cli/lib/rabbitmq/cli/ctl/commands/help_command.ex
Labels: backport-v3.10.x, backport-v3.11.x

#6185 Just in time mixed version testing artifacts
  .github/workflows/secondary-umbrella.yaml
  .github/workflows/test-mixed-versions.yaml
  bazel/bzlmod/secondary_umbrella.bzl
Labels: bazel, backport-v3.10.x, backport-v3.11.x

#6263 Report flow/blocked shovel status in Mgmt UI
  deps/rabbit_common/src/credit_flow.erl
  deps/rabbitmq_shovel/src/Elixir.RabbitMQ.CLI.Ctl.Commands.ShovelStatusCommand.erl
  deps/rabbitmq_shovel/src/rabbit_amqp091_shovel.erl
  deps/rabbitmq_shovel/src/rabbit_amqp10_shovel.erl
  deps/rabbitmq_shovel/src/rabbit_shovel_behaviour.erl
  deps/rabbitmq_shovel/src/rabbit_shovel_status.erl
  deps/rabbitmq_shovel/src/rabbit_shovel_worker.erl
  deps/rabbitmq_shovel/test/dynamic_SUITE.erl
  deps/rabbitmq_shovel/test/shovel_test_utils.erl
  deps/rabbitmq_shovel_management/BUILD.bazel
  deps/rabbitmq_shovel_management/priv/www/js/tmpl/shovels.ejs
  deps/rabbitmq_shovel_management/src/rabbit_shovel_mgmt_util.erl
  deps/rabbitmq_shovel_management/test/rabbit_shovel_mgmt_util_SUITE.erl
Labels: bazel, backport-v3.10.x, backport-v3.11.x

#6610 Make CT helpers available for erlang_ls
  tools/BUILD.bazel
Labels: bazel, backport-v3.9.x, backport-v3.10.x, backport-v3.11.x

#6607 Relax rabbit_auth_cache_SUITE:random_timing a bit
  deps/rabbitmq_auth_backend_cache/test/rabbit_auth_cache_SUITE.erl
Labels: backport-v3.9.x, backport-v3.10.x, backport-v3.11.x

#6614 Use powershell as a backup to handle.exe
  deps/rabbit_common/src/rabbit_misc.erl
  deps/rabbitmq_management_agent/src/rabbit_mgmt_external_stats.erl
Labels: backport-v3.10.x, backport-v3.11.x

#6632 Expose aten poll interval in rabbitmq.conf
  deps/rabbit/priv/schema/rabbit.schema
  deps/rabbit/test/config_schema_SUITE_data/rabbit.snippets
Labels: backport-v3.9.x, backport-v3.10.x, backport-v3.11.x

#6634 Use ubuntu-20.04 in actions as the base OS
  .github/workflows/oci-base.yaml
  .github/workflows/oci.yaml
  .github/workflows/perform-bazel-execution-comparison.yaml
  .github/workflows/rabbitmq_peer_discovery_aws.yaml
  .github/workflows/secondary-umbrella.yaml
  .github/workflows/test-erlang-git.yaml
  .github/workflows/test-mixed-versions.yaml
  .github/workflows/test-selenium.yaml
  .github/workflows/test.yaml
  .github/workflows/update-elixir-patches.yaml
  .github/workflows/update-otp-patches.yaml
Labels: backport-v3.9.x, backport-v3.10.x, backport-v3.11.x

#6651 Backport #5726 (disk monitor resiliency improvements)
  deps/rabbit/BUILD.bazel
  deps/rabbit/src/rabbit_disk_monitor.erl
  deps/rabbit/test/disk_monitor_SUITE.erl
  deps/rabbit/test/unit_disk_monitor_SUITE.erl
Labels: bazel

#6652 Update mix_task_archve_deps to 1.0.0
  deps/rabbit_common/mk/rabbitmq-dist.mk
Labels: make, backport-v3.9.x, backport-v3.10.x, backport-v3.11.x

#6662 Bump Ra to 2.4.5
  MODULE.bazel
  rabbitmq-components.mk
  release-notes/3.11.5.md
  workspace_helpers.bzl
Labels: bazel, make, backport-v3.11.x

#6663 Bump Ra to 2.4.5 in v3.10.x
  MODULE.bazel
  rabbitmq-components.mk
  workspace_helpers.bzl
Labels: bazel, make

#6665 Update 3.10.13 release notes
  release-notes/3.10.13.md
Labels: backport-v3.10.x, backport-v3.11.x

#6658 Use direct exchange routing v1 for custom exchange types
  deps/rabbit/src/rabbit_exchange_type_direct.erl
Labels: backport-v3.11.x

#6440 Streams rebalancing
  MODULE.bazel
  deps/rabbit/Makefile
  deps/rabbit/include/amqqueue.hrl
  deps/rabbit/src/amqqueue.erl
  deps/rabbit/src/rabbit_amqqueue.erl
  deps/rabbit/src/rabbit_core_ff.erl
  deps/rabbit/src/rabbit_maintenance.erl
  deps/rabbit/src/rabbit_quorum_queue.erl
  deps/rabbit/src/rabbit_stream_coordinator.erl
  deps/rabbit/src/rabbit_stream_coordinator.hrl
  deps/rabbit/src/rabbit_stream_queue.erl
  deps/rabbit/test/rabbit_stream_coordinator_SUITE.erl
  deps/rabbit/test/rabbit_stream_queue_SUITE.erl
  deps/rabbitmq_cli/lib/rabbitmq/cli/queues/commands/rebalance_command.ex
  deps/rabbitmq_cli/lib/rabbitmq/cli/streams/commands/restart_stream_command.ex
  workspace_helpers.bzl
Labels: bazel, make

#6674 Use more modern method to download definitions
  deps/rabbitmq_management/priv/www/js/main.js
Labels: backport-v3.10.x, backport-v3.11.x

#6681 Adopt OTP 25.2
  .bazelrc
  .github/workflows/oci.yaml
  .github/workflows/test-mixed-versions.yaml
  .github/workflows/test-selenium.yaml
  .github/workflows/test-windows.yaml
  .github/workflows/test.yaml
  .github/workflows/update-otp-patches.yaml
  MODULE.bazel
  WORKSPACE
  bazel/platforms/BUILD.bazel
  deps/rabbitmq_peer_discovery_common/src/rabbit_peer_discovery_httpc.erl
  packaging/docker-image/BUILD.bazel
Labels: bazel, backport-v3.10.x, backport-v3.11.x

#6690 Remove redundant binary_to_list/1 call
  deps/rabbit/src/rabbit_stream_queue.erl
Labels: backport-v3.11.x

#6687 Parse and apply default_policies.operator
  deps/rabbit/BUILD.bazel
  deps/rabbit/priv/schema/rabbit.schema
  deps/rabbit/src/rabbit_cuttlefish.erl
  deps/rabbit/src/rabbit_vhost.erl
  deps/rabbit/test/config_schema_SUITE_data/rabbit.snippets
  deps/rabbit/test/rabbit_cuttlefish_SUITE.erl
  deps/rabbit/test/vhost_SUITE.erl
Labels: bazel, backport-v3.11.x

#6695 Use rules_erlang 3.8.5
  .bazelrc
  .gitignore
  BUILD.bazel
  MODULE.bazel
  WORKSPACE
  bazel/util/BUILD.bazel
  bazel/util/ct_logdir_vars.bzl
  user-template.bazelrc
Labels: bazel, backport-v3.9.x, backport-v3.10.x, backport-v3.11.x

#6707 Pin recon to master
  MODULE.bazel
  rabbitmq-components.mk
Labels: bazel, make, backport-v3.9.x, backport-v3.10.x, backport-v3.11.x

#6704 Bazel minor updates
  BUILD.bazel
  deps/rabbit/BUILD.bazel
Labels: bazel, backport-v3.10.x, backport-v3.11.x

#6708 Preserve heartbeat error reason
  deps/rabbit/src/rabbit_reader.erl
Labels: backport-v3.9.x, backport-v3.10.x, backport-v3.11.x

#6719 Don't crash listing listeners when a node is shutting down
  deps/rabbit/src/rabbit_networking.erl
Labels: backport-v3.9.x, backport-v3.10.x, backport-v3.11.x

#6724 Adopt elixir 1.13.4
  MODULE.bazel
Labels: bazel, backport-v3.9.x, backport-v3.10.x, backport-v3.11.x

#6739 Ra 2.4.6
  MODULE.bazel
  rabbitmq-components.mk
  workspace_helpers.bzl
Labels: bazel, make, backport-v3.10.x, backport-v3.11.x

#6740 Fix Bazel 6 compatibility for tests
  deps/rabbitmq_ct_helpers/src/rabbit_ct_helpers.erl
  rabbitmq.bzl
Labels: bazel, backport-v3.9.x, backport-v3.10.x, backport-v3.11.x

#6761 Pin to recon 2.5.3
  MODULE.bazel
  rabbitmq-components.mk
  workspace_helpers.bzl
Labels: bazel, make

#6771 Adopt otp 24.3.4.7
  MODULE.bazel
  WORKSPACE
Labels: bazel, backport-v3.9.x

#6780 Management UI: escape the user controlled error parameter
  deps/rabbitmq_management/priv/www/js/main.js
Labels: backport-v3.9.x, backport-v3.10.x, backport-v3.11.x
