Repository rabbitmq/rabbitmq-server, pull requests merged in 2022-11, with the labels that each got.

#6295 CLI: improve isolation of set_disk_free_limit tests
  deps/rabbitmq_cli/lib/rabbitmq/cli/formatters/formatter_helpers.ex
  deps/rabbitmq_cli/test/ctl/set_disk_free_limit_command_test.exs
Labels: backport-v3.9.x, backport-v3.10.x, backport-v3.11.x

#6292 Refine and fix AMQP 1.0 modified outcome behaviour
  deps/amqp10_client/src/amqp10_client_session.erl
  deps/amqp10_client/src/amqp10_client_types.erl
  deps/amqp10_client/src/amqp10_msg.erl
  deps/rabbitmq_amqp1_0/src/rabbit_amqp1_0_session_process.erl
  deps/rabbitmq_amqp1_0/test/amqp10_client_SUITE.erl
Labels: rabbitmq-amqp1.0-client, rabbitmq-amqp1.0, backport-v3.10.x, backport-v3.11.x

#6305 Fail fast in the rabbitmq_cli tests if test_helper.exs is missing
  deps/rabbitmq_cli/rabbitmqctl_test.bzl
Labels: bazel, backport-v3.9.x, backport-v3.10.x, backport-v3.11.x

#6311 Copy rather than symlink files in rabbitmqctl_test.bzl
  deps/rabbitmq_cli/rabbitmqctl_test.bzl
Labels: bazel, backport-v3.9.x, backport-v3.10.x, backport-v3.11.x

#6321 Remove trust_store_http from MODULE.bazel since it's an internal dep
  MODULE.bazel
Labels: bazel, backport-v3.11.x

#6316 CLI tools: discover commands in plugins that are enabled indirectly as dependencies; rework plugin state assertions
  deps/rabbitmq_cli/BUILD.bazel
  deps/rabbitmq_cli/lib/rabbitmq/cli/core/code_path.ex
  deps/rabbitmq_cli/lib/rabbitmq/cli/core/command_modules.ex
  deps/rabbitmq_cli/lib/rabbitmq/cli/plugins/plugins_helpers.ex
  deps/rabbitmq_cli/test/plugins/enable_plugins_command_test.exs
  deps/rabbitmq_cli/test/plugins/list_plugins_command_test.exs
  deps/rabbitmq_cli/test/test_helper.exs
  scripts/bazel/rabbitmq-run.bat
  scripts/bazel/rabbitmq-run.sh
Labels: bazel, backport-v3.9.x, backport-v3.10.x, backport-v3.11.x

#6327 Remove duplicate dep_thoas declaration
  rabbitmq-components.mk
Labels: make, backport-v3.11.x

#6325 Fix seshat counter leaks
  MODULE.bazel
  deps/rabbit/Makefile
  deps/rabbit/src/rabbit_quorum_queue.erl
  deps/rabbit/src/rabbit_stream_queue.erl
  deps/rabbitmq_stream/src/rabbit_stream_reader.erl
  deps/rabbitmq_stream/test/rabbit_stream_SUITE.erl
  workspace_helpers.bzl
Labels: bazel, make, backport-v3.10.x, backport-v3.11.x

#6337 Adopt otp 25.1.2
  MODULE.bazel
Labels: bazel, backport-v3.10.x, backport-v3.11.x

#6333 Adopt otp 24.3.4.6
  MODULE.bazel
Labels: bazel, backport-v3.9.x

#6349 Bump Ra to 2.4.0
  MODULE.bazel
  workspace_helpers.bzl
Labels: bazel, backport-v3.11.x

#6358 Bump Ra to 2.4.0
  MODULE.bazel
  rabbitmq-components.mk
  workspace_helpers.bzl
Labels: bazel, make

#6362 Bump Osiris to 1.3.3, Seshat to 0.4.0
  MODULE.bazel
  deps/rabbit/Makefile
  workspace_helpers.bzl
Labels: bazel, make, backport-v3.10.x

#6363 Bump credentials_obfuscation to 3.2.0
  MODULE.bazel
  deps/rabbit_common/Makefile
  workspace_helpers.bzl
Labels: bazel, make, backport-v3.9.x, backport-v3.10.x, backport-v3.11.x

#6369 Bump Ra to 2.4.1
  MODULE.bazel
  rabbitmq-components.mk
  workspace_helpers.bzl
Labels: bazel, make, backport-v3.9.x, backport-v3.10.x, backport-v3.11.x

#6370 Adopt otp 24.3.4.6
  MODULE.bazel
Labels: bazel, backport-v3.9.x

#6374 Adjust generated .app file for ra to include seshat as a dep
  MODULE.bazel
  workspace_helpers.bzl
Labels: bazel

#6381 3.11.3 release notes
  release-notes/3.11.3.md
Labels: backport-v3.11.x

#6383 Update 3.10.11 release notes
  release-notes/3.10.11.md
Labels: backport-v3.10.x, backport-v3.11.x

#6386 Adopt otp 24.3.4.6
  MODULE.bazel
Labels: bazel, backport-v3.9.x

#6390 Aggregate memory usage on ra_server_sup_sup level
  deps/rabbit/src/rabbit_vm.erl
Labels: backport-v3.10.x, backport-v3.11.x

#6398 fix rabbit_direct_reply_to:compute_key_and_suffix_v1 type signature
  deps/rabbit/BUILD.bazel
  deps/rabbit/src/rabbit_direct_reply_to.erl
  deps/rabbit/test/rabbit_direct_reply_to_prop_SUITE.erl
Labels: bazel, backport-v3.9.x, backport-v3.10.x, backport-v3.11.x

#6412 Introduce aliasing for CLI tools info keys, use more inclusive names for some CMQ-related fields
  deps/rabbit/docs/rabbitmqctl.8
  deps/rabbit/src/rabbit_amqqueue.erl
  deps/rabbit/src/rabbit_queue_type.erl
  deps/rabbitmq_cli/DESIGN.md
  deps/rabbitmq_cli/lib/rabbitmq/cli/ctl/commands/list_channels_command.ex
  deps/rabbitmq_cli/lib/rabbitmq/cli/ctl/commands/list_connections_command.ex
  deps/rabbitmq_cli/lib/rabbitmq/cli/ctl/commands/list_queues_command.ex
  deps/rabbitmq_cli/lib/rabbitmq/cli/ctl/commands/list_unresponsive_queues_command.ex
  deps/rabbitmq_cli/lib/rabbitmq/cli/ctl/info_keys.ex
  deps/rabbitmq_cli/test/ctl/info_keys_test.exs
Labels: backport-v3.10.x, backport-v3.11.x

#6397 #4842: obfuscate a sensitive field in authenticated user state
  deps/rabbit/src/rabbit_auth_backend_internal.erl
  deps/rabbitmq_auth_backend_cache/test/rabbit_auth_backend_cache_SUITE.erl
  deps/rabbitmq_auth_backend_http/src/rabbit_auth_backend_http.erl
  deps/rabbitmq_auth_backend_http/test/auth_SUITE.erl
  deps/rabbitmq_auth_backend_ldap/src/rabbit_auth_backend_ldap.erl
  deps/rabbitmq_auth_backend_ldap/test/system_SUITE.erl
  deps/rabbitmq_auth_backend_oauth2/src/rabbit_auth_backend_oauth2.erl
Labels: backport-v3.9.x, backport-v3.10.x, backport-v3.11.x

#6418 load_definitions should fail on invalid JSON
  deps/rabbit/src/rabbit_definitions.erl
Labels: backport-v3.10.x, backport-v3.11.x

#6421 Support x-max-age argument in stomp
  deps/rabbitmq_stomp/examples/python/stream-receiver.py
  deps/rabbitmq_stomp/include/rabbit_stomp_headers.hrl
  deps/rabbitmq_stomp/src/rabbit_stomp_util.erl
  deps/rabbitmq_stomp/test/python_SUITE_data/src/x_queue_type_stream.py
Labels: backport-v3.10.x, backport-v3.11.x

#6431 Filter out global runtime parameters not meant to be exposed
  deps/rabbit/src/rabbit_runtime_parameters.erl
Labels: backport-v3.10.x, backport-v3.11.x

#6436 Osiris 1.4.0
  MODULE.bazel
  deps/rabbit/Makefile
  workspace_helpers.bzl
Labels: bazel, make, backport-v3.11.x

#6442 Get counters from stream replicas first
  deps/rabbit/src/rabbit_stream_queue.erl
Labels: backport-v3.10.x, backport-v3.11.x

#6448 Consider streams when quorum critical check
  deps/rabbit/src/rabbit_quorum_queue.erl
  deps/rabbit/src/rabbit_stream_queue.erl
  deps/rabbit/src/rabbit_upgrade_preparation.erl
  deps/rabbit/test/upgrade_preparation_SUITE.erl
  deps/rabbitmq_cli/lib/rabbitmq/cli/queues/commands/check_if_node_is_quorum_critical_command.ex
  deps/rabbitmq_management/src/rabbit_mgmt_wm_health_check_node_is_quorum_critical.erl
Labels: backport-v3.11.x

#6468 QQs: hint Ra at taking a snapshot when a consumer is added
  deps/rabbit/src/rabbit_fifo.erl
Labels: backport-v3.10.x, backport-v3.11.x

#6481 Updated django url to re_path
  deps/rabbitmq_auth_backend_http/examples/rabbitmq_auth_backend_django/rabbitmq_auth_backend_django/urls.py
Labels: backport-v3.9.x, backport-v3.10.x, backport-v3.11.x

#6488 Fix case_clause crash when stream queue provided for quorum queue commands
  deps/rabbit/src/rabbit_quorum_queue.erl
  deps/rabbit/test/quorum_queue_SUITE.erl
Labels: backport-v3.10.x, backport-v3.11.x

#6494 Initial 3.11.4 release notes
  release-notes/3.11.4.md
Labels: backport-v3.11.x

#6502 CQ: Remove an assert causing issues on SAC switch
  deps/rabbit/src/rabbit_amqqueue_process.erl
Labels: backport-v3.9.x, backport-v3.10.x, backport-v3.11.x

#6521 Add rabbit_fifo_dlx_worker test
  deps/rabbit/test/rabbit_fifo_dlx_integration_SUITE.erl
Labels: backport-v3.10.x, backport-v3.11.x

#6520 Add log when channel stops with pending confirms
  deps/rabbit/src/rabbit_channel.erl
Labels: backport-v3.10.x, backport-v3.11.x

#6524 rabbit_feature_flags: Fix the loading of a plugin's feature flag states
  deps/rabbit/src/rabbit_ff_registry_factory.erl
  deps/rabbit/test/feature_flags_SUITE.erl
Labels: bug

#6532 Fix feature-flags-related Dialyzer warnings
  deps/rabbit/src/rabbit_feature_flags.erl
  deps/rabbit/src/rabbit_ff_controller.erl
  deps/rabbit/src/rabbit_ff_registry.erl
Labels: backport-v3.10.x, backport-v3.11.x

#6462 Use "data directory" instead of "Mnesia directory" to indicate RabbitMQ's data location
  deps/rabbit/src/rabbit.erl
  deps/rabbit/src/rabbit_disk_monitor.erl
  deps/rabbit/src/rabbit_guid.erl
  deps/rabbit/src/rabbit_node_monitor.erl
  deps/rabbit/src/rabbit_plugins.erl
  deps/rabbit/src/rabbit_policy.erl
  deps/rabbit/src/rabbit_ra_systems.erl
  deps/rabbit/src/rabbit_vhost.erl
  deps/rabbit/test/unit_file_handle_cache_SUITE.erl
  deps/rabbit_common/mk/rabbitmq-run.mk
  deps/rabbit_common/src/rabbit_env.erl
  deps/rabbit_common/test/rabbit_env_SUITE.erl
  deps/rabbitmq_cli/lib/rabbitmq/cli/core/config.ex
  deps/rabbitmq_cli/lib/rabbitmq/cli/core/parser.ex
  deps/rabbitmq_cli/lib/rabbitmq/cli/core/paths.ex
  deps/rabbitmq_cli/lib/rabbitmq/cli/core/validators.ex
  deps/rabbitmq_cli/lib/rabbitmq/cli/ctl/commands/force_boot_command.ex
  deps/rabbitmq_cli/lib/rabbitmq/cli/ctl/commands/forget_cluster_node_command.ex
  deps/rabbitmq_cli/lib/rabbitmq/cli/ctl/commands/rename_cluster_node_command.ex
  deps/rabbitmq_cli/test/ctl/force_boot_command_test.exs
  deps/rabbitmq_cli/test/ctl/forget_cluster_node_command_test.exs
  deps/rabbitmq_cli/test/ctl/rename_cluster_node_command_test.exs
  deps/rabbitmq_ct_helpers/src/rabbit_ct_broker_helpers.erl
  deps/rabbitmq_management_agent/src/rabbit_mgmt_external_stats.erl
  deps/rabbitmq_mqtt/src/rabbit_mqtt_retainer.erl
  deps/rabbitmq_trust_store/src/rabbit_trust_store_file_provider.erl
Labels: make
