Repository rabbitmq/rabbitmq-server, pull requests merged in 2022-08, with the labels that each got.

#5401 3.10.7 release notes
  release-notes/3.10.7.md
Labels: backport-v3.10.x, backport-v3.11.x

#5404 3.9.22 release notes
  release-notes/3.9.22.md
Labels: backport-v3.9.x, backport-v3.10.x, backport-v3.11.x

#5410 ctl add_vhost: check if relevant feature flags are enabled
  deps/rabbit/src/rabbit_queue_type.erl
  deps/rabbit/src/rabbit_vhost.erl
  deps/rabbitmq_cli/lib/rabbitmq/cli/core/feature_flags.ex
  deps/rabbitmq_cli/lib/rabbitmq/cli/ctl/commands/add_vhost_command.ex
Labels: backport-v3.11.x

#5408 Import default queue type when virtual host is imported
  deps/rabbit/src/rabbit_definitions.erl
  deps/rabbit/test/definition_import_SUITE.erl
  deps/rabbit/test/definition_import_SUITE_data/case16.json
Labels: backport-v3.11.x

#5418 rabbitmqctl(8): add new virtual host information items (follow-up to #5399)
  deps/rabbit/docs/rabbitmqctl.8
Labels: backport-v3.10.x, backport-v3.11.x

#5433 CQv1: Fix failure to recover messages in rare cases
  deps/rabbit/BUILD.bazel
  deps/rabbit/src/rabbit_classic_queue_index_v2.erl
  deps/rabbit/test/classic_queue_prop_SUITE.erl
Labels: bazel, backport-v3.10.x, backport-v3.11.x

#5438 Prevent global:sync/0 from being stuck when hostname resolution is not available early on boot
  deps/rabbit/src/rabbit_ff_controller.erl
  deps/rabbit/src/rabbit_node_monitor.erl
Labels: backport-v3.11.x

#5445 Drop Erlang 23 from Actions test matrix (in 3.12.x/master, 3.11.x)
  .github/workflows/oci.yaml
  .github/workflows/perform-bazel-execution-comparison.yaml
  .github/workflows/test.yaml
  .github/workflows/update-otp-patches.yaml
Labels: backport-v3.11.x

#5447 Require Erlang 24.3
  deps/rabbit/apps/rabbitmq_prelaunch/src/rabbit_prelaunch_erlang_compat.erl
  deps/rabbitmq_ct_helpers/tools/terraform/direct-vms/templates/setup-erlang.sh
Labels: backport-v3.11.x

#4563 Don't delete durable queues from rabbit_queue table on node down
  deps/rabbit/src/rabbit_amqqueue.erl
Labels: backport-v3.11.x

#5319 HTTP API: allow connections to be listed and closed by username
  deps/rabbitmq_management/priv/www/api/index.html
  deps/rabbitmq_management/src/rabbit_mgmt_dispatcher.erl
  deps/rabbitmq_management/src/rabbit_mgmt_wm_connection.erl
  deps/rabbitmq_management/src/rabbit_mgmt_wm_connection_user_name.erl
  deps/rabbitmq_management/src/rabbit_mgmt_wm_connections.erl
Labels: backport-v3.10.x, backport-v3.11.x

#5458 Exclude a QQ test from mixed version testing in v3.10.x and v3.9.x
  deps/rabbit/test/quorum_queue_SUITE.erl
Labels: backport-v3.9.x

#5464 Require Erlang 24.2 (ERTS 12.2)
  .github/workflows/oci.yaml
  .github/workflows/perform-bazel-execution-comparison.yaml
  .github/workflows/test.yaml
  .github/workflows/update-rbe-images.yaml
  deps/rabbit/apps/rabbitmq_prelaunch/src/rabbit_prelaunch_erlang_compat.erl
Labels: backport-v3.9.x

#5427 Add StreamStats command to stream protocol
  deps/rabbitmq_stream/docs/PROTOCOL.adoc
  deps/rabbitmq_stream/src/rabbit_stream_manager.erl
  deps/rabbitmq_stream/src/rabbit_stream_reader.erl
  deps/rabbitmq_stream/src/rabbit_stream_utils.erl
  deps/rabbitmq_stream/test/rabbit_stream_SUITE.erl
  deps/rabbitmq_stream/test/rabbit_stream_manager_SUITE.erl
  deps/rabbitmq_stream_common/include/rabbit_stream.hrl
  deps/rabbitmq_stream_common/src/rabbit_stream_core.erl
  deps/rabbitmq_stream_common/test/rabbit_stream_core_SUITE.erl
Labels: backport-v3.11.x

#5467 Bump eetcd to 0.3.6
  MODULE.bazel
  deps/rabbitmq_peer_discovery_etcd/Makefile
  workspace_helpers.bzl
Labels: bazel, make, backport-v3.9.x, backport-v3.8.x, backport-v3.10.x, backport-v3.11.x

#5479 Streams: adapt tests to the latest Java stream client listener interface
  deps/rabbitmq_stream/test/rabbit_stream_SUITE_data/src/test/java/com/rabbitmq/stream/FailureTest.java
  deps/rabbitmq_stream/test/rabbit_stream_SUITE_data/src/test/java/com/rabbitmq/stream/StreamTest.java
Labels: backport-v3.9.x, backport-v3.10.x, backport-v3.11.x

#5487 Fix stream creation on validation failure
  deps/rabbitmq_stream/src/rabbit_stream_manager.erl
Labels: bug

#5488 Update prometheus to 4.9. close #4380
  MODULE.bazel
  rabbitmq-components.mk
Labels: bazel, make, backport-v3.9.x, backport-v3.10.x, backport-v3.11.x

#5492 amqp10_client system test suite reliability
  deps/amqp10_client/test/system_SUITE.erl
Labels: backport-v3.10.x, backport-v3.11.x

#5105 Remove dependency on rabbit_channel for deliveries
  deps/rabbit/src/rabbit_amqqueue_process.erl
  deps/rabbit/src/rabbit_classic_queue.erl
  deps/rabbit/src/rabbit_queue_consumers.erl
  deps/rabbit/src/rabbit_queue_type.erl
  deps/rabbit/src/rabbit_quorum_queue.erl
Labels: backport-v3.10.x, backport-v3.11.x

#5506 Simplify check for non-amq exchanges
  deps/rabbit/src/rabbit_definitions.erl
  deps/rabbit/src/rabbit_exchange.erl
Labels: backport-v3.11.x

#5514 Use rules_erlang 3.5.0
  MODULE.bazel
Labels: bazel, backport-v3.9.x, backport-v3.10.x, backport-v3.11.x

#5517 Remove all of the .travis.yml files
  .travis.yml
  .travis.yml.patch
  deps/rabbit/.travis.yml
  deps/rabbit/.travis.yml.patch
  deps/rabbit_common/.travis.yml
  deps/rabbitmq_amqp1_0/.travis.yml
  deps/rabbitmq_amqp1_0/.travis.yml.patch
  deps/rabbitmq_auth_backend_cache/.travis.yml
  deps/rabbitmq_auth_backend_http/.travis.yml
  deps/rabbitmq_auth_backend_ldap/.travis.yml
  deps/rabbitmq_auth_backend_ldap/.travis.yml.patch
  deps/rabbitmq_auth_backend_oauth2/.travis.yml
  deps/rabbitmq_auth_mechanism_ssl/.travis.yml
  deps/rabbitmq_aws/.travis.yml
  deps/rabbitmq_cli/.travis.yml
  deps/rabbitmq_cli/.travis.yml.patch
  deps/rabbitmq_consistent_hash_exchange/.travis.yml
  deps/rabbitmq_event_exchange/.travis.yml
  deps/rabbitmq_federation/.travis.yml
  deps/rabbitmq_federation_management/.travis.yml
  deps/rabbitmq_jms_topic_exchange/.travis.yml
  deps/rabbitmq_management/.travis.yml
  deps/rabbitmq_management_agent/.travis.yml
  deps/rabbitmq_mqtt/.travis.yml
  deps/rabbitmq_mqtt/.travis.yml.patch
  deps/rabbitmq_peer_discovery_aws/.travis.yml
  deps/rabbitmq_peer_discovery_common/.travis.yml
  deps/rabbitmq_peer_discovery_consul/.travis.yml
  deps/rabbitmq_peer_discovery_etcd/.travis.yml
  deps/rabbitmq_peer_discovery_etcd/.travis.yml.patch
  deps/rabbitmq_peer_discovery_k8s/.travis.yml
  deps/rabbitmq_random_exchange/.travis.yml
  deps/rabbitmq_recent_history_exchange/.travis.yml
  deps/rabbitmq_sharding/.travis.yml
  deps/rabbitmq_shovel/.travis.yml
  deps/rabbitmq_shovel_management/.travis.yml
  deps/rabbitmq_stomp/.travis.yml
  deps/rabbitmq_top/.travis.yml
  deps/rabbitmq_tracing/.travis.yml
  deps/rabbitmq_trust_store/.travis.yml
  deps/rabbitmq_web_dispatch/.travis.yml
  deps/rabbitmq_web_mqtt/.travis.yml
  deps/rabbitmq_web_stomp/.travis.yml
Labels: backport-v3.9.x, backport-v3.10.x, backport-v3.11.x

#5522 Add missing rabbitmq-upgrade to rabbitmq_home.bzl
  deps/rabbit/BUILD.bazel
  rabbitmq_home.bzl
Labels: bazel, backport-v3.9.x, backport-v3.10.x, backport-v3.11.x

#5525 AMQP 1.0 client: fix TLS hostname verification
  deps/amqp10_client/src/amqp10_client_frame_reader.erl
Labels: backport-v3.10.x, backport-v3.11.x

#5529 Sync prometheus version between MODULE.bazel & workspace_helpers
  workspace_helpers.bzl
Labels: bazel, backport-v3.9.x, backport-v3.10.x, backport-v3.11.x

#5534 Fix `badmatch` by taking edge case into account
  deps/rabbit_common/src/rabbit_net.erl
Labels: backport-v3.9.x, backport-v3.10.x, backport-v3.11.x

#5547 Force gc while importing definitions
  deps/rabbit/src/rabbit_definitions.erl
Labels: backport-v3.9.x, backport-v3.10.x, backport-v3.11.x

#5557 Add platforms repo to MODULE.bazel
  MODULE.bazel
Labels: bazel, backport-v3.9.x, backport-v3.8.x, backport-v3.10.x, backport-v3.11.x

#5564 Adopt otp 24.3.4.3
  bazel/toolchains/BUILD.bazel
Labels: bazel, backport-v3.9.x, backport-v3.8.x, backport-v3.10.x, backport-v3.11.x

#5565 Adopt otp 25.0.4
  bazel/toolchains/BUILD.bazel
Labels: bazel, backport-v3.9.x, backport-v3.8.x, backport-v3.10.x, backport-v3.11.x

#5566 Adopt latest rabbitmq-server-buildenv:linux-rbe for RBE
  WORKSPACE.bazel
Labels: bazel, backport-v3.9.x, backport-v3.8.x, backport-v3.10.x, backport-v3.11.x

#5580 Remove an old function check (pre-OTP20)
  deps/rabbit_common/src/rabbit_event.erl
Labels: backport-v3.9.x, backport-v3.10.x, backport-v3.11.x

#5581 Check for vhost's existence every 5 seconds
  deps/rabbit/src/rabbit_vhost_process.erl
Labels: backport-v3.11.x

#5585 Add a bazel based OCI image build to the oci.yaml workflow
  .github/workflows/oci.yaml
  .github/workflows/test-erlang-git.yaml
  .github/workflows/test-mixed-versions.yaml
  .github/workflows/test-windows.yaml
  .github/workflows/test.yaml
  WORKSPACE
  packaging/BUILD.bazel
  packaging/base-image/Dockerfile
  packaging/docker-image/BUILD.bazel
  packaging/docker-image/build_install_openssh.sh
  packaging/docker-image/build_install_otp.sh
  packaging/docker-image/install_rabbitmq.sh
  packaging/docker-image/test_configs/BUILD.bazel
  packaging/docker-image/test_configs/openssl_ubuntu.yaml
  packaging/docker-image/test_configs/otp_ubuntu.yaml
  packaging/docker-image/test_configs/rabbitmq_ubuntu.yaml
  user-template.bazelrc
Labels: bazel

#5611 Fix some typos in comments
  deps/rabbit_common/src/rabbit_env.erl
  deps/rabbitmq_prometheus/src/collectors/prometheus_rabbitmq_core_metrics_collector.erl
Labels: backport-v3.9.x, backport-v3.10.x, backport-v3.11.x

#5623 Adopt otp 24.3.4.3
  WORKSPACE
Labels: backport-v3.9.x, backport-v3.8.x, backport-v3.10.x, backport-v3.11.x

#5610 connection/channel tracking refactorings
  deps/rabbit/src/rabbit_channel_tracking.erl
  deps/rabbit/src/rabbit_connection_tracking.erl
  deps/rabbit/src/rabbit_tracking.erl
Labels: backport-v3.11.x

#5624 Adopt otp 25.0.4
  WORKSPACE
Labels: backport-v3.9.x, backport-v3.8.x, backport-v3.10.x, backport-v3.11.x

#5234 Support Rich Authorization Request OAuth2 specification
  deps/rabbitmq_auth_backend_oauth2/README.md
  deps/rabbitmq_auth_backend_oauth2/priv/schema/rabbitmq_auth_backend_oauth2.schema
  deps/rabbitmq_auth_backend_oauth2/src/rabbit_auth_backend_oauth2.erl
  deps/rabbitmq_auth_backend_oauth2/test/jwks_SUITE.erl
  deps/rabbitmq_auth_backend_oauth2/test/rabbit_auth_backend_oauth2_test_util.erl
  deps/rabbitmq_auth_backend_oauth2/test/system_SUITE.erl
  deps/rabbitmq_auth_backend_oauth2/test/unit_SUITE.erl
  deps/rabbitmq_management/test/rabbit_mgmt_http_SUITE.erl
Labels: bazel, make, backport-v3.11.x

#5635 Exclude OCI targets from wildcards like `bazel test //... ...`
  .github/workflows/oci.yaml
  packaging/docker-image/BUILD.bazel
Labels: bazel, backport-v3.9.x, backport-v3.8.x, backport-v3.10.x, backport-v3.11.x

#5640 Fix typo
  deps/rabbit_common/src/supervisor2.erl
Labels: backport-v3.9.x, backport-v3.10.x, backport-v3.11.x

#5449 Update RabbitMQ Dashboards to support latest Grafana versions
  deps/rabbitmq_prometheus/Makefile
  deps/rabbitmq_prometheus/docker/docker-compose-metrics.yml
  deps/rabbitmq_prometheus/docker/grafana/README.md
  deps/rabbitmq_prometheus/docker/grafana/__inputs.json
  deps/rabbitmq_prometheus/docker/grafana/dashboards/Erlang-Distribution.json
  deps/rabbitmq_prometheus/docker/grafana/dashboards/Erlang-Distributions-Compare.json
  deps/rabbitmq_prometheus/docker/grafana/dashboards/Erlang-Memory-Allocators.json
  deps/rabbitmq_prometheus/docker/grafana/dashboards/RabbitMQ-Overview.json
  deps/rabbitmq_prometheus/docker/grafana/dashboards/RabbitMQ-PerfTest.json
  deps/rabbitmq_prometheus/docker/grafana/dashboards/RabbitMQ-Quorum-Queues-Raft.json
  deps/rabbitmq_prometheus/docker/grafana/dashboards/RabbitMQ-Stream.json
  deps/rabbitmq_prometheus/docker/grafana/dashboards/inet_tcp_metrics.json
  deps/rabbitmq_prometheus/docker/grafana/dashboards/rabbitmq-exporter_vs_rabbitmq-prometheus.json
Labels: make

#5655 Avoid crash when client disconnects before server handles MQTT CONNECT
  deps/rabbitmq_mqtt/src/rabbit_mqtt_processor.erl
  deps/rabbitmq_mqtt/test/reader_SUITE.erl
Labels: backport-v3.9.x, backport-v3.10.x, backport-v3.11.x

#5660 Adopt otp 24.3.4.4
  WORKSPACE
  bazel/toolchains/BUILD.bazel
Labels: bazel, backport-v3.9.x, backport-v3.8.x, backport-v3.10.x, backport-v3.11.x

#5659 Controllable way to ignore supervisor2 error reports
  deps/rabbit/Makefile
  deps/rabbit_common/BUILD.bazel
  deps/rabbit_common/src/supervisor2.erl
  deps/rabbit_common/test/supervisor2_SUITE.erl
  deps/rabbit_common/test/test_event_handler.erl
Labels: bazel, make

#5674 Bump deps: michaelklishin/erlang-jose and Thoas
  MODULE.bazel
  deps/rabbitmq_auth_backend_oauth2/Makefile
  rabbitmq-components.mk
Labels: bazel, make, backport-v3.11.x

#5677 Use OTP 24.3.4.4 to build docker images using make
  packaging/docker-image/Makefile
Labels: make, backport-v3.9.x, backport-v3.10.x, backport-v3.11.x

#5689 Use OTP 25.0.4 to build RabbitMq docker image
  packaging/docker-image/Makefile
Labels: make, backport-v3.9.x, backport-v3.10.x, backport-v3.11.x

#5693 Upgrade MQTT Erlang client
  MODULE.bazel
  deps/rabbitmq_mqtt/BUILD.bazel
  deps/rabbitmq_mqtt/Makefile
  deps/rabbitmq_mqtt/test/auth_SUITE.erl
  deps/rabbitmq_mqtt/test/cluster_SUITE.erl
  deps/rabbitmq_mqtt/test/command_SUITE.erl
  deps/rabbitmq_mqtt/test/reader_SUITE.erl
  deps/rabbitmq_mqtt/test/retainer_SUITE.erl
  workspace_helpers.bzl
Labels: rabbitmq-mqtt, bazel, make, backport-v3.9.x, backport-v3.10.x, backport-v3.11.x
