Repository rabbitmq/rabbitmq-server, pull requests merged in 2022-02, with the labels that each got.

#4068 Update buildbuddy toolchain
  .bazelrc
  .github/workflows/test-erlang-git.yaml
  WORKSPACE.bazel
Labels: bazel, backport-v3.9.x, backport-v3.8.x, backport-v3.10.x

#4074 Use rules_erlang 2.1.0
  WORKSPACE.bazel
Labels: bazel, backport-v3.9.x, backport-v3.8.x

#4078 Remove lines that do not apply to modern Erlang
  deps/rabbit/src/rabbit.erl
Labels: backport-v3.9.x, backport-v3.8.x, backport-v3.10.x

#4073 Fix performance regression when stream_queue feature is not enabled
  deps/rabbit/src/rabbit_channel.erl
  deps/rabbit/src/rabbit_queue_type.erl
Labels: backport-v3.9.x

#4092 Use feature flag public API in stream mgmt utils
  deps/rabbitmq_stream_management/src/rabbit_stream_management_utils.erl
Labels: bug, backport-v3.9.x, backport-v3.10.x

#4090 Tolerate unknown fields in stream CLI command requests
  deps/rabbitmq_stream/src/rabbit_stream_reader.erl
Labels: usability, backport-v3.9.x, backport-v3.10.x

#4081 Adopt latest rules_erlang
  WORKSPACE.bazel
Labels: bazel

#4098 Shovel crashes with delete-after=0, causes RabbitMQ to not boot after
  deps/rabbitmq_shovel/src/rabbit_shovel_dyn_worker_sup.erl
  deps/rabbitmq_shovel/src/rabbit_shovel_parameters.erl
  deps/rabbitmq_shovel/test/dynamic_SUITE.erl
Labels: backport-v3.9.x, backport-v3.8.x, backport-v3.10.x

#4103 Oauth2 plugin configuration additional_scopes_key is not converted to the correct Erlang App Config
  deps/rabbitmq_auth_backend_oauth2/priv/schema/rabbitmq_auth_backend_oauth2.schema
  deps/rabbitmq_auth_backend_oauth2/test/config_schema_SUITE_data/rabbitmq_auth_backend_oauth2.snippets
Labels: backport-v3.9.x, backport-v3.8.x, backport-v3.10.x

#4062 Make it possible to skip definition import if imported contents have not changed
  deps/rabbit/priv/schema/rabbit.schema
  deps/rabbit/src/rabbit_definitions.erl
  deps/rabbit/src/rabbit_definitions_hashing.erl
  deps/rabbit/src/rabbit_definitions_import_https.erl
  deps/rabbit/src/rabbit_definitions_import_local_filesystem.erl
  deps/rabbit/src/rabbit_runtime_parameters.erl
  deps/rabbit/test/definition_import_SUITE.erl
  deps/rabbit_common/src/rabbit_misc.erl
  deps/rabbitmq_cli/lib/rabbitmq/cli/ctl/commands/import_definitions_command.ex
  deps/rabbitmq_cli/test/ctl/import_definitions_command_test.exs
Labels: usability, enhancement, backport-v3.10.x

#4108 Support Elixir 1.13
  deps/rabbitmq_cli/lib/rabbitmq/cli/core/command_modules.ex
  deps/rabbitmq_cli/lib/rabbitmq/cli/core/helpers.ex
  deps/rabbitmq_cli/lib/rabbitmq/cli/core/parser.ex
  deps/rabbitmq_cli/lib/rabbitmq/cli/ctl/commands/decode_command.ex
  deps/rabbitmq_cli/lib/rabbitmq/cli/ctl/commands/encode_command.ex
  deps/rabbitmq_cli/mix.exs
  deps/rabbitmq_ct_client_helpers/rabbitmq-components.mk
  deps/rabbitmq_ct_helpers/rabbitmq-components.mk
  rabbitmq-components.mk
Labels: make, backport-v3.9.x, backport-v3.10.x

#4117 Handle stream coordinator error response for topology request
  deps/rabbitmq_stream/src/rabbit_stream_manager.erl
  deps/rabbitmq_stream/src/rabbit_stream_reader.erl
Labels: bug, backport-v3.9.x, backport-v3.10.x

#4110 Allocate less memory when invoking lqueue functions
  deps/rabbit/BUILD.bazel
  deps/rabbit/src/lqueue.erl
  deps/rabbit/src/rabbit_channel.erl
  deps/rabbit/src/rabbit_fifo.erl
  deps/rabbit/src/rabbit_variable_queue.erl
  deps/rabbit/test/lqueue_SUITE.erl
Labels: bazel, backport-v3.10.x

#4124 Allow clearing of user tags while also setting a user password
  deps/rabbit/src/rabbit_auth_backend_internal.erl
  deps/rabbitmq_management/test/rabbit_mgmt_http_SUITE.erl
Labels: backport-v3.9.x, backport-v3.10.x

#4071 Additional testing for CQv2 changes
  deps/rabbit/BUILD.bazel
  deps/rabbit/test/classic_queue_prop_SUITE.erl
Labels: bazel, backport-v3.10.x

#4131 CQv2: Fix Dialyzer warnings
  deps/rabbit/src/rabbit_classic_queue_index_v2.erl
  deps/rabbit/src/rabbit_queue_index.erl
Labels: backport-v3.10.x

#4136 Bump observer_cli to v1.7.2
  deps/rabbitmq_cli/mix.exs
  rabbitmq-components.mk
  workspace_helpers.bzl
Labels: bazel, make, backport-v3.9.x, backport-v3.8.x, backport-v3.10.x

#4144 Initial 3.10 release notes
  release-notes/3.10.0.md
Labels: backport-v3.10.x

#4146 Add option to choose payload encoding when manually publishing a message in the Management UI
  deps/rabbitmq_management/priv/www/js/main.js
  deps/rabbitmq_management/priv/www/js/tmpl/publish.ejs
Labels: backport-v3.10.x

#4143 Allow headers exchange to match headers starting with `x-`
  deps/rabbit/src/rabbit_exchange_type_headers.erl
  deps/rabbit/test/dead_lettering_SUITE.erl
Labels: backport-v3.10.x

#4153 Support Consul 1.11 responses
  deps/rabbitmq_peer_discovery_consul/src/rabbit_peer_discovery_consul.erl
Labels: backport-v3.9.x, backport-v3.8.x, backport-v3.10.x

#4168 Use rules erlang 2.2.0
  WORKSPACE.bazel
  deps/amqp10_client/BUILD.bazel
  deps/amqp_client/BUILD.bazel
  deps/rabbit/BUILD.bazel
  deps/rabbit/apps/rabbitmq_prelaunch/BUILD.bazel
  deps/rabbit_common/BUILD.bazel
  deps/rabbitmq_amqp1_0/BUILD.bazel
  deps/rabbitmq_auth_backend_cache/BUILD.bazel
  deps/rabbitmq_auth_backend_http/BUILD.bazel
  deps/rabbitmq_auth_backend_ldap/BUILD.bazel
  deps/rabbitmq_auth_backend_oauth2/BUILD.bazel
  deps/rabbitmq_auth_mechanism_ssl/BUILD.bazel
  deps/rabbitmq_aws/BUILD.bazel
  deps/rabbitmq_consistent_hash_exchange/BUILD.bazel
  deps/rabbitmq_event_exchange/BUILD.bazel
  deps/rabbitmq_federation/BUILD.bazel
  deps/rabbitmq_federation_management/BUILD.bazel
  deps/rabbitmq_jms_topic_exchange/BUILD.bazel
  deps/rabbitmq_management/BUILD.bazel
  deps/rabbitmq_management_agent/BUILD.bazel
  deps/rabbitmq_mqtt/BUILD.bazel
  deps/rabbitmq_peer_discovery_aws/BUILD.bazel
  deps/rabbitmq_peer_discovery_common/BUILD.bazel
  deps/rabbitmq_peer_discovery_consul/BUILD.bazel
  deps/rabbitmq_peer_discovery_etcd/BUILD.bazel
  deps/rabbitmq_peer_discovery_k8s/BUILD.bazel
  deps/rabbitmq_prometheus/BUILD.bazel
  deps/rabbitmq_random_exchange/BUILD.bazel
  deps/rabbitmq_recent_history_exchange/BUILD.bazel
  deps/rabbitmq_sharding/BUILD.bazel
  deps/rabbitmq_shovel/BUILD.bazel
  deps/rabbitmq_shovel_management/BUILD.bazel
  deps/rabbitmq_stomp/BUILD.bazel
  deps/rabbitmq_stream/BUILD.bazel
  deps/rabbitmq_stream_management/BUILD.bazel
  deps/rabbitmq_top/BUILD.bazel
  deps/rabbitmq_tracing/BUILD.bazel
  deps/rabbitmq_trust_store/BUILD.bazel
  deps/rabbitmq_web_dispatch/BUILD.bazel
  deps/rabbitmq_web_mqtt/BUILD.bazel
  deps/rabbitmq_web_mqtt_examples/BUILD.bazel
  deps/rabbitmq_web_stomp/BUILD.bazel
  deps/rabbitmq_web_stomp_examples/BUILD.bazel
Labels: bazel, backport-v3.9.x, backport-v3.8.x

#4171 Adjust catch clause in rabbitmq_ct_helpers which has been causing flakiness in some suites
  deps/rabbitmq_ct_helpers/src/rabbit_ct_broker_helpers.erl
Labels: backport-v3.9.x, backport-v3.8.x, backport-v3.10.x

#4172 Adjust test to avoid race condition and flake
  deps/amqp_client/test/system_SUITE.erl
Labels: backport-v3.9.x, backport-v3.8.x, backport-v3.10.x

#4182 Adopt latest rules_erlang
  WORKSPACE.bazel
  deps/amqp10_client/BUILD.bazel
  deps/amqp10_client/src/amqp10_client_frame_reader.erl
  deps/amqp_client/BUILD.bazel
  deps/rabbit/BUILD.bazel
  deps/rabbit/apps/rabbitmq_prelaunch/BUILD.bazel
  deps/rabbitmq_amqp1_0/BUILD.bazel
  deps/rabbitmq_auth_backend_cache/BUILD.bazel
  deps/rabbitmq_auth_backend_http/BUILD.bazel
  deps/rabbitmq_auth_backend_ldap/BUILD.bazel
  deps/rabbitmq_auth_backend_oauth2/BUILD.bazel
  deps/rabbitmq_auth_mechanism_ssl/BUILD.bazel
  deps/rabbitmq_consistent_hash_exchange/BUILD.bazel
  deps/rabbitmq_event_exchange/BUILD.bazel
  deps/rabbitmq_federation/BUILD.bazel
  deps/rabbitmq_federation_management/BUILD.bazel
  deps/rabbitmq_jms_topic_exchange/BUILD.bazel
  deps/rabbitmq_management/BUILD.bazel
  deps/rabbitmq_management_agent/BUILD.bazel
  deps/rabbitmq_mqtt/BUILD.bazel
  deps/rabbitmq_peer_discovery_aws/BUILD.bazel
  deps/rabbitmq_peer_discovery_common/BUILD.bazel
  deps/rabbitmq_peer_discovery_consul/BUILD.bazel
  deps/rabbitmq_peer_discovery_etcd/BUILD.bazel
  deps/rabbitmq_peer_discovery_k8s/BUILD.bazel
  deps/rabbitmq_prometheus/BUILD.bazel
  deps/rabbitmq_random_exchange/BUILD.bazel
  deps/rabbitmq_recent_history_exchange/BUILD.bazel
  deps/rabbitmq_sharding/BUILD.bazel
  deps/rabbitmq_shovel/BUILD.bazel
  deps/rabbitmq_shovel_management/BUILD.bazel
  deps/rabbitmq_stomp/BUILD.bazel
  deps/rabbitmq_stream/BUILD.bazel
  deps/rabbitmq_stream_management/BUILD.bazel
  deps/rabbitmq_top/BUILD.bazel
  deps/rabbitmq_tracing/BUILD.bazel
  deps/rabbitmq_trust_store/BUILD.bazel
  deps/rabbitmq_web_dispatch/BUILD.bazel
  deps/rabbitmq_web_mqtt/BUILD.bazel
  deps/rabbitmq_web_mqtt_examples/BUILD.bazel
  deps/rabbitmq_web_stomp/BUILD.bazel
  deps/rabbitmq_web_stomp_examples/BUILD.bazel
Labels: bazel

#4183 Use rules_erlang 2.2.1
  WORKSPACE.bazel
  deps/amqp10_client/BUILD.bazel
  deps/amqp10_client/src/amqp10_client_frame_reader.erl
  deps/amqp_client/BUILD.bazel
  deps/rabbit/BUILD.bazel
  deps/rabbit/apps/rabbitmq_prelaunch/BUILD.bazel
  deps/rabbitmq_amqp1_0/BUILD.bazel
  deps/rabbitmq_auth_backend_cache/BUILD.bazel
  deps/rabbitmq_auth_backend_http/BUILD.bazel
  deps/rabbitmq_auth_backend_ldap/BUILD.bazel
  deps/rabbitmq_auth_backend_oauth2/BUILD.bazel
  deps/rabbitmq_auth_mechanism_ssl/BUILD.bazel
  deps/rabbitmq_consistent_hash_exchange/BUILD.bazel
  deps/rabbitmq_event_exchange/BUILD.bazel
  deps/rabbitmq_federation/BUILD.bazel
  deps/rabbitmq_federation_management/BUILD.bazel
  deps/rabbitmq_jms_topic_exchange/BUILD.bazel
  deps/rabbitmq_management/BUILD.bazel
  deps/rabbitmq_management_agent/BUILD.bazel
  deps/rabbitmq_mqtt/BUILD.bazel
  deps/rabbitmq_peer_discovery_aws/BUILD.bazel
  deps/rabbitmq_peer_discovery_common/BUILD.bazel
  deps/rabbitmq_peer_discovery_consul/BUILD.bazel
  deps/rabbitmq_peer_discovery_etcd/BUILD.bazel
  deps/rabbitmq_peer_discovery_k8s/BUILD.bazel
  deps/rabbitmq_prometheus/BUILD.bazel
  deps/rabbitmq_random_exchange/BUILD.bazel
  deps/rabbitmq_recent_history_exchange/BUILD.bazel
  deps/rabbitmq_sharding/BUILD.bazel
  deps/rabbitmq_shovel/BUILD.bazel
  deps/rabbitmq_shovel_management/BUILD.bazel
  deps/rabbitmq_stomp/BUILD.bazel
  deps/rabbitmq_stream/BUILD.bazel
  deps/rabbitmq_stream_management/BUILD.bazel
  deps/rabbitmq_top/BUILD.bazel
  deps/rabbitmq_tracing/BUILD.bazel
  deps/rabbitmq_trust_store/BUILD.bazel
  deps/rabbitmq_web_dispatch/BUILD.bazel
  deps/rabbitmq_web_mqtt/BUILD.bazel
  deps/rabbitmq_web_mqtt_examples/BUILD.bazel
  deps/rabbitmq_web_stomp/BUILD.bazel
  deps/rabbitmq_web_stomp_examples/BUILD.bazel
Labels: bazel, backport-v3.9.x, backport-v3.8.x

#4194 Use lowercase "connection" in two more log entries
  deps/rabbit/src/rabbit_reader.erl
Labels: backport-v3.10.x

#4198 Additional dialyzer warning fixes
  deps/rabbitmq_amqp1_0/BUILD.bazel
  deps/rabbitmq_auth_backend_oauth2/BUILD.bazel
  deps/rabbitmq_consistent_hash_exchange/BUILD.bazel
  deps/rabbitmq_consistent_hash_exchange/src/rabbit_exchange_type_consistent_hash.erl
  deps/rabbitmq_federation/BUILD.bazel
  deps/rabbitmq_management_agent/BUILD.bazel
  deps/rabbitmq_mqtt/BUILD.bazel
  deps/rabbitmq_shovel/BUILD.bazel
  deps/rabbitmq_shovel/src/rabbit_shovel_status.erl
  deps/rabbitmq_stomp/BUILD.bazel
  deps/rabbitmq_stream/BUILD.bazel
Labels: bazel, backport-v3.9.x, backport-v3.8.x, backport-v3.10.x

#4203 Support `all-with-x` in `x-match` binding argument for headers exchange
  deps/rabbit/src/rabbit_exchange_type_headers.erl
Labels: backport-v3.10.x

#4208 Use rabbitmq 3.9 for mixed version testsing
  WORKSPACE.bazel
  rabbitmq.bzl
Labels: bazel, backport-v3.10.x

#4207 Use the assert_suites function from rules_erlang
  rabbitmq.bzl
Labels: bazel, backport-v3.9.x, backport-v3.8.x, backport-v3.10.x
