Repository rabbitmq/rabbitmq-server, pull requests merged in 2022-07, with the labels that each got.

#5131 Fix read frame_max and heartbeat parameters
  deps/rabbitmq_stream/src/rabbit_stream_sup.erl
Labels: backport-v3.9.x, backport-v3.10.x

#5137 3.10.6 release notes
  release-notes/3.10.6.md
Labels: backport-v3.10.x

#5147 3.9.21 release notes
  release-notes/3.9.21.md
Labels: backport-v3.9.x, backport-v3.10.x

#5150 Add Bazel targets start-cluster and stop-cluster
  BUILD.bazel
  rabbitmq_run.bzl
  scripts/bazel/rabbitmq-run.sh
Labels: bazel, backport-v3.9.x, backport-v3.10.x

#5157 Lower log level on stream creation validation failure
  deps/rabbitmq_stream/src/rabbit_stream_manager.erl
  deps/rabbitmq_stream/src/rabbit_stream_sup.erl
Labels: backport-v3.9.x, backport-v3.10.x

#5155 Add client-side TLS options support to Consul peer discovery
  deps/rabbitmq_peer_discovery_common/src/rabbit_peer_discovery_httpc.erl
  deps/rabbitmq_peer_discovery_consul/priv/schema/rabbitmq_peer_discovery_consul.schema
  deps/rabbitmq_peer_discovery_consul/src/rabbit_peer_discovery_consul.erl
  deps/rabbitmq_peer_discovery_consul/test/rabbitmq_peer_discovery_consul_SUITE.erl
Labels: backport-v3.9.x, backport-v3.10.x

#5166 Make computing checksums for quorum queues configurable
  deps/rabbit/priv/schema/rabbit.schema
  deps/rabbit/src/rabbit_ra_systems.erl
  deps/rabbit/test/config_schema_SUITE_data/rabbit.snippets
Labels: backport-v3.10.x

#5169 Update 3.10.6 release notes
  release-notes/3.10.6.md
Labels: backport-v3.10.x

#5171 Update 3.9.21 release notes
  release-notes/3.9.21.md
Labels: backport-v3.9.x, backport-v3.10.x

#5098 Use our own fork of the bazel-central-registry
  .bazelrc
  MODULE.bazel
  WORKSPACE.bazel
  bazel/bzlmod/extensions.bzl
  bazel/bzlmod/secondary_umbrella.bzl
Labels: bazel, backport-v3.9.x, backport-v3.8.x, backport-v3.10.x

#5192 Optimise rabbit_stream_coordinator:eval_listeners
  deps/rabbit/src/rabbit_stream_coordinator.erl
  deps/rabbit/src/rabbit_stream_coordinator.hrl
Labels: backport-v3.9.x, backport-v3.10.x

#5199 Add process_start_time_seconds metric.
  deps/rabbitmq_prometheus/src/collectors/prometheus_process_collector.erl
  deps/rabbitmq_prometheus/src/rabbit_prometheus_dispatcher.erl
Labels: backport-v3.9.x, backport-v3.10.x

#5223 enhance package-generic-unix bazel macro
  BUILD.bazel
  dist.bzl
Labels: bazel, backport-v3.9.x, backport-v3.8.x, backport-v3.10.x

#4328 Continuously run powershell to get disk free space
  deps/rabbit/src/rabbit_disk_monitor.erl
  deps/rabbit_common/src/rabbit_misc.erl
Labels: backport-v3.10.x

#5203 Ensure rabbit_index_route table is created after joining a cluster
  deps/rabbit/BUILD.bazel
  deps/rabbit/src/rabbit_mnesia.erl
  deps/rabbit/src/rabbit_table.erl
  deps/rabbit/test/direct_exchange_routing_v2_SUITE.erl
  deps/rabbit/test/direct_exchange_routing_v2_post_3_11_SUITE.erl
Labels: bazel

#5248 Be less noisy when sysctl cannot be used for vm_memory_monitor
  deps/rabbit_common/src/vm_memory_monitor.erl
Labels: backport-v3.9.x, backport-v3.10.x

#5254 Use new feature flags API for direct_exchange_routing_v2
  deps/rabbit/BUILD.bazel
  deps/rabbit/src/rabbit_binding.erl
  deps/rabbit/src/rabbit_core_ff.erl
  deps/rabbit/src/rabbit_mnesia.erl
  deps/rabbit/src/rabbit_networking.erl
  deps/rabbit/src/rabbit_table.erl
  deps/rabbit/test/direct_exchange_routing_v2_SUITE.erl
  deps/rabbit/test/direct_exchange_routing_v2_post_3_11_SUITE.erl
Labels: bazel

#5280 Split the OCI workflow into a nightly and on push phase for less flakiness
  .github/workflows/oci-base.yaml
  .github/workflows/oci.yaml
  packaging/base-image/Dockerfile
  packaging/docker-image/Dockerfile
Labels: backport-v3.9.x, backport-v3.8.x, backport-v3.10.x

#5284 OCI workflow updates from master
  .github/workflows/oci-base.yaml
  .github/workflows/oci.yaml
  packaging/base-image/Dockerfile
  packaging/docker-image/Dockerfile
  packaging/docker-image/otp-versions/otp-max.yaml
  packaging/docker-image/otp-versions/otp-min.yaml
Labels: backport-v3.9.x, backport-v3.8.x

#5291 Adopt otp 25.0.3
  bazel/toolchains/BUILD.bazel
Labels: bazel, backport-v3.9.x, backport-v3.8.x, backport-v3.10.x

#5290 Adopt otp 24.3.4.2
  bazel/toolchains/BUILD.bazel
Labels: bazel, backport-v3.9.x, backport-v3.8.x, backport-v3.10.x

#5289 Adopt otp 23.3.4.16
  bazel/toolchains/BUILD.bazel
Labels: bazel, backport-v3.9.x, backport-v3.8.x, backport-v3.10.x

#5302 Restore the mixed-ness of mixed version testing
  deps/rabbitmq_ct_helpers/src/rabbit_ct_helpers.erl
  rabbitmq.bzl
Labels: bazel, backport-v3.9.x, backport-v3.8.x, backport-v3.10.x

#5317 Bazel: Set `$RABBITMQ_FEATURE_FLAGS` to the list of required flags in 3.11.0
  rabbitmq.bzl
Labels: bazel

#5324 Avoid direct references to jsx
  deps/rabbit/apps/rabbitmq_prelaunch/src/rabbit_logger_json_fmt.erl
  deps/rabbit/test/honeycomb_cth.erl
  deps/rabbit/test/logging_SUITE.erl
  deps/rabbitmq_auth_backend_oauth2/test/jwks_http_handler.erl
Labels: backport-v3.9.x, backport-v3.8.x, backport-v3.10.x

#5323 HTTP API: allow for setting a few extra security-related response headers
  deps/rabbitmq_management/priv/schema/rabbitmq_management.schema
  deps/rabbitmq_management/src/rabbit_mgmt_headers.erl
  deps/rabbitmq_management/test/config_schema_SUITE_data/rabbitmq_management.snippets
Labels: backport-v3.10.x

#5305 Configure default queue type by vhost
  deps/rabbit/src/rabbit_amqqueue.erl
  deps/rabbit/src/rabbit_channel.erl
  deps/rabbit/src/rabbit_classic_queue.erl
  deps/rabbit/src/rabbit_queue_type.erl
  deps/rabbit/src/rabbit_quorum_queue.erl
  deps/rabbit/src/rabbit_stream_queue.erl
  deps/rabbit/src/rabbit_vhost.erl
  deps/rabbit/src/vhost.erl
  deps/rabbit/test/quorum_queue_SUITE.erl
  deps/rabbitmq_cli/lib/rabbitmq/cli/ctl/commands/add_vhost_command.ex
  deps/rabbitmq_cli/lib/rabbitmq/cli/ctl/commands/list_vhosts_command.ex
  deps/rabbitmq_cli/test/ctl/add_vhost_command_test.exs
  deps/rabbitmq_management/priv/www/js/tmpl/vhosts.ejs
  deps/rabbitmq_management/src/rabbit_mgmt_wm_vhost.erl
Labels: backport-v3.10.x

#5331 Add retry for erl_epmd:port_please
  deps/rabbit/src/rabbit_networking.erl
  deps/rabbit_common/src/rabbit_nodes_common.erl
Labels: backport-v3.9.x, backport-v3.10.x

#5332 Stream queue suite flake fixes
  deps/rabbit/src/rabbit_stream_coordinator.erl
  deps/rabbit/test/rabbit_stream_queue_SUITE.erl
Labels: bazel, make

#5336 Mixed Version Testing uses bytecode compiled for test (in bazel)
  .github/workflows/secondary-umbrella.yaml
  bazel/bzlmod/secondary_umbrella.bzl
  bazel/secondary-umbrella.patch
  deps/rabbitmq_cli/test/fixtures/plugins/plugins_with_version_requirements/mock_rabbitmq_plugin_for_3_8-0.1.0/ebin/mock_rabbitmq_plugin_for_3_8.app
  rabbitmq.bzl
Labels: bazel, backport-v3.9.x, backport-v3.8.x, backport-v3.10.x

#5342 Pin Osiris to 1.2.8
  MODULE.bazel
  deps/rabbit/Makefile
  workspace_helpers.bzl
Labels: bazel, make, backport-v3.9.x, backport-v3.10.x

#5325 Fix rabbit_index_route inconsistencies
  deps/rabbit/BUILD.bazel
  deps/rabbit/src/rabbit_binding.erl
  deps/rabbit/src/rabbit_table.erl
  deps/rabbit/test/direct_exchange_routing_v2_SUITE.erl
Labels: bazel

#5353 Adopt elixir 1.13.4
  bazel/toolchains/BUILD.bazel
Labels: bazel, backport-v3.9.x, backport-v3.8.x, backport-v3.10.x, backport-v3.11.x

#5352 Adopt elixir 1.12.3
  bazel/toolchains/BUILD.bazel
Labels: bazel, backport-v3.9.x, backport-v3.8.x, backport-v3.10.x, backport-v3.11.x

#5359 Fold trust_store_http dependency into this repository
  .gitignore
  deps/rabbitmq_trust_store/BUILD.bazel
  deps/rabbitmq_trust_store/Makefile
  deps/trust_store_http/.gitignore
  deps/trust_store_http/BUILD.bazel
  deps/trust_store_http/Makefile
  deps/trust_store_http/README.md
  deps/trust_store_http/rel/sys.config
  deps/trust_store_http/rel/vm.args
  deps/trust_store_http/relx.config
  deps/trust_store_http/src/trust_store_http.erl
  deps/trust_store_http/src/trust_store_http_app.erl
  deps/trust_store_http/src/trust_store_http_sup.erl
  deps/trust_store_http/src/trust_store_invalid_handler.erl
  deps/trust_store_http/src/trust_store_list_handler.erl
Labels: bazel, make, backport-v3.9.x, backport-v3.8.x, backport-v3.10.x, backport-v3.11.x

#5351 Adopt elixir 1.10.4
  bazel/toolchains/BUILD.bazel
Labels: bazel, backport-v3.9.x, backport-v3.8.x, backport-v3.10.x, backport-v3.11.x

#5372 Remove old reference to external trust-store-http
  MODULE.bazel
  deps/rabbitmq_trust_store/BUILD.bazel
  workspace_helpers.bzl
Labels: bazel, backport-v3.9.x, backport-v3.8.x, backport-v3.10.x, backport-v3.11.x

#5253 rabbit_stream: Use rabbit_feature_flags, not `rabbit_ff_registry`
  deps/rabbitmq_stream/src/rabbit_stream.erl
Labels: bug

#5358 Add more direct_exchange_routing_v2 tests
  .github/workflows/oci.yaml
  .github/workflows/test-mixed-versions.yaml
  .github/workflows/test.yaml
  deps/rabbit/test/direct_exchange_routing_v2_SUITE.erl
  deps/rabbit/test/direct_exchange_routing_v2_SUITE_data/definition.json
Labels: bazel, backport-v3.11.x

#5350 Bump the rabbitmq version on this branch to 3.12.0 (bazel)
  deps/rabbitmq_cli/test/fixtures/plugins/plugins_with_version_requirements/mock_rabbitmq_plugin_for_3_8-0.1.0/ebin/mock_rabbitmq_plugin_for_3_8.app
  rabbitmq.bzl
Labels: bazel

#5239 Remove pre-user_limits compatibility code
  deps/rabbit/src/internal_user.erl
  deps/rabbit/src/internal_user_v1.erl
  deps/rabbit/src/rabbit_auth_backend_internal.erl
  deps/rabbit/test/definition_import_SUITE.erl
  deps/rabbit/test/per_user_connection_channel_limit_SUITE.erl
  deps/rabbit/test/per_user_connection_channel_limit_partitions_SUITE.erl
  deps/rabbit/test/per_user_connection_channel_tracking_SUITE.erl
  deps/rabbitmq_management/BUILD.bazel
  deps/rabbitmq_management/test/rabbit_mgmt_http_SUITE.erl
  deps/rabbitmq_stream/test/rabbit_stream_SUITE.erl
Labels: bazel

#5388 Direct exchange routing v2 more tests
  deps/rabbit/src/rabbit_binding.erl
  deps/rabbit/src/rabbit_core_ff.erl
  deps/rabbit/test/direct_exchange_routing_v2_SUITE.erl
Labels: backport-v3.11.x

#5390 Remove pre-implicit_default_bindings compatibility code
  deps/rabbit/src/rabbit_binding.erl
  deps/rabbit/src/rabbit_fifo_dlx_worker.erl
  deps/rabbitmq_stream/test/rabbit_stream_SUITE.erl
Labels: backport-v3.11.x

#5392 Channel PID as primary key of channel tracking ETS table
  deps/rabbit/src/rabbit_channel_tracking.erl
  deps/rabbit/src/rabbit_mnesia.erl
Labels: backport-v3.11.x

#5385 Add conditional logging to text formatter
  deps/rabbit/apps/rabbitmq_prelaunch/src/rabbit_logger_text_fmt.erl
  deps/rabbit/test/logging_SUITE.erl
Labels: backport-v3.9.x, backport-v3.10.x, backport-v3.11.x

#5356 Replace JSON library: move from JSX to Thoas
  MODULE.bazel
  deps/rabbit/apps/rabbitmq_prelaunch/BUILD.bazel
  deps/rabbit/apps/rabbitmq_prelaunch/Makefile
  deps/rabbit/apps/rabbitmq_prelaunch/src/rabbit_logger_json_fmt.erl
  deps/rabbit/src/rabbit_auth_backend_internal.erl
  deps/rabbit/src/rabbit_policy.erl
  deps/rabbit/src/rabbit_runtime_parameters.erl
  deps/rabbit/src/rabbit_vhost_limit.erl
  deps/rabbit/test/logging_SUITE.erl
  deps/rabbit_common/BUILD.bazel
  deps/rabbit_common/Makefile
  deps/rabbit_common/src/rabbit_json.erl
  deps/rabbitmq_aws/src/rabbitmq_aws_json.erl
  deps/rabbitmq_aws/test/src/rabbitmq_aws_json_tests.erl
  deps/rabbitmq_ct_helpers/src/rabbit_mgmt_test_util.erl
  deps/rabbitmq_management/test/rabbit_mgmt_http_SUITE.erl
  deps/rabbitmq_management/test/rabbit_mgmt_only_http_SUITE.erl
  deps/rabbitmq_management/test/rabbit_mgmt_rabbitmqadmin_SUITE.erl
  deps/trust_store_http/BUILD.bazel
  deps/trust_store_http/Makefile
  deps/trust_store_http/src/trust_store_list_handler.erl
  rabbitmq-components.mk
  workspace_helpers.bzl
Labels: bazel, make, backport-v3.11.x
