Repository rabbitmq/rabbitmq-server, pull requests merged in 2022-04, with the labels that each got.

#4402 Attempt to reduce flakes in aws integration tests
  deps/rabbitmq_peer_discovery_aws/test/aws_ecs_util.erl
  deps/rabbitmq_peer_discovery_aws/test/integration_SUITE.erl
Labels: backport-v3.9.x, backport-v3.8.x, backport-v3.10.x

#4408 Fixed reading SSL settings from rabbitmqadmin config file
  deps/rabbitmq_management/bin/rabbitmqadmin
Labels: backport-v3.9.x, backport-v3.10.x

#4411 Update 3.10.0 release notes
  release-notes/3.10.0.md
Labels: backport-v3.10.x

#4413 Initial 3.9.15 release notes
  release-notes/3.9.15.md
Labels: backport-v3.9.x

#4416 Minor 3.10.0 release notes corrections
  release-notes/3.10.0.md
Labels: backport-v3.10.x

#4418 Proactively add #4376 to 3.10.0 release notes
  release-notes/3.10.0.md
Labels: backport-v3.10.x

#4420 Proactively add #4376 to release notes
  release-notes/3.9.15.md
Labels: backport-v3.9.x, backport-v3.10.x

#4377 Fix next_seq_id value when none is found in terms
  deps/rabbit/src/rabbit_variable_queue.erl
Labels: backport-v3.10.x

#4376 Update Prometheus.erl to 4.8.2
  rabbitmq-components.mk
  workspace_helpers.bzl
Labels: bazel, make, backport-v3.9.x, backport-v3.10.x

#4400 CQv2: Consolidate index writes when possible
  deps/rabbit/src/rabbit_classic_queue_index_v2.erl
Labels: backport-v3.10.x

#4435 Erlang 25 compat: drop a duplicate flaky test
  deps/rabbitmq_federation/test/exchange_SUITE.erl
  deps/rabbitmq_federation/test/queue_SUITE.erl
Labels: backport-v3.9.x, backport-v3.10.x, erlang-25

#4438 Update rabbitmq.conf.example to mention QQ support for MQTT
  deps/rabbit/docs/rabbitmq.conf.example
Labels: backport-v3.10.x

#4443 Remove max-in-memory-* in Management UI
  deps/rabbitmq_management/priv/www/js/global.js
  deps/rabbitmq_management/priv/www/js/tmpl/policies.ejs
  deps/rabbitmq_management/priv/www/js/tmpl/queues.ejs
Labels: backport-v3.10.x

#4431 CQv1: Disable expensive stats killing v1 performance
  deps/rabbit/src/rabbit_queue_index.erl
  deps/rabbit_common/src/file_handle_cache.erl
  deps/rabbit_common/src/file_handle_cache_stats.erl
  deps/rabbitmq_management/priv/www/js/tmpl/node.ejs
  deps/rabbitmq_management/src/rabbit_mgmt_stats.erl
  deps/rabbitmq_management/test/rabbit_mgmt_stats_SUITE.erl
  deps/rabbitmq_management_agent/include/rabbit_mgmt_metrics.hrl
  deps/rabbitmq_management_agent/src/rabbit_mgmt_metrics_collector.erl
  deps/rabbitmq_prometheus/metrics-detailed.md
  deps/rabbitmq_prometheus/metrics.md
  deps/rabbitmq_prometheus/src/collectors/prometheus_rabbitmq_core_metrics_collector.erl
Labels: backport-v3.10.x, performance

#4451 Upgrade ra to 2.0.7
  rabbitmq-components.mk
  release-notes/3.10.0.md
  release-notes/3.9.15.md
  workspace_helpers.bzl
Labels: bazel, make

#4452 Update 3.10.0 release notes
  release-notes/3.10.0.md
Labels: backport-v3.10.x

#4458 Fix report crashing priority queues
  deps/rabbit/src/rabbit_priority_queue.erl
  deps/rabbit/test/priority_queue_SUITE.erl
Labels: backport-v3.9.x, backport-v3.8.x, backport-v3.10.x

#4440 Updates for rules_erlang 2.5.0
  BUILD.ranch
  WORKSPACE.bazel
  deps/amqp10_client/BUILD.bazel
  deps/amqp10_common/BUILD.bazel
  deps/amqp_client/BUILD.bazel
  deps/rabbit/BUILD.bazel
  deps/rabbit/test/feature_flags_SUITE_data/my_plugin/BUILD.bazel
  deps/rabbit_common/BUILD.bazel
  deps/rabbitmq_amqp1_0/BUILD.bazel
  deps/rabbitmq_auth_backend_cache/BUILD.bazel
  deps/rabbitmq_auth_backend_http/BUILD.bazel
  deps/rabbitmq_auth_backend_ldap/BUILD.bazel
  deps/rabbitmq_auth_mechanism_ssl/BUILD.bazel
  deps/rabbitmq_cli/rabbitmqctl_test.bzl
  deps/rabbitmq_consistent_hash_exchange/BUILD.bazel
  deps/rabbitmq_event_exchange/BUILD.bazel
  deps/rabbitmq_federation/BUILD.bazel
  deps/rabbitmq_federation_management/BUILD.bazel
  deps/rabbitmq_management/BUILD.bazel
  deps/rabbitmq_management_agent/BUILD.bazel
  deps/rabbitmq_mqtt/BUILD.bazel
  deps/rabbitmq_recent_history_exchange/BUILD.bazel
  deps/rabbitmq_sharding/BUILD.bazel
  deps/rabbitmq_shovel/BUILD.bazel
  deps/rabbitmq_shovel_management/BUILD.bazel
  deps/rabbitmq_stomp/BUILD.bazel
  deps/rabbitmq_stream/src/rabbit_stream_metrics_gc.erl
  deps/rabbitmq_top/BUILD.bazel
  deps/rabbitmq_tracing/BUILD.bazel
  deps/rabbitmq_trust_store/BUILD.bazel
  deps/rabbitmq_web_dispatch/BUILD.bazel
  deps/rabbitmq_web_stomp/BUILD.bazel
  rabbitmq.bzl
  workspace_helpers.bzl
Labels: bazel, backport-v3.9.x, backport-v3.8.x, backport-v3.10.x

#4472 rules_erlang 2.5.1
  WORKSPACE.bazel
  deps/amqp10_client/BUILD.bazel
  deps/rabbit/BUILD.bazel
  deps/rabbitmq_aws/BUILD.bazel
  deps/rabbitmq_web_mqtt/BUILD.bazel
Labels: bazel, backport-v3.9.x

#4456 Adopt latest rules_erlang
  WORKSPACE.bazel
Labels: bazel

#4474 Attempt to make the OCI workflow behave reasonably for PRs
  .github/workflows/oci.yaml
Labels: backport-v3.9.x, backport-v3.8.x, backport-v3.10.x

#4463 Bugfix: check unsupported policies on queue.declare
  deps/rabbit/src/rabbit_amqqueue.erl
  deps/rabbit/src/rabbit_policy.erl
  deps/rabbit/test/quorum_queue_SUITE.erl
Labels: backport-v3.9.x, backport-v3.8.x, backport-v3.10.x

#4468 Fix migrate leadership timeout
  deps/rabbit/src/rabbit_maintenance.erl
  deps/rabbit/src/rabbit_mirror_queue_misc.erl
Labels: backport-v3.9.x, backport-v3.10.x

#4490 Another 3.9.15 release note update
  release-notes/3.9.15.md
Labels: backport-v3.9.x, backport-v3.10.x

#4495 Correct a management UI metric description
  deps/rabbitmq_management/priv/www/js/global.js
Labels: backport-v3.9.x, backport-v3.8.x, backport-v3.10.x

#4499 Upgrade eetcd to 0.3.5
  deps/rabbitmq_peer_discovery_etcd/Makefile
  release-notes/3.10.0.md
  release-notes/3.9.15.md
  workspace_helpers.bzl
Labels: bazel, make, backport-v3.9.x, backport-v3.10.x

#4502 AWS peer discovery integration suite: squash a compiler warning
  deps/rabbitmq_peer_discovery_aws/test/integration_SUITE.erl
Labels: backport-v3.9.x, backport-v3.8.x, backport-v3.10.x

#4506 Adopt otp 24.3.3 for OCI workflow
  packaging/docker-image/otp-versions/otp-max.yaml
Labels: backport-v3.9.x, backport-v3.8.x, backport-v3.10.x

#4513 3.8.29 release notes
  release-notes/3.8.29.md
Labels: backport-v3.9.x, backport-v3.8.x, backport-v3.10.x

#4511 Handle machine upgrades incrementally in stream coordinator
  deps/rabbit/src/rabbit_stream_coordinator.erl
  deps/rabbit/test/rabbit_stream_coordinator_SUITE.erl
Labels: backport-v3.9.x, backport-v3.10.x

#4519 Add #4510 to 3.9.15 release notes
  release-notes/3.9.15.md
Labels: backport-v3.9.x, backport-v3.10.x

#4524 Speed up reimport queue definitions
  deps/rabbit/src/rabbit_definitions.erl
  deps/rabbit/test/definition_import_SUITE.erl
  deps/rabbit/test/definition_import_SUITE_data/case13a.json
Labels: backport-v3.9.x, backport-v3.10.x, performance

#4543 Update 3.8.29 release notes
  release-notes/3.8.29.md
Labels: backport-v3.9.x, backport-v3.8.x, backport-v3.10.x

#4545 Update 3.9.15 release notes
  release-notes/3.9.15.md
Labels: backport-v3.9.x, backport-v3.10.x

#4542 SI prefix formatter improvement
  deps/rabbitmq_management/priv/www/js/formatters.js
Labels: backport-v3.9.x, backport-v3.8.x, backport-v3.10.x

#4553 SI binary prefix fix (ki => Ki)
  deps/rabbitmq_management/priv/www/js/formatters.js
Labels: backport-v3.9.x, backport-v3.8.x, backport-v3.10.x

#4558 CQ: Fix potential crash when collecting stats
  deps/rabbit/src/rabbit_amqqueue_process.erl
Labels: backport-v3.10.x

#4567 Make await_online_synchronized_mirror no-op in single-node clusters
  deps/rabbitmq_cli/lib/rabbitmq/cli/upgrade/commands/await_online_synchronized_mirror_command.ex
Labels: backport-v3.9.x, backport-v3.8.x, backport-v3.10.x

#4566 Add filter for "Discarding message..." messages
  deps/rabbit/apps/rabbitmq_prelaunch/src/rabbit_prelaunch_early_logging.erl
Labels: backport-v3.9.x, backport-v3.10.x

#4578 Speed up reimport exchange definitions
  deps/rabbit/src/rabbit_definitions.erl
Labels: backport-v3.9.x, backport-v3.8.x, backport-v3.10.x

#4586 Bump observer_cli to 1.7.3
  deps/rabbitmq_cli/mix.exs
  rabbitmq-components.mk
  release-notes/3.10.0.md
  workspace_helpers.bzl
Labels: bazel, make, backport-v3.10.x

#4589 Initial 3.8.30 release notes
  release-notes/3.8.30.md
Labels: backport-v3.9.x, backport-v3.8.x, backport-v3.10.x

#4593 Initial 3.9.16 release notes
  release-notes/3.9.16.md
Labels: backport-v3.9.x, backport-v3.10.x

#4572 Validate queue and consumer arguments
  deps/rabbit/src/rabbit_amqqueue.erl
  deps/rabbit/src/rabbit_classic_queue.erl
  deps/rabbit/src/rabbit_queue_type.erl
  deps/rabbit/src/rabbit_quorum_queue.erl
  deps/rabbit/src/rabbit_stream_queue.erl
  deps/rabbit/test/quorum_queue_SUITE.erl
  deps/rabbit/test/rabbit_fifo_dlx_integration_SUITE.erl
  deps/rabbit/test/rabbit_stream_queue_SUITE.erl
Labels: backport-v3.10.x

#4596 Update 3.10 release notes
  release-notes/3.10.0.md
Labels: backport-v3.10.x

#4579 Use "native" erlang.mk publishing for hex
  .gitignore
  deps/amqp10_client/Makefile
  deps/amqp10_common/Makefile
  deps/amqp_client/Makefile
  deps/rabbit_common/Makefile
  deps/rabbit_common/mk/rabbitmq-components.hexpm.mk
  deps/rabbit_common/mk/rabbitmq-hexpm.mk
Labels: make

#4600 Merge pull request #4579 from rabbitmq/rabbitmq-server-4577
  .gitignore
  deps/amqp10_client/Makefile
  deps/amqp10_common/Makefile
  deps/amqp_client/Makefile
  deps/rabbit_common/Makefile
  deps/rabbit_common/mk/rabbitmq-components.hexpm.mk
  deps/rabbit_common/mk/rabbitmq-hexpm.mk
Labels: make

#4602 Bump Osiris to 1.2.5 in v3.9.x
  deps/rabbit/Makefile
  release-notes/3.9.16.md
  workspace_helpers.bzl
Labels: bazel, make

#4603 Correct GitHub repo links in Hex metadata
  deps/amqp10_client/Makefile
  deps/amqp10_common/Makefile
  deps/amqp_client/Makefile
  deps/rabbit_common/Makefile
Labels: make

#4610 Optimise local RPC call when starting Ra cluster
  deps/rabbit/src/rabbit_quorum_queue.erl
Labels: backport-v3.10.x

#4604 OAuth 2: support for scope aliases
  deps/rabbitmq_auth_backend_oauth2/src/rabbit_auth_backend_oauth2.erl
  deps/rabbitmq_auth_backend_oauth2/test/rabbit_auth_backend_oauth2_test_util.erl
  deps/rabbitmq_auth_backend_oauth2/test/system_SUITE.erl
  deps/rabbitmq_auth_backend_oauth2/test/unit_SUITE.erl
  release-notes/3.10.0.md
Labels: bazel, make, backport-v3.10.x

#4620 Update 3.10 release highlights
  release-notes/3.10.0.md
Labels: backport-v3.10.x

#4624 Port #4603 to v3.10.x
  deps/amqp10_client/Makefile
  deps/amqp10_common/Makefile
  deps/amqp_client/Makefile
  deps/rabbit_common/Makefile
Labels: make

#4625 Port 4603 and related to 3.8.x
  .gitignore
  deps/amqp10_client/Makefile
  deps/amqp10_common/Makefile
  deps/amqp_client/Makefile
  deps/rabbit_common/Makefile
  deps/rabbit_common/mk/rabbitmq-components.hexpm.mk
  deps/rabbit_common/mk/rabbitmq-hexpm.mk
Labels: make

#4631 Add helpers for quickly opening test logs from bazel
  BUILD.bazel
Labels: bazel, backport-v3.9.x, backport-v3.8.x, backport-v3.10.x

#4630 Adopt latest rabbitmq-server-buildenv:linux-erlang-24.3 for RBE
  WORKSPACE.bazel
Labels: bazel, backport-v3.9.x, backport-v3.8.x, backport-v3.10.x

#4629 Adopt latest rabbitmq-server-buildenv:linux-erlang-23.3 for RBE
  WORKSPACE.bazel
Labels: bazel, backport-v3.9.x, backport-v3.8.x, backport-v3.10.x

#4628 Adopt latest rules_erlang
  WORKSPACE.bazel
Labels: bazel

#4643 Bump Osiris to 1.2.6
  deps/rabbit/Makefile
  release-notes/3.9.16.md
  workspace_helpers.bzl
Labels: bazel, make

#4644 Use rules_erlang 2.5.2
  WORKSPACE.bazel
Labels: bazel, backport-v3.9.x, backport-v3.8.x

#4647 v3.10.x: pin Osiris to 1.2.6
  BUILD.osiris
  deps/rabbit/Makefile
  workspace_helpers.bzl
Labels: bazel, make

#4645 Expose head_message_timestamp via Prometheus plugin as well
  deps/rabbitmq_prometheus/metrics-detailed.md
  deps/rabbitmq_prometheus/src/collectors/prometheus_rabbitmq_core_metrics_collector.erl
Labels: backport-v3.9.x, backport-v3.10.x

#4649 Fix info(all_keys) for stream queues
  deps/rabbit/src/rabbit_stream_queue.erl
Labels: backport-v3.9.x, backport-v3.10.x

#4656 Update 3.9.16 release notes
  release-notes/3.10.0.md
  release-notes/3.9.16.md
Labels: backport-v3.9.x, backport-v3.10.x

#4659 Adopt latest rules_erlang
  WORKSPACE.bazel
Labels: bazel

#4662 Add a MODULE.bazel file and enable bzlmod
  .bazelrc
  .github/workflows/test-windows.yaml
  MODULE.bazel
  WORKSPACE.bazel
  deps/rabbit/BUILD.bazel
  deps/rabbit_common/BUILD.bazel
  workspace_helpers.bzl
Labels: bazel, backport-v3.9.x, backport-v3.8.x, backport-v3.10.x

#4665 OAuth 2: expand all scope aliases provided
  deps/rabbit_common/src/rabbit_data_coercion.erl
  deps/rabbitmq_auth_backend_oauth2/src/rabbit_auth_backend_oauth2.erl
  deps/rabbitmq_auth_backend_oauth2/test/rabbit_auth_backend_oauth2_test_util.erl
  deps/rabbitmq_auth_backend_oauth2/test/system_SUITE.erl
  deps/rabbitmq_auth_backend_oauth2/test/unit_SUITE.erl
Labels: backport-v3.10.x

#4671 Add set_user_limits to rabbitmqctl(8)
  deps/rabbit/docs/rabbitmqctl.8
Labels: doc, backport-v3.9.x, backport-v3.8.x, backport-v3.10.x

#4675 Add clear_user_limits to rabbitmqctl(8)
  deps/rabbit/docs/rabbitmqctl.8
Labels: doc, backport-v3.9.x, backport-v3.8.x, backport-v3.10.x

#4681 Remove a stray ct:pal/2 call in production code
  deps/rabbitmq_auth_backend_oauth2/src/rabbit_auth_backend_oauth2.erl
Labels: backport-v3.10.x

#4684 Drop -Wrace_conditions from Dialyzer opts
  erlang.mk
Labels: make, backport-v3.9.x, backport-v3.8.x, backport-v3.10.x, erlang-25

#4689 Drop -Wrace_conditions from Dialyzer opts in more places
  deps/rabbit/src/rabbit_channel_tracking.erl
  deps/rabbit/src/rabbit_connection_tracking.erl
  deps/rabbit_common/mk/rabbitmq-early-test.mk
Labels: make, backport-v3.9.x, backport-v3.8.x, backport-v3.10.x, erlang-25
