Repository rabbitmq/rabbitmq-server, pull requests merged in 2022-03, with the labels that each got.

#4218 Fix `rabbitmqctl list_queues --help` output
  deps/rabbitmq_cli/lib/rabbitmq/cli/ctl/commands/list_queues_command.ex
Labels: backport-v3.9.x, backport-v3.10.x

#4233 Wait between retries if nxdomain
  deps/rabbit_common/src/rabbit_nodes_common.erl
Labels: backport-v3.9.x, backport-v3.10.x

#4242 Make it possible to delete or restart a dynamic Shovel on/from any cluster node (take two)
  deps/rabbitmq_shovel/src/Elixir.RabbitMQ.CLI.Ctl.Commands.DeleteShovelCommand.erl
  deps/rabbitmq_shovel/src/Elixir.RabbitMQ.CLI.Ctl.Commands.RestartShovelCommand.erl
  deps/rabbitmq_shovel/src/rabbit_shovel_status.erl
  deps/rabbitmq_shovel_management/BUILD.bazel
  deps/rabbitmq_shovel_management/priv/www/js/shovel.js
  deps/rabbitmq_shovel_management/src/rabbit_shovel_mgmt.erl
  deps/rabbitmq_shovel_management/src/rabbit_shovel_mgmt.hrl
  deps/rabbitmq_shovel_management/src/rabbit_shovel_mgmt_util.erl
  deps/rabbitmq_shovel_management/test/rabbit_shovel_mgmt_SUITE.erl
Labels: bazel, make, backport-v3.10.x

#4253 Disable kernel.prevent_overlapping_partitions early on boot
  deps/rabbit/apps/rabbitmq_prelaunch/src/rabbit_prelaunch_conf.erl
  deps/rabbit/scripts/rabbitmq-server
  deps/rabbit/scripts/rabbitmq-server.bat
  deps/rabbit/scripts/rabbitmq-service.bat
Labels: backport-v3.9.x, backport-v3.10.x

#4258 rabbitmqct {encode, decode}: accept more values via standard input
  deps/rabbitmq_cli/lib/rabbitmq/cli/core/input.ex
  deps/rabbitmq_cli/lib/rabbitmq/cli/ctl/commands/decode_command.ex
  deps/rabbitmq_cli/lib/rabbitmq/cli/ctl/commands/encode_command.ex
  deps/rabbitmq_cli/test/ctl/decode_command_test.exs
  deps/rabbitmq_cli/test/ctl/encode_command_test.exs
Labels: backport-v3.10.x

#4261 Pin unpinned deps
  rabbitmq-components.mk
  release-notes/3.10.0.md
  workspace_helpers.bzl
Labels: bazel, make

#4264 Attempt to reduce test flakes in consistent_hash_exchange suite
  deps/rabbitmq_consistent_hash_exchange/BUILD.bazel
  deps/rabbitmq_consistent_hash_exchange/test/rabbit_exchange_type_consistent_hash_SUITE.erl
Labels: bazel, backport-v3.9.x, backport-v3.8.x, backport-v3.10.x

#4214 Adopt latest rules_erlang
  WORKSPACE.bazel
Labels: bazel

#4285 LDAP: match on tuples instead of the #eldap_search_result record for OTP 24.3 compat
  deps/rabbitmq_auth_backend_ldap/src/rabbit_auth_backend_ldap.erl
Labels: usability, rabbitmq-auth-backend-ldap, erlang-24, backport-v3.9.x, backport-v3.8.x, backport-v3.10.x

#4289 Update 3.9.14 release notes
  release-notes/3.9.14.md
Labels: backport-v3.9.x, backport-v3.10.x

#4293 Adopt latest rabbitmq-server-buildenv:linux-erlang-24.3 for RBE
  WORKSPACE.bazel
Labels: bazel, backport-v3.9.x, backport-v3.8.x, backport-v3.10.x

#4297 Make backing_queue_SUITE fast on macOS
  deps/rabbit/test/backing_queue_SUITE.erl
Labels: backport-v3.9.x, backport-v3.8.x, backport-v3.10.x

#4301 3.8.28 release notes
  release-notes/3.8.28.md
Labels: backport-v3.8.x

#4272 Adjust assertions in an effort to reduce flakes
  deps/rabbit/test/rabbit_fifo_dlx_integration_SUITE.erl
Labels: backport-v3.10.x

#4306 Adopt latest rules_erlang
  WORKSPACE.bazel
Labels: bazel

#4307 Naming from #4305
  deps/rabbit/src/rabbit_channel.erl
Labels: backport-v3.9.x, backport-v3.8.x, backport-v3.10.x

#4308 Adopt latest rabbitmq-server-buildenv:linux-erlang-23.3 for RBE
  WORKSPACE.bazel
Labels: bazel, backport-v3.9.x, backport-v3.8.x, backport-v3.10.x

#4323 Allow selective cli test runs with --test_env TEST_FILE
  deps/rabbitmq_cli/rabbitmqctl_test.bzl
Labels: backport-v3.9.x, backport-v3.8.x, backport-v3.10.x

#4322 Use bazel for building the oci in github actions
  .github/workflows/oci.yaml
  workspace_helpers.bzl
Labels: backport-v3.9.x, backport-v3.8.x, backport-v3.10.x

#4329 Fix return value of now_to_str
  deps/rabbitmq_management_agent/src/rabbit_mgmt_format.erl
Labels: backport-v3.10.x

#4327 CQv2 index: Increase threshold before flushing to disk
  deps/rabbit/src/rabbit_classic_queue_index_v2.erl
Labels: backport-v3.10.x

#4343 Make Quorum queue snapshot interval configurable
  deps/rabbit/src/rabbit_quorum_queue.erl
Labels: backport-v3.9.x, backport-v3.10.x

#4350 Bump a few timeouts in a flakey suite
  deps/rabbit/test/rabbit_fifo_int_SUITE.erl
Labels: backport-v3.9.x, backport-v3.8.x, backport-v3.10.x

#4274 Upgrade erlang.mk to latest
  erlang.mk
Labels: make

#4354 Use ra 2.0.6
  rabbitmq-components.mk
  release-notes/3.10.0.md
  workspace_helpers.bzl
Labels: bazel, make, backport-v3.9.x

#4355 Remove extra copies of rabbitmq-components.mk & erlang.mk
  deps/rabbitmq_ct_client_helpers/Makefile
  deps/rabbitmq_ct_client_helpers/erlang.mk
  deps/rabbitmq_ct_client_helpers/rabbitmq-components.mk
  deps/rabbitmq_ct_helpers/Makefile
  deps/rabbitmq_ct_helpers/erlang.mk
  deps/rabbitmq_ct_helpers/rabbitmq-components.mk
Labels: make, backport-v3.9.x, backport-v3.8.x, backport-v3.10.x

#4366 Federated queue suite: make it easier to identify messages
  deps/rabbitmq_federation/test/queue_SUITE.erl
Labels: backport-v3.9.x, backport-v3.8.x, backport-v3.10.x

#4365 Adopt latest rules_erlang
  WORKSPACE.bazel
Labels: bazel

#4368 Make Osiris listener registration idempotent
  deps/rabbitmq_stream/src/rabbit_stream_reader.erl
Labels: bug, backport-v3.9.x, backport-v3.10.x

#4245 Update amqp10_client and amqp10_common for hex.pm publish
  deps/amqp10_client/Makefile
  deps/amqp10_common/.travis.yml
  deps/amqp10_common/Makefile
  deps/amqp_client/.travis.yml
  deps/amqp_client/Makefile
  deps/rabbit_common/mk/rabbitmq-hexpm.mk
Labels: make, backport-v3.9.x, backport-v3.8.x, backport-v3.10.x

#4374 Adopt latest rules_erlang
  WORKSPACE.bazel
Labels: bazel

#4254 Add quorum queues support for MQTT
  deps/rabbitmq_mqtt/priv/schema/rabbitmq_mqtt.schema
  deps/rabbitmq_mqtt/src/rabbit_mqtt_processor.erl
  deps/rabbitmq_mqtt/src/rabbit_mqtt_reader.erl
  deps/rabbitmq_mqtt/test/config_schema_SUITE_data/rabbitmq_mqtt.snippets
  deps/rabbitmq_mqtt/test/processor_SUITE.erl
  deps/rabbitmq_mqtt/test/reader_SUITE.erl
Labels: backport-v3.10.x
