Repository rabbitmq/rabbitmq-server, pull requests merged in 2022-06, with the labels that each got.

#4941 Temporarily tag osiris to v1.2.7
  MODULE.bazel
  deps/rabbit/Makefile
Labels: bazel, make

#4928 Seshat 0.3.2
  MODULE.bazel
  deps/rabbit/Makefile
  deps/rabbit/src/rabbit_global_counters.erl
  deps/rabbit/src/rabbit_stream_queue.erl
  workspace_helpers.bzl
Labels: bazel, make, backport-v3.10.x

#4955 Switch the default python binary for codegen scripts to python3
  deps/amqp10_common/development.post.mk
  deps/rabbit_common/development.post.mk
Labels: make, backport-v3.9.x, backport-v3.8.x, backport-v3.10.x

#4962 Remove duplicate call to rabbit_exchange_decorator:set/1
  deps/rabbit/src/rabbit_exchange.erl
Labels: backport-v3.9.x, backport-v3.10.x

#4982 Log two more connection lifecycle events for AMQP 1.0 clients
  deps/rabbitmq_amqp1_0/src/rabbit_amqp1_0_reader.erl
Labels: backport-v3.9.x, backport-v3.10.x

#4932 Add custom consult code to rabbit_prelaunch_file module
  deps/rabbit/apps/rabbitmq_prelaunch/BUILD.bazel
  deps/rabbit/apps/rabbitmq_prelaunch/src/rabbit_logger_fmt_helpers.erl
  deps/rabbit/apps/rabbitmq_prelaunch/src/rabbit_prelaunch_conf.erl
  deps/rabbit/apps/rabbitmq_prelaunch/src/rabbit_prelaunch_file.erl
  deps/rabbit/apps/rabbitmq_prelaunch/test/rabbit_prelaunch_file_SUITE.erl
  deps/rabbit/apps/rabbitmq_prelaunch/test/rabbit_prelaunch_file_SUITE_data/advanced.config
  deps/rabbit/apps/rabbitmq_prelaunch/test/rabbit_prelaunch_file_SUITE_data/bad-advanced.config
  deps/rabbit/apps/rabbitmq_prelaunch/test/rabbit_prelaunch_file_SUITE_data/rabbitmq.config
  deps/rabbit_common/src/rabbit_data_coercion.erl
  deps/rabbit_common/src/rabbit_json.erl
  deps/rabbitmq_management_agent/src/rabbit_mgmt_format.erl
Labels: effort-tiny, bazel, make, backport-v3.9.x, backport-v3.10.x

#4991 Use rabbit_prelaunch_file:consult_file/1 for Osiris TLS replication configuration
  deps/rabbit/apps/rabbitmq_prelaunch/src/rabbit_prelaunch_conf.erl
Labels: backport-v3.10.x

#4990 Delay generating a guid for basic_messages until it is needed
  deps/rabbit/src/rabbit_basic.erl
  deps/rabbit/src/rabbit_channel.erl
  deps/rabbit/src/rabbit_classic_queue.erl
Labels: bazel

#5009 Remove Erlang 25 from the build matrix for now
  .github/workflows/test-mixed-versions.yaml
  .github/workflows/test-windows.yaml
  .github/workflows/test.yaml
Labels: backport-v3.9.x, backport-v3.10.x

#5014 Adopt latest rabbitmq-server-buildenv:linux-rbe for RBE
  WORKSPACE.bazel
Labels: bazel, backport-v3.9.x, backport-v3.8.x, backport-v3.10.x

#5022 rabbit_classic_queue: Use `rabbit_feature_flags`, not `rabbit_ff_registry`
  deps/rabbit/src/rabbit_classic_queue.erl
Labels: bug, backport-v3.10.x

#5020 Limit stream max segment size to 3 GB
  deps/rabbit/src/rabbit_policies.erl
  deps/rabbit/src/rabbit_stream_queue.erl
  deps/rabbit/test/rabbit_stream_queue_SUITE.erl
  deps/rabbit_common/include/rabbit.hrl
  deps/rabbitmq_stream/src/Elixir.RabbitMQ.CLI.Ctl.Commands.AddSuperStreamCommand.erl
  deps/rabbitmq_stream/src/rabbit_stream_manager.erl
  deps/rabbitmq_stream/src/rabbit_stream_reader.erl
  deps/rabbitmq_stream/test/rabbit_stream_SUITE.erl
Labels: backport-v3.9.x, backport-v3.10.x

#5025 Fixup rabbitmqctl build for missing formatters & otp 25
  MODULE.bazel
  WORKSPACE.bazel
  bazel/bzlmod/BUILD.bazel
  bazel/bzlmod/extensions.bzl
  bazel/mix/BUILD.bazel
  bazel/mix/mix_app.bzl
  deps/rabbitmq_cli/BUILD.bazel
  deps/rabbitmq_cli/mix.exs
  deps/rabbitmq_cli/rabbitmqctl.bzl
  deps/rabbitmq_cli/rabbitmqctl_test.bzl
Labels: bazel, backport-v3.9.x, backport-v3.8.x, backport-v3.10.x

#5037 Change normal connection close log level from warning to debug
  deps/rabbitmq_stream/src/rabbit_stream_reader.erl
Labels: backport-v3.9.x, backport-v3.10.x

#5036 Add action to stream coordinator warning
  deps/rabbit/src/rabbit_stream_coordinator.erl
Labels: backport-v3.10.x

#5027 Add a rule for building a source archive
  BUILD.bazel
  deps/rabbitmq_cli/BUILD.bazel
  deps/rabbitmq_cli/rabbitmqctl.bzl
  dist.bzl
Labels: bazel

#5045 Remove extra tar options not supported on macos
  deps/rabbitmq_cli/rabbitmqctl.bzl
Labels: bazel, backport-v3.9.x, backport-v3.8.x, backport-v3.10.x

#5051 Fixup the bazel build when used without bzlmod
  BUILD.bats
  BUILD.inet_tcp_proxy
  BUILD.jose
  BUILD.ranch
  BUILD.trust_store_http
  MODULE.bazel
  bazel/elixir/elixir.bzl
  workspace_helpers.bzl
Labels: bazel, backport-v3.9.x, backport-v3.8.x, backport-v3.10.x

#5059 Again try to make Dockerfile more cacheable
  packaging/docker-image/Dockerfile
Labels: backport-v3.9.x, backport-v3.8.x, backport-v3.10.x

#5065 Manual Backport 5059
  packaging/docker-image/Dockerfile
Labels: backport-v3.9.x, backport-v3.8.x

#5068 Adopt latest rabbitmq-server-buildenv:linux-rbe for RBE
  WORKSPACE.bazel
Labels: bazel, backport-v3.9.x, backport-v3.8.x, backport-v3.10.x

#5058 Add missing bazel deps
  MODULE.bazel
  WORKSPACE.bazel
  bazel/bzlmod/BUILD.bazel
  bazel/bzlmod/extensions.bzl
  dist.bzl
Labels: bazel, backport-v3.9.x, backport-v3.8.x, backport-v3.10.x

#5085 Close osiris log when cancelling AMQP stream consumer
  deps/rabbit/src/rabbit_stream_queue.erl
Labels: backport-v3.9.x, backport-v3.10.x

#5078 Allow `bazel run test-logs` to work when logs are compressed
  BUILD.bazel
Labels: bazel, backport-v3.9.x, backport-v3.8.x, backport-v3.10.x

#5107 Handle quorum queue timeout errors on rare 'basic.get' operations
  deps/rabbit/src/rabbit_queue_type.erl
Labels: backport-v3.9.x, backport-v3.8.x, backport-v3.10.x

#5113 Do not route to duplicate extra BCC destinations
  deps/rabbit/src/rabbit_amqqueue.erl
  deps/rabbit/test/queue_parallel_SUITE.erl
Labels: backport-v3.9.x, backport-v3.10.x

#5121 Make adding bindings idempotent
  deps/rabbitmq_consistent_hash_exchange/BUILD.bazel
  deps/rabbitmq_consistent_hash_exchange/include/rabbitmq_consistent_hash_exchange.hrl
  deps/rabbitmq_consistent_hash_exchange/src/rabbit_exchange_type_consistent_hash.erl
  deps/rabbitmq_consistent_hash_exchange/test/rabbit_exchange_type_consistent_hash_SUITE.erl
Labels: bazel, backport-v3.9.x, backport-v3.10.x

#5125 Use microsecond abbreviation 'us' instead of 'µs'
  deps/rabbit/src/rabbit.erl
  deps/rabbit/src/rabbit_feature_flags.erl
  deps/rabbit/src/rabbit_ff_registry_factory.erl
  deps/rabbitmq_ct_helpers/src/rabbit_ct_broker_helpers.erl
Labels: backport-v3.9.x, backport-v3.10.x
