Repository rabbitmq/rabbitmq-server, pull requests merged in 2022-10, with the labels that each got.

#4522 CQ: Merge lazy/default behavior into a unified mode
  deps/rabbit/BUILD.bazel
  deps/rabbit/src/rabbit_amqqueue_process.erl
  deps/rabbit/src/rabbit_backing_queue.erl
  deps/rabbit/src/rabbit_classic_queue_index_v2.erl
  deps/rabbit/src/rabbit_classic_queue_store_v2.erl
  deps/rabbit/src/rabbit_mirror_queue_master.erl
  deps/rabbit/src/rabbit_mirror_queue_slave.erl
  deps/rabbit/src/rabbit_mirror_queue_sync.erl
  deps/rabbit/src/rabbit_msg_store.erl
  deps/rabbit/src/rabbit_priority_queue.erl
  deps/rabbit/src/rabbit_queue_index.erl
  deps/rabbit/src/rabbit_time_travel_dbg.erl
  deps/rabbit/src/rabbit_variable_queue.erl
  deps/rabbit/test/backing_queue_SUITE.erl
  deps/rabbit/test/channel_operation_timeout_test_queue.erl
  deps/rabbit/test/classic_queue_prop_SUITE.erl
  deps/rabbit/test/lazy_queue_SUITE.erl
  deps/rabbit_common/src/rabbit_misc.erl
  deps/rabbitmq_prometheus/test/rabbit_prometheus_http_SUITE.erl
  deps/rabbitmq_recent_history_exchange/test/system_SUITE.erl
Labels: bazel, make

#5962 Add otp 25.1 to //packaging/docker-image:rabbitmq
  WORKSPACE
  packaging/docker-image/BUILD.bazel
  packaging/docker-image/test_configs/otp_ubuntu.yaml
Labels: bazel, backport-v3.11.x

#5964 Use otp 25.1 for CI instead of 25.0
  .bazelrc
  MODULE.bazel
  WORKSPACE
  bazel/platforms/BUILD.bazel
  packaging/docker-image/BUILD.bazel
  packaging/docker-image/test_configs/otp_ubuntu.yaml
Labels: bazel, backport-v3.9.x

#5966 Use leader locator "balanced" by default for add_super_stream
  deps/rabbitmq_stream/src/rabbit_stream_manager.erl
Labels: bug, backport-v3.11.x

#5969 Use rules_erlang 3.7.2
  MODULE.bazel
  WORKSPACE
Labels: bazel, backport-v3.9.x, backport-v3.10.x, backport-v3.11.x

#5961 Fix keys for route and partitions responses
  deps/rabbitmq_stream/src/rabbit_stream.erl
  deps/rabbitmq_stream/src/rabbit_stream_connection_sup.erl
  deps/rabbitmq_stream/src/rabbit_stream_reader.erl
  deps/rabbitmq_stream_common/src/rabbit_stream_core.erl
  deps/rabbitmq_stream_common/test/rabbit_stream_core_SUITE.erl
Labels: backport-v3.11.x

#5968 Refactor how selenium suites are run
  .github/workflows/test-selenium.yaml
  deps/rabbitmq_management/.gitignore
  deps/rabbitmq_management/selenium/Makefile
  deps/rabbitmq_management/selenium/README.md
  deps/rabbitmq_management/selenium/run-suites.sh
  deps/rabbitmq_management/selenium/suites/oauth-with-uaa-down.sh
  deps/rabbitmq_management/selenium/suites/oauth-with-uaa.sh
  deps/rabbitmq_management/selenium/suites/suite_template
  deps/rabbitmq_management/selenium/test/oauth/Makefile
  deps/rabbitmq_management/selenium/test/oauth/enabled_plugins
  deps/rabbitmq_management/selenium/test/oauth/logging.conf
  deps/rabbitmq_management/selenium/test/oauth/rabbitmq-localhost.config
  deps/rabbitmq_management/selenium/test/oauth/rabbitmq-with-mgt-prefix.config
  deps/rabbitmq_management/selenium/test/oauth/rabbitmq.config
  deps/rabbitmq_management/selenium/test/oauth/start-uaa.sh
  deps/rabbitmq_management/selenium/test/oauth/stop-uaa.sh
  deps/rabbitmq_management/selenium/test/oauth/uaa-localhost/log4j2.properties
  deps/rabbitmq_management/selenium/test/oauth/uaa-localhost/uaa.yml
  deps/rabbitmq_management/selenium/test/oauth/uaa-with-mgt-prefix/log4j2.properties
  deps/rabbitmq_management/selenium/test/oauth/uaa-with-mgt-prefix/uaa.yml
  deps/rabbitmq_management/selenium/test/oauth/uaa/log4j2.properties
  deps/rabbitmq_management/selenium/test/oauth/uaa/uaa.yml
  deps/rabbitmq_management/selenium/test/oauth/waitTillUAAReady
  deps/rabbitmq_management/selenium/test/oauth/with-uaa-down/landing.js
  deps/rabbitmq_management/selenium/test/oauth/with-uaa-down/setup.sh
  deps/rabbitmq_management/selenium/test/oauth/with-uaa-down/teardown.sh
  deps/rabbitmq_management/selenium/test/oauth/with-uaa/happy-login.js
  deps/rabbitmq_management/selenium/test/oauth/with-uaa/hard-session-logout.js
  deps/rabbitmq_management/selenium/test/oauth/with-uaa/landing.js
  deps/rabbitmq_management/selenium/test/oauth/with-uaa/logout.js
  deps/rabbitmq_management/selenium/test/oauth/with-uaa/setup.sh
  deps/rabbitmq_management/selenium/test/oauth/with-uaa/teardown.sh
  deps/rabbitmq_management/selenium/test/oauth/with-uaa/token-refresh.js
Labels: make

#5981 Update from `master` to `main`
  deps/rabbit_common/mk/rabbitmq-early-test.mk
  deps/rabbit_common/mk/rabbitmq-tools.mk
  rabbitmq-components.mk
Labels: make

#5944 Fix channel crash when cancelling then consuming using the same consumer tag and channel
  deps/rabbit/src/rabbit_fifo.erl
  deps/rabbit/src/rabbit_fifo_client.erl
  deps/rabbit/test/quorum_queue_SUITE.erl
  deps/rabbit/test/rabbit_fifo_int_SUITE.erl
Labels: bug, backport-v3.10.x, backport-v3.11.x

#6001 Adopt otp 25.1.1
  MODULE.bazel
  WORKSPACE
Labels: bazel, backport-v3.9.x, backport-v3.10.x, backport-v3.11.x

#6003 Use Elixir 1.13.x with otp 24.x in bazel build
  bazel/platforms/BUILD.bazel
Labels: bazel, backport-v3.9.x, backport-v3.10.x, backport-v3.11.x

#6010 Add 'mix format --check-formatted' to the rabbitmqctl_tests in bazel
  deps/rabbitmq_cli/BUILD.bazel
  deps/rabbitmq_cli/rabbitmqctl.bzl
  deps/rabbitmq_cli/rabbitmqctl_test.bzl
Labels: bazel, backport-v3.9.x, backport-v3.10.x, backport-v3.11.x

#6026 Fix docs for rabbitmqctl restart_vhost
  deps/rabbit/docs/rabbitmqctl.8
Labels: backport-v3.9.x, backport-v3.10.x, backport-v3.11.x

#6024 Update Stream protocol document
  deps/rabbitmq_stream/docs/PROTOCOL.adoc
Labels: backport-v3.10.x, backport-v3.11.x

#5984 Support management path prefix when using OAuth2
  deps/rabbitmq_management/.gitignore
  deps/rabbitmq_management/priv/www/js/oidc-oauth/helper.js
  deps/rabbitmq_management/selenium/README.md
  deps/rabbitmq_management/selenium/suites/oauth-with-uaa-with-mgt-prefix.sh
  deps/rabbitmq_management/selenium/test/oauth/rabbitmq-localhost.config
  deps/rabbitmq_management/selenium/test/oauth/rabbitmq-with-mgt-prefix.config
  deps/rabbitmq_management/selenium/test/oauth/uaa-localhost/uaa.yml
  deps/rabbitmq_management/selenium/test/oauth/uaa-with-mgt-prefix/uaa.yml
Labels: backport-v3.11.x

#5934 Introduce new feature flag to avoid сhannel exceptions when delivering to CQs post #5105
  deps/rabbit/src/rabbit_classic_queue.erl
  deps/rabbit/src/rabbit_core_ff.erl
  deps/rabbitmq_management/test/clustering_SUITE.erl
Labels: bug, backport-v3.10.x, backport-v3.11.x

#3314 Observer CLI plugin: classic queues
  deps/rabbit/src/rabbit.erl
  deps/rabbit/src/rabbit_classic_queue_index_v2.erl
  deps/rabbit/src/rabbit_classic_queue_store_v2.erl
  deps/rabbit/src/rabbit_observer_cli.erl
  deps/rabbit/src/rabbit_observer_cli_classic_queues.erl
  deps/rabbit/src/rabbit_queue_index.erl
  deps/rabbit/src/rabbit_variable_queue.erl
Labels: make

#6041 Upgrade cuttlefish to 3.1.0
  MODULE.bazel
  deps/rabbit/apps/rabbitmq_prelaunch/Makefile
Labels: bazel, make, backport-v3.10.x, backport-v3.11.x

#6019 Load plugins in dependency order
  deps/rabbit/src/rabbit_plugins.erl
  deps/rabbit/test/unit_plugin_versioning_SUITE.erl
Labels: backport-v3.10.x, backport-v3.11.x

#6050 Adopt otp 24.3.4.6
  MODULE.bazel
  WORKSPACE
Labels: bazel, backport-v3.9.x, backport-v3.10.x, backport-v3.11.x

#5892 Tiny shovel-related fixes
  deps/rabbitmq_shovel/src/rabbit_shovel_behaviour.erl
  deps/rabbitmq_shovel/src/rabbit_shovel_worker.erl
  deps/rabbitmq_shovel_management/Makefile
  deps/rabbitmq_shovel_management/priv/www/js/tmpl/shovels.ejs
  deps/rabbitmq_shovel_management/src/rabbit_shovel_mgmt.erl
  deps/rabbitmq_shovel_management/test/rabbit_shovel_mgmt_SUITE.erl
Labels: make, backport-v3.9.x, backport-v3.10.x, backport-v3.11.x

#6067 Formatting normalization for MODULE.bazel
  MODULE.bazel
Labels: bazel, backport-v3.9.x

#6046 Make "global hang workaround" support OTP >= 25.1
  deps/rabbit/src/rabbit_node_monitor.erl
Labels: backport-v3.10.x, backport-v3.11.x

#6070 Remove erlang 23 from bazel build
  .bazelrc
  MODULE.bazel
  WORKSPACE
  bazel/platforms/BUILD.bazel
  packaging/docker-image/BUILD.bazel
Labels: bazel, backport-v3.9.x, backport-v3.10.x, backport-v3.11.x

#6075 Make rabbit_fifo_basics_SUITE:basics less dependent on ra_event order
  deps/rabbit/test/rabbit_fifo_int_SUITE.erl
Labels: backport-v3.10.x, backport-v3.11.x

#6082 Adopt elixir 1.14.1
  MODULE.bazel
  WORKSPACE
Labels: bazel, backport-v3.9.x, backport-v3.10.x, backport-v3.11.x

#6091 Drop Elixir 1.12 toolchain
  .github/workflows/update-elixir-patches.yaml
  MODULE.bazel
  WORKSPACE
Labels: bazel, backport-v3.9.x, backport-v3.10.x, backport-v3.11.x

#6100 3.10.9 release notes
  release-notes/3.10.9.md
Labels: backport-v3.10.x, backport-v3.11.x

#6073 Implement ra_machine:overview/1 for rabbit_stream_coordinator
  deps/rabbit/src/rabbit_stream_coordinator.erl
  deps/rabbit/src/rabbit_stream_sac_coordinator.erl
  deps/rabbit/test/rabbit_stream_coordinator_SUITE.erl
Labels: usability, backport-v3.11.x

#6108 Close local MQTT connections when draining node
  deps/rabbit/src/rabbit_maintenance.erl
  deps/rabbitmq_mqtt/src/rabbit_mqtt.erl
  deps/rabbitmq_mqtt/src/rabbit_mqtt_collector.erl
  deps/rabbitmq_mqtt/src/rabbit_mqtt_internal_event_handler.erl
  deps/rabbitmq_mqtt/test/cluster_SUITE.erl
Labels: bug, rabbitmq-mqtt, backport-v3.9.x, backport-v3.10.x, backport-v3.11.x

#6110 Avoid double debiting credit when sending to queue mirrors
  deps/rabbit/src/rabbit_classic_queue.erl
Labels: backport-v3.10.x, backport-v3.11.x

#6127 Node metric collection: handle a rare case with multiple dist ports
  deps/rabbit_common/src/rabbit_net.erl
Labels: backport-v3.9.x, backport-v3.10.x, backport-v3.11.x

#6128 Use rules_erlang 3.8.2
  MODULE.bazel
Labels: bazel, backport-v3.9.x, backport-v3.10.x, backport-v3.11.x

#6126 Partially revert delegate optimisation
  deps/rabbit_common/src/delegate.erl
Labels: backport-v3.10.x, backport-v3.11.x

#6142 3.10.10 release notes
  release-notes/3.10.10.md
Labels: backport-v3.10.x, backport-v3.11.x

#6147 3.9.24 release notes
  release-notes/3.9.24.md
Labels: backport-v3.9.x, backport-v3.10.x, backport-v3.11.x

#6151 Adjustments to the OCI workflow to ensure the correct otp version
  .github/workflows/oci.yaml
Labels: backport-v3.9.x, backport-v3.10.x, backport-v3.11.x

#6157 Correct a copy-and-paste artifact in 3.9.24 release notes
  release-notes/3.9.24.md
Labels: backport-v3.9.x, backport-v3.10.x, backport-v3.11.x

#6162 Add otp 25.0 to the matrix in the non-mixed tests in actions
  .github/workflows/test.yaml
Labels: backport-v3.11.x

#6181 Make main branch use 3.11.2 as mixed version tests
  .github/workflows/secondary-umbrella.yaml
  MODULE.bazel
  bazel/bzlmod/secondary_umbrella.bzl
  rabbitmq.bzl
Labels: bazel

#6182 Stream coordinator: fix member check in ensure_coordinator_started/0
  deps/rabbit/src/rabbit_stream_coordinator.erl
  deps/rabbit/test/rabbit_stream_queue_SUITE.erl
Labels: bug, backport-v3.10.x, backport-v3.11.x

#6186 Sync the approach in oci.yaml workflow across branches
  .github/workflows/oci.yaml
Labels: backport-v3.11.x

#6191 Add ability to set default vhost limits by pattern (with a naming change)
  deps/rabbit/priv/schema/rabbit.schema
  deps/rabbit/src/rabbit_vhost.erl
  deps/rabbit/src/rabbit_vhost_limit.erl
  deps/rabbit/test/config_schema_SUITE_data/rabbit.snippets
  deps/rabbit/test/vhost_SUITE.erl
Labels: backport-v3.11.x

#6184 Add a build flag for compiling with `-DTEST` in all deps/... apps
  .bazelrc
  BUILD.bazel
  rabbitmq.bzl
Labels: bazel, backport-v3.9.x, backport-v3.10.x, backport-v3.11.x

#6196 Fixup ra osiris pinning for make
  deps/rabbit/Makefile
  rabbitmq-components.mk
Labels: make

#6199 Make rabbit_fifo_int_SUITE:basics test less flaky
  deps/rabbit/test/rabbit_fifo_int_SUITE.erl
Labels: backport-v3.11.x

#6207 Add noopener, noreferrer to hrefs in rabbitmq_management
  deps/rabbitmq_management/priv/www/js/tmpl/layout.ejs
Labels: backport-v3.9.x, backport-v3.10.x, backport-v3.11.x

#6198 Fix v2 CMQs in v3.11
  deps/rabbit/src/rabbit_variable_queue.erl
Labels: backport-v3.10.x

#6226 Make actions secrets optional in Windows workflow
  .github/workflows/test-windows.yaml
Labels: backport-v3.9.x, backport-v3.10.x, backport-v3.11.x

#6230 Ignore `.exrc` file
  .gitignore
Labels: backport-v3.9.x, backport-v3.10.x, backport-v3.11.x

#6224 Shovel: handle `connection.(un)blocked` messages
  deps/rabbitmq_shovel/src/rabbit_amqp091_shovel.erl
  deps/rabbitmq_shovel/src/rabbit_shovel_worker.erl
  deps/rabbitmq_shovel/test/dynamic_SUITE.erl
  deps/rabbitmq_shovel/test/shovel_test_utils.erl
Labels: backport-v3.11.x

#6216 Stream Coordinator: fail active mnesia update actions on leader change
  deps/rabbit/src/rabbit_stream_coordinator.erl
  deps/rabbit/test/rabbit_stream_queue_SUITE.erl
Labels: bug, backport-v3.11.x

#6237 Fix the CQ Observer CLI plugin with clusters
  deps/rabbit/src/rabbit_observer_cli_classic_queues.erl
Labels: backport-v3.10.x, backport-v3.11.x

#6231 Adopt otp 25.1.2
  MODULE.bazel
  WORKSPACE
Labels: bazel, backport-v3.10.x, backport-v3.11.x

#6248 Update lqueue based on OTP-25.1.2
  deps/rabbit/src/lqueue.erl
Labels: backport-v3.9.x, backport-v3.10.x, backport-v3.11.x

#6244 Correctly decrease global counters in rabbit_channel:terminate/2
  deps/rabbit/src/rabbit_channel.erl
  deps/rabbit/test/queue_type_SUITE.erl
Labels: bug, backport-v3.10.x, backport-v3.11.x

#6250 Mark @rbe as non-dev dependency
  MODULE.bazel
Labels: bazel, backport-v3.9.x, backport-v3.10.x, backport-v3.11.x

#6266 Make package_generic_unix & source_archive macros from dist.bzl useful outside of this repo
  BUILD.bazel
  dist.bzl
  rabbitmq.bzl
  rabbitmq_home.bzl
Labels: bazel, backport-v3.9.x, backport-v3.10.x, backport-v3.11.x

#6183 QQ: don't try to contact non-connected nodes for stats
  deps/rabbit/src/rabbit_quorum_queue.erl
  deps/rabbit/test/quorum_queue_SUITE.erl
Labels: backport-v3.10.x, backport-v3.11.x

#6280 Avoid crashing shovel plugin when another node goes down
  deps/rabbitmq_shovel/src/rabbit_shovel_status.erl
Labels: backport-v3.9.x, backport-v3.10.x, backport-v3.11.x

#6278 Use erpc optimisation for local rpcs
  deps/rabbit/src/rabbit_quorum_queue.erl
Labels: backport-v3.10.x, backport-v3.11.x
