Repository rabbitmq/rabbitmq-server, pull requests merged in 2022-01, with the labels that each got.

#3934 Reduce CPU usage of rabbit_framing_amqp_0_9_1:decode_method_fields/2
  deps/rabbitmq_codegen/amqp-rabbitmq-0.9.1.json
Labels: backport-v3.9.x, backport-v3.8.x

#3941 Disable +deterministic in compilation_mode dbg under bazel
  BUILD.bazel
  WORKSPACE.bazel
  deps/rabbit/BUILD.bazel
  rabbitmq.bzl
Labels: bazel

#3936 Fix all uses of file:read_file/1
  deps/rabbit/apps/rabbitmq_prelaunch/src/rabbit_prelaunch_conf.erl
  deps/rabbit/src/rabbit.erl
  deps/rabbit/src/rabbit_definitions_import_local_filesystem.erl
  deps/rabbit_common/src/rabbit_misc.erl
  deps/rabbit_common/src/rabbit_semver_parser.erl
  deps/rabbitmq_management/src/rabbit_mgmt_wm_health_check_certificate_expiration.erl
  deps/rabbitmq_peer_discovery_k8s/src/rabbit_peer_discovery_k8s.erl
  deps/rabbitmq_tracing/src/rabbit_tracing_files.erl
  deps/rabbitmq_tracing/src/rabbit_tracing_wm_file.erl
  deps/rabbitmq_trust_store/src/rabbit_trust_store_file_provider.erl
Labels: backport-v3.9.x, backport-v3.8.x

#3947 Fix config example in README.md for rabbitmq_auth_backend_cache
  deps/rabbitmq_auth_backend_cache/README.md
Labels: backport-v3.9.x, backport-v3.8.x

#3950 3.9.12 release notes
  release-notes/3.9.12.md
Labels: backport-v3.9.x

#3952 3.8.27 release notes
  release-notes/3.8.27.md
Labels: backport-v3.8.x

#3953 Bump (c) year in node startup banner
  deps/rabbit_common/include/rabbit.hrl
Labels: backport-v3.9.x, backport-v3.8.x

#3957 Limit the version of rebar3_hex to v6
  erlang.mk
Labels: make, backport-v3.9.x, backport-v3.8.x

#3956 Distribution listener IP address is hardcoded in listener metadata
  deps/rabbit/src/rabbit_networking.erl
Labels: backport-v3.9.x, backport-v3.8.x

#3967 Fix Stream coordinator leader selection bug
  deps/rabbit/src/rabbit_stream_coordinator.erl
  deps/rabbit/src/rabbit_stream_coordinator.hrl
  deps/rabbit/test/rabbit_stream_coordinator_SUITE.erl
Labels: backport-v3.9.x

#3970 Fix issue with fsutil
  deps/rabbit/src/rabbit_disk_monitor.erl
Labels: backport-v3.9.x

#3980 Replace one use of filelib:is_regular/1
  deps/rabbit/src/rabbit_config.erl
  deps/rabbit_common/src/rabbit_misc.erl
Labels: backport-v3.9.x, backport-v3.8.x

#3981 Import queue and binding definitions when a certain number of nodes join
  deps/rabbit/src/rabbit_definitions.erl
  deps/rabbit/src/rabbit_nodes.erl
Labels: backport-v3.9.x

#4031 Adopt latest rules_erlang
  WORKSPACE.bazel
Labels: bazel

#4025 Adopt latest rabbitmq-server-buildenv:linux-erlang-23.3 for RBE
  WORKSPACE.bazel
Labels: bazel, backport-v3.9.x, backport-v3.8.x, backport-v3.10.x

#4026 Adopt latest rabbitmq-server-buildenv:linux-erlang-24.1 for RBE
  WORKSPACE.bazel
Labels: bazel, backport-v3.9.x, backport-v3.8.x, backport-v3.10.x

#4042 Adopt latest rules_erlang
  WORKSPACE.bazel
Labels: bazel

#4028 Run some portion of the test suite on Windows in GitHub Actions
  .github/workflows/test-windows.yaml
  deps/rabbitmq_cli/rabbitmqctl.bzl
Labels: bazel

#4043 Use separate colours for different queue types (and streams) in memory breakdown chart
  deps/rabbitmq_management/priv/www/css/main.css
  deps/rabbitmq_management/priv/www/js/tmpl/binary.ejs
  deps/rabbitmq_management/priv/www/js/tmpl/memory.ejs
Labels: backport-v3.9.x, backport-v3.10.x

#3029 Replace classic queue index with a modern implementation
  deps/rabbit/BUILD.bazel
  deps/rabbit/priv/schema/rabbit.schema
  deps/rabbit/src/rabbit_amqqueue.erl
  deps/rabbit/src/rabbit_amqqueue_process.erl
  deps/rabbit/src/rabbit_amqqueue_sup.erl
  deps/rabbit/src/rabbit_backing_queue.erl
  deps/rabbit/src/rabbit_classic_queue.erl
  deps/rabbit/src/rabbit_classic_queue_index_v2.erl
  deps/rabbit/src/rabbit_classic_queue_store_v2.erl
  deps/rabbit/src/rabbit_mirror_queue_master.erl
  deps/rabbit/src/rabbit_mirror_queue_slave.erl
  deps/rabbit/src/rabbit_msg_store.erl
  deps/rabbit/src/rabbit_policies.erl
  deps/rabbit/src/rabbit_priority_queue.erl
  deps/rabbit/src/rabbit_queue_index.erl
  deps/rabbit/src/rabbit_variable_queue.erl
  deps/rabbit/src/rabbit_vhost_msg_store.erl
  deps/rabbit/test/backing_queue_SUITE.erl
  deps/rabbit/test/channel_operation_timeout_test_queue.erl
  deps/rabbit/test/classic_queue_SUITE.erl
  deps/rabbit/test/config_schema_SUITE_data/rabbit.snippets
  deps/rabbit/test/priority_queue_SUITE.erl
  deps/rabbitmq_management/priv/www/js/global.js
  deps/rabbitmq_management/priv/www/js/tmpl/policies.ejs
  deps/rabbitmq_management/priv/www/js/tmpl/queues.ejs
Labels: bazel, backport-v3.10.x
