Repository rabbitmq/rabbitmq-server, pull requests merged in 2022-05, with the labels that each got.

#4695 Bump credentials_obfuscation to 3.0.0 (backport only after 3.10.0 GA)
  MODULE.bazel
  deps/rabbit_common/Makefile
  deps/rabbitmq_federation/test/exchange_SUITE.erl
  workspace_helpers.bzl
Labels: backport-pending, bazel, make

#4696 Return empty array when JMS topic exchange state does not exist
  deps/rabbitmq_jms_topic_exchange/src/rabbit_jms_topic_exchange.erl
Labels: backport-pending

#4699 Be sure to inclued apps/ dirs
  erlang_ls.config
Labels: backport-v3.9.x, backport-v3.8.x, backport-v3.10.x

#4706 Remove leftover compiler option for get_stacktrace
  deps/rabbit/src/rabbit_channel.erl
  deps/rabbit/src/rabbit_node_monitor.erl
  deps/rabbit/src/rabbit_reader.erl
  deps/rabbit/src/rabbit_vhost_process.erl
  deps/rabbitmq_amqp1_0/include/rabbit_amqp1_0.hrl
  deps/rabbitmq_amqp1_0/src/rabbit_amqp1_0_reader.erl
  deps/rabbitmq_amqp1_0/src/rabbit_amqp1_0_session_process.erl
  deps/rabbitmq_auth_backend_oauth2/src/uaa_jwt_jwt.erl
  deps/rabbitmq_management_agent/src/rabbit_mgmt_external_stats.erl
  deps/rabbitmq_mqtt/src/rabbit_mqtt_reader.erl
  deps/rabbitmq_trust_store/src/rabbit_trust_store.erl
Labels: backport-v3.9.x, backport-v3.8.x, backport-v3.10.x

#4710 Adopt otp 24.3.4 for OCI workflow
  packaging/docker-image/otp-versions/otp-max.yaml
Labels: backport-v3.9.x, backport-v3.8.x, backport-v3.10.x

#4722 Use rabbitmqctl await_startup instead if erl eval
  deps/rabbit_common/mk/rabbitmq-run.mk
  rabbitmq_run.bzl
  scripts/bazel/rabbitmq-run.sh
Labels: bazel, make, backport-v3.9.x, backport-v3.8.x, backport-v3.10.x

#4727 Add consumer count to stream queue metrics
  deps/rabbit/src/rabbit_osiris_metrics.erl
  deps/rabbit/src/rabbit_stream_queue.erl
  deps/rabbitmq_management/test/rabbit_mgmt_http_SUITE.erl
Labels: backport-v3.10.x

#4735 No longer file:allocate CQv2 index files
  deps/rabbit/src/rabbit_classic_queue_index_v2.erl
Labels: backport-v3.10.x

#4737 rabbit_ra_systems: New module to configure Ra systems
  deps/rabbit/src/rabbit.erl
  deps/rabbit/src/rabbit_ra_systems.erl
Labels: backport-v3.9.x, backport-v3.10.x

#4756 Adopt latest rules_erlang
  WORKSPACE.bazel
Labels: bazel

#4759 Ensure maintenance mode state table exists after node [re]boot
  deps/rabbit/src/rabbit_maintenance.erl
Labels: backport-v3.9.x, backport-v3.10.x

#4762 Add test-node-logs and remote-test-node-logs rules for bazel
  BUILD.bazel
Labels: bazel, backport-v3.9.x, backport-v3.8.x, backport-v3.10.x

#4772 Pin Ra to 2.0.11
  MODULE.bazel
  rabbitmq-components.mk
  workspace_helpers.bzl
Labels: bazel, make, backport-v3.9.x

#4774 Check queue and exchange existence with ets:member/2
  deps/rabbit/src/rabbit_amqqueue.erl
  deps/rabbit/src/rabbit_binding.erl
  deps/rabbit/src/rabbit_definitions.erl
  deps/rabbit/src/rabbit_exchange.erl
  deps/rabbit/src/rabbit_fifo_dlx_worker.erl
  deps/rabbitmq_management_agent/src/rabbit_mgmt_metrics_collector.erl
  deps/rabbitmq_mqtt/src/rabbit_mqtt_processor.erl
  deps/rabbitmq_stream/src/rabbit_stream_manager.erl
Labels: backport-v3.9.x, backport-v3.8.x, backport-v3.10.x

#4776 3.10.1 release notes
  release-notes/3.10.1.md
Labels: backport-v3.10.x

#4783 3.8.31 release notes
  release-notes/3.8.31.md
Labels: backport-v3.9.x, backport-v3.8.x, backport-v3.10.x

#4787 Avoid ETS lookup if no extra_bcc queue set
  deps/rabbit/src/rabbit_amqqueue.erl
  deps/rabbit/src/rabbit_channel.erl
  deps/rabbit/src/rabbit_dead_letter.erl
  deps/rabbit/src/rabbit_exchange.erl
  deps/rabbit/src/rabbit_fifo_dlx_worker.erl
  deps/rabbit/test/queue_parallel_SUITE.erl
Labels: backport-v3.10.x, performance

#4606 Route faster in direct exchange
  deps/rabbit/BUILD.bazel
  deps/rabbit/src/rabbit_binding.erl
  deps/rabbit/src/rabbit_core_ff.erl
  deps/rabbit/src/rabbit_exchange.erl
  deps/rabbit/src/rabbit_exchange_type_direct.erl
  deps/rabbit/src/rabbit_feature_flags.erl
  deps/rabbit/src/rabbit_ff_registry.erl
  deps/rabbit/src/rabbit_quorum_queue.erl
  deps/rabbit/src/rabbit_router.erl
  deps/rabbit/src/rabbit_table.erl
  deps/rabbit/test/direct_exchange_routing_v2_SUITE.erl
  deps/rabbit_common/include/rabbit.hrl
Labels: bazel, performance

#4793 Clarify documented/allowed log_level arg of rabbitmqctl set_log_level
  deps/rabbit/docs/rabbitmqctl.8
  deps/rabbitmq_cli/lib/rabbitmq/cli/ctl/commands/set_log_level_command.ex
Labels: backport-v3.9.x, backport-v3.8.x, backport-v3.10.x

#4798 Change default format of log level to full name
  deps/rabbit/apps/rabbitmq_prelaunch/src/rabbit_logger_fmt_helpers.erl
  deps/rabbit/test/logging_SUITE.erl
Labels: backport-v3.9.x, backport-v3.10.x

#4801 Save memory when acking messages to quorum queue
  deps/rabbit/src/rabbit_fifo_client.erl
Labels: backport-v3.9.x, backport-v3.10.x, performance

#4803 Report crypto library version in 'rabbitmq-diagnostics status'
  deps/rabbit/src/rabbit.erl
  deps/rabbitmq_cli/lib/rabbitmq/cli/ctl/commands/status_command.ex
Labels: backport-v3.9.x, backport-v3.8.x, backport-v3.10.x

#4811 Increase receiving throughput from a stream for AMQP 0-9-1 clients
  deps/amqp10_common/Makefile
  deps/amqp10_common/src/amqp10_binary_parser.erl
  deps/amqp10_common/src/amqp10_framing.erl
  deps/amqp10_common/test/binary_generator_SUITE.erl
  deps/amqp10_common/test/binary_parser_SUITE.erl
  deps/rabbit/src/rabbit_msg_record.erl
  deps/rabbit/test/rabbit_stream_queue_SUITE.erl
Labels: make, backport-v3.9.x, backport-v3.10.x, performance

#4815 3.10.2 release notes
  release-notes/3.10.2.md
Labels: backport-v3.10.x

#4817 3.9.18 release notes
  release-notes/3.9.18.md
Labels: backport-v3.9.x, backport-v3.10.x

#4819 3.8.32 release notes
  release-notes/3.8.32.md
Labels: backport-v3.9.x, backport-v3.8.x, backport-v3.10.x

#4814 Bump credentials_obfuscation to 3.1.0
  MODULE.bazel
  deps/rabbit_common/Makefile
  workspace_helpers.bzl
Labels: bazel, make, backport-v3.9.x, backport-v3.8.x, backport-v3.10.x

#4836 Set maximum expiration
  deps/rabbit/test/quorum_queue_SUITE.erl
  deps/rabbit_common/src/rabbit_misc.erl
Labels: backport-v3.10.x

#4838 Handle void types in AMQP 0.9.1 -> AMQP 1.0 conversion
  deps/rabbit/src/rabbit_msg_record.erl
  deps/rabbit/test/rabbit_msg_record_SUITE.erl
Labels: backport-v3.9.x, backport-v3.10.x

#4843 Bump Ra to 2.0.12
  rabbitmq-components.mk
  workspace_helpers.bzl
Labels: bazel, make, backport-v3.9.x, backport-v3.10.x

#4841 Implement fallback secret for credentials obfuscation (by @luos)
  deps/rabbit/BUILD.bazel
  deps/rabbit/Makefile
  deps/rabbit/apps/rabbitmq_prelaunch/src/rabbit_prelaunch_conf.erl
  deps/rabbit/apps/rabbitmq_prelaunch/src/rabbit_prelaunch_dist.erl
  deps/rabbit/test/cluster_SUITE.erl
Labels: bazel, make, backport-v3.9.x, backport-v3.8.x, backport-v3.10.x

#4846 Bump Aten to 0.5.8
  MODULE.bazel
  workspace_helpers.bzl
Labels: bazel, backport-v3.9.x

#4844 CQv2: file:delete/1 -> prim_file:delete/1
  deps/rabbit/src/rabbit_classic_queue_index_v2.erl
  deps/rabbit/src/rabbit_classic_queue_store_v2.erl
Labels: backport-v3.10.x

#4855 Update 3.8.32 release notes
  release-notes/3.8.32.md
Labels: backport-v3.9.x, backport-v3.8.x, backport-v3.10.x

#4857 Update 3.9.18 release notes
  release-notes/3.9.18.md
Labels: backport-v3.9.x, backport-v3.10.x

#4862 Update 3.10.2 release notes
  release-notes/3.10.2.md
  release-notes/3.9.18.md
Labels: backport-v3.10.x

#4869 Update 3.10.2 release notes
  release-notes/3.10.2.md
Labels: backport-v3.10.x

#4879 3.10.3 release notes stub
  release-notes/3.10.3.md
Labels: backport-v3.10.x

#4873 Optimise rabbit_fifo:complete function
  deps/rabbit/src/rabbit_fifo.erl
  deps/rabbit/src/rabbit_fifo_index.erl
Labels: backport-v3.9.x, backport-v3.10.x

#4891 Allow updating config (eg log level) of log exchange
  deps/rabbit/src/rabbit_logger_exchange_h.erl
  deps/rabbit/test/logging_SUITE.erl
Labels: backport-v3.9.x, backport-v3.10.x

#4897 Fix `rabbitmqctl status` when the disk_free cannot be determined
  deps/rabbitmq_cli/lib/rabbitmq/cli/information_unit.ex
  user-template.bazelrc
Labels: backport-v3.9.x, backport-v3.8.x, backport-v3.10.x

#4904 Skip default definitions when definitions are imported using management.load_definitions
  deps/rabbit/src/rabbit_definitions.erl
Labels: backport-v3.9.x, backport-v3.8.x, backport-v3.10.x

#4913 Update 3.10.3 release notes
  release-notes/3.10.3.md
Labels: backport-v3.10.x

#4916 One more missing 3.10.3 release notes entry
  release-notes/3.10.3.md
Labels: backport-v3.10.x

#4922 3.8.33 release notes
  release-notes/3.8.33.md
Labels: backport-v3.9.x, backport-v3.8.x, backport-v3.10.x
