Repository rabbitmq/rabbitmq-server, pull requests merged in 2022-09, with the labels that each got.

#5704 3.11.0 initial release notes
  release-notes/3.11.0.md
Labels: backport-v3.11.x

#5709 CLI tools: whitelist Elixir 1.14
  deps/rabbitmq_cli/mix.exs
Labels: backport-v3.9.x, backport-v3.8.x, backport-v3.10.x, backport-v3.11.x

#5718 Fix MQTT protocol version in MQTT tests
  deps/rabbitmq_mqtt/test/auth_SUITE.erl
  deps/rabbitmq_mqtt/test/cluster_SUITE.erl
  deps/rabbitmq_mqtt/test/command_SUITE.erl
  deps/rabbitmq_mqtt/test/reader_SUITE.erl
  deps/rabbitmq_mqtt/test/retainer_SUITE.erl
Labels: rabbitmq-mqtt, backport-v3.9.x, backport-v3.10.x, backport-v3.11.x

#5732 3.11 release notes: reword as suggested in #5319
  release-notes/3.11.0.md
Labels: backport-v3.11.x

#5730 Fix typo in plugins.mk
  plugins.mk
Labels: make, backport-v3.9.x, backport-v3.10.x, backport-v3.11.x

#5726 Disk monitor strikes back!
  deps/rabbit/BUILD.bazel
  deps/rabbit/src/rabbit_disk_monitor.erl
  deps/rabbit/test/disk_monitor_SUITE.erl
  deps/rabbit/test/unit_disk_monitor_SUITE.erl
Labels: bazel

#5740 Bump Osiris to 1.3.1
  MODULE.bazel
  deps/rabbit/Makefile
  workspace_helpers.bzl
Labels: dependencies, bazel, make, backport-v3.10.x, backport-v3.11.x

#5741 Fix flaky rabbit_fifio_int:credit test
  deps/rabbit/test/rabbit_fifo_int_SUITE.erl
Labels: backport-v3.9.x, backport-v3.10.x, backport-v3.11.x

#5737 Stop sending stats to rabbit_event
  deps/rabbit/src/rabbit_amqqueue_process.erl
  deps/rabbit/src/rabbit_event_consumer.erl
  deps/rabbit/src/rabbit_osiris_metrics.erl
  deps/rabbit/src/rabbit_quorum_memory_manager.erl
  deps/rabbit/src/rabbit_quorum_queue.erl
  deps/rabbit/src/rabbit_reader.erl
  deps/rabbit/test/dummy_event_receiver.erl
  deps/rabbit/test/dynamic_ha_SUITE.erl
  deps/rabbit/test/eager_sync_SUITE.erl
  deps/rabbit/test/simple_ha_SUITE.erl
  deps/rabbit/test/unit_stats_and_metrics_SUITE.erl
  deps/rabbit_common/src/rabbit_event.erl
  deps/rabbit_common/src/rabbit_misc.erl
  deps/rabbitmq_ct_helpers/src/rabbit_ct_broker_helpers.erl
  deps/rabbitmq_event_exchange/src/rabbit_exchange_type_event.erl
  deps/rabbitmq_mqtt/src/rabbit_mqtt_reader.erl
  deps/rabbitmq_stomp/src/rabbit_stomp_reader.erl
  deps/rabbitmq_stream/src/rabbit_stream_reader.erl
Labels: backport-v3.11.x

#5759 Fix rabbit_stream_metrics_gc child spec identifier
  deps/rabbitmq_stream/src/rabbit_stream_sup.erl
Labels: backport-v3.10.x, backport-v3.11.x

#5755 Add login_timeout to mqtt and stomp reader
  deps/rabbitmq_mqtt/priv/schema/rabbitmq_mqtt.schema
  deps/rabbitmq_mqtt/src/rabbit_mqtt_reader.erl
  deps/rabbitmq_mqtt/test/reader_SUITE.erl
  deps/rabbitmq_stomp/priv/schema/rabbitmq_stomp.schema
  deps/rabbitmq_stomp/src/rabbit_stomp_reader.erl
  deps/rabbitmq_stomp/test/connections_SUITE.erl
Labels: backport-v3.9.x, backport-v3.8.x, backport-v3.10.x, backport-v3.11.x

#5775 rabbit_definitions: Apply default-queue-type logic to imported queues
  deps/rabbit/src/rabbit_definitions.erl
  deps/rabbit/src/rabbit_vhost.erl
Labels: backport-v3.11.x

#5769 rabbit_definitions: Apply default-queue-type logic to imported queues
  deps/rabbit/src/rabbit_definitions.erl
Labels: backport-v3.11.x

#5715 Use credit flow for dest side of on-publish shovels
  deps/rabbitmq_shovel/src/rabbit_amqp091_shovel.erl
  deps/rabbitmq_shovel/test/dynamic_SUITE.erl
Labels: backport-v3.11.x

#5779 Adopt otp 24.3.4.5
  WORKSPACE
  bazel/toolchains/BUILD.bazel
Labels: bazel, backport-v3.9.x, backport-v3.8.x, backport-v3.10.x, backport-v3.11.x

#5789 Temporarily reduce and simplify exchange federation suite to be Erlang 25-compatible
  deps/rabbitmq_federation/BUILD.bazel
  deps/rabbitmq_federation/test/exchange_SUITE.erl
  deps/rabbitmq_federation/test/rabbit_federation_status_SUITE.erl
  deps/rabbitmq_federation/test/rabbit_federation_test_util.erl
Labels: bazel, backport-v3.11.x

#5796 Fix dialyzer warning due to renamed type in OTP 21.3
  deps/amqp10_client/README.md
  deps/amqp10_client/src/amqp10_client_connection.erl
Labels: backport-v3.9.x, backport-v3.8.x, backport-v3.10.x, backport-v3.11.x

#5793 Build multi-arch dev images.
  .github/workflows/oci-base.yaml
  .github/workflows/oci.yaml
Labels: backport-v3.9.x, backport-v3.10.x, backport-v3.11.x

#5806 Use tlsv1.2 in //deps/rabbitmq_trust_store:system_SUITE
  deps/rabbitmq_trust_store/test/system_SUITE.erl
Labels: backport-v3.9.x, backport-v3.10.x, backport-v3.11.x

#5791 Re-enable Erlang 25 in Actions
  .github/workflows/test-mixed-versions.yaml
  .github/workflows/test-windows.yaml
  .github/workflows/test.yaml
  deps/rabbitmq_trust_store/src/rabbit_trust_store.erl
Labels: backport-v3.11.x

#5811 Require Erlang/OTP 25.0 (3.11 and 3.12/main only)
  .github/workflows/oci.yaml
  .github/workflows/perform-bazel-execution-comparison.yaml
  .github/workflows/secondary-umbrella.yaml
  .github/workflows/test-mixed-versions.yaml
  .github/workflows/test-windows.yaml
  .github/workflows/test.yaml
  .github/workflows/update-otp-patches.yaml
  deps/rabbit/apps/rabbitmq_prelaunch/src/rabbit_prelaunch_erlang_compat.erl
  deps/rabbitmq_cli/mix.exs
  user-template.bazelrc
Labels: backport-v3.11.x

#5813 Add elixir 1.14 to bazel
  WORKSPACE
  bazel/platforms/BUILD.bazel
  bazel/toolchains/BUILD.bazel
Labels: bazel, backport-v3.11.x

#5815 Ignore failure of optional step in OCI github actions workflow
  .github/workflows/oci.yaml
Labels: backport-v3.9.x, backport-v3.10.x, backport-v3.11.x

#5821 (Possibly temporarily) remove non-Bazel OCI image builds
  .github/workflows/oci.yaml
Labels: backport-v3.11.x

#5824 Updates to 3.11.0 release notes
  release-notes/3.11.0.md
Labels: backport-v3.11.x

#5694 Updates for latest rules_erlang
  .bazelrc
  .github/workflows/oci.yaml
  .github/workflows/test-mixed-versions.yaml
  .github/workflows/test-windows.yaml
  .github/workflows/test.yaml
  .github/workflows/update-otp-patches.yaml
  BUILD.bazel
  MODULE.bazel
  WORKSPACE
  bazel/elixir/elixir.bzl
  bazel/platforms/BUILD.bazel
  bazel/toolchains/BUILD.bazel
  packaging/docker-image/BUILD.bazel
  user-template.bazelrc
Labels: bazel, backport-v3.9.x, backport-v3.10.x, backport-v3.11.x

#4967 Implement header conversion between AMQP 1.0 and 0.9.1
  deps/rabbit/src/rabbit_msg_record.erl
  deps/rabbitmq_amqp1_0/BUILD.bazel
  deps/rabbitmq_amqp1_0/README.md
  deps/rabbitmq_amqp1_0/priv/schema/rabbitmq_amqp1_0.schema
  deps/rabbitmq_amqp1_0/src/rabbit_amqp1_0_message.erl
  deps/rabbitmq_amqp1_0/test/amqp10_client_SUITE.erl
  deps/rabbitmq_amqp1_0/test/config_schema_SUITE.erl
  deps/rabbitmq_amqp1_0/test/config_schema_SUITE_data/rabbitmq_amqp1_0.snippets
Labels: bazel, backport-v3.11.x

#5835 Add Erlang 25.1 to Actions matrix
  .github/workflows/perform-bazel-execution-comparison.yaml
  .github/workflows/update-otp-patches.yaml
Labels: backport-v3.11.x

#5836 Point emqtt test dependency to emqx
  MODULE.bazel
  deps/rabbitmq_mqtt/Makefile
  workspace_helpers.bzl
Labels: rabbitmq-mqtt, dependencies, bazel, make, backport-v3.9.x, backport-v3.10.x, backport-v3.11.x

#5845 Use rules_cc 0.0.2
  MODULE.bazel
Labels: bazel, backport-v3.9.x, backport-v3.10.x, backport-v3.11.x

#5846 Add rabbitmq-streams manpage
  deps/rabbit/docs/rabbitmq-diagnostics.8
  deps/rabbit/docs/rabbitmq-env.conf.5
  deps/rabbit/docs/rabbitmq-plugins.8
  deps/rabbit/docs/rabbitmq-queues.8
  deps/rabbit/docs/rabbitmq-server.8
  deps/rabbit/docs/rabbitmq-service.8
  deps/rabbit/docs/rabbitmq-streams.8
  deps/rabbit/docs/rabbitmq-upgrade.8
  deps/rabbit/docs/rabbitmqctl.8
Labels: doc, backport-v3.10.x, backport-v3.11.x

#5855 3.9.23 release notes
  release-notes/3.9.23.md
Labels: backport-v3.9.x, backport-v3.10.x, backport-v3.11.x

#5863 Pin Osiris to 1.3.1 and Ra to 2.3.0
  MODULE.bazel
  WORKSPACE
  bazel/bzlmod/secondary_umbrella.bzl
  workspace_helpers.bzl
Labels: bazel

#5865 Minor typos fix
  release-notes/3.10.8.md
Labels: backport-v3.10.x, backport-v3.11.x

#5869 Filter out elixir compilation from local execution in bazel
  bazel/elixir/elixir.bzl
  bazel/platforms/BUILD.bazel
Labels: bazel, backport-v3.9.x, backport-v3.10.x, backport-v3.11.x

#5873 Adopt otp 25.0.4
  MODULE.bazel
Labels: bazel, backport-v3.9.x, backport-v3.8.x, backport-v3.10.x, backport-v3.11.x

#5551 Ensure that strings from external sources eventually end up as utf-8 encoded binaries
  deps/rabbit/apps/rabbitmq_prelaunch/src/rabbit_prelaunch.erl
  deps/rabbit/apps/rabbitmq_prelaunch/src/rabbit_prelaunch_conf.erl
  deps/rabbit/src/rabbit_access_control.erl
  deps/rabbit/src/rabbit_amqqueue.erl
  deps/rabbit/src/rabbit_amqqueue_process.erl
  deps/rabbit/src/rabbit_amqqueue_sup_sup.erl
  deps/rabbit/src/rabbit_auth_backend_internal.erl
  deps/rabbit/src/rabbit_channel.erl
  deps/rabbit/src/rabbit_classic_queue.erl
  deps/rabbit/src/rabbit_classic_queue_index_v2.erl
  deps/rabbit/src/rabbit_connection_tracking.erl
  deps/rabbit/src/rabbit_direct.erl
  deps/rabbit/src/rabbit_disk_monitor.erl
  deps/rabbit/src/rabbit_logger_exchange_h.erl
  deps/rabbit/src/rabbit_msg_store.erl
  deps/rabbit/src/rabbit_prelaunch_logging.erl
  deps/rabbit/src/rabbit_queue_index.erl
  deps/rabbit/src/rabbit_ra_systems.erl
  deps/rabbit/src/rabbit_reader.erl
  deps/rabbit/src/rabbit_recovery_terms.erl
  deps/rabbit/src/rabbit_runtime_parameters.erl
  deps/rabbit/src/rabbit_trace.erl
  deps/rabbit/src/rabbit_variable_queue.erl
  deps/rabbit/src/rabbit_vhost.erl
  deps/rabbit/src/rabbit_vhost_msg_store.erl
  deps/rabbit/src/rabbit_vhost_process.erl
  deps/rabbit/src/rabbit_vhost_sup_sup.erl
  deps/rabbit_common/src/rabbit_data_coercion.erl
  deps/rabbit_common/src/rabbit_env.erl
  deps/rabbit_common/src/rabbit_json.erl
  deps/rabbit_common/src/rabbit_misc.erl
  deps/rabbitmq_amqp1_0/src/rabbit_amqp1_0_reader.erl
  deps/rabbitmq_management/src/rabbit_mgmt_wm_nodes.erl
  deps/rabbitmq_management_agent/src/rabbit_mgmt_external_stats.erl
  deps/rabbitmq_shovel/src/Elixir.RabbitMQ.CLI.Ctl.Commands.DeleteShovelCommand.erl
  deps/rabbitmq_shovel/src/rabbit_amqp091_shovel.erl
  deps/rabbitmq_shovel_management/src/rabbit_shovel_mgmt.erl
Labels: backport-pending

#5878 Mark the rbe repo as a dev dependency
  MODULE.bazel
Labels: bazel, backport-v3.9.x, backport-v3.10.x, backport-v3.11.x

#5831 Make rabbit_disk_monitor more resilient
  deps/rabbit/src/rabbit_disk_monitor.erl
Labels: backport-pending

#5883 Adopt otp 24.3.4.5
  MODULE.bazel
  WORKSPACE
Labels: bazel, backport-v3.9.x, backport-v3.10.x, backport-v3.11.x

#5887 mapping deliverycount if present in headers
  deps/rabbitmq_amqp1_0/src/rabbit_amqp1_0_message.erl
Labels: backport-v3.9.x, backport-v3.10.x, backport-v3.11.x

#5890 @elixir_config to match @erlang_config introduced in rules_erlang 3.6
  .github/workflows/oci.yaml
  .github/workflows/update-elixir-patches.yaml
  MODULE.bazel
  WORKSPACE
  bazel/bzlmod/extensions.bzl
  bazel/elixir/elixir.bzl
  bazel/elixir/elixir_build.bzl
  bazel/platforms/BUILD.bazel
  bazel/repositories/BUILD.bazel
  bazel/repositories/BUILD_external.tpl
  bazel/repositories/BUILD_internal.tpl
  bazel/repositories/defaults.bzl.tpl
  bazel/repositories/elixir_config.bzl
  bazel/toolchains/BUILD.bazel
  user-template.bazelrc
Labels: bazel, backport-v3.9.x, backport-v3.10.x, backport-v3.11.x

#5904 Adopt otp 24.3.4.5
  MODULE.bazel
Labels: bazel, backport-v3.9.x, backport-v3.10.x, backport-v3.11.x

#5910 Add option for wildcard certificates to auth_backend_http docs
  deps/rabbitmq_auth_backend_http/README.md
Labels: backport-v3.9.x, backport-v3.10.x, backport-v3.11.x

#5896 fixup windows actions
  .github/workflows/test-windows.yaml
  MODULE.bazel
  WORKSPACE
  bazel/repositories/elixir_config.bzl
Labels: bazel

#5919 Enhance inference of ELIXIR_HOME from the path of iex/elixir
  bazel/repositories/elixir_config.bzl
Labels: bazel, backport-v3.9.x, backport-v3.10.x, backport-v3.11.x

#5930 Add erlang 25.1 to github actions
  .bazelrc
  .github/workflows/oci.yaml
  .github/workflows/test-mixed-versions.yaml
  .github/workflows/test-selenium.yaml
  .github/workflows/test-windows.yaml
  .github/workflows/test.yaml
  .github/workflows/update-otp-patches.yaml
  MODULE.bazel
  WORKSPACE
  bazel/platforms/BUILD.bazel
Labels: bazel, backport-v3.11.x

#5881 List amqp10 connections
  deps/rabbitmq_amqp1_0/BUILD.bazel
  deps/rabbitmq_amqp1_0/src/rabbit_amqp1_0.erl
  deps/rabbitmq_amqp1_0/src/rabbit_amqp1_0_reader.erl
  deps/rabbitmq_amqp1_0/test/command_SUITE.erl
  deps/rabbitmq_amqp1_0/test/system_SUITE_data/console/Program.cs
  deps/rabbitmq_amqp1_0/test/system_SUITE_data/console/README.md
  deps/rabbitmq_amqp1_0/test/system_SUITE_data/console/standalone.csproj
Labels: bazel, backport-v3.9.x, backport-v3.10.x, backport-v3.11.x

#5929 Fix publishing to hex.pm so that projects can be used with erlang.mk
  deps/amqp10_client/Makefile
  deps/amqp10_client/erlang.mk
  deps/amqp10_client/rabbitmq-components.mk
  deps/amqp10_common/Makefile
  deps/amqp10_common/erlang.mk
  deps/amqp10_common/rabbitmq-components.mk
  deps/amqp_client/Makefile
  deps/amqp_client/erlang.mk
  deps/amqp_client/rabbitmq-components.mk
  deps/rabbit_common/Makefile
  deps/rabbit_common/erlang.mk
  deps/rabbit_common/rabbitmq-components.mk
  deps/rabbitmq_auth_backend_cache/README.md
  deps/rabbitmq_peer_discovery_k8s/README.md
  deps/rabbitmq_peer_discovery_k8s/examples/gke/README.md
  deps/rabbitmq_peer_discovery_k8s/examples/kind/README.md
  deps/rabbitmq_peer_discovery_k8s/examples/minikube/README.md
Labels: make, backport-v3.9.x, backport-v3.10.x, backport-v3.11.x

#5897 Make ensure_monitors more defensive in SAC coordinator
  deps/rabbit/src/rabbit_stream_sac_coordinator.erl
  deps/rabbit/test/rabbit_stream_sac_coordinator_SUITE.erl
Labels: backport-v3.11.x
