Repository rabbitmq/rabbitmq-server, pull requests merged in 2023-04, with the labels that each got.

#7798 Introduce a limit for how many virtual hosts can be created in a cluster
  deps/rabbit/priv/schema/rabbit.schema
  deps/rabbit/src/rabbit_queue_type.erl
  deps/rabbit/src/rabbit_vhost.erl
  deps/rabbit/src/vhost.erl
  deps/rabbit/test/per_node_limit_SUITE.erl
  deps/rabbitmq_cli/lib/rabbitmq/cli/ctl/commands/add_vhost_command.ex
  deps/rabbitmq_management/src/rabbit_mgmt_wm_vhost.erl
Labels: backport-v3.12.x

#7809 Management UI footer link updates
  deps/rabbitmq_management/priv/www/js/tmpl/layout.ejs
Labels: backport-v3.10.x, backport-v3.11.x, backport-v3.12.x

#7802 Pass the message to `rabbit_backing_queue:discard` callback
  deps/rabbit/src/rabbit_amqqueue_process.erl
  deps/rabbit/src/rabbit_backing_queue.erl
  deps/rabbit/src/rabbit_mirror_queue_master.erl
  deps/rabbit/src/rabbit_mirror_queue_slave.erl
  deps/rabbit/src/rabbit_priority_queue.erl
  deps/rabbit/src/rabbit_variable_queue.erl
Labels: backport-v3.12.x

#7806 Update Cowlib to 2.12.1
  MODULE.bazel
  deps/rabbitmq_management/test/rabbit_mgmt_http_SUITE.erl
  rabbitmq-components.mk
Labels: bazel, make, backport-v3.11.x, backport-v3.12.x

#7831 Regenerate BUILD.cowlib using 'bazel run gazelle-update-repos -- -args hex.pm/cowlib@2.12.1'
  bazel/BUILD.cowlib
Labels: backport-v3.11.x, backport-v3.12.x

#7765 Unblock group of consumers on super stream partition
  deps/rabbit/BUILD.bazel
  deps/rabbit/src/rabbit_core_ff.erl
  deps/rabbit/src/rabbit_stream_sac_coordinator.erl
  deps/rabbit/test/rabbit_stream_sac_coordinator_SUITE.erl
  deps/rabbitmq_stream/src/rabbit_stream_reader.erl
  deps/rabbitmq_stream/test/rabbit_stream_SUITE.erl
Labels: bazel, make, backport-v3.11.x, backport-v3.12.x

#7821 Update ct_helper
  MODULE.bazel
  bazel/BUILD.ct_helper
  deps/rabbitmq_trust_store/test/system_SUITE.erl
  moduleindex.yaml
Labels: bazel, backport-v3.10.x, backport-v3.11.x, backport-v3.12.x

#7841 Remove debug log statements in stream SAC coordinator
  deps/rabbit/src/rabbit_stream_sac_coordinator.erl
Labels: backport-v3.11.x, backport-v3.12.x

#7827 Quorum queues: avoid potential crash when returning message.
  MODULE.bazel
  deps/rabbit/src/rabbit_fifo.erl
  deps/rabbit/test/quorum_queue_SUITE.erl
  rabbitmq-components.mk
Labels: bazel, make, backport-v3.11.x, backport-v3.12.x

#7846 Streams: make at-most-once dead lettering work
  MODULE.bazel
  deps/rabbit/Makefile
  deps/rabbit/src/rabbit_stream_queue.erl
  deps/rabbit/test/rabbit_stream_queue_SUITE.erl
Labels: bazel, make, backport-v3.11.x, backport-v3.12.x

#7853 Quorum queues: warn when policy command was not successful
  deps/rabbit/src/rabbit_quorum_queue.erl
Labels: backport-v3.11.x, backport-v3.12.x

#7881 See #7880. Remove node_deleted handling in rabbit_channel_tracking_ha…
  deps/rabbit/src/rabbit_channel_tracking_handler.erl
Labels: backport-v3.12.x

#7884 Revert "Pass the message to `rabbit_backing_queue:discard` callback "
  deps/rabbit/src/rabbit_amqqueue_process.erl
  deps/rabbit/src/rabbit_backing_queue.erl
  deps/rabbit/src/rabbit_mirror_queue_master.erl
  deps/rabbit/src/rabbit_mirror_queue_slave.erl
  deps/rabbit/src/rabbit_priority_queue.erl
  deps/rabbit/src/rabbit_variable_queue.erl
Labels: backport-v3.12.x

#7885 Fetch hexpm/hex via bzlmod
  MODULE.bazel
  WORKSPACE
  bazel/BUILD.hex
  bazel/bzlmod/extensions.bzl
  bazel/elixir/mix_archive_build.bzl
  deps/rabbitmq_cli/BUILD.bazel
  deps/rabbitmq_cli/rabbitmqctl.bzl
  deps/rabbitmq_cli/rabbitmqctl_test.bzl
  dist.bzl
Labels: bazel, backport-v3.10.x, backport-v3.11.x, backport-v3.12.x

#7889 Mark per_user_connection_channel_limit_partitions_SUITE flaky
  deps/rabbit/BUILD.bazel
  deps/rabbit/test/per_user_connection_channel_limit_partitions_SUITE.erl
Labels: bazel

#7887 Remove deprecated UAA oauth settings
  deps/rabbitmq_auth_backend_oauth2/priv/schema/rabbitmq_auth_backend_oauth2.schema
  deps/rabbitmq_management/priv/schema/rabbitmq_management.schema
  deps/rabbitmq_management/priv/www/js/oidc-oauth/helper.js
  deps/rabbitmq_management/selenium/test/oauth/rabbitmq.conf
  deps/rabbitmq_management/src/rabbit_mgmt_oauth_bootstrap.erl
  deps/rabbitmq_management/src/rabbit_mgmt_wm_auth.erl
Labels: backport-v3.12.x

#7896 Handle all queue types in is_process_hibernated
  deps/rabbit/src/rabbit_process.erl
Labels: backport-v3.12.x

#7894 Fix dialyzer errors for rabbitmq_shovel on OTP 26
  BUILD.bazel
  MODULE.bazel
  WORKSPACE
  deps/rabbitmq_auth_backend_oauth2/BUILD.bazel
  deps/rabbitmq_shovel/BUILD.bazel
Labels: bazel, backport-v3.12.x

#7909 Revert "Remove an old version of rabbit_mgmt_wm_auth"
  deps/rabbitmq_management/src/rabbit_mgmt_oauth_bootstrap.erl
Labels: backport-v3.12.x

#7906 Ignore warnings when building plt files for dependencies (OTP 26 build compatibility)
  deps/amqp10_client/BUILD.bazel
  deps/amqp_client/BUILD.bazel
  deps/rabbit/BUILD.bazel
  deps/rabbit/apps/rabbitmq_prelaunch/BUILD.bazel
  deps/rabbit_common/BUILD.bazel
  deps/rabbitmq_amqp1_0/BUILD.bazel
  deps/rabbitmq_auth_backend_cache/BUILD.bazel
  deps/rabbitmq_auth_backend_http/BUILD.bazel
  deps/rabbitmq_auth_backend_ldap/BUILD.bazel
  deps/rabbitmq_auth_mechanism_ssl/BUILD.bazel
  deps/rabbitmq_aws/BUILD.bazel
  deps/rabbitmq_cli/BUILD.bazel
  deps/rabbitmq_consistent_hash_exchange/BUILD.bazel
  deps/rabbitmq_event_exchange/BUILD.bazel
  deps/rabbitmq_federation/BUILD.bazel
  deps/rabbitmq_federation_management/BUILD.bazel
  deps/rabbitmq_jms_topic_exchange/BUILD.bazel
  deps/rabbitmq_management/BUILD.bazel
  deps/rabbitmq_management_agent/BUILD.bazel
  deps/rabbitmq_mqtt/BUILD.bazel
  deps/rabbitmq_peer_discovery_aws/BUILD.bazel
  deps/rabbitmq_peer_discovery_common/BUILD.bazel
  deps/rabbitmq_peer_discovery_consul/BUILD.bazel
  deps/rabbitmq_peer_discovery_etcd/BUILD.bazel
  deps/rabbitmq_peer_discovery_k8s/BUILD.bazel
  deps/rabbitmq_prometheus/BUILD.bazel
  deps/rabbitmq_random_exchange/BUILD.bazel
  deps/rabbitmq_recent_history_exchange/BUILD.bazel
  deps/rabbitmq_sharding/BUILD.bazel
  deps/rabbitmq_shovel_management/BUILD.bazel
  deps/rabbitmq_stomp/BUILD.bazel
  deps/rabbitmq_stream/BUILD.bazel
  deps/rabbitmq_stream_common/BUILD.bazel
  deps/rabbitmq_stream_management/BUILD.bazel
  deps/rabbitmq_top/BUILD.bazel
  deps/rabbitmq_tracing/BUILD.bazel
  deps/rabbitmq_trust_store/BUILD.bazel
  deps/rabbitmq_web_dispatch/BUILD.bazel
  deps/rabbitmq_web_mqtt/BUILD.bazel
  deps/rabbitmq_web_mqtt_examples/BUILD.bazel
  deps/rabbitmq_web_stomp/BUILD.bazel
  deps/rabbitmq_web_stomp_examples/BUILD.bazel
Labels: bazel, backport-v3.12.x

#7900 (Initial, incomplete) OTP26 compatibility
  .github/workflows/test-erlang-git.yaml
  .github/workflows/test-windows.yaml
  deps/amqp_client/src/amqp_ssl.erl
  deps/rabbit/apps/rabbitmq_prelaunch/src/rabbit_prelaunch_conf.erl
  deps/rabbit/src/rabbit_stream_coordinator.erl
  deps/rabbit/test/definition_import_SUITE.erl
  deps/rabbit/test/proxy_protocol_SUITE.erl
  deps/rabbit/test/term_to_binary_compat_prop_SUITE.erl
  deps/rabbit/test/unit_collections_SUITE.erl
  deps/rabbit/test/unit_config_value_encryption_SUITE.erl
  deps/rabbit_common/src/rabbit_misc.erl
  deps/rabbit_common/src/rabbit_net.erl
  deps/rabbit_common/test/unit_SUITE.erl
  deps/rabbitmq_cli/test/ctl/list_bindings_command_test.exs
  deps/rabbitmq_cli/test/ctl/list_channels_command_test.exs
  deps/rabbitmq_cli/test/ctl/list_connections_command_test.exs
  deps/rabbitmq_cli/test/ctl/list_consumers_command_test.exs
  deps/rabbitmq_cli/test/ctl/list_exchanges_command_test.exs
  deps/rabbitmq_cli/test/ctl/list_feature_flags_command_test.exs
  deps/rabbitmq_cli/test/ctl/list_queues_command_test.exs
  deps/rabbitmq_cli/test/ctl/list_vhosts_command_test.exs
  deps/rabbitmq_cli/test/ctl/wait_command_test.exs
  deps/rabbitmq_cli/test/diagnostics/schema_info_command_test.exs
  deps/rabbitmq_management/src/rabbit_mgmt_app.erl
  deps/rabbitmq_mqtt/test/reader_SUITE.erl
  deps/rabbitmq_stomp/src/rabbit_stomp_util.erl
  deps/rabbitmq_stream/test/rabbit_stream_SUITE.erl
  deps/rabbitmq_trust_store/test/system_SUITE.erl
  deps/rabbitmq_web_mqtt/test/src/rfc6455_client.erl
  deps/rabbitmq_web_stomp/test/src/rfc6455_client.erl
Labels: backport-v3.12.x

#7914 Introduce a way to update virtual host metadata using CLI tools
  deps/rabbit/src/rabbit_vhost.erl
  deps/rabbitmq_cli/lib/rabbitmq/cli/core/virtual_hosts.ex
  deps/rabbitmq_cli/lib/rabbitmq/cli/ctl/commands/add_vhost_command.ex
  deps/rabbitmq_cli/lib/rabbitmq/cli/ctl/commands/update_vhost_metadata_command.ex
  deps/rabbitmq_cli/test/ctl/add_vhost_command_test.exs
  deps/rabbitmq_cli/test/ctl/update_vhost_metadata_command_test.exs
  deps/rabbitmq_cli/test/test_helper.exs
Labels: backport-v3.11.x, backport-v3.12.x

#7917 Make it possible to configure per-node runtime parameter limits
  deps/rabbit/BUILD.bazel
  deps/rabbit/priv/schema/rabbit.schema
  deps/rabbit/src/rabbit_runtime_parameters.erl
  deps/rabbit/test/config_schema_SUITE_data/rabbit.snippets
  deps/rabbit/test/dummy_runtime_parameters.erl
  deps/rabbit/test/runtime_parameters_SUITE.erl
Labels: bazel, backport-v3.11.x, backport-v3.12.x

#7921 Revert erlang:port_command/2 to gen_tcp:send/2 change
  deps/rabbit_common/src/rabbit_net.erl
Labels: backport-v3.12.x

#7925 Fix test case confirm_minority
  deps/rabbit/src/rabbit_quorum_queue.erl
Labels: backport-v3.12.x

#7924 Support variable expansion in JWT token scopes in the context of topic operation authorization (#7178)
  deps/rabbitmq_auth_backend_oauth2/src/rabbit_auth_backend_oauth2.erl
  deps/rabbitmq_auth_backend_oauth2/test/rabbit_auth_backend_oauth2_test_util.erl
  deps/rabbitmq_auth_backend_oauth2/test/scope_SUITE.erl
  deps/rabbitmq_auth_backend_oauth2/test/unit_SUITE.erl
Labels: backport-v3.10.x, backport-v3.11.x, backport-v3.12.x

#7937 Use `additional_beam instead` of `additional_srcs`
  deps/rabbit/BUILD.bazel
  deps/rabbit/app.bzl
Labels: bazel

#7745 Recovery terms: use ram_file on start, but not on shutdown
  deps/rabbit/src/rabbit_queue_index.erl
  deps/rabbit/src/rabbit_recovery_terms.erl
  deps/rabbit/src/rabbit_vhost_sup_sup.erl
Labels: performance, backport-v3.12.x

#7866 Fix stream import on startup
  deps/rabbit/src/rabbit_db_queue.erl
  deps/rabbit/src/rabbit_stream_coordinator.erl
Labels: bug, backport-v3.12.x

#7943 Ensure monitor is started when dequeuing
  deps/rabbit/src/rabbit_classic_queue.erl
Labels: backport-v3.10.x, backport-v3.11.x, backport-v3.12.x

#7938 Adjust `-include(...` in some tests to work with both bazel and make
  deps/rabbit/test/rabbit_fifo_SUITE.erl
  deps/rabbit/test/rabbit_fifo_dlx_SUITE.erl
  deps/rabbit/test/rabbit_fifo_prop_SUITE.erl
  deps/rabbit/test/rabbit_fifo_v0_SUITE.erl
  deps/rabbit/test/rabbit_stream_coordinator_SUITE.erl
  deps/rabbit/test/rabbit_stream_sac_coordinator_SUITE.erl
Labels: backport-v3.10.x, backport-v3.11.x, backport-v3.12.x

#7958 Adopt otp 24.3.4.11
  MODULE.bazel
  WORKSPACE
Labels: bazel

#7927 Make tcp send OTP 26 compatible
  deps/rabbit_common/src/rabbit_net.erl
Labels: backport-v3.12.x

#7965 Bump test cluster creation timeouts
  deps/rabbitmq_mqtt/test/cluster_SUITE.erl
  deps/rabbitmq_mqtt/test/command_SUITE.erl
  deps/rabbitmq_mqtt/test/ff_SUITE.erl
  deps/rabbitmq_mqtt/test/shared_SUITE.erl
Labels: backport-v3.12.x

#7966 OTP26 compatibility: `{verify_none}`
  deps/rabbitmq_amqp1_0/test/proxy_protocol_SUITE.erl
  deps/rabbitmq_mqtt/test/proxy_protocol_SUITE.erl
  deps/rabbitmq_stomp/test/proxy_protocol_SUITE.erl
  deps/rabbitmq_stream/test/commands_SUITE.erl
  deps/rabbitmq_web_mqtt/test/src/rfc6455_client.erl
  deps/rabbitmq_web_stomp/test/src/rfc6455_client.erl
Labels: backport-v3.12.x

#7963 CLI: make input ordering preditable when formatting a table
  deps/rabbitmq_cli/lib/rabbitmq/cli/formatters/formatter_helpers.ex
  deps/rabbitmq_cli/lib/rabbitmq/cli/formatters/table.ex
  deps/rabbitmq_cli/test/core/table_formatter_test.exs
Labels: backport-v3.12.x, erlang-26

#7970 CLI: more OTP 26 compatibility for remote_shell
  deps/rabbitmq_cli/lib/rabbitmq/cli/diagnostics/commands/remote_shell_command.ex
Labels: backport-v3.12.x, erlang-26

#7964 Adjust the platform definition for the erlang git master pipeline
  bazel/platforms/BUILD.bazel
Labels: bazel, backport-v3.10.x, backport-v3.11.x, backport-v3.12.x

#7981 Allow setting consumer timeout via queue policy/arg and as consumer argument
  deps/rabbit/src/rabbit_channel.erl
  deps/rabbit/src/rabbit_networking.erl
  deps/rabbit/src/rabbit_policies.erl
  deps/rabbit/test/consumer_timeout_SUITE.erl
Labels: backport-v3.11.x, backport-v3.12.x

#7980 CQv1: Don't limit messages in memory based on consume rate
  deps/rabbit/src/rabbit_variable_queue.erl
Labels: backport-v3.12.x

#7989 Simplify the reference to RABBITMQ_RUN in bazel in integration tests
  rabbitmq.bzl
Labels: bazel, backport-v3.10.x, backport-v3.11.x, backport-v3.12.x

#7990 Adopt elixir 1.14.4
  MODULE.bazel
  WORKSPACE
Labels: bazel, backport-v3.10.x, backport-v3.11.x, backport-v3.12.x

#8012 CONTRIBUTING.md: explain how to use BrowserSync
  CONTRIBUTING.md
Labels: backport-v3.9.x, backport-v3.10.x, backport-v3.11.x, backport-v3.12.x

#8018 Update CONTRIBUTING.md to mention Bazel
  CONTRIBUTING.md
Labels: backport-v3.9.x, backport-v3.10.x, backport-v3.11.x, backport-v3.12.x

#8010 Management UI: handle invalid regular expressions in filters when switching tabs
  deps/rabbitmq_management/priv/www/js/global.js
  deps/rabbitmq_management/priv/www/js/main.js
Labels: backport-v3.9.x, backport-v3.10.x, backport-v3.11.x, backport-v3.12.x

#8003 OTP26 compatibility
  .github/workflows/oci.yaml
  .github/workflows/test-windows.yaml
  MODULE.bazel
  bazel/BUILD.emqtt
  deps/rabbit/src/rabbit_time_travel_dbg.erl
  deps/rabbitmq_auth_backend_oauth2/Makefile
  deps/rabbitmq_mqtt/Makefile
  deps/rabbitmq_trust_store/test/system_SUITE.erl
  deps/rabbitmq_web_mqtt/Makefile
Labels: bazel, make, backport-v3.12.x

#8029 Do not run windows tests in github actions on any pushes
  .github/workflows/test-windows.yaml
Labels: backport-v3.10.x, backport-v3.11.x, backport-v3.12.x

#8032 3.11.14 release notes
  release-notes/3.11.14.md
Labels: backport-v3.11.x, backport-v3.12.x

#8035 3.12.0 release notes updates
  release-notes/3.12.0.md
Labels: backport-v3.12.x

#8037 3.10.21 release notes
  release-notes/3.10.20.md
  release-notes/3.10.21.md
Labels: backport-v3.10.x, backport-v3.11.x, backport-v3.12.x

#8043 Add ha-sync-mode as an operator policy
  deps/rabbit/priv/schema/rabbit.schema
  deps/rabbit/src/rabbit_mirror_queue_misc.erl
  deps/rabbit/test/config_schema_SUITE_data/rabbit.snippets
  deps/rabbit/test/policy_SUITE.erl
Labels: backport-v3.11.x, backport-v3.12.x

#8046 Adopt otp 25.0.4
  MODULE.bazel
Labels: bazel, backport-v3.11.x, backport-v3.12.x

#8051 Adopt otp 25.3.1
  MODULE.bazel
  WORKSPACE
Labels: bazel, backport-v3.10.x, backport-v3.11.x, backport-v3.12.x

#8056 Keep storing MQTT client IDs as lists in Ra
  deps/rabbitmq_mqtt/include/mqtt_machine.hrl
  deps/rabbitmq_mqtt/src/mqtt_machine.erl
  deps/rabbitmq_mqtt/src/rabbit_mqtt_collector.erl
  deps/rabbitmq_mqtt/src/rabbit_mqtt_processor.erl
  deps/rabbitmq_mqtt/test/cluster_SUITE.erl
  deps/rabbitmq_mqtt/test/ff_SUITE.erl
  deps/rabbitmq_mqtt/test/shared_SUITE.erl
  deps/rabbitmq_mqtt/test/util.erl
Labels: backport-v3.12.x

#8062 Update Cowboy to 2.10.0 for OTP-26
  MODULE.bazel
  deps/rabbitmq_web_dispatch/Makefile
  rabbitmq-components.mk
Labels: bazel, make, backport-v3.12.x

#8066 3.11.15 release notes
  release-notes/3.11.15.md
Labels: backport-v3.11.x, backport-v3.12.x

#8068 3.10.22 release notes
  release-notes/3.10.22.md
Labels: backport-v3.10.x, backport-v3.11.x, backport-v3.12.x
