Repository rabbitmq/rabbitmq-server, pull requests merged in 2023-07, with the labels that each got.

#8727 Adopt otp 24.3.4.13
  MODULE.bazel
  WORKSPACE
Labels: bazel

#8701 Table column selection pane cutts off "Close", and other attributes
  deps/rabbitmq_management/priv/www/css/main.css
Labels: backport-v3.10.x, backport-v3.11.x, backport-v3.12.x

#8015 Settle unroutable message with released state
  deps/amqp_client/src/amqp_channel.erl
  deps/rabbit/src/rabbit_channel.erl
  deps/rabbit_common/src/rabbit_writer.erl
  deps/rabbitmq_amqp1_0/src/rabbit_amqp1_0_incoming_link.erl
  deps/rabbitmq_amqp1_0/src/rabbit_amqp1_0_session.erl
  deps/rabbitmq_amqp1_0/src/rabbit_amqp1_0_session_process.erl
  deps/rabbitmq_amqp1_0/test/amqp10_client_SUITE.erl
  deps/rabbitmq_amqp1_0/test/system_SUITE.erl
  deps/rabbitmq_amqp1_0/test/system_SUITE_data/fsharp-tests/Program.fs
Labels: backport-v3.11.x, backport-v3.12.x

#8743 CLI tools: introduce commands that enable and disable free disk space monitoring
  deps/rabbit/src/rabbit_disk_monitor.erl
  deps/rabbitmq_cli/lib/rabbitmq/cli/ctl/commands/disable_free_disk_space_monitoring_command.ex
  deps/rabbitmq_cli/lib/rabbitmq/cli/ctl/commands/enable_free_disk_space_monitoring_command.ex
  deps/rabbitmq_cli/test/ctl/disable_disk_free_space_monitoring_command_test.exs
  deps/rabbitmq_cli/test/ctl/enable_disk_free_space_monitoring_command_test.exs
Labels: backport-v3.11.x, backport-v3.12.x

#8753 Allow bazel modules depending on rabbitmq-server to override @rbe
  bazel/bzlmod/extensions.bzl
Labels: bazel, backport-v3.10.x, backport-v3.11.x, backport-v3.12.x

#8748 Add elixir 1.15.2
  MODULE.bazel
  WORKSPACE
  bazel/amqp.patch
  bazel/platforms/BUILD.bazel
  deps/rabbitmq_cli/BUILD.bazel
  deps/rabbitmq_cli/config/config.exs
  deps/rabbitmq_cli/lib/rabbit_common/records.ex
  deps/rabbitmq_cli/lib/rabbitmq/cli/core/code_path.ex
  deps/rabbitmq_cli/lib/rabbitmq/cli/core/config.ex
  deps/rabbitmq_cli/lib/rabbitmq/cli/core/listeners.ex
  deps/rabbitmq_cli/lib/rabbitmq/cli/ctl/commands/shutdown_command.ex
  deps/rabbitmq_cli/lib/rabbitmq/cli/ctl/commands/wait_command.ex
  deps/rabbitmq_cli/lib/rabbitmq/cli/diagnostics/commands/remote_shell_command.ex
  deps/rabbitmq_cli/lib/rabbitmq/cli/formatters/csv.ex
  deps/rabbitmq_cli/lib/rabbitmq/cli/formatters/pretty_table.ex
  deps/rabbitmq_cli/lib/rabbitmqctl.ex
  deps/rabbitmq_cli/mix.exs
  deps/rabbitmq_cli/rabbitmqctl.bzl
  deps/rabbitmq_cli/rabbitmqctl_test.bzl
  deps/rabbitmq_cli/test/core/default_output_test.exs
  deps/rabbitmq_cli/test/core/helpers_test.exs
  deps/rabbitmq_cli/test/core/table_formatter_test.exs
  deps/rabbitmq_cli/test/ctl/clear_global_parameter_command_test.exs
  deps/rabbitmq_cli/test/ctl/clear_operator_policy_command_test.exs
  deps/rabbitmq_cli/test/ctl/clear_parameter_command_test.exs
  deps/rabbitmq_cli/test/ctl/clear_policy_command_test.exs
  deps/rabbitmq_cli/test/ctl/clear_vhost_limits_command_test.exs
  deps/rabbitmq_cli/test/ctl/enable_feature_flag_test.exs
  deps/rabbitmq_cli/test/ctl/list_feature_flags_command_test.exs
  deps/rabbitmq_cli/test/ctl/set_operator_policy_command_test.exs
  deps/rabbitmq_cli/test/ctl/set_parameter_command_test.exs
  deps/rabbitmq_cli/test/ctl/set_permissions_command_test.exs
  deps/rabbitmq_cli/test/ctl/set_permissions_globally_command_test.exs
  deps/rabbitmq_cli/test/ctl/set_policy_command_test.exs
  deps/rabbitmq_cli/test/ctl/set_user_limits_command_test.exs
  deps/rabbitmq_cli/test/ctl/set_vhost_limits_command_test.exs
  deps/rabbitmq_cli/test/diagnostics/check_port_connectivity_command_test.exs
  deps/rabbitmq_cli/test/diagnostics/log_tail_command_test.exs
  deps/rabbitmq_cli/test/plugins/disable_plugins_command_test.exs
  deps/rabbitmq_cli/test/plugins/enable_plugins_command_test.exs
  deps/rabbitmq_cli/test/plugins/list_plugins_command_test.exs
  deps/rabbitmq_cli/test/plugins/plugins_formatter_test.exs
  deps/rabbitmq_cli/test/test_helper.exs
Labels: bazel, backport-v3.12.x

#8765 Adopt otp 25.3.2.3
  MODULE.bazel
Labels: bazel, backport-v3.10.x, backport-v3.11.x, backport-v3.12.x

#8747 Fix combination of `amqqueue:get_pid/1` and `node/1`
  deps/rabbit/src/rabbit_classic_queue.erl
  deps/rabbit/src/rabbit_quorum_queue.erl
Labels: backport-v3.11.x, backport-v3.12.x

#8788 Explicitly set HOME in `elixir_build` rule
  bazel/elixir/elixir_build.bzl
Labels: bazel, backport-v3.10.x, backport-v3.11.x, backport-v3.12.x

#8667 Deprecate features in the code for RabbitMQ 4.0
  deps/rabbit/BUILD.bazel
  deps/rabbit/app.bzl
  deps/rabbit/src/rabbit.erl
  deps/rabbit/src/rabbit_amqqueue.erl
  deps/rabbit/src/rabbit_channel.erl
  deps/rabbit/src/rabbit_mirror_queue_misc.erl
  deps/rabbit/src/rabbit_mnesia.erl
  deps/rabbit/test/config_schema_SUITE_data/rabbit.snippets
  deps/rabbit/test/rabbitmq_4_0_deprecations_SUITE.erl
  deps/rabbitmq_management/src/rabbit_mgmt_app.erl
  deps/rabbitmq_management/src/rabbit_mgmt_features.erl
  deps/rabbitmq_management/src/rabbit_mgmt_util.erl
  deps/rabbitmq_management_agent/src/rabbit_mgmt_agent_config.erl
  deps/rabbitmq_management_agent/src/rabbit_mgmt_agent_sup.erl
Labels: bazel

#8502 rabbit_db: Further split Mnesia-specific and non-Mnesia-specific clustering steps
  deps/rabbit/BUILD.bazel
  deps/rabbit/src/rabbit_db.erl
  deps/rabbit/src/rabbit_db_cluster.erl
  deps/rabbit/src/rabbit_mnesia.erl
  deps/rabbit/src/rabbit_nodes.erl
  deps/rabbit/src/rabbit_peer_discovery.erl
  deps/rabbit/test/clustering_management_SUITE.erl
  deps/rabbit/test/peer_discovery_classic_config_SUITE.erl
  deps/rabbit/test/unit_cluster_formation_locking_mocks_SUITE.erl
  deps/rabbit_common/include/logging.hrl
  deps/rabbit_common/src/rabbit_misc.erl
  deps/rabbit_common/test/unit_SUITE.erl
  deps/rabbitmq_cli/test/ctl/join_cluster_command_test.exs
Labels: bazel

#8694 Tests: more resilient time-dependent tests
  deps/rabbit/BUILD.bazel
  deps/rabbit/Makefile
  deps/rabbit/app.bzl
  deps/rabbit/test/dead_lettering_SUITE.erl
  deps/rabbit/test/definition_import_SUITE.erl
  deps/rabbit/test/dynamic_qq_SUITE.erl
  deps/rabbit/test/per_user_connection_channel_limit_partitions_SUITE.erl
  deps/rabbit/test/per_user_connection_channel_tracking_SUITE.erl
  deps/rabbit/test/per_user_connection_tracking_SUITE.erl
  deps/rabbit/test/per_vhost_connection_limit_SUITE.erl
  deps/rabbit/test/per_vhost_queue_limit_SUITE.erl
  deps/rabbit/test/queue_master_location_SUITE.erl
  deps/rabbit/test/quorum_queue_SUITE.erl
  deps/rabbit/test/rabbit_stream_queue_SUITE.erl
  deps/rabbit/test/unit_log_management_SUITE.erl
  deps/rabbit/test/vhost_SUITE.erl
Labels: bazel, make, backport-v3.11.x, backport-v3.12.x

#8803 bazel run gazelle
  deps/rabbit/app.bzl
Labels: bazel

#8804 bazel run gazelle
  deps/rabbit/app.bzl
Labels: bazel

#8801 CLI: Rename disk space monitoring commands
  deps/rabbitmq_cli/lib/rabbitmq/cli/ctl/commands/activate_free_disk_space_monitoring_command.ex
  deps/rabbitmq_cli/lib/rabbitmq/cli/ctl/commands/deactivate_free_disk_space_monitoring_command.ex
  deps/rabbitmq_cli/test/ctl/activate_disk_free_space_monitoring_command_test.exs
  deps/rabbitmq_cli/test/ctl/deactivate_disk_free_space_monitoring_command_test.exs
Labels: backport-v3.11.x, backport-v3.12.x

#8808 Prometheus core metrics collector: Do not render samples that are NaN or undefined
  deps/rabbitmq_prometheus/src/collectors/prometheus_rabbitmq_core_metrics_collector.erl
Labels: backport-v3.11.x, backport-v3.12.x

#8802 STOMP: introduce a max frame size limit
  .gitignore
  deps/rabbitmq_stomp/include/rabbit_stomp.hrl
  deps/rabbitmq_stomp/priv/schema/rabbitmq_stomp.schema
  deps/rabbitmq_stomp/src/rabbit_stomp_reader.erl
  deps/rabbitmq_stomp/test/connections_SUITE.erl
  deps/rabbitmq_stomp/test/python_SUITE.erl
  deps/rabbitmq_stomp/test/python_SUITE_data/src/main_runner.py
  deps/rabbitmq_stomp/test/python_SUITE_data/src/requirements.txt
  deps/rabbitmq_stomp/test/python_SUITE_data/src/test_runner.py
  deps/rabbitmq_stomp/test/python_SUITE_data/src/tls_runner.py
Labels: backport-v3.12.x

#8790 FHC: use exception-safe versions of ets update functions
  deps/rabbit/src/rabbit_msg_store.erl
  deps/rabbit_common/src/file_handle_cache.erl
  deps/rabbit_common/src/file_handle_cache_stats.erl
  deps/rabbit_common/src/rabbit_misc.erl
  deps/rabbit_common/src/rabbit_types.erl
  deps/rabbitmq_web_mqtt/priv/schema/rabbitmq_web_mqtt.schema
  deps/rabbitmq_web_mqtt/src/rabbit_web_mqtt_handler.erl
  deps/rabbitmq_web_mqtt/test/config_schema_SUITE_data/rabbitmq_web_mqtt.snippets
  deps/rabbitmq_web_stomp/priv/schema/rabbitmq_web_stomp.schema
  deps/rabbitmq_web_stomp/src/rabbit_web_stomp_handler.erl
  deps/rabbitmq_web_stomp/test/config_schema_SUITE_data/rabbitmq_web_stomp.snippets
Labels: backport-v3.12.x

#8813 Drop deprecated set-output github actions command in oci-base.yaml
  .github/workflows/oci-base.yaml
Labels: backport-v3.10.x, backport-v3.11.x, backport-v3.12.x

#8816 3.12.2 release notes
  release-notes/3.12.2.md
Labels: backport-v3.12.x

#8799 Fix at-least-once dead lettering when the target include the source
  deps/rabbit/src/rabbit_fifo_dlx.erl
  deps/rabbit/src/rabbit_fifo_dlx_client.erl
  deps/rabbit/src/rabbit_fifo_dlx_worker.erl
  deps/rabbit/test/dead_lettering_SUITE.erl
  deps/rabbit/test/rabbit_fifo_dlx_integration_SUITE.erl
Labels: backport-v3.11.x, backport-v3.12.x

#8207 Stream server side filtering
  deps/rabbit/src/rabbit_amqqueue.erl
  deps/rabbit/src/rabbit_core_ff.erl
  deps/rabbit/src/rabbit_policies.erl
  deps/rabbit/src/rabbit_stream_queue.erl
  deps/rabbit/test/rabbit_stream_queue_SUITE.erl
  deps/rabbitmq_management/priv/www/js/global.js
  deps/rabbitmq_management/priv/www/js/tmpl/policies.ejs
  deps/rabbitmq_management/priv/www/js/tmpl/queues.ejs
  deps/rabbitmq_stream/docs/PROTOCOL.adoc
  deps/rabbitmq_stream/src/rabbit_stream_manager.erl
  deps/rabbitmq_stream/src/rabbit_stream_reader.erl
  deps/rabbitmq_stream/src/rabbit_stream_utils.erl
  deps/rabbitmq_stream/test/commands_SUITE.erl
  deps/rabbitmq_stream/test/rabbit_stream_SUITE.erl
  deps/rabbitmq_stream/test/rabbit_stream_utils_SUITE.erl
  deps/rabbitmq_stream_common/src/rabbit_stream_core.erl
  deps/rabbitmq_stream_common/test/rabbit_stream_core_SUITE.erl
Labels: bazel, make

#8838 Fix default topic exchange stomp test
  deps/rabbitmq_stomp/test/topic_SUITE.erl
Labels: rabbitmq-stomp, backport-v3.11.x, backport-v3.12.x

#8841 3.12.2 release notes update
  release-notes/3.12.2.md
Labels: backport-v3.12.x

#8837 rabbit_disk_monitor: handle gen_server timeouts to reduce log noise
  deps/rabbit/src/rabbit_disk_monitor.erl
Labels: backport-v3.12.x

#8844 Document stream management plugin endpoints
  deps/rabbitmq_management/priv/www/api/index.html
Labels: backport-v3.11.x, backport-v3.12.x

#8218 Reconcile (repair or expand) quorum queue membership periodically
  deps/rabbit/BUILD.bazel
  deps/rabbit/app.bzl
  deps/rabbit/priv/schema/rabbit.schema
  deps/rabbit/src/rabbit.erl
  deps/rabbit/src/rabbit_node_monitor.erl
  deps/rabbit/src/rabbit_nodes.erl
  deps/rabbit/src/rabbit_policy.erl
  deps/rabbit/src/rabbit_quorum_queue.erl
  deps/rabbit/src/rabbit_quorum_queue_periodic_membership_reconciliation.erl
  deps/rabbit/test/quorum_queue_member_reconciliation_SUITE.erl
  deps/rabbit_common/src/rabbit_misc.erl
  deps/rabbitmq_management/priv/www/js/tmpl/queues.ejs
  moduleindex.yaml
Labels: bazel

#8846 Make mqtt.subscription_ttl unsupported
  deps/rabbit/docs/rabbitmq.conf.example
  deps/rabbitmq_mqtt/BUILD.bazel
  deps/rabbitmq_mqtt/Makefile
  deps/rabbitmq_mqtt/priv/schema/rabbitmq_mqtt.schema
  deps/rabbitmq_mqtt/src/rabbit_mqtt_processor.erl
  deps/rabbitmq_mqtt/test/config_schema_SUITE_data/rabbitmq_mqtt.snippets
  deps/rabbitmq_mqtt/test/shared_SUITE.erl
  deps/rabbitmq_mqtt/test/v5_SUITE.erl
Labels: bazel, make

#8858 Mention Ra bump in 3.12.2 release notes
  release-notes/3.12.2.md
Labels: backport-v3.12.x

#8872 Do not force mix format check as part of build
  deps/rabbitmq_cli/mix.exs
Labels: backport-v3.10.x, backport-v3.11.x, backport-v3.12.x

#8877 3.11.20 release notes
  release-notes/3.11.20.md
Labels: backport-v3.11.x, backport-v3.12.x

#8880 Adapt stream Java tests to client 0.12.0 snapshot
  deps/rabbitmq_stream/test/rabbit_stream_SUITE_data/pom.xml
  deps/rabbitmq_stream/test/rabbit_stream_SUITE_data/src/test/java/com/rabbitmq/stream/FailureTest.java
  deps/rabbitmq_stream/test/rabbit_stream_SUITE_data/src/test/java/com/rabbitmq/stream/StreamTest.java
  deps/rabbitmq_stream/test/rabbit_stream_SUITE_data/src/test/java/com/rabbitmq/stream/TestUtils.java
  deps/rabbitmq_stream_management/test/http_SUITE_data/pom.xml
  deps/rabbitmq_stream_management/test/http_SUITE_data/src/test/java/com/rabbitmq/stream/HttpTest.java
  deps/rabbitmq_stream_management/test/http_SUITE_data/src/test/java/com/rabbitmq/stream/TestUtils.java
Labels: backport-v3.9.x, backport-v3.10.x, backport-v3.11.x, backport-v3.12.x

#8881 Update Erlang.mk + small cleanup
  deps/trust_store_http/Makefile
  erlang.mk
Labels: make

#8894 3.10.25 release notes
  release-notes/3.10.25.md
Labels: backport-v3.10.x, backport-v3.11.x, backport-v3.12.x

#8891 Adopt otp 24.3.4.13
  MODULE.bazel
Labels: bazel

#8892 Adopt otp 25.3.2.4
  MODULE.bazel
  WORKSPACE
Labels: bazel, backport-v3.10.x, backport-v3.11.x, backport-v3.12.x

#8902 Use rules_erlang 3.11.3
  MODULE.bazel
  WORKSPACE
Labels: bazel, backport-v3.10.x, backport-v3.11.x, backport-v3.12.x

#8925 Remove amqp_client dep from rabbitmq_mqtt
  deps/rabbitmq_mqtt/BUILD.bazel
  deps/rabbitmq_mqtt/Makefile
Labels: bazel, make, backport-v3.12.x

#8964 Tests: split parallel stream queue groups and retry if coordinator unavailable
  deps/rabbit/BUILD.bazel
  deps/rabbit/test/rabbit_stream_queue_SUITE.erl
Labels: bazel, backport-v3.12.x
