Repository rabbitmq/rabbitmq-server, pull requests merged in 2023-09, with the labels that each got.

#9252 bazel run gazelle
  deps/rabbit/BUILD.bazel
Labels: bazel

#9254 routing_SUITE: extract topic test from unit_access_control_SUITE
  deps/rabbit/BUILD.bazel
  deps/rabbit/app.bzl
  deps/rabbit/test/routing_SUITE.erl
  deps/rabbit/test/unit_access_control_SUITE.erl
Labels: bazel

#9253 rabbit_feature_flags: Lower the level of some log messages
  deps/rabbit/src/rabbit_feature_flags.erl
  deps/rabbit/src/rabbit_ff_controller.erl
  deps/rabbit/src/rabbit_ff_registry_factory.erl
Labels: backport-v3.11.x, backport-v3.12.x

#9256 CQ msg_store: Don't debug log when a cache update_counter fails
  deps/rabbit/src/rabbit_msg_store.erl
Labels: backport-v3.12.x

#9265 bazel run gazelle
  deps/rabbit/app.bzl
Labels: bazel

#9229 Use the no-remote-exec instead of exclusive tag for some tests
  .bazelrc
  .github/workflows/test-erlang-git.yaml
  .github/workflows/test-mixed-versions.yaml
  .github/workflows/test.yaml
  deps/rabbit/BUILD.bazel
Labels: bazel, backport-v3.10.x, backport-v3.11.x, backport-v3.12.x

#9276 Use our fork of BCR for erlang specific packages
  .bazelrc
  MODULE.bazel
Labels: bazel, backport-v3.10.x, backport-v3.11.x, backport-v3.12.x

#9271 Close MQTT connection if sending fails
  deps/rabbitmq_mqtt/src/rabbit_mqtt_reader.erl
  deps/rabbitmq_mqtt/test/java_SUITE_data/src/test/java/com/rabbitmq/mqtt/test/MqttTest.java
Labels: backport-v3.12.x

#9291 Add integration test MQTT 5.0 -> Stream
  deps/rabbitmq_mqtt/BUILD.bazel
  deps/rabbitmq_mqtt/test/protocol_interop_SUITE.erl
Labels: bazel

#9294 Update key and restore-key for the actions/cache action in actions
  .github/workflows/oci.yaml
  .github/workflows/rabbitmq_peer_discovery_aws.yaml
  .github/workflows/test-erlang-git.yaml
  .github/workflows/test-mixed-versions.yaml
Labels: backport-v3.10.x, backport-v3.11.x, backport-v3.12.x

#9269 Allow several env variables to be set in rabbitmq-env-conf.bat
  deps/rabbit/scripts/rabbitmq-env.bat
  deps/rabbit/scripts/rabbitmq-service.bat
Labels: backport-v3.11.x, backport-v3.12.x

#9316 Run authnz workflow when code changes on authnz modules
  .github/workflows/test-authnz.yaml
Labels: backport-v3.12.x

#9328 Adopt otp 25.3.2.6
  MODULE.bazel
  WORKSPACE
Labels: bazel, backport-v3.10.x, backport-v3.11.x, backport-v3.12.x

#9332 Fix crash in rabbit_writer
  deps/rabbit/src/mc_amqpl.erl
  deps/rabbitmq_amqp1_0/test/amqp10_client_SUITE.erl
Labels: bug

#9338 3.11.23 release notes
  release-notes/3.11.23.md
Labels: backport-v3.11.x, backport-v3.12.x

#9343 Update 3.11.23 release notes
  release-notes/3.11.23.md
Labels: backport-v3.11.x, backport-v3.12.x

#9337 Try to avoid running out of space in the OCI workflow in actions
  .github/workflows/oci.yaml
Labels: backport-v3.10.x, backport-v3.11.x, backport-v3.12.x

#9349 3.12.5 release notes
  release-notes/3.12.5.md
Labels: backport-v3.12.x

#9356 Improve consumer metric cleanup when a channel goes down
  deps/rabbit/src/rabbit_amqqueue_process.erl
  deps/rabbitmq_management_agent/src/rabbit_mgmt_metrics_gc.erl
Labels: backport-v3.12.x

#9324 Make rabbitmqctl delete_queue more robust
  deps/rabbit/app.bzl
  deps/rabbit/src/rabbit_amqqueue.erl
  deps/rabbit/src/rabbit_amqqueue_control.erl
  deps/rabbit/src/rabbit_channel.erl
  deps/rabbit/test/crashing_queues_SUITE.erl
  deps/rabbit_common/src/rabbit_misc.erl
  deps/rabbit_common/src/rabbit_types.erl
  deps/rabbitmq_cli/lib/rabbitmq/cli/ctl/commands/delete_queue_command.ex
  deps/rabbitmq_cli/test/ctl/delete_queue_command_test.exs
  deps/rabbitmq_cli/test/rabbitmqctl_test.exs
  deps/rabbitmq_cli/test/test_helper.exs
  moduleindex.yaml
Labels: bazel, backport-v3.12.x

#9383 Improve grammar of rabbitmqctl.8
  deps/rabbit/docs/rabbitmqctl.8
Labels: backport-v3.11.x, backport-v3.12.x

#9384 Fix queue storage version returned by priority queues
  deps/rabbit/src/rabbit_priority_queue.erl
  deps/rabbit/test/priority_queue_SUITE.erl
Labels: backport-v3.12.x

#9405 Forward compatibility with Erlang 27: distinguish between positive and negative 0.0
  deps/rabbit_common/src/rabbit_numerical.erl
Labels: backport-v3.11.x, backport-v3.12.x

#9409 Fix bazel/make discrepancies
  .github/workflows/check-build-system-equivalence.yaml
  deps/rabbit/Makefile
  deps/rabbitmq_mqtt/Makefile
Labels: make

#9411 Request more disk space for docker image jobs on RBE
  packaging/docker-image/BUILD.bazel
Labels: bazel, backport-v3.10.x, backport-v3.11.x, backport-v3.12.x

#9417 Rename quorum_queue_utils to queue_utils
  deps/rabbit/BUILD.bazel
  deps/rabbit/app.bzl
  deps/rabbit/test/consumer_timeout_SUITE.erl
  deps/rabbit/test/dead_lettering_SUITE.erl
  deps/rabbit/test/direct_exchange_routing_v2_SUITE.erl
  deps/rabbit/test/dynamic_qq_SUITE.erl
  deps/rabbit/test/exchanges_SUITE.erl
  deps/rabbit/test/maintenance_mode_SUITE.erl
  deps/rabbit/test/publisher_confirms_parallel_SUITE.erl
  deps/rabbit/test/queue_utils.erl
  deps/rabbit/test/quorum_queue_SUITE.erl
  deps/rabbit/test/quorum_queue_member_reconciliation_SUITE.erl
  deps/rabbit/test/rabbit_fifo_dlx_integration_SUITE.erl
  deps/rabbit/test/rabbit_stream_queue_SUITE.erl
  deps/rabbit/test/single_active_consumer_SUITE.erl
Labels: bazel

#9414 Forward compatibility with Erlang 27: negative zero fix, take 2
  deps/rabbit_common/src/rabbit_numerical.erl
Labels: backport-v3.11.x, backport-v3.12.x

#9412 Use the latest rules_erlang
  BAZEL.md
  MODULE.bazel
  WORKSPACE
Labels: bazel, backport-v3.10.x, backport-v3.11.x, backport-v3.12.x

#9427 bazel run gazelle
  deps/rabbit/BUILD.bazel
Labels: bazel

#9428 bazel run gazelle
  deps/rabbit/BUILD.bazel
Labels: bazel

#9429 bazel run gazelle
  deps/rabbit/BUILD.bazel
Labels: bazel

#9438 Tests: replace some sleeps for wait for condition
  deps/rabbit/app.bzl
  deps/rabbit/test/logging_SUITE.erl
  deps/rabbit/test/rabbit_fifo_dlx_integration_SUITE.erl
Labels: bazel

#9442 forget_cluster_node: handle errors while shrinking streams and/or QQs
  deps/rabbit/BUILD.bazel
  deps/rabbit/app.bzl
  deps/rabbit/src/rabbit_stream_queue.erl
  deps/rabbit/test/cli_forget_cluster_node_SUITE.erl
  deps/rabbitmq_cli/lib/rabbitmq/cli/ctl/commands/forget_cluster_node_command.ex
Labels: bazel, backport-v3.12.x

#9418 Osiris 1.6.7
  MODULE.bazel
  deps/rabbit/Makefile
  deps/rabbit/src/rabbit_stream_coordinator.erl
  deps/rabbit/src/rabbit_stream_queue.erl
Labels: bazel, make, backport-v3.12.x

#9374 Use pg_local to track AMQP 1.0 connections
  deps/amqp_client/src/amqp_connection.erl
  deps/amqp_client/src/amqp_direct_connection.erl
  deps/rabbit/test/rabbit_core_metrics_gc_SUITE.erl
  deps/rabbit_common/src/rabbit_core_metrics.erl
  deps/rabbitmq_amqp1_0/src/rabbit_amqp1_0.erl
  deps/rabbitmq_amqp1_0/src/rabbit_amqp1_0_reader.erl
  deps/rabbitmq_amqp1_0/src/rabbit_amqp1_0_session_sup.erl
  deps/rabbitmq_amqp1_0/test/proxy_protocol_SUITE.erl
Labels: bazel, backport-v3.12.x

#9450 Tests: increase await timeout
  deps/rabbit/test/logging_SUITE.erl
  deps/rabbit/test/rabbit_fifo_dlx_integration_SUITE.erl
Labels: backport-v3.12.x

#9293 Delete stream replica even if the node is down
  deps/rabbit/src/rabbit_stream_coordinator.erl
  deps/rabbit/src/rabbit_stream_queue.erl
  deps/rabbit/test/rabbit_stream_queue_SUITE.erl
Labels: bazel, make, backport-v3.11.x, backport-v3.12.x

#9318 Add integration tests after mc merge
  deps/rabbit/BUILD.bazel
  deps/rabbit/app.bzl
  deps/rabbit/src/mc_amqpl.erl
  deps/rabbit/src/rabbit_basic.erl
  deps/rabbit/src/rabbit_channel.erl
  deps/rabbit/src/rabbit_trace.erl
  deps/rabbit/test/backing_queue_SUITE.erl
  deps/rabbit/test/classic_queue_prop_SUITE.erl
  deps/rabbit/test/dead_lettering_SUITE.erl
  deps/rabbit/test/mc_unit_SUITE.erl
  deps/rabbit/test/priority_queue_SUITE.erl
  deps/rabbit/test/queue_parallel_SUITE.erl
  deps/rabbit/test/routing_SUITE.erl
  deps/rabbit/test/transactions_SUITE.erl
  deps/rabbit/test/unit_classic_mirrored_queue_sync_throttling_SUITE.erl
  deps/rabbitmq_event_exchange/src/rabbit_exchange_type_event.erl
  deps/rabbitmq_mqtt/src/rabbit_mqtt_processor.erl
  deps/rabbitmq_stream/src/rabbit_stream_manager.erl
Labels: bazel

#9460 cli_forget_cluster_node_SUITE: wait for leader election in both queues
  deps/rabbit/test/cli_forget_cluster_node_SUITE.erl
Labels: backport-v3.12.x

#9459 Handle and propagate protocol exceptions in channel interceptors to the calling parent channels
  deps/rabbit/src/rabbit_channel_interceptor.erl
  deps/rabbit/test/channel_interceptor_SUITE.erl
  deps/rabbit/test/dummy_interceptor.erl
Labels: backport-v3.12.x

#9463 Expose the "start-background-broker" CMD
  BUILD.bazel
Labels: bazel, backport-v3.11.x, backport-v3.12.x

#9467 Expose the "stop-broker" CMD
  BUILD.bazel
Labels: bazel, backport-v3.11.x, backport-v3.12.x

#9466 Change log level for startup time to info
  deps/rabbit/src/rabbit.erl
Labels: backport-v3.11.x, backport-v3.12.x

#9465 Expose number of unreachable cluster peers via Prometheus
  deps/rabbitmq_prometheus/app.bzl
  deps/rabbitmq_prometheus/src/collectors/prometheus_rabbitmq_dynamic_collector.erl
  deps/rabbitmq_prometheus/src/rabbit_prometheus_dispatcher.erl
Labels: bazel, backport-v3.11.x, backport-v3.12.x

#9475 BUILD.bazel: fix a few typos
  BUILD.bazel
Labels: backport-v3.11.x, backport-v3.12.x

#9478 bazel run gazelle
  BUILD.bazel
  deps/rabbit/app.bzl
  moduleindex.yaml
Labels: bazel

#9484 Use seshat from our bzlmod registry
  MODULE.bazel
Labels: bazel, backport-v3.11.x, backport-v3.12.x

#9485 Fix OTP 27 float match warning
  deps/rabbit/src/rabbit_amqqueue_process.erl
Labels: backport-v3.10.x, backport-v3.11.x, backport-v3.12.x

#9486 Use OTP 26.1 as OTP 26 in CI
  .bazelrc
  .github/workflows/check-build-system-equivalence-release-branches.yaml
  .github/workflows/check-build-system-equivalence.yaml
  .github/workflows/oci.yaml
  .github/workflows/test-authnz.yaml
  .github/workflows/test-selenium.yaml
  .github/workflows/test-windows.yaml
  .github/workflows/update-otp-patches.yaml
  MODULE.bazel
  WORKSPACE
  bazel/platforms/BUILD.bazel
  packaging/docker-image/BUILD.bazel
Labels: bazel, backport-v3.12.x

#9495 3.12.5 release notes
  release-notes/3.12.5.md
Labels: backport-v3.12.x

#9493 Adopt elixir 1.15.6
  MODULE.bazel
Labels: bazel, backport-v3.10.x, backport-v3.11.x, backport-v3.12.x

#9507 CQ: Fix a crash when CMQ master changes in mixed environment test
  deps/rabbit/src/rabbit_variable_queue.erl
Labels: backport-v3.12.x

#9505 Match credentials_obfuscation version in bazel/make
  MODULE.bazel
  bazel/BUILD.credentials_obfuscation
Labels: bazel

#9509 Add amqp_client to the rabbitmq_web_mqtt deps in Make
  deps/rabbitmq_web_mqtt/Makefile
Labels: make, backport-v3.12.x

#9511 3.12.6 release notes
  release-notes/3.12.5.md
  release-notes/3.12.6.md
Labels: backport-v3.12.x

#8341 Use 3.12.6 for the secondary umbrella
  MODULE.bazel
  bazel/bzlmod/secondary_umbrella.bzl
  rabbitmq.bzl
Labels: bazel

#9523 Do not confirm MQTT messages if in partition
  deps/rabbitmq_mqtt/src/rabbit_mqtt_processor.erl
Labels: backport-v3.12.x

#9534 Support both transaction and serials on exchange callbacks
  deps/rabbitmq_jms_topic_exchange/src/rabbit_jms_topic_exchange.erl
  deps/rabbitmq_jms_topic_exchange/test/rjms_topic_selector_SUITE.erl
  deps/rabbitmq_recent_history_exchange/src/rabbit_exchange_type_recent_history.erl
  deps/rabbitmq_sharding/src/rabbit_sharding_exchange_decorator.erl
Labels: backport-v3.12.x

#9483 Test suites: wait for conditions to reduce flakiness
  deps/rabbit/BUILD.bazel
  deps/rabbit/app.bzl
  deps/rabbit/test/logging_SUITE.erl
  deps/rabbit/test/quorum_queue_SUITE.erl
  deps/rabbit/test/rabbitmqctl_integration_SUITE.erl
Labels: bazel, backport-v3.12.x

#9525 Operator policies
  deps/rabbit/app.bzl
  deps/rabbit/src/rabbit_classic_queue.erl
  deps/rabbit/src/rabbit_stream_queue.erl
  deps/rabbit/test/policy_SUITE.erl
  deps/rabbitmq_management/priv/www/js/tmpl/policies.ejs
Labels: bazel, backport-v3.12.x

#9542 Fix wrong queue-pattern type
  deps/rabbit/priv/schema/rabbit.schema
  deps/rabbit/test/config_schema_SUITE_data/rabbit.snippets
Labels: backport-v3.11.x, backport-v3.12.x

#9547 Add Classic Queue version to operator policies
  deps/rabbit/priv/schema/rabbit.schema
  deps/rabbit/src/rabbit_policies.erl
  deps/rabbit/test/config_schema_SUITE_data/rabbit.snippets
  deps/rabbit/test/policy_SUITE.erl
  deps/rabbitmq_management/priv/www/js/tmpl/policies.ejs
Labels: bazel, backport-v3.11.x, backport-v3.12.x

#9550 HTTP API: DELETE /api/queues/{vhost}/{name} use internal API call
  deps/rabbitmq_management/src/rabbit_mgmt_wm_queue.erl
  deps/rabbitmq_management/test/rabbit_mgmt_http_SUITE.erl
Labels: backport-v3.11.x, backport-v3.12.x

#9562 HTTP API: document disable_stats and enable_queue_totals
  deps/rabbitmq_management/priv/www/api/index.html
Labels: backport-v3.11.x, backport-v3.12.x

#9568 Drop an action that we no longer need
  .github/workflows/oci.yaml
Labels: backport-v3.11.x, backport-v3.12.x

#9573 Do not log HTTP[S] listener options
  deps/rabbitmq_web_dispatch/src/rabbit_web_dispatch_sup.erl
Labels: backport-v3.11.x, backport-v3.12.x

#9572 Monitor members to the same stream in stream connection
  deps/rabbitmq_stream/src/rabbit_stream_reader.erl
  deps/rabbitmq_stream/test/rabbit_stream_SUITE.erl
  deps/rabbitmq_stream/test/rabbit_stream_SUITE_data/src/test/java/com/rabbitmq/stream/FailureTest.java
  deps/rabbitmq_stream/test/rabbit_stream_SUITE_data/src/test/java/com/rabbitmq/stream/Host.java
  deps/rabbitmq_stream/test/rabbit_stream_SUITE_data/src/test/java/com/rabbitmq/stream/TestUtils.java
Labels: backport-v3.11.x, backport-v3.12.x

#9319 Ra 2.7.0 + rabbitmq-queues quorum_status improvements
  MODULE.bazel
  deps/rabbit/Makefile
  deps/rabbit/src/rabbit_observer_cli_quorum_queues.erl
  deps/rabbit/src/rabbit_quorum_queue.erl
  deps/rabbit/test/quorum_queue_SUITE.erl
  rabbitmq-components.mk
Labels: bazel, make

#9578 Core metrics: remove backing_queue_status from the core metrics
  deps/rabbit/src/rabbit_amqqueue_process.erl
Labels: backport-v3.12.x

#9580 Adopt otp 26.1.1
  MODULE.bazel
  WORKSPACE
Labels: bazel, backport-v3.11.x, backport-v3.12.x

#9585 bazel run gazelle
  deps/rabbit/BUILD.bazel
  deps/rabbit/app.bzl
Labels: bazel

#9586 Make looking_glass an optional dep for deps/rabbit
  deps/rabbit/BUILD.bazel
Labels: bazel

#9596 Adopt otp 26.1.1
  MODULE.bazel
Labels: bazel, backport-v3.12.x

#9583 Add columns to stream CLI commands
  deps/rabbitmq_stream/src/Elixir.RabbitMQ.CLI.Ctl.Commands.ListStreamConnectionsCommand.erl
  deps/rabbitmq_stream/src/Elixir.RabbitMQ.CLI.Ctl.Commands.ListStreamConsumersCommand.erl
  deps/rabbitmq_stream/src/Elixir.RabbitMQ.CLI.Ctl.Commands.ListStreamPublishersCommand.erl
  deps/rabbitmq_stream/src/rabbit_stream_reader.erl
  deps/rabbitmq_stream/test/commands_SUITE.erl
  deps/rabbitmq_stream_common/include/rabbit_stream.hrl
Labels: backport-v3.12.x
