Repository rabbitmq/rabbitmq-server, pull requests merged in 2023-02, with the labels that each got.

#7133 Fix one more issue reported by CLI tools Dialyzer
  deps/rabbitmq_cli/lib/rabbitmqctl.ex
Labels: backport-v3.11.x

#7118 Activate stream delivery v2 correctly
  deps/rabbitmq_stream/src/rabbit_stream_reader.erl
Labels: bug, backport-v3.11.x

#7135 List CPU core count in 'rabbitmq-diagnostics cluster_status'
  deps/rabbitmq_cli/lib/rabbitmq/cli/ctl/commands/cluster_status_command.ex
Labels: backport-v3.10.x, backport-v3.11.x

#7143 Fix shell quoting in bazel rabbitmqctl helper
  rabbitmqctl.bzl
Labels: bazel, backport-v3.10.x, backport-v3.11.x

#7149 Forward-port dialyzer related rabbitmq_cli fixes from #7122
  deps/rabbitmq_cli/lib/rabbitmqctl.ex
Labels: backport-v3.10.x, backport-v3.11.x

#7141 Fix channel crash when draining AMQP 1.0 credits from classic queue
  deps/amqp10_client/src/amqp10_client.erl
  deps/amqp10_client/src/amqp10_client_session.erl
  deps/rabbit/src/rabbit_channel.erl
  deps/rabbit/src/rabbit_classic_queue.erl
  deps/rabbit/src/rabbit_queue_consumers.erl
  deps/rabbitmq_amqp1_0/src/rabbit_amqp1_0_outgoing_link.erl
  deps/rabbitmq_amqp1_0/test/amqp10_client_SUITE.erl
Labels: rabbitmq-amqp1.0-client, rabbitmq-amqp1.0, backport-v3.10.x, backport-v3.11.x

#7156 Feature flags: Fix experimental feature flags inventory
  deps/rabbit/src/rabbit_feature_flags.erl
  deps/rabbit/src/rabbit_ff_controller.erl
  deps/rabbit/src/rabbit_ff_registry_factory.erl
Labels: backport-v3.11.x

#7162 Fix pid tracking when decommissioning an MQTT node
  deps/rabbitmq_mqtt/src/mqtt_machine.erl
Labels: bug, rabbitmq-mqtt, backport-v3.10.x, backport-v3.11.x

#7163 Remove extra dollar sign
  deps/rabbitmq_auth_backend_ldap/BUILD.bazel
  deps/rabbitmq_auth_backend_ldap/test/unit_SUITE.erl
Labels: bazel

#7159 Fix all dialyzer warnings in rabbitmq_prelaunch
  deps/rabbit/apps/rabbitmq_prelaunch/BUILD.bazel
  deps/rabbit/apps/rabbitmq_prelaunch/src/rabbit_logger_std_h.erl
  deps/rabbit/apps/rabbitmq_prelaunch/src/rabbit_prelaunch_conf.erl
Labels: bazel, backport-v3.10.x, backport-v3.11.x

#7164 Use sharding on //deps/rabbitmq_amqp1_0:system_SUITE
  deps/rabbitmq_amqp1_0/BUILD.bazel
  deps/rabbitmq_amqp1_0/test/system_SUITE.erl
Labels: bazel, backport-v3.9.x, backport-v3.10.x, backport-v3.11.x

#7183 3.11.9 release notes
  release-notes/3.11.9.md
Labels: backport-v3.11.x

#7190 Fixing the rabbitmq_auth_backend_oauth2 schema
  deps/rabbitmq_auth_backend_oauth2/priv/schema/rabbitmq_auth_backend_oauth2.schema
Labels: backport-v3.11.x

#7195 Cleanup dialyzer calls
  deps/amqp10_client/BUILD.bazel
  deps/amqp10_common/BUILD.bazel
  deps/rabbit/apps/rabbitmq_prelaunch/BUILD.bazel
  deps/rabbit/src/rabbit_classic_queue.erl
  deps/rabbit/src/rabbit_networking.erl
  deps/rabbit/src/rabbit_quorum_queue.erl
  deps/rabbit/src/rabbit_table.erl
  deps/rabbit/src/tcp_listener_sup.erl
  deps/rabbit_common/src/rabbit_pbe.erl
  deps/rabbitmq_amqp1_0/BUILD.bazel
  deps/rabbitmq_auth_backend_cache/BUILD.bazel
  deps/rabbitmq_consistent_hash_exchange/BUILD.bazel
  deps/rabbitmq_consistent_hash_exchange/src/rabbit_db_ch_exchange.erl
  deps/rabbitmq_event_exchange/BUILD.bazel
  deps/rabbitmq_federation/BUILD.bazel
  deps/rabbitmq_federation_management/BUILD.bazel
  deps/rabbitmq_management/BUILD.bazel
  deps/rabbitmq_management_agent/BUILD.bazel
  deps/rabbitmq_peer_discovery_consul/BUILD.bazel
  deps/rabbitmq_peer_discovery_k8s/BUILD.bazel
  deps/rabbitmq_prometheus/BUILD.bazel
  deps/rabbitmq_random_exchange/BUILD.bazel
  deps/rabbitmq_sharding/BUILD.bazel
  deps/rabbitmq_shovel/BUILD.bazel
  deps/rabbitmq_shovel_management/BUILD.bazel
  deps/rabbitmq_stomp/BUILD.bazel
  deps/rabbitmq_stream/BUILD.bazel
  deps/rabbitmq_stream_management/BUILD.bazel
  deps/rabbitmq_top/BUILD.bazel
  deps/rabbitmq_tracing/BUILD.bazel
  deps/rabbitmq_trust_store/BUILD.bazel
  deps/rabbitmq_trust_store/src/rabbit_trust_store_http_provider.erl
  deps/rabbitmq_web_mqtt_examples/BUILD.bazel
  deps/rabbitmq_web_stomp/BUILD.bazel
  deps/rabbitmq_web_stomp_examples/BUILD.bazel
Labels: bazel, backport-v3.10.x, backport-v3.11.x

#7197 Introduce a CLI command that grants permissions to all virtual hosts
  deps/rabbit/src/rabbit_auth_backend_internal.erl
  deps/rabbitmq_cli/lib/rabbitmq/cli/ctl/commands/set_permissions_globally.ex
  deps/rabbitmq_cli/test/ctl/set_permissions_globally_command_test.exs
  deps/rabbitmq_cli/test/test_helper.exs
Labels: backport-v3.10.x, backport-v3.11.x

#7202 HTTP API: make it possible to restrict operator policy changes via API (with slightly different naming)
  deps/rabbit_common/src/rabbit_misc.erl
  deps/rabbit_common/test/unit_SUITE.erl
  deps/rabbitmq_ct_helpers/include/rabbit_mgmt_test.hrl
  deps/rabbitmq_management/bin/rabbitmqadmin
  deps/rabbitmq_management/priv/schema/rabbitmq_management.schema
  deps/rabbitmq_management/priv/www/js/global.js
  deps/rabbitmq_management/priv/www/js/tmpl/policies.ejs
  deps/rabbitmq_management/src/rabbit_mgmt_features.erl
  deps/rabbitmq_management/src/rabbit_mgmt_util.erl
  deps/rabbitmq_management/src/rabbit_mgmt_wm_operator_policy.erl
  deps/rabbitmq_management/src/rabbit_mgmt_wm_overview.erl
  deps/rabbitmq_management/test/rabbit_mgmt_http_SUITE.erl
  deps/rabbitmq_management/test/rabbit_mgmt_runtime_parameters_util.erl
  deps/rabbitmq_management/test/rabbit_mgmt_test_unit_SUITE.erl
Labels: backport-v3.11.x

#7177 Add OAuth 2.0 MQTT system test
  MODULE.bazel
  deps/rabbitmq_auth_backend_oauth2/BUILD.bazel
  deps/rabbitmq_auth_backend_oauth2/Makefile
  deps/rabbitmq_auth_backend_oauth2/test/system_SUITE.erl
  deps/rabbitmq_mqtt/Makefile
  deps/rabbitmq_web_mqtt/Makefile
Labels: rabbitmq-auth-backend-oauth2, rabbitmq-mqtt, bazel, make, backport-v3.11.x

#7185 Add API functions to behaviour module
  deps/rabbitmq_mqtt/src/rabbit_mqtt_internal_event_handler.erl
  deps/rabbitmq_mqtt/src/rabbit_mqtt_processor.erl
  deps/rabbitmq_mqtt/src/rabbit_mqtt_retained_msg_store.erl
  deps/rabbitmq_mqtt/src/rabbit_mqtt_retained_msg_store_dets.erl
  deps/rabbitmq_mqtt/src/rabbit_mqtt_retained_msg_store_ets.erl
  deps/rabbitmq_mqtt/src/rabbit_mqtt_retained_msg_store_noop.erl
  deps/rabbitmq_mqtt/src/rabbit_mqtt_retainer.erl
  deps/rabbitmq_mqtt/src/rabbit_mqtt_retainer_sup.erl
  deps/rabbitmq_mqtt/src/rabbit_mqtt_sup.erl
Labels: rabbitmq-mqtt

#7176 Handle various credentials scenarios while authenticating in the internal backend
  deps/rabbit/src/rabbit_auth_backend_internal.erl
Labels: backport-v3.11.x

#7222 Ignore stream data folder in rabbit_mnesia:is_virgin_node/0
  deps/rabbit/src/rabbit_mnesia.erl
  deps/rabbit/src/rabbit_node_monitor.erl
Labels: backport-v3.10.x, backport-v3.11.x

#7219 Require all feature flags introduced before 3.11.1
  deps/rabbit/src/rabbit_channel_tracking.erl
  deps/rabbit/src/rabbit_connection_tracking.erl
  deps/rabbit/src/rabbit_core_ff.erl
  deps/rabbit/src/rabbit_db_binding.erl
  deps/rabbit/src/rabbit_table.erl
  deps/rabbit/test/direct_exchange_routing_v2_SUITE.erl
  deps/rabbit/test/queue_type_SUITE.erl
  deps/rabbitmq_management_agent/src/rabbit_mgmt_ff.erl
  deps/rabbitmq_stream/test/rabbit_stream_SUITE.erl
  rabbitmq.bzl
Labels: bazel

#7223 Remove compatibility code for management agent feature flags
  deps/rabbitmq_management_agent/src/rabbit_mgmt_data.erl
  deps/rabbitmq_management_agent/src/rabbit_mgmt_data_compat.erl
  deps/rabbitmq_management_agent/src/rabbit_mgmt_ff.erl
  deps/rabbitmq_mqtt/src/rabbit_mqtt_ff.erl
Labels: bazel

#7232 rabbit_feature_flags: Fix formatting of the logged list of feature flags
  deps/rabbit/src/rabbit_ff_registry_factory.erl
Labels: backport-v3.11.x

#7235 Correct a copy-and-paste artifact in LICENSE
  LICENSE
Labels: backport-v3.9.x, backport-v3.10.x, backport-v3.11.x

#7239 ctl add_vhost: minor improvements to help output
  deps/rabbitmq_cli/lib/rabbitmq/cli/ctl/commands/add_vhost_command.ex
Labels: backport-v3.10.x, backport-v3.11.x

#7242 Update 3.11.9 release notes
  release-notes/3.11.9.md
Labels: backport-v3.11.x

#7244 3.10.18 release notes
  release-notes/3.10.18.md
Labels: backport-v3.10.x, backport-v3.11.x

#7277 Manual backport #7271
  .github/workflows/secondary-umbrella.yaml
Labels: backport-v3.9.x, backport-v3.10.x

#7280 rabbit_vhost:set_tags/2 avoids notifying if tags are unchanged
  deps/rabbit/BUILD.bazel
  deps/rabbit/src/rabbit_db_vhost.erl
  deps/rabbit/src/rabbit_vhost.erl
  deps/rabbit/test/test_rabbit_event_handler.erl
  deps/rabbit/test/vhost_SUITE.erl
  deps/rabbitmq_cli/test/ctl/set_vhost_tags_command_test.exs
Labels: bazel, backport-v3.10.x, backport-v3.11.x

#7284 Add rabbit_queue_type:is_enabled/1
  deps/rabbit/src/rabbit_amqqueue.erl
  deps/rabbit/src/rabbit_classic_queue.erl
  deps/rabbit/src/rabbit_queue_type.erl
  deps/rabbit/src/rabbit_quorum_queue.erl
  deps/rabbit/src/rabbit_stream_queue.erl
  deps/rabbitmq_mqtt/src/rabbit_mqtt_processor.erl
  deps/rabbitmq_mqtt/src/rabbit_mqtt_qos0_queue.erl
Labels: backport-v3.12.x

#7196 Fix all dependencies for the dialyzer
  deps/rabbit/BUILD.bazel
  deps/rabbit/apps/rabbitmq_prelaunch/BUILD.bazel
  deps/rabbit/src/rabbit_access_control.erl
  deps/rabbit/src/rabbit_channel.erl
  deps/rabbit/src/rabbit_exchange.erl
  deps/rabbit/src/rabbit_guid.erl
  deps/rabbit/src/rabbit_router.erl
  deps/rabbit/src/vhost.erl
  deps/rabbit_common/BUILD.bazel
  deps/rabbit_common/src/rabbit_authz_backend.erl
  deps/rabbit_common/src/rabbit_binary_generator.erl
  deps/rabbit_common/src/rabbit_core_metrics.erl
  deps/rabbit_common/src/rabbit_framing.erl
  deps/rabbit_common/src/rabbit_misc.erl
  deps/rabbit_common/src/rabbit_net.erl
  deps/rabbit_common/src/rabbit_types.erl
  deps/rabbit_common/src/rabbit_writer.erl
  deps/rabbitmq_amqp1_0/BUILD.bazel
  deps/rabbitmq_auth_mechanism_ssl/BUILD.bazel
  deps/rabbitmq_aws/BUILD.bazel
  deps/rabbitmq_cli/BUILD.bazel
  deps/rabbitmq_consistent_hash_exchange/BUILD.bazel
  deps/rabbitmq_mqtt/BUILD.bazel
  deps/rabbitmq_peer_discovery_etcd/BUILD.bazel
  deps/rabbitmq_stream_common/BUILD.bazel
  deps/rabbitmq_web_mqtt/BUILD.bazel
  rabbitmq.bzl
Labels: bazel, backport-v3.10.x, backport-v3.11.x, backport-v3.12.x

#7281 Remove compatibility for flag listener_records_in_ets
  deps/rabbit/src/rabbit_core_ff.erl
  deps/rabbit/src/rabbit_networking.erl
  deps/rabbit/src/rabbit_node_monitor.erl
  deps/rabbit/src/rabbit_table.erl
Labels: backport-v3.12.x

#7286 Add additional v3.12.x references
  .github/workflows/update-elixir-patches.yaml
  .github/workflows/update-otp-patches.yaml
  MODULE.bazel
  deps/rabbitmq_cli/test/fixtures/plugins/plugins_with_version_requirements/mock_rabbitmq_plugin_for_3_8-0.1.0/ebin/mock_rabbitmq_plugin_for_3_8.app
  rabbitmq.bzl
Labels: bazel

#7303 CQ: Remove compat code for classic_mirrored_queue_version
  deps/rabbit/src/rabbit_core_ff.erl
  deps/rabbit/src/rabbit_mirror_queue_master.erl
Labels: backport-v3.12.x

#7304 Fix issue 7301 - broken vhost link
  deps/rabbitmq_management/priv/www/js/tmpl/permissions.ejs
  deps/rabbitmq_management/priv/www/js/tmpl/topic-permissions.ejs
  deps/rabbitmq_management/priv/www/js/tmpl/vhost.ejs
  deps/rabbitmq_management/selenium/README.md
  deps/rabbitmq_management/selenium/package.json
  deps/rabbitmq_management/selenium/suites/vhosts.sh
  deps/rabbitmq_management/selenium/test/pageobjects/AdminTab.js
  deps/rabbitmq_management/selenium/test/pageobjects/VhostAdminTab.js
  deps/rabbitmq_management/selenium/test/pageobjects/VhostsAdminTab.js
  deps/rabbitmq_management/selenium/test/vhosts/Makefile
  deps/rabbitmq_management/selenium/test/vhosts/admin-vhosts.js
Labels: make

#7319 Delete rabbit_stream_SUITE setup steps
  deps/rabbitmq_stream/test/rabbit_stream_SUITE.erl
Labels: backport-v3.12.x

#7315 Use the latest rules_erlang
  MODULE.bazel
  WORKSPACE
  bazel/BUILD.eetcd
  deps/rabbit/BUILD.bazel
  deps/rabbitmq_aws/BUILD.bazel
  deps/rabbitmq_peer_discovery_etcd/BUILD.bazel
Labels: bazel, backport-v3.10.x, backport-v3.11.x, backport-v3.12.x

#7268 Remove unused catch clauses
  deps/rabbit/src/rabbit_auth_backend_internal.erl
Labels: backport-v3.12.x

#7270 Remove compatibility for flag tracking_records_in_ets
  deps/rabbit/src/rabbit.erl
  deps/rabbit/src/rabbit_channel_tracking.erl
  deps/rabbit/src/rabbit_channel_tracking_handler.erl
  deps/rabbit/src/rabbit_connection_tracking.erl
  deps/rabbit/src/rabbit_connection_tracking_handler.erl
  deps/rabbit/src/rabbit_core_ff.erl
  deps/rabbit/src/rabbit_tracking.erl
  deps/rabbit/test/per_user_connection_channel_limit_SUITE.erl
  deps/rabbit/test/per_user_connection_channel_tracking_SUITE.erl
  deps/rabbit/test/per_user_connection_tracking_SUITE.erl
  deps/rabbit/test/per_vhost_connection_limit_SUITE.erl
  deps/rabbit/test/vhost_SUITE.erl
Labels: backport-v3.12.x

#7328 Rename the tanzu cli scope to vmware
  .github/SECURITY.md
  Makefile
  README.md
  deps/rabbit/scripts/vmware-rabbitmq
  deps/rabbit/scripts/vmware-rabbitmq.bat
  deps/rabbitmq_cli/Makefile
  deps/rabbitmq_cli/lib/rabbitmq/cli/ctl/commands/help_command.ex
  deps/rabbitmq_cli/mix.exs
  deps/rabbitmq_prometheus/docker/docker-compose-dist-metrics.yml
  deps/rabbitmq_prometheus/docker/grafana/dashboards/inet_tcp_metrics.json
  rabbitmq_home.bzl
Labels: bazel, make, backport-v3.10.x, backport-v3.11.x, backport-v3.12.x

#7336 Add timeout for test AMQP 0.9.1 connection to open
  deps/rabbitmq_ct_client_helpers/src/rabbit_ct_client_helpers.erl
  deps/rabbitmq_mqtt/test/shared_SUITE.erl
Labels: backport-v3.12.x

#7335 Rebuild bazel/BUILD.* files with recent rules_erlang
  bazel/BUILD.accept
  bazel/BUILD.aten
  bazel/BUILD.base64url
  bazel/BUILD.cowboy
  bazel/BUILD.cowlib
  bazel/BUILD.credentials_obfuscation
  bazel/BUILD.ct_helper
  bazel/BUILD.cuttlefish
  bazel/BUILD.emqtt
  bazel/BUILD.enough
  bazel/BUILD.gen_batch_server
  bazel/BUILD.getopt
  bazel/BUILD.gun
  bazel/BUILD.jose
  bazel/BUILD.meck
  bazel/BUILD.observer_cli
  bazel/BUILD.prometheus
  bazel/BUILD.proper
  bazel/BUILD.quantile_estimator
  bazel/BUILD.ra
  bazel/BUILD.ranch
  bazel/BUILD.recon
  bazel/BUILD.redbug
  bazel/BUILD.seshat
  bazel/BUILD.stdout_formatter
  bazel/BUILD.sysmon_handler
  bazel/BUILD.systemd
  bazel/BUILD.thoas
Labels: backport-v3.10.x, backport-v3.11.x, backport-v3.12.x

#7326 Faster node startup with many classic queues
  deps/rabbit/src/rabbit_classic_queue.erl
Labels: backport-v3.10.x, backport-v3.11.x, backport-v3.12.x

#7353 Adopt otp 25.2.3
  MODULE.bazel
  WORKSPACE
Labels: bazel, backport-v3.10.x, backport-v3.11.x, backport-v3.12.x

#7357 Fix flaky MQTT Java test
  deps/rabbitmq_mqtt/test/java_SUITE_data/src/test/java/com/rabbitmq/mqtt/test/MqttTest.java
Labels: backport-v3.10.x, backport-v3.11.x, backport-v3.12.x

#7305 rabbit_feature_flags: Support required feature flags in plugins
  deps/rabbit/src/rabbit_ff_controller.erl
  deps/rabbit/src/rabbit_ff_registry_factory.erl
  deps/rabbit/test/feature_flags_SUITE.erl
  deps/rabbit/test/feature_flags_SUITE_data/my_plugin/src/my_plugin.erl
  deps/rabbit/test/feature_flags_v2_SUITE.erl
Labels: bug

#7371 Fix 7369
  deps/rabbitmq_management/priv/www/js/tmpl/exchanges.ejs
  deps/rabbitmq_management/selenium/fakeportal/views/rabbitmq.html
  deps/rabbitmq_management/selenium/suites/exchanges.sh
  deps/rabbitmq_management/selenium/suites/mgt-only-exchanges.sh
  deps/rabbitmq_management/selenium/suites/suite_template
  deps/rabbitmq_management/selenium/test/basic-auth/happy-login.js
  deps/rabbitmq_management/selenium/test/exchanges/Makefile
  deps/rabbitmq_management/selenium/test/exchanges/management.js
  deps/rabbitmq_management/selenium/test/mgt-only/enabled_plugins
  deps/rabbitmq_management/selenium/test/mgt-only/rabbitmq.config
  deps/rabbitmq_management/selenium/test/oauth/rabbitmq-idp-initiated-localhost.config
  deps/rabbitmq_management/selenium/test/pageobjects/BasePage.js
  deps/rabbitmq_management/selenium/test/pageobjects/ExchangePage.js
  deps/rabbitmq_management/selenium/test/pageobjects/ExchangesPage.js
  deps/rabbitmq_management/selenium/test/pageobjects/FakePortalPage.js
  deps/rabbitmq_management/selenium/test/pageobjects/LoginPage.js
  deps/rabbitmq_management/selenium/test/pageobjects/OverviewPage.js
  deps/rabbitmq_management/selenium/test/pageobjects/SSOHomePage.js
  deps/rabbitmq_management/selenium/test/pageobjects/VhostAdminTab.js
  deps/rabbitmq_management/selenium/test/pageobjects/VhostsAdminTab.js
  deps/rabbitmq_management/selenium/test/utils.js
  deps/rabbitmq_management/src/rabbit_mgmt_wm_exchange.erl
Labels: bug, make, backport-v3.10.x, backport-v3.11.x, backport-v3.12.x

#7374 Bump emqx/emqtt to 1.8.2
  MODULE.bazel
  deps/rabbitmq_auth_backend_oauth2/Makefile
  deps/rabbitmq_mqtt/Makefile
  deps/rabbitmq_web_mqtt/Makefile
Labels: bazel, make, backport-v3.10.x, backport-v3.11.x, backport-v3.12.x

#7370 Update Ra to 2.4.9
  MODULE.bazel
  rabbitmq-components.mk
Labels: bazel, make, backport-v3.11.x, backport-v3.12.x

#7368 See #7323. Oper policy for ha-mode and ha-params
  deps/rabbit/priv/schema/rabbit.schema
  deps/rabbit/src/rabbit_cuttlefish.erl
  deps/rabbit/src/rabbit_mirror_queue_misc.erl
  deps/rabbit/test/config_schema_SUITE_data/rabbit.snippets
  deps/rabbit/test/policy_SUITE.erl
Labels: backport-v3.10.x, backport-v3.11.x, backport-v3.12.x

#7391 Remove RABBITMQ_ERLANG_COOKIE warning
  deps/rabbitmq_cli/lib/rabbitmq/cli/core/distribution.ex
Labels: backport-v3.10.x, backport-v3.11.x, backport-v3.12.x

#7398 Reduce the default number of attempts to start the broker in tests
  deps/rabbitmq_ct_helpers/src/rabbit_ct_broker_helpers.erl
Labels: backport-v3.10.x, backport-v3.11.x, backport-v3.12.x

#7403 3.11.10 release notes
  release-notes/3.11.10.md
Labels: backport-v3.11.x, backport-v3.12.x

#7407 Adopt otp 24.3.4.9
  MODULE.bazel
  WORKSPACE
  deps/rabbitmq_amqp1_0/src/rabbit_amqp1_0_reader.erl
Labels: bazel, backport-v3.9.x

#7409 3.10.19 release notes
  release-notes/3.10.18.md
  release-notes/3.10.19.md
Labels: backport-v3.10.x, backport-v3.11.x, backport-v3.12.x

#7412 3.11.x: resolve a Web MQTT Makefile conflict
  deps/rabbitmq_web_mqtt/Makefile
Labels: make

#7414 Exclude bazel related files from `make source-dist`
  Makefile
Labels: make, backport-v3.10.x, backport-v3.11.x, backport-v3.12.x

#7429 Move rabbit_password to rabbit_common
  deps/rabbit_common/BUILD.bazel
  deps/rabbit_common/src/rabbit_password.erl
  deps/rabbit_common/src/rabbit_password_hashing_md5.erl
  deps/rabbit_common/src/rabbit_password_hashing_sha256.erl
  deps/rabbit_common/src/rabbit_password_hashing_sha512.erl
  deps/rabbit_common/test/unit_password_hashing_SUITE.erl
  deps/rabbitmq_cli/lib/rabbitmq/cli/core/distribution.ex
  deps/rabbitmq_cli/lib/rabbitmq/cli/ctl/commands/add_vhost_command.ex
  deps/rabbitmq_cli/lib/rabbitmq/cli/ctl/commands/hash_password_command.ex
Labels: bazel, backport-v3.10.x, backport-v3.11.x, backport-v3.12.x

#7439 Add documentation for hashing passwords
  deps/rabbit/docs/rabbitmqctl.8
  deps/rabbitmq_cli/lib/rabbitmq/cli/ctl/commands/hash_password_command.ex
  deps/rabbitmq_management/priv/www/api/index.html
Labels: backport-v3.10.x, backport-v3.11.x, backport-v3.12.x

#7441 Fix rabbitmq-diagnostics remote_shell for 26.0
  deps/rabbitmq_cli/lib/rabbitmq/cli/diagnostics/commands/remote_shell_command.ex
Labels: backport-v3.12.x

#7175 Quorum queues: chunk consumer log effects
  deps/rabbit/src/rabbit_fifo.erl
  deps/rabbit/src/rabbit_fifo.hrl
  deps/rabbit/test/quorum_queue_SUITE.erl
  deps/rabbit/test/rabbit_fifo_SUITE.erl
Labels: backport-v3.12.x

#7445 Fix remote_shell on win32
  deps/rabbit/scripts/rabbitmq-diagnostics.bat
Labels: backport-v3.10.x, backport-v3.11.x, backport-v3.12.x

#7452 Added documentation for decommission_mqtt_node
  deps/rabbit/docs/rabbitmqctl.8
Labels: backport-v3.10.x, backport-v3.11.x, backport-v3.12.x

#7455 Web MQTT: Send CONNACK error code before closing connection
  deps/rabbitmq_mqtt/src/rabbit_mqtt.erl
  deps/rabbitmq_mqtt/test/reader_SUITE.erl
  deps/rabbitmq_mqtt/test/shared_SUITE.erl
  deps/rabbitmq_web_mqtt/src/rabbit_web_mqtt_handler.erl
Labels: backport-v3.12.x

#7461 `rabbit_db*`: Fix EDoc syntax errors
  deps/rabbit/src/rabbit_db_binding.erl
  deps/rabbit/src/rabbit_db_exchange.erl
  deps/rabbit/src/rabbit_db_queue.erl
Labels: backport-v3.12.x

#7458 Fix 2549 - auth_oauth2.preferred_username_claims should accept multiple values
  deps/rabbitmq_auth_backend_oauth2/priv/schema/rabbitmq_auth_backend_oauth2.schema
  deps/rabbitmq_auth_backend_oauth2/test/config_schema_SUITE_data/rabbitmq_auth_backend_oauth2.snippets
  deps/rabbitmq_management/selenium/suites/oauth-idp-initiated-with-uaa.sh
  deps/rabbitmq_management/selenium/suites/oauth-with-uaa.sh
  deps/rabbitmq_management/selenium/suites/suite_template
  deps/rabbitmq_management/selenium/test/oauth/rabbitmq-idp-initiated.conf
  deps/rabbitmq_management/selenium/test/oauth/rabbitmq-localhost.conf
  deps/rabbitmq_management/selenium/test/oauth/rabbitmq-localhost.config
  deps/rabbitmq_management/selenium/test/oauth/rabbitmq.conf
  deps/rabbitmq_management/selenium/test/oauth/uaa-localhost/signing-key.pem
  deps/rabbitmq_management/selenium/test/oauth/uaa-localhost/uaa.yml
  deps/rabbitmq_management/selenium/test/oauth/uaa/signing-key.pem
  deps/rabbitmq_management/test/config_schema_SUITE_data/rabbitmq_management.snippets
Labels: backport-v3.10.x, backport-v3.11.x, backport-v3.12.x
