Repository rabbitmq/rabbitmq-server, pull requests merged in 2023-11, with the labels that each got.

#9843 Remove POODLE check
  deps/rabbit/src/rabbit_networking.erl
  deps/rabbit_common/src/rabbit_misc.erl
  deps/rabbitmq_mqtt/src/rabbit_mqtt_sup.erl
  deps/rabbitmq_stomp/src/rabbit_stomp_sup.erl
  deps/rabbitmq_stream/src/rabbit_stream_sup.erl
  deps/rabbitmq_web_dispatch/src/rabbit_web_dispatch_sup.erl
Labels: backport-v3.11.x, backport-v3.12.x

#9846 Update RabbitMQ-Overview.json
  deps/rabbitmq_prometheus/docker/grafana/dashboards/RabbitMQ-Overview.json
Labels: backport-v3.11.x, backport-v3.12.x

#9820 Redirect user back to landing page
  deps/rabbitmq_management/priv/www/js/main.js
  deps/rabbitmq_management/priv/www/js/oidc-oauth/helper.js
  deps/rabbitmq_management/priv/www/js/prefs.js
  deps/rabbitmq_management/selenium/test/oauth/with-sp-initiated/redirection-after-login.js
  deps/rabbitmq_management/selenium/test/utils.js
Labels: backport-v3.12.x

#9865 Use rules_erlang 3.14.0
  MODULE.bazel
Labels: bazel, backport-v3.11.x, backport-v3.12.x

#9870 Fix error insufficient_credit for AMQP 1.0 shovel
  deps/amqp10_client/src/amqp10_client_session.erl
  deps/rabbitmq_shovel/src/rabbit_amqp10_shovel.erl
  deps/rabbitmq_shovel/src/rabbit_shovel_behaviour.erl
Labels: backport-v3.12.x

#9877 Adjust strategy flags for bazel
  .bazelrc
  user-template.bazelrc
Labels: backport-v3.10.x, backport-v3.11.x, backport-v3.12.x

#9884 Avoid warning of unhandled message
  deps/rabbitmq_mqtt/src/rabbit_mqtt_internal_event_handler.erl
Labels: backport-v3.12.x

#9874 Optimise HTTP API /queues endpoint
  deps/rabbit/src/rabbit_amqqueue.erl
  deps/rabbit/src/rabbit_amqqueue_process.erl
  deps/rabbit/src/rabbit_classic_queue.erl
  deps/rabbit/src/rabbit_queue_type.erl
  deps/rabbit/src/rabbit_quorum_queue.erl
  deps/rabbit/src/rabbit_stream_queue.erl
  deps/rabbit/test/quorum_queue_SUITE.erl
  deps/rabbitmq_management/priv/www/js/formatters.js
  deps/rabbitmq_management/src/rabbit_mgmt_db.erl
  deps/rabbitmq_management/src/rabbit_mgmt_util.erl
  deps/rabbitmq_management/src/rabbit_mgmt_wm_queues.erl
  deps/rabbitmq_management_agent/src/rabbit_mgmt_format.erl
  deps/rabbitmq_mqtt/src/rabbit_mqtt_qos0_queue.erl
  deps/rabbitmq_stream_management/src/rabbit_stream_publishers_mgmt.erl
Labels: backport-v3.11.x, backport-v3.12.x

#9898 OCI updates: bump OpenSSL, remove outdated/unused Dockerfile
  WORKSPACE
  packaging/docker-image/BUILD.bazel
  packaging/docker-image/Dockerfile
  packaging/docker-image/test_configs/openssl_ubuntu.yaml
Labels: bazel

#9903 Bump CLI deps, remove dialyxir
  MODULE.bazel
  bazel/BUILD.amqp
  bazel/BUILD.dialyxir
  bazel/BUILD.x509
  deps/rabbitmq_cli/BUILD.bazel
  deps/rabbitmq_cli/Makefile
  deps/rabbitmq_cli/mix.exs
Labels: bazel, make, backport-v3.11.x, backport-v3.12.x

#9912 Add `rabbitmq-diagnostics list_policies_that_match` command
  deps/rabbit/src/rabbit_policy.erl
  deps/rabbitmq_cli/lib/rabbitmq/cli/diagnostics/commands/list_policies_that_match.ex
  deps/rabbitmq_cli/test/diagnostics/list_policies_that_match_command_test.exs
  deps/rabbitmq_cli/test/test_helper.exs
Labels: backport-v3.11.x, backport-v3.12.x

#9909 Dynamic Shovels: support old (pre-3.13.0, 3.12.8) and new supervisor child ID formats
  deps/rabbitmq_shovel/src/rabbit_shovel_dyn_worker_sup_sup.erl
Labels: backport-v3.12.x

#9924 Add --binding-keys to add_super_stream command
  deps/rabbit/docs/rabbitmq-streams.8
  deps/rabbitmq_stream/src/Elixir.RabbitMQ.CLI.Ctl.Commands.AddSuperStreamCommand.erl
  deps/rabbitmq_stream/test/commands_SUITE.erl
Labels: backport-v3.11.x, backport-v3.12.x

#9927 3.12.9 release notes
  release-notes/3.12.9.md
Labels: backport-v3.12.x

#9926 Use rabbit_json in the CLI
  deps/rabbitmq_cli/Makefile
  deps/rabbitmq_cli/lib/rabbitmq/cli/ctl/commands/export_definitions_command.ex
  deps/rabbitmq_cli/lib/rabbitmq/cli/ctl/commands/import_definitions_command.ex
  deps/rabbitmq_cli/lib/rabbitmq/cli/ctl/commands/list_user_limits_command.ex
  deps/rabbitmq_cli/lib/rabbitmq/cli/ctl/commands/list_vhost_limits_command.ex
  deps/rabbitmq_cli/lib/rabbitmq/cli/formatters/json.ex
  deps/rabbitmq_cli/lib/rabbitmq/cli/formatters/json_stream.ex
  deps/rabbitmq_cli/lib/rabbitmqctl.ex
  deps/rabbitmq_cli/mix.exs
  deps/rabbitmq_cli/test/ctl/export_definitions_command_test.exs
  deps/rabbitmq_cli/test/ctl/set_user_limits_command_test.exs
  deps/rabbitmq_cli/test/ctl/set_vhost_limits_command_test.exs
  deps/rabbitmq_cli/test/json_formatting.exs
  deps/rabbitmq_cli/test/test_helper.exs
Labels: make, backport-v3.11.x, backport-v3.12.x

#9932 Bazel bits for #9926
  deps/rabbitmq_cli/BUILD.bazel
Labels: backport-v3.11.x, backport-v3.12.x

#9940 Fixes #9937
  deps/rabbit/src/rabbit_auth_backend_internal.erl
Labels: backport-v3.11.x, backport-v3.12.x

#9944 Add #9937 to 3.12.9 release notes
  release-notes/3.12.9.md
Labels: backport-v3.12.x

#9946 Check virtual host queue limit on stream creation
  deps/rabbitmq_stream/src/rabbit_stream_manager.erl
  deps/rabbitmq_stream/test/rabbit_stream_SUITE.erl
Labels: backport-v3.11.x, backport-v3.12.x

#9953 Fix AMQP 1.0 connection throttling
  deps/rabbitmq_amqp1_0/src/rabbit_amqp1_0_reader.erl
  deps/rabbitmq_amqp1_0/test/amqp10_client_SUITE.erl
Labels: backport-v3.11.x, backport-v3.12.x

#9952 Revert elixir json switch
  BUILD.bazel
  MODULE.bazel
  Makefile
  deps/rabbitmq_cli/BUILD.bazel
  deps/rabbitmq_cli/Makefile
  deps/rabbitmq_cli/lib/rabbitmq/cli/ctl/commands/export_definitions_command.ex
  deps/rabbitmq_cli/lib/rabbitmq/cli/ctl/commands/import_definitions_command.ex
  deps/rabbitmq_cli/lib/rabbitmq/cli/ctl/commands/list_user_limits_command.ex
  deps/rabbitmq_cli/lib/rabbitmq/cli/ctl/commands/list_vhost_limits_command.ex
  deps/rabbitmq_cli/lib/rabbitmq/cli/formatters/json.ex
  deps/rabbitmq_cli/lib/rabbitmq/cli/formatters/json_stream.ex
  deps/rabbitmq_cli/lib/rabbitmqctl.ex
  deps/rabbitmq_cli/mix.exs
  deps/rabbitmq_cli/test/ctl/export_definitions_command_test.exs
  deps/rabbitmq_cli/test/ctl/set_user_limits_command_test.exs
  deps/rabbitmq_cli/test/ctl/set_vhost_limits_command_test.exs
  deps/rabbitmq_cli/test/json_formatting.exs
  deps/rabbitmq_cli/test/test_helper.exs
  dist.bzl
Labels: bazel, make, backport-v3.11.x, backport-v3.12.x

#9959 3.11.26 release notes
  release-notes/3.11.26.md
Labels: backport-v3.11.x, backport-v3.12.x

#9966 3.12.10 release notes
  release-notes/3.12.10.md
Labels: backport-v3.12.x

#9977 rabbitmq-dist.mk: Install CLI scripts as part of the build instead of the `dist` target
  deps/rabbit_common/mk/rabbitmq-dist.mk
Labels: make

#9830 Message container conversion improvements
  deps/rabbit/include/mc.hrl
  deps/rabbit/src/mc.erl
  deps/rabbit/src/mc_amqp.erl
  deps/rabbit/src/mc_amqpl.erl
  deps/rabbit/src/mc_util.erl
  deps/rabbit/test/mc_unit_SUITE.erl
  deps/rabbit/test/rabbit_stream_queue_SUITE.erl
  deps/rabbit_common/src/rabbit_misc.erl
  deps/rabbitmq_mqtt/app.bzl
  deps/rabbitmq_mqtt/include/rabbit_mqtt.hrl
  deps/rabbitmq_mqtt/src/mc_mqtt.erl
  deps/rabbitmq_mqtt/src/rabbit_mqtt_processor.erl
  deps/rabbitmq_mqtt/test/mc_mqtt_SUITE.erl
  deps/rabbitmq_mqtt/test/protocol_interop_SUITE.erl
  deps/rabbitmq_mqtt/test/v5_SUITE.erl
Labels: bazel, make

#9984 Fixes #9983
  deps/rabbitmq_management/src/rabbit_mgmt_wm_policy.erl
Labels: backport-v3.11.x, backport-v3.12.x

#9994 rabbit_writer: ignore unknown messages
  deps/rabbit_common/src/rabbit_writer.erl
Labels: backport-v3.11.x, backport-v3.12.x
