Repository rabbitmq/rabbitmq-server, pull requests merged in 2023-03, with the labels that each got.

#7467 Pin rabbitmq_cli prod deps
  deps/rabbitmq_cli/BUILD.bazel
  deps/rabbitmq_cli/Makefile
  deps/rabbitmq_cli/mix.exs
Labels: bazel, make

#7476 per_user_connection_channel_tracking_SUITE: Remove dead code
  deps/rabbit/test/per_user_connection_channel_tracking_SUITE.erl
Labels: backport-v3.12.x

#7481 Update 3.10.19 release notes
  release-notes/3.10.19.md
Labels: backport-v3.10.x, backport-v3.11.x, backport-v3.12.x

#7488 Release notes issue number formatting
  release-notes/3.10.19.md
  release-notes/3.11.10.md
Labels: backport-v3.11.x, backport-v3.12.x

#7491 Adopt otp 24.3.4.9
  MODULE.bazel
Labels: bazel

#7492 Adopt elixir 1.13.4
  MODULE.bazel
Labels: bazel, backport-v3.10.x, backport-v3.11.x, backport-v3.12.x

#7513 3.10.x: EOL date is now known
  deps/rabbit/BUILD.bazel
  deps/rabbit/Makefile
Labels: bazel, make

#7514 3.9.x: EOL date
  deps/rabbit/BUILD.bazel
  deps/rabbit/Makefile
Labels: bazel, make

#7518 Initial 3.12 release notes
  release-notes/3.11.0.md
  release-notes/3.12.0.md
Labels: backport-v3.12.x

#7516 CQ: Confirm related optimisations
  deps/rabbit/src/rabbit_msg_store.erl
  deps/rabbit/src/rabbit_variable_queue.erl
Labels: backport-v3.12.x

#7522 Update 3.12.0 release notes
  release-notes/3.12.0.md
Labels: backport-v3.12.x

#7535 Fix reached_target_cluster_size() after recent changes
  deps/rabbit/src/rabbit_nodes.erl
Labels: backport-v3.12.x

#7537 Tweak dev Docker images
  .github/workflows/oci.yaml
  packaging/docker-image/install_rabbitmq.sh
Labels: backport-v3.10.x, backport-v3.11.x, backport-v3.12.x

#7534 rabbit_db_cluster: Figure out members list even if Mnesia is stopped
  deps/rabbit/src/rabbit_db_cluster.erl
  deps/rabbit/src/rabbit_mnesia.erl
  deps/rabbit/test/clustering_management_SUITE.erl
Labels: backport-v3.12.x

#7540 Add OTP 25.3 to the build and CI matrix as otp-max
  .bazelrc
  .github/workflows/oci.yaml
  .github/workflows/rabbitmq_peer_discovery_aws.yaml
  .github/workflows/test-selenium.yaml
  .github/workflows/test-windows.yaml
  .github/workflows/test.yaml
  .github/workflows/update-otp-patches.yaml
  MODULE.bazel
  WORKSPACE
  bazel/platforms/BUILD.bazel
  deps/rabbitmq_amqp1_0/src/rabbit_amqp1_0_reader.erl
  packaging/docker-image/BUILD.bazel
Labels: bazel, backport-v3.10.x, backport-v3.11.x, backport-v3.12.x

#7544 Fixup remaining otp 25.2 reference
  .github/workflows/test-mixed-versions.yaml
Labels: backport-v3.10.x, backport-v3.11.x, backport-v3.12.x

#7560 Document set_permissions_globally CLI command
  deps/rabbit/docs/rabbitmqctl.8
Labels: backport-v3.10.x, backport-v3.11.x, backport-v3.12.x

#7573 Add two file rotation test cases
  deps/rabbit/apps/rabbitmq_prelaunch/test/rabbit_logger_std_h_SUITE.erl
Labels: backport-v3.11.x, backport-v3.12.x

#7552 Return "precondition failed" on exchange deletion if appropriate
  deps/rabbit/src/rabbit_exchange.erl
Labels: backport-v3.12.x

#7577 Fix various type specs
  deps/rabbit/src/amqqueue.erl
  deps/rabbit/src/rabbit_feature_flags.erl
  deps/rabbit/src/rabbit_ff_registry.erl
  deps/rabbitmq_cli/test/ctl/enable_feature_flag_test.exs
  deps/rabbitmq_cli/test/ctl/list_feature_flags_command_test.exs
Labels: backport-v3.11.x, backport-v3.12.x

#7561 Allow picking ports for `bazel run broker`
  BAZEL.md
  scripts/bazel/rabbitmq-run.sh
Labels: backport-v3.10.x, backport-v3.11.x, backport-v3.12.x

#7553 Ra 2.5.0
  MODULE.bazel
  bazel/BUILD.ra
  moduleindex.yaml
  rabbitmq-components.mk
Labels: bazel, make, backport-v3.12.x

#7587 Update 3.12.0 release notes
  release-notes/3.12.0.md
Labels: backport-v3.12.x

#7589 etcd: do not filter out node TTL
  deps/rabbitmq_peer_discovery_etcd/src/rabbitmq_peer_discovery_etcd_v3_client.erl
Labels: backport-v3.10.x, backport-v3.11.x, backport-v3.12.x

#7594 MQTT: Fix 3.12-beta.1 cluster creation
  deps/rabbitmq_mqtt/src/mqtt_node.erl
  deps/rabbitmq_mqtt/src/rabbit_mqtt_processor.erl
Labels: bug, rabbitmq-mqtt, backport-v3.12.x

#7601 Allow applying policies to specific queue types
  deps/rabbit/docs/rabbitmqctl.8
  deps/rabbit/src/rabbit_policy.erl
  deps/rabbit/test/policy_SUITE.erl
  deps/rabbitmq_management/priv/www/js/tmpl/policies.ejs
  release-notes/3.12.0.md
Labels: backport-v3.12.x

#7605 Support x-stream-max-segment-size-bytes in STOMP plugin
  deps/rabbitmq_stomp/include/rabbit_stomp_headers.hrl
  deps/rabbitmq_stomp/src/rabbit_stomp_util.erl
  deps/rabbitmq_stomp/test/python_SUITE_data/src/x_queue_type_stream.py
Labels: backport-v3.11.x, backport-v3.12.x

#7610 Remove missleading text
  deps/amqp_client/README.in
Labels: backport-v3.9.x, backport-v3.10.x, backport-v3.11.x, backport-v3.12.x

#7548 Fix rabbit_vm:memory returning stream_queue_coordinator_procs
  deps/rabbit/src/rabbit_vm.erl
Labels: backport-v3.11.x, backport-v3.12.x

#7609 Fetch cli prod deps via bazel or erlang.mk instead of mix
  BUILD.bazel
  MODULE.bazel
  Makefile
  WORKSPACE
  bazel/BUILD.csv
  bazel/BUILD.json
  deps/rabbitmq_cli/BUILD.bazel
  deps/rabbitmq_cli/Makefile
  deps/rabbitmq_cli/mix.exs
  deps/rabbitmq_cli/rabbitmqctl.bzl
  deps/rabbitmq_cli/rabbitmqctl_test.bzl
  dist.bzl
Labels: bazel, make, backport-v3.10.x, backport-v3.11.x, backport-v3.12.x

#7620 added :streams to the help command scopes
  deps/rabbitmq_cli/lib/rabbitmq/cli/ctl/commands/help_command.ex
Labels: backport-v3.10.x, backport-v3.11.x, backport-v3.12.x

#7629 Remove "dev_dependency = True" from erlang_dev_package in MODULE
  MODULE.bazel
Labels: bazel, backport-v3.10.x, backport-v3.11.x, backport-v3.12.x

#7619 Avoid fetching test deps when building rabbitmqctl with bazel
  deps/rabbitmq_cli/rabbitmqctl.bzl
Labels: bazel, backport-v3.10.x, backport-v3.11.x, backport-v3.12.x

#7631 Add "Summary" jobs to test workflows in actions
  .github/workflows/oci.yaml
  .github/workflows/test-mixed-versions.yaml
  .github/workflows/test-selenium.yaml
  .github/workflows/test-windows.yaml
  .github/workflows/test.yaml
Labels: backport-v3.10.x, backport-v3.11.x, backport-v3.12.x

#7638 Take credits for inactive stream subscription
  deps/rabbitmq_stream/src/rabbit_stream_reader.erl
Labels: bug, backport-v3.11.x, backport-v3.12.x

#7640 Give each of the summary jobs in actions different names
  .github/workflows/oci.yaml
  .github/workflows/test-mixed-versions.yaml
  .github/workflows/test-selenium.yaml
  .github/workflows/test-windows.yaml
  .github/workflows/test.yaml
Labels: backport-v3.10.x, backport-v3.11.x, backport-v3.12.x

#7660 3.12.0 release notes edits
  release-notes/3.12.0.md
Labels: backport-v3.12.x

#7663 Fix flaky test rabbit_mqtt_qos0_queue_overflow
  deps/rabbitmq_mqtt/test/reader_SUITE.erl
Labels: backport-v3.12.x

#7659 Include the queue type in the queue_deleted rabbit_event
  deps/rabbit/src/rabbit_amqqueue.erl
  deps/rabbit/src/rabbit_amqqueue_process.erl
  deps/rabbit/src/rabbit_classic_queue.erl
  deps/rabbit/src/rabbit_quorum_queue.erl
  deps/rabbit/src/rabbit_stream_coordinator.erl
  deps/rabbit/src/rabbit_stream_queue.erl
  deps/rabbit/src/rabbit_vhost.erl
  deps/rabbit/test/backing_queue_SUITE.erl
  deps/rabbitmq_mqtt/src/rabbit_mqtt_qos0_queue.erl
Labels: backport-v3.12.x

#7666 3.12.0 release notes corrections
  release-notes/3.12.0.md
Labels: backport-v3.12.x

#7669 Adopt otp 24.3.4.10
  MODULE.bazel
  WORKSPACE
Labels: bazel

#7670 More 3.12.0 release notes updates
  release-notes/3.12.0.md
Labels: backport-v3.12.x

#7672 Classic queues: make CQv2 the new default
  deps/rabbit/BUILD.bazel
  deps/rabbit/Makefile
  deps/rabbit/priv/schema/rabbit.schema
  deps/rabbit/src/rabbit_amqqueue_process.erl
  deps/rabbit/src/rabbit_variable_queue.erl
  release-notes/3.12.0.md
Labels: bazel, make, backport-v3.12.x

#7684 Revert #7672
  deps/rabbit/BUILD.bazel
  deps/rabbit/Makefile
  deps/rabbit/priv/schema/rabbit.schema
  deps/rabbit/src/rabbit_amqqueue_process.erl
  deps/rabbit/src/rabbit_variable_queue.erl
  release-notes/3.12.0.md
Labels: bazel, make

#7682 Use 3.11.11 for mixed version testing
  bazel/bzlmod/secondary_umbrella.bzl
Labels: bazel, backport-v3.12.x

#7689 Closes #7685
  deps/rabbit/src/rabbit_definitions.erl
  deps/rabbit/src/rabbit_definitions_import_local_filesystem.erl
Labels: backport-v3.10.x, backport-v3.11.x, backport-v3.12.x

#7675 Fix return value of mgmt login handler on bad method
  deps/rabbitmq_management/src/rabbit_mgmt_login.erl
Labels: backport-v3.10.x, backport-v3.11.x, backport-v3.12.x

#7686 rabbit_node_monitor: Use `rabbit_mnesia` in partition handling-specific code
  deps/rabbit/src/rabbit_node_monitor.erl
Labels: bug, backport-v3.12.x

#7700 3.10.20 release notes
  release-notes/3.10.20.md
Labels: backport-v3.10.x, backport-v3.11.x, backport-v3.12.x

#7707 Update 3.10.20 release notes
  release-notes/3.10.20.md
Labels: backport-v3.10.x, backport-v3.11.x, backport-v3.12.x

#7711 Update 3.11.11 release notes
  release-notes/3.11.11.md
Labels: backport-v3.11.x, backport-v3.12.x

#7717 CLI: correctly override DocGuide.virtual_hosts path segment
  deps/rabbitmq_cli/lib/rabbitmq/cli/core/doc_guide.ex
Labels: backport-v3.10.x, backport-v3.11.x, backport-v3.12.x

#7727 More cleanup for the old upgrade subsystem
  deps/rabbit/src/rabbit.erl
  deps/rabbit/src/rabbit_policy.erl
Labels: backport-v3.12.x

#7579 Fix CMQ crash when master goes down, queue length at x-max-length limit with consumers connected
  deps/rabbit/src/rabbit_mirror_queue_master.erl
Labels: backport-v3.12.x

#7732 QQ: do not add x-delivery-count header for the first delivery.
  deps/rabbit/src/rabbit_fifo_client.erl
  deps/rabbit/test/quorum_queue_SUITE.erl
  release-notes/3.12.0.md
Labels: backport-v3.12.x

#7738 HTTP API: rename default queue type key
  deps/rabbitmq_management/priv/www/js/tmpl/vhosts.ejs
  deps/rabbitmq_management/src/rabbit_mgmt_wm_vhost.erl
  deps/rabbitmq_management/test/rabbit_mgmt_http_SUITE.erl
Labels: backport-v3.11.x, backport-v3.12.x

#7747 QQ: add test for message ttl using a policy.
  deps/rabbit/test/quorum_queue_SUITE.erl
Labels: backport-v3.11.x, backport-v3.12.x

#7753 See #7593. Use connection_max to stop connections in rabbitmq
  deps/rabbit/BUILD.bazel
  deps/rabbit/Makefile
  deps/rabbit/priv/schema/rabbit.schema
  deps/rabbit/src/rabbit_reader.erl
  deps/rabbit/src/tcp_listener_sup.erl
  deps/rabbit/test/config_schema_SUITE_data/rabbit.snippets
  deps/rabbit/test/per_node_limit_SUITE.erl
Labels: bazel, make, backport-v3.11.x, backport-v3.12.x

#7692 fix up bazel build of rabbitmq_cli when branch switching
  deps/rabbitmq_cli/lib/rabbitmq/cli/diagnostics/diagnostics_helpers.ex
  deps/rabbitmq_cli/rabbitmqctl.bzl
  deps/rabbitmq_cli/rabbitmqctl_test.bzl
Labels: bazel, backport-v3.10.x, backport-v3.11.x, backport-v3.12.x

#7668 See #7389. One tick process per quorum queue
  deps/rabbit/src/rabbit_fifo.erl
  deps/rabbit/test/rabbit_fifo_SUITE.erl
Labels: backport-v3.12.x

#7761 Restore the tanzu cli scope
  Makefile
  deps/rabbit/scripts/rabbitmq-tanzu
  deps/rabbit/scripts/rabbitmq-tanzu.bat
  deps/rabbitmq_cli/Makefile
  deps/rabbitmq_cli/lib/rabbitmq/cli/ctl/commands/help_command.ex
  deps/rabbitmq_cli/mix.exs
  rabbitmq_home.bzl
Labels: bazel, make, backport-v3.10.x

#7770 bazel: Pin ct_helper
  MODULE.bazel
Labels: bazel, backport-v3.9.x, backport-v3.10.x, backport-v3.11.x, backport-v3.12.x

#7795 3.11.13 release notes
  release-notes/3.11.13.md
Labels: backport-v3.11.x, backport-v3.12.x
