Repository rabbitmq/rabbitmq-server, pull requests merged in 2023-12, with the labels that each got.

#10023 GitHub Actions: Convert '_' to '-' in `$AWS_ECS_CLUSTER_NAME`
  .github/workflows/rabbitmq_peer_discovery_aws.yaml
Labels: backport-v3.11.x, backport-v3.12.x

#10032 Osiris 1.7.1
  MODULE.bazel
  deps/rabbit/Makefile
Labels: bazel, make, backport-v3.12.x

#10033 Capture container logs in rabbitmq_peer_discovery_aws suite
  deps/rabbitmq_peer_discovery_aws/test/integration_SUITE.erl
  deps/rabbitmq_peer_discovery_aws/test/integration_SUITE_data/task_definition.json
Labels: backport-v3.10.x, backport-v3.11.x, backport-v3.12.x

#10034 QQ: ensure members that are started late have right config.
  deps/rabbit/src/rabbit_quorum_queue.erl
  deps/rabbit/test/quorum_queue_SUITE.erl
Labels: backport-v3.12.x

#9797 rabbit_peer_discovery: Rewrite the core logic
  deps/rabbit/BUILD.bazel
  deps/rabbit/app.bzl
  deps/rabbit/src/rabbit_db.erl
  deps/rabbit/src/rabbit_mnesia.erl
  deps/rabbit/src/rabbit_peer_discovery.erl
  deps/rabbit/src/rabbit_peer_discovery_classic_config.erl
  deps/rabbit/src/rabbit_peer_discovery_dns.erl
  deps/rabbit/test/clustering_management_SUITE.erl
  deps/rabbit/test/peer_discovery_classic_config_SUITE.erl
  deps/rabbit/test/unit_cluster_formation_locking_mocks_SUITE.erl
  deps/rabbit/test/unit_cluster_formation_sort_nodes_SUITE.erl
  deps/rabbit_common/mk/rabbitmq-run.mk
  deps/rabbit_common/src/rabbit_peer_discovery_backend.erl
  deps/rabbitmq_cli/test/diagnostics/discover_peers_command_test.exs
  deps/rabbitmq_peer_discovery_aws/src/rabbit_peer_discovery_aws.erl
  deps/rabbitmq_peer_discovery_aws/src/rabbitmq_peer_discovery_aws.erl
  deps/rabbitmq_peer_discovery_aws/test/unit_SUITE.erl
  deps/rabbitmq_peer_discovery_consul/src/rabbit_peer_discovery_consul.erl
  deps/rabbitmq_peer_discovery_consul/src/rabbitmq_peer_discovery_consul.erl
  deps/rabbitmq_peer_discovery_etcd/src/rabbit_peer_discovery_etcd.erl
  deps/rabbitmq_peer_discovery_etcd/src/rabbitmq_peer_discovery_etcd.erl
  deps/rabbitmq_peer_discovery_k8s/src/rabbit_peer_discovery_k8s.erl
  deps/rabbitmq_peer_discovery_k8s/src/rabbitmq_peer_discovery_k8s.erl
  deps/rabbitmq_peer_discovery_k8s/test/rabbitmq_peer_discovery_k8s_SUITE.erl
Labels: bazel, make

#10058 Support stream filtering in STOMP
  deps/rabbitmq_stomp/include/rabbit_stomp_headers.hrl
  deps/rabbitmq_stomp/src/rabbit_stomp_frame.erl
  deps/rabbitmq_stomp/src/rabbit_stomp_processor.erl
  deps/rabbitmq_stomp/src/rabbit_stomp_util.erl
  deps/rabbitmq_stomp/test/frame_SUITE.erl
  deps/rabbitmq_stomp/test/python_SUITE_data/src/x_queue_type_stream.py
  deps/rabbitmq_stomp/test/system_SUITE.erl
Labels: rabbitmq-stomp, streams

#10081 Update 3.11.26 release notes
  release-notes/3.11.26.md
Labels: backport-v3.11.x, backport-v3.12.x

#10072 Usability improvements during definition import #10068
  deps/rabbit/src/rabbit_definitions.erl
  deps/rabbit/src/rabbit_definitions_import_local_filesystem.erl
  deps/rabbit/test/definition_import_SUITE.erl
  deps/rabbit/test/definition_import_SUITE_data/failing_case21.json
  deps/rabbitmq_cli/lib/rabbitmq/cli/ctl/commands/import_definitions_command.ex
  deps/rabbitmq_management/src/rabbit_mgmt_load_definitions.erl
  deps/rabbitmq_management/src/rabbit_mgmt_wm_definitions.erl
Labels: backport-v3.11.x, backport-v3.12.x

#10084 bazel run gazelle
  deps/rabbit/BUILD.bazel
  deps/rabbitmq_ct_helpers/BUILD.bazel
Labels: bazel

#10087 rabbitmq_management_agent: Use `rabbit_plugins:enabled_plugins/0`
  deps/rabbitmq_management_agent/src/rabbit_mgmt_external_stats.erl
Labels: backport-v3.11.x, backport-v3.12.x

#10106 Bazel: Pin the bazel version to v6.4.0
  .bazelversion
Labels: bazel, backport-v3.11.x, backport-v3.12.x

#10103 CI: Use 'bazel cquery' to find OCI tests
  .github/workflows/oci.yaml
Labels: bazel, backport-v3.11.x, backport-v3.12.x

#9901 CLI: list_deprecated_features command
  deps/rabbit/app.bzl
  deps/rabbit/src/rabbit_depr_ff_extra.erl
  deps/rabbit/src/rabbit_deprecated_features.erl
  deps/rabbit/test/deprecated_features_SUITE.erl
  deps/rabbitmq_cli/lib/rabbitmq/cli/ctl/commands/list_deprecated_features_command.ex
  deps/rabbitmq_cli/test/ctl/list_deprecated_features_command_test.exs
Labels: bazel

#9646 Migrate records from Mnesia to Khepri with async commands
  MODULE.bazel
  bazel/BUILD.khepri
  deps/rabbit/src/rabbit_db_binding_m2k_converter.erl
  deps/rabbit/src/rabbit_db_exchange_m2k_converter.erl
  deps/rabbit/src/rabbit_db_m2k_converter.erl
  deps/rabbit/src/rabbit_db_maintenance_m2k_converter.erl
  deps/rabbit/src/rabbit_db_msup_m2k_converter.erl
  deps/rabbit/src/rabbit_db_queue_m2k_converter.erl
  deps/rabbit/src/rabbit_db_rtparams_m2k_converter.erl
  deps/rabbit/src/rabbit_db_user_m2k_converter.erl
  deps/rabbit/src/rabbit_db_vhost_m2k_converter.erl
  deps/rabbit/src/rabbit_khepri.erl
  deps/rabbitmq_consistent_hash_exchange/src/rabbit_db_ch_exchange_m2k_converter.erl
  deps/rabbitmq_jms_topic_exchange/src/rabbit_db_jms_exchange_m2k_converter.erl
  deps/rabbitmq_recent_history_exchange/src/rabbit_db_rh_exchange_m2k_converter.erl
  rabbitmq-components.mk
Labels: bazel, make

#10114 3.11.27 release notes
  release-notes/3.11.27.md
Labels: backport-v3.11.x, backport-v3.12.x

#10118 3.12.11 release notes
  release-notes/3.12.11.md
Labels: backport-v3.12.x

#10120 Bump Osiris to 1.7.2
  MODULE.bazel
  deps/rabbit/Makefile
Labels: bazel, make, backport-v3.12.x

#10102 Avoid expensive rabbit_nodes:list_running()
  deps/rabbit/src/rabbit_mirror_queue_misc.erl
Labels: backport-v3.12.x

#10101 Optimise cluster_status cli command when not all nodes are online and responding.
  deps/rabbit/src/rabbit_feature_flags.erl
  deps/rabbit/src/rabbit_networking.erl
  deps/rabbitmq_cli/lib/rabbitmq/cli/ctl/commands/cluster_status_command.ex
Labels: backport-v3.12.x

#9893 Improve feature flags and deprecated features management
  deps/rabbit/src/rabbit_deprecated_features.erl
  deps/rabbitmq_management/app.bzl
  deps/rabbitmq_management/priv/www/api/index.html
  deps/rabbitmq_management/priv/www/css/main.css
  deps/rabbitmq_management/priv/www/js/dispatcher.js
  deps/rabbitmq_management/priv/www/js/formatters.js
  deps/rabbitmq_management/priv/www/js/global.js
  deps/rabbitmq_management/priv/www/js/main.js
  deps/rabbitmq_management/priv/www/js/tmpl/deprecated-features.ejs
  deps/rabbitmq_management/priv/www/js/tmpl/feature-flags.ejs
  deps/rabbitmq_management/priv/www/js/tmpl/layout.ejs
  deps/rabbitmq_management/src/rabbit_mgmt_dispatcher.erl
  deps/rabbitmq_management/src/rabbit_mgmt_wm_deprecated_features.erl
  deps/rabbitmq_management/test/rabbit_mgmt_http_SUITE.erl
Labels: bazel

#10138 Fix crash when closing connection
  deps/rabbitmq_management/src/rabbit_mgmt_wm_connection_user_name.erl
  deps/rabbitmq_mqtt/test/shared_SUITE.erl
Labels: bug, backport-v3.12.x

#10096 Khepri migration: upgrade #mirrored_sup_childspec{} records for shovel & federation
  deps/rabbit/app.bzl
  deps/rabbit/include/mirrored_supervisor.hrl
  deps/rabbit/src/rabbit_db_m2k_converter.erl
  deps/rabbit/src/rabbit_db_msup_m2k_converter.erl
  deps/rabbit/src/rabbit_mnesia_to_khepri_record_converter.erl
  deps/rabbitmq_federation/src/rabbit_federation_exchange_link_sup_sup.erl
  deps/rabbitmq_federation/src/rabbit_federation_queue_link_sup_sup.erl
  deps/rabbitmq_shovel/src/rabbit_shovel_dyn_worker_sup_sup.erl
  moduleindex.yaml
Labels: bazel

#10139 Use long type names in queue_created events
  deps/rabbit/src/rabbit_amqqueue.erl
  deps/rabbit/src/rabbit_amqqueue_process.erl
Labels: backport-v3.12.x

#10162 Generate manpages in markdown in addition to HTML
  deps/rabbit/Makefile
Labels: make

#10165 Adopt otp 25.3.2.8
  MODULE.bazel
  WORKSPACE
Labels: bazel, backport-v3.10.x, backport-v3.11.x, backport-v3.12.x

#10171 Tolerate race condition when starting management db cache process
  deps/rabbitmq_management/src/rabbit_mgmt_db_cache.erl
Labels: backport-v3.11.x, backport-v3.12.x

#10163 Add log on queue expiry
  deps/rabbit/src/rabbit_amqqueue_process.erl
Labels: backport-v3.12.x

#10179 Very minor: Prevent formatter crash in mgmt_util
  deps/rabbitmq_management/src/rabbit_mgmt_util.erl
Labels: backport-v3.12.x

#10185 Revert "HTTP API: DELETE /api/queues/{vhost}/{name} use internal API call
  deps/rabbitmq_management/src/rabbit_mgmt_wm_queue.erl
  deps/rabbitmq_management/test/rabbit_mgmt_http_SUITE.erl
Labels: backport-v3.11.x, backport-v3.12.x

#10158 Add internal incremental ID for stream publishers
  deps/rabbitmq_stream/src/rabbit_stream_reader.erl
  deps/rabbitmq_stream/src/rabbit_stream_utils.erl
Labels: usability, streams, backport-v3.12.x

#9656 Escape prometheus core metric label values
  MODULE.bazel
  deps/rabbitmq_prometheus/src/collectors/prometheus_rabbitmq_core_metrics_collector.erl
  deps/rabbitmq_prometheus/test/rabbit_prometheus_http_SUITE.erl
  rabbitmq-components.mk
Labels: bazel, make, backport-v3.11.x, backport-v3.12.x

#10203 Overwrite rabbit_mqtt_qos0_queue record from crashed node
  deps/rabbitmq_mqtt/src/rabbit_mqtt_qos0_queue.erl
  deps/rabbitmq_mqtt/test/shared_SUITE.erl
Labels: bug, backport-v3.12.x

#10212 3.11.28 release notes
  release-notes/3.11.28.md
Labels: backport-v3.11.x, backport-v3.12.x

#10216 Update 3.12.11 release notes
  release-notes/3.12.11.md
Labels: backport-v3.12.x

#10224 [deps/rabbitmq_aws] Modified type annotations, and fixed typos
  deps/rabbitmq_aws/src/rabbitmq_aws.erl
Labels: backport-v3.11.x, backport-v3.12.x

#10225 Replaced true | false by boolean()
  deps/amqp10_common/src/amqp10_binary_generator.erl
  deps/amqp_client/src/amqp_channel.erl
  deps/rabbit/src/rabbit_amqqueue_process.erl
  deps/rabbitmq_aws/src/rabbitmq_aws_config.erl
  deps/rabbitmq_management/src/rabbit_mgmt_util.erl
  deps/rabbitmq_peer_discovery_common/src/rabbit_peer_discovery_cleanup.erl
  deps/rabbitmq_peer_discovery_common/src/rabbit_peer_discovery_util.erl
Labels: backport-v3.12.x

#10200 Propagate all credentials to http backend
  deps/rabbitmq_auth_backend_http/README.md
  deps/rabbitmq_auth_backend_http/examples/rabbitmq_auth_backend_spring_boot/pom.xml
  deps/rabbitmq_auth_backend_http/examples/rabbitmq_auth_backend_spring_boot/src/main/java/com/rabbitmq/examples/AuthBackendHttpController.java
  deps/rabbitmq_auth_backend_http/examples/rabbitmq_auth_backend_spring_boot/src/main/java/com/rabbitmq/examples/BaseCheck.java
  deps/rabbitmq_auth_backend_http/examples/rabbitmq_auth_backend_spring_boot/src/main/java/com/rabbitmq/examples/RabbitMqAuthBackendHttp.java
  deps/rabbitmq_auth_backend_http/examples/rabbitmq_auth_backend_spring_boot/src/main/java/com/rabbitmq/examples/ResourceCheck.java
  deps/rabbitmq_auth_backend_http/examples/rabbitmq_auth_backend_spring_boot/src/main/java/com/rabbitmq/examples/TopicCheck.java
  deps/rabbitmq_auth_backend_http/examples/rabbitmq_auth_backend_spring_boot/src/main/java/com/rabbitmq/examples/User.java
  deps/rabbitmq_auth_backend_http/examples/rabbitmq_auth_backend_spring_boot/src/main/java/com/rabbitmq/examples/VirtualHostCheck.java
  deps/rabbitmq_auth_backend_http/examples/rabbitmq_auth_backend_spring_boot/src/test/java/com/rabbitmq/examples/AuthBackendHttpControllerTest.java
  deps/rabbitmq_auth_backend_http/examples/rabbitmq_auth_backend_spring_boot_kotlin/src/main/kotlin/com/rabbitmq/examples/AuthController.kt
  deps/rabbitmq_auth_backend_http/examples/rabbitmq_auth_backend_spring_boot_kotlin/src/main/kotlin/com/rabbitmq/examples/RabbitmqAuthBackendApplication.kt
  deps/rabbitmq_auth_backend_http/examples/rabbitmq_auth_backend_spring_boot_kotlin/src/test/kotlin/com/rabbitmq/examples/AuthApiTest.kt
  deps/rabbitmq_auth_backend_http/src/rabbit_auth_backend_http.erl
  deps/rabbitmq_auth_backend_http/test/auth_SUITE.erl
  deps/rabbitmq_auth_backend_http/test/auth_http_mock.erl
  deps/rabbitmq_management/selenium/bin/suite_template
  deps/rabbitmq_management/selenium/full-suite-authnz
  deps/rabbitmq_management/selenium/full-suite-authnz-messaging
  deps/rabbitmq_management/selenium/package.json
  deps/rabbitmq_management/selenium/suites/authnz-messaging/auth-cache-http-backends.sh
  deps/rabbitmq_management/selenium/suites/authnz-messaging/auth-cache-ldap-backends.sh
  deps/rabbitmq_management/selenium/suites/authnz-messaging/auth-http-backend.sh
  deps/rabbitmq_management/selenium/suites/authnz-messaging/auth-http-internal-backends-with-internal.sh
  deps/rabbitmq_management/selenium/suites/authnz-messaging/auth-http-internal-backends.sh
  deps/rabbitmq_management/selenium/suites/authnz-messaging/auth-internal-backend.sh
  deps/rabbitmq_management/selenium/suites/authnz-messaging/auth-internal-http-backends.sh
  deps/rabbitmq_management/selenium/suites/authnz-messaging/auth-ldap-backend.sh
  deps/rabbitmq_management/selenium/test/authnz-msg-protocols/amqp10.js
  deps/rabbitmq_management/selenium/test/authnz-msg-protocols/mock-auth-backend-http/defaultExpectations.json
  deps/rabbitmq_management/selenium/test/authnz-msg-protocols/mock-auth-backend-http/expectationInitialiser.json
  deps/rabbitmq_management/selenium/test/authnz-msg-protocols/mqtt.js
  deps/rabbitmq_management/selenium/test/mock_http_backend.js
Labels: backport-v3.12.x

#10243 Use correct user to test authentication via various messaging protocols
  .github/workflows/test-authnz.yaml
  deps/rabbitmq_management/selenium/test/authnz-msg-protocols/.env.internal-user
  deps/rabbitmq_management/selenium/test/authnz-msg-protocols/amqp10.js
  deps/rabbitmq_management/selenium/test/authnz-msg-protocols/imports/users.json
  deps/rabbitmq_management/selenium/test/authnz-msg-protocols/mqtt.js
Labels: backport-v3.12.x

#10246 Defined "tags" as list in /api/users/name
  deps/rabbitmq_management/priv/www/api/index.html
Labels: backport-v3.11.x, backport-v3.12.x

#10244 Allow MQTT QoS 0 subscribers to reconnect
  deps/rabbit/src/rabbit_amqqueue.erl
  deps/rabbitmq_mqtt/src/rabbit_mqtt_qos0_queue.erl
  deps/rabbitmq_mqtt/test/shared_SUITE.erl
Labels: backport-v3.12.x
