Repository rabbitmq/rabbitmq-server, pull requests merged in 2023-08, with the labels that each got.

#8985 Adopt otp 25.3.2.5
  MODULE.bazel
  WORKSPACE
Labels: bazel, backport-v3.10.x, backport-v3.11.x, backport-v3.12.x

#8991 Replace remaining direct calls to `rabbit_ff_registry`
  deps/rabbit/src/rabbit_deprecated_features.erl
  deps/rabbit/src/rabbit_feature_flags.erl
  deps/rabbit/src/rabbit_ff_controller.erl
  deps/rabbit/src/rabbit_ff_registry.erl
  deps/rabbit/src/rabbit_ff_registry_factory.erl
Labels: backport-v3.11.x, backport-v3.12.x

#8961 Remove Powershell as a backup to `handle.exe`
  deps/rabbitmq_management_agent/src/rabbit_mgmt_external_stats.erl
Labels: backport-v3.10.x, backport-v3.11.x, backport-v3.12.x

#9003 mqtt shared_SUITE: another case of a time dependent test
  deps/rabbitmq_mqtt/test/shared_SUITE.erl
Labels: backport-v3.12.x

#9006 rabbit_stream_queue_SUITE: Fix `consume_and_reject` channel close detection
  deps/rabbit/test/rabbit_stream_queue_SUITE.erl
  deps/rabbitmq_ct_client_helpers/src/rabbit_ct_client_helpers.erl
Labels: backport-v3.11.x, backport-v3.12.x

#9026 Fixes from the `khepri` branch
  deps/rabbit/src/rabbit.erl
  deps/rabbit/src/rabbit_db_cluster.erl
  deps/rabbit/src/rabbit_mnesia.erl
  deps/rabbit/src/rabbit_table.erl
  deps/rabbit/test/peer_discovery_classic_config_SUITE.erl
  deps/rabbit/test/per_vhost_connection_limit_SUITE.erl
  deps/rabbitmq_ct_helpers/src/rabbit_ct_broker_helpers.erl
  deps/rabbitmq_mqtt/test/reader_SUITE.erl
  deps/rabbitmq_mqtt/test/util.erl
Labels: backport-v3.12.x

#9040 Fix crash in MQTT reader
  deps/rabbitmq_mqtt/src/rabbit_mqtt_reader.erl
Labels: bug, backport-v3.12.x

#9034 Nack rejected messages to MQTT 5.0 client
  deps/rabbit/src/rabbit_confirms.erl
  deps/rabbit/test/rabbit_confirms_SUITE.erl
  deps/rabbitmq_mqtt/BUILD.bazel
  deps/rabbitmq_mqtt/app.bzl
  deps/rabbitmq_mqtt/src/rabbit_mqtt_confirms.erl
  deps/rabbitmq_mqtt/src/rabbit_mqtt_processor.erl
  deps/rabbitmq_mqtt/test/rabbit_mqtt_confirms_SUITE.erl
  deps/rabbitmq_mqtt/test/shared_SUITE.erl
Labels: bazel

#9055 Bump Osiris to 1.6.2, references #8616
  MODULE.bazel
  bazel/BUILD.osiris
  deps/rabbit/Makefile
  release-notes/3.12.1.md
Labels: bazel, make

#9063 Run bazel/make equivalence checks on all release branches
  .github/workflows/check-build-system-equivalence-release-branches.yaml
  .github/workflows/check-build-system-equivalence.yaml
Labels: backport-v3.11.x, backport-v3.12.x

#9069 Delete MQTT usage from rabbitmq_auth_mechanism_ssl
  deps/rabbitmq_auth_mechanism_ssl/README.md
Labels: backport-v3.10.x, backport-v3.11.x, backport-v3.12.x

#9052 Fixes 9043
  deps/rabbit/src/rabbit_auth_backend_internal.erl
  deps/rabbit/test/unit_access_control_SUITE.erl
  deps/rabbitmq_auth_backend_http/src/rabbit_auth_backend_http.erl
  deps/rabbitmq_auth_backend_http/test/auth_SUITE.erl
  deps/rabbitmq_auth_backend_ldap/src/rabbit_auth_backend_ldap.erl
  deps/rabbitmq_management/.gitignore
  deps/rabbitmq_management/selenium/Dockerfile
  deps/rabbitmq_management/selenium/amqp10-roundtriptest/pom.xml
  deps/rabbitmq_management/selenium/amqp10-roundtriptest/src/main/java/com/rabbitmq/amqp1_0/RoundTripTest.java
  deps/rabbitmq_management/selenium/bin/gen-advanced-config
  deps/rabbitmq_management/selenium/bin/suite_template
  deps/rabbitmq_management/selenium/package.json
  deps/rabbitmq_management/selenium/run-amqp10-roundtriptest
  deps/rabbitmq_management/selenium/suites/auth-cache-http-backends.sh
  deps/rabbitmq_management/selenium/suites/auth-cache-ldap-backends.sh
  deps/rabbitmq_management/selenium/suites/auth-http-backend.sh
  deps/rabbitmq_management/selenium/suites/auth-http-internal-backends-with-internal.sh
  deps/rabbitmq_management/selenium/suites/auth-http-internal-backends.sh
  deps/rabbitmq_management/selenium/suites/auth-internal-backend.sh
  deps/rabbitmq_management/selenium/suites/auth-internal-http-backends.sh
  deps/rabbitmq_management/selenium/suites/auth-ldap-backend.sh
  deps/rabbitmq_management/selenium/test/.env.docker
  deps/rabbitmq_management/selenium/test/.env.local
  deps/rabbitmq_management/selenium/test/authnz-msg-protocols/.env.auth-http.docker
  deps/rabbitmq_management/selenium/test/authnz-msg-protocols/.env.auth-http.local
  deps/rabbitmq_management/selenium/test/authnz-msg-protocols/.env.auth-ldap.docker
  deps/rabbitmq_management/selenium/test/authnz-msg-protocols/.env.auth-ldap.local
  deps/rabbitmq_management/selenium/test/authnz-msg-protocols/.env.http-user
  deps/rabbitmq_management/selenium/test/authnz-msg-protocols/.env.internal-user
  deps/rabbitmq_management/selenium/test/authnz-msg-protocols/.env.ldap-user
  deps/rabbitmq_management/selenium/test/authnz-msg-protocols/.env.local
  deps/rabbitmq_management/selenium/test/authnz-msg-protocols/advanced.auth-ldap.config
  deps/rabbitmq_management/selenium/test/authnz-msg-protocols/amqp10.js
  deps/rabbitmq_management/selenium/test/authnz-msg-protocols/enabled_plugins
  deps/rabbitmq_management/selenium/test/authnz-msg-protocols/imports/users.json
  deps/rabbitmq_management/selenium/test/authnz-msg-protocols/logging.conf
  deps/rabbitmq_management/selenium/test/authnz-msg-protocols/mock-auth-backend-http/expectationInitialiser.json
  deps/rabbitmq_management/selenium/test/authnz-msg-protocols/mock-auth-backend-ldap/import.ldif
  deps/rabbitmq_management/selenium/test/authnz-msg-protocols/rabbitmq.auth-http.conf
  deps/rabbitmq_management/selenium/test/authnz-msg-protocols/rabbitmq.auth-ldap.conf
  deps/rabbitmq_management/selenium/test/authnz-msg-protocols/rabbitmq.auth_backends-cache-http.conf
  deps/rabbitmq_management/selenium/test/authnz-msg-protocols/rabbitmq.auth_backends-cache-ldap.conf
  deps/rabbitmq_management/selenium/test/authnz-msg-protocols/rabbitmq.auth_backends-http-internal.conf
  deps/rabbitmq_management/selenium/test/authnz-msg-protocols/rabbitmq.auth_backends-http.conf
  deps/rabbitmq_management/selenium/test/authnz-msg-protocols/rabbitmq.auth_backends-internal-http.conf
  deps/rabbitmq_management/selenium/test/authnz-msg-protocols/rabbitmq.auth_backends-internal.conf
  deps/rabbitmq_management/selenium/test/authnz-msg-protocols/rabbitmq.auth_backends-ldap.conf
  deps/rabbitmq_management/selenium/test/authnz-msg-protocols/rabbitmq.conf
  deps/rabbitmq_management/selenium/test/basic-auth/.env.local
  deps/rabbitmq_management/selenium/test/basic-auth/rabbitmq.conf
  deps/rabbitmq_management/selenium/test/utils.js
Labels: bazel, make, backport-v3.11.x, backport-v3.12.x

#9073 Fix MQTT VHost mapping test
  deps/rabbitmq_ct_helpers/src/rabbit_ct_broker_helpers.erl
  deps/rabbitmq_mqtt/test/auth_SUITE.erl
Labels: backport-v3.11.x, backport-v3.12.x

#9066 Use latest rules_erlang
  MODULE.bazel
  WORKSPACE
  bazel/BUILD.cowboy
  bazel/BUILD.cowlib
  bazel/BUILD.ranch
Labels: bazel, backport-v3.10.x, backport-v3.11.x, backport-v3.12.x

#9083 Use osiris from Bazel Central Repository
  MODULE.bazel
  bazel/BUILD.osiris
Labels: bazel, backport-v3.10.x, backport-v3.11.x, backport-v3.12.x

#9095 Adopt otp 25.3.2.5
  MODULE.bazel
Labels: bazel, backport-v3.10.x, backport-v3.11.x, backport-v3.12.x

#9080 Add Prometheus metric for messages dropped by MQTT QoS 0 Queue
  deps/rabbit/include/rabbit_global_counters.hrl
  deps/rabbit/src/rabbit_global_counters.erl
  deps/rabbitmq_mqtt/src/rabbit_mqtt.erl
  deps/rabbitmq_mqtt/src/rabbit_mqtt_processor.erl
  deps/rabbitmq_mqtt/test/reader_SUITE.erl
  deps/rabbitmq_mqtt/test/v5_SUITE.erl
  deps/rabbitmq_prometheus/metrics.md
Labels: backport-v3.12.x

#9117 Bump emqtt
  MODULE.bazel
  deps/rabbitmq_auth_backend_oauth2/Makefile
  deps/rabbitmq_mqtt/Makefile
  deps/rabbitmq_web_mqtt/Makefile
Labels: bazel, make

#9122 Disallow empty password in MQTT
  deps/rabbitmq_mqtt/src/rabbit_mqtt_processor.erl
Labels: backport-v3.11.x, backport-v3.12.x

#9128 3.11.21 release notes
  release-notes/3.11.21.md
Labels: backport-v3.11.x, backport-v3.12.x

#9135 3.12.3 release notes
  release-notes/3.12.3.md
Labels: backport-v3.12.x

#9145 Use ra from bazel-central-registry
  MODULE.bazel
Labels: bazel, backport-v3.11.x, backport-v3.12.x

#9153 Remove the secondary otp and elixir definitions in WORKSPACE file
  WORKSPACE
Labels: backport-v3.10.x, backport-v3.11.x, backport-v3.12.x

#9151 Disable add/delete/shrink/grow QQ operations via HTTP api
  deps/rabbitmq_management/priv/schema/rabbitmq_management.schema
  deps/rabbitmq_management/src/rabbit_mgmt_features.erl
  deps/rabbitmq_management/src/rabbit_mgmt_wm_quorum_queue_replicas_add_member.erl
  deps/rabbitmq_management/src/rabbit_mgmt_wm_quorum_queue_replicas_delete_member.erl
  deps/rabbitmq_management/src/rabbit_mgmt_wm_quorum_queue_replicas_grow.erl
  deps/rabbitmq_management/src/rabbit_mgmt_wm_quorum_queue_replicas_shrink.erl
  deps/rabbitmq_management/test/rabbit_mgmt_http_SUITE.erl
Labels: backport-v3.11.x, backport-v3.12.x

#9158 QQ: fix bug when subscribing using an already existing consumer tag
  deps/rabbit/src/rabbit_fifo.erl
  deps/rabbit/src/rabbit_fifo_client.erl
  deps/rabbit/test/quorum_queue_SUITE.erl
  deps/rabbit/test/rabbit_fifo_SUITE.erl
Labels: backport-v3.11.x, backport-v3.12.x

#9149 Fix issue 9059
  deps/rabbitmq_auth_backend_ldap/src/rabbit_auth_backend_ldap.erl
  deps/rabbitmq_auth_backend_ldap/test/unit_SUITE.erl
Labels: backport-v3.11.x, backport-v3.12.x

#9165 rabbit_stream_queue: Only update leader PID on stream_leader_change event
  deps/rabbit/src/rabbit_stream_queue.erl
Labels: backport-v3.11.x, backport-v3.12.x

#9176 3.12.4 release notes
  release-notes/3.12.4.md
Labels: backport-v3.12.x

#9180 3.12.4 release notes updates
  release-notes/3.12.4.md
Labels: backport-v3.12.x

#9183 3.11.22 release notes
  release-notes/3.11.22.md
Labels: backport-v3.11.x, backport-v3.12.x

#9199 Gazelle: ignore test deps fetched by make
  BUILD.bazel
Labels: bazel, backport-v3.10.x, backport-v3.11.x, backport-v3.12.x

#9190 Minor spec correction
  deps/rabbit/src/rabbit_mirror_queue_misc.erl
  deps/rabbit/src/rabbit_mirror_queue_slave.erl
Labels: backport-v3.11.x, backport-v3.12.x

#9217 rabbit_autoheal: handle request_start in not_healing state
  deps/rabbit/src/rabbit_autoheal.erl
Labels: backport-v3.11.x, backport-v3.12.x

#9221 QQ: remove machine version 0 check in rabbit_fifo_client
  deps/rabbit/src/rabbit_fifo_client.erl
Labels: backport-v3.11.x, backport-v3.12.x

#9238 confirms_rejects_SUITE: replace timer:sleep by wait for conditions
  deps/rabbit/app.bzl
  deps/rabbit/test/confirms_rejects_SUITE.erl
Labels: bazel, backport-v3.12.x

#9233 feature_flags_SUITE: wait for cluster status instead of a fixed time
  deps/rabbit/BUILD.bazel
  deps/rabbit/app.bzl
  deps/rabbit/test/clustering_management_SUITE.erl
  deps/rabbit/test/clustering_utils.erl
  deps/rabbit/test/feature_flags_SUITE.erl
Labels: bazel, backport-v3.12.x

#9228 Adjust the node uri in //deps/rabbitmq_amqp1_0:system_SUITE
  deps/rabbitmq_amqp1_0/BUILD.bazel
  deps/rabbitmq_amqp1_0/test/system_SUITE.erl
Labels: bazel, backport-v3.10.x, backport-v3.11.x, backport-v3.12.x

#9241 Use ra_leaderboard when initialising quorum queue client.
  deps/rabbit/src/rabbit_fifo_client.erl
  deps/rabbit/src/rabbit_quorum_queue.erl
Labels: backport-v3.11.x, backport-v3.12.x

#9248 Add the peek command to the manpage
  deps/rabbit/docs/rabbitmq-queues.8
Labels: backport-v3.11.x, backport-v3.12.x
