Repository rabbitmq/rabbitmq-server, pull requests merged in 2023-10, with the labels that each got.

#9622 formatting of log message for deprecated features
  deps/rabbit/src/rabbit_deprecated_features.erl
Labels: backport-v3.12.x

#9628 Increase the erpc timeout when starting a QQ cluster.
  deps/rabbit/src/rabbit_quorum_queue.erl
Labels: backport-v3.11.x, backport-v3.12.x

#9162 Add new QQ members as non-voters
  deps/rabbit/BUILD.bazel
  deps/rabbit/app.bzl
  deps/rabbit/src/rabbit_observer_cli_quorum_queues.erl
  deps/rabbit/src/rabbit_quorum_queue.erl
  deps/rabbit/test/quorum_queue_SUITE.erl
  deps/rabbit/test/unit_quorum_queue_SUITE.erl
  deps/rabbitmq_cli/lib/rabbitmq/cli/queues/commands/add_member_command.ex
  deps/rabbitmq_cli/lib/rabbitmq/cli/queues/commands/grow_command.ex
  deps/rabbitmq_cli/test/queues/add_member_command_test.exs
  deps/rabbitmq_cli/test/queues/grow_command_test.exs
  deps/rabbitmq_management/src/rabbit_mgmt_wm_quorum_queue_replicas_add_member.erl
  deps/rabbitmq_management/src/rabbit_mgmt_wm_quorum_queue_replicas_grow.erl
Labels: bazel

#9640 Improve rabbit_stream_queue:get_local_pid/1
  deps/rabbit/src/rabbit_stream_queue.erl
Labels: backport-v3.11.x, backport-v3.12.x

#9650 Support queue length limit overflow behavior in operator policies
  deps/rabbit/src/rabbit_policies.erl
  deps/rabbit/test/policy_SUITE.erl
  deps/rabbitmq_management/priv/www/js/tmpl/policies.ejs
Labels: backport-v3.12.x

#9639 Add overflow as operpolicy
  deps/rabbit/src/rabbit_policies.erl
  deps/rabbit/test/policy_SUITE.erl
Labels: backport-v3.12.x

#9651 bazel run gazelle
  deps/rabbit/app.bzl
Labels: bazel

#9654 Web-MQTT: don't call FHC when connection terminates early
  deps/rabbitmq_web_mqtt/src/rabbit_web_mqtt_handler.erl
Labels: backport-v3.11.x, backport-v3.12.x

#9663 Prevent node monitor crashing from doing multiple node disconnects in unstable networks
  deps/rabbit/src/rabbit_node_monitor.erl
Labels: backport-v3.11.x, backport-v3.12.x

#9642 Add command and REST endpoint to list stream tracking info
  deps/rabbitmq_stream/app.bzl
  deps/rabbitmq_stream/src/Elixir.RabbitMQ.CLI.Ctl.Commands.ListStreamTrackingCommand.erl
  deps/rabbitmq_stream/test/commands_SUITE.erl
  deps/rabbitmq_stream/test/rabbit_stream_SUITE.erl
  deps/rabbitmq_stream_management/app.bzl
  deps/rabbitmq_stream_management/src/rabbit_stream_tracking_mgmt.erl
  deps/rabbitmq_stream_management/test/http_SUITE_data/.mvn/wrapper/MavenWrapperDownloader.java
  deps/rabbitmq_stream_management/test/http_SUITE_data/.mvn/wrapper/maven-wrapper.jar
  deps/rabbitmq_stream_management/test/http_SUITE_data/.mvn/wrapper/maven-wrapper.properties
  deps/rabbitmq_stream_management/test/http_SUITE_data/mvnw
  deps/rabbitmq_stream_management/test/http_SUITE_data/mvnw.cmd
  deps/rabbitmq_stream_management/test/http_SUITE_data/pom.xml
  deps/rabbitmq_stream_management/test/http_SUITE_data/src/test/java/com/rabbitmq/stream/HttpTest.java
Labels: bazel

#9670 Fix list_stream_consumer_groups validation
  deps/rabbitmq_stream/src/Elixir.RabbitMQ.CLI.Ctl.Commands.ListStreamConsumerGroupsCommand.erl
  deps/rabbitmq_stream/test/commands_SUITE.erl
Labels: bug, backport-v3.11.x, backport-v3.12.x

#9669 CLI: support for pre-hashed passwords
  deps/rabbit/src/rabbit_auth_backend_internal.erl
  deps/rabbitmq_cli/lib/rabbitmq/cli/core/doc_guide.ex
  deps/rabbitmq_cli/lib/rabbitmq/cli/ctl/commands/add_user_command.ex
  deps/rabbitmq_cli/test/ctl/add_user_command_test.exs
Labels: backport-v3.12.x

#9633 Return storage_version as top-level key in queue objects
  deps/rabbit/src/rabbit_amqqueue_process.erl
  deps/rabbitmq_management/priv/www/js/formatters.js
  deps/rabbitmq_management/test/rabbit_mgmt_http_SUITE.erl
  deps/rabbitmq_management_agent/src/rabbit_mgmt_format.erl
Labels: backport-v3.12.x

#9675 bazel run gazelle
  deps/rabbitmq_stream_management/BUILD.bazel
  moduleindex.yaml
Labels: bazel

#9678 Osiris v1.6.8
  MODULE.bazel
  deps/rabbit/Makefile
  deps/rabbit/src/rabbit_stream_queue.erl
Labels: bazel, make, backport-v3.12.x

#9687 Update 3.12.7 release notes
  release-notes/3.12.7.md
Labels: backport-v3.12.x

#9693 Adopt otp 26.1.2
  MODULE.bazel
  WORKSPACE
Labels: bazel, backport-v3.12.x

#9692 Adopt otp 25.3.2.7
  MODULE.bazel
  WORKSPACE
Labels: bazel, backport-v3.10.x, backport-v3.11.x, backport-v3.12.x

#9698 Osiris v1.6.9
  MODULE.bazel
  deps/rabbit/Makefile
Labels: bazel, make, backport-v3.12.x

#9700 Adopt otp 24.3.4.14
  MODULE.bazel
  WORKSPACE
Labels: bazel

#9701 Adopt elixir 1.15.7
  MODULE.bazel
Labels: bazel, backport-v3.10.x, backport-v3.11.x, backport-v3.12.x

#9706 Fixup bazel/make divergence
  MODULE.bazel
  deps/rabbit/Makefile
  deps/rabbitmq_consistent_hash_exchange/Makefile
  deps/rabbitmq_jms_topic_exchange/Makefile
  deps/rabbitmq_management/BUILD.bazel
  deps/rabbitmq_management_agent/BUILD.bazel
  deps/rabbitmq_recent_history_exchange/Makefile
  deps/rabbitmq_stream_management/Makefile
  rabbitmq-components.mk
Labels: bazel, make

#9708 Introduce a configurable limit to HTTP API request body size
  deps/rabbitmq_management/BUILD.bazel
  deps/rabbitmq_management/Makefile
  deps/rabbitmq_management/include/rabbit_mgmt.hrl
  deps/rabbitmq_management/priv/schema/rabbitmq_management.schema
  deps/rabbitmq_management/src/rabbit_mgmt_util.erl
  deps/rabbitmq_management/src/rabbit_mgmt_wm_definitions.erl
  deps/rabbitmq_management/test/rabbit_mgmt_http_SUITE.erl
Labels: bazel, make, backport-v3.11.x, backport-v3.12.x

#9717 3.11.24 release notes
  release-notes/3.11.24.md
Labels: backport-v3.11.x, backport-v3.12.x

#9715 Actually nack when using 'Nack message requeue true'
  deps/rabbitmq_management/src/rabbit_mgmt_wm_queue_get.erl
Labels: backport-v3.11.x, backport-v3.12.x

#9735 Use 3.9.29 for mixed version tests
  .github/workflows/test-mixed-versions.yaml
  bazel/bzlmod/secondary_umbrella.bzl
Labels: bazel

#9737 rabbitmq.conf: restrict raft.segment_max_entries to [1; (u16 max value -1)]
  deps/rabbit/priv/schema/rabbit.schema
  deps/rabbit/test/config_schema_SUITE_data/rabbit.snippets
Labels: backport-v3.11.x, backport-v3.12.x

#9742 Update rules_erlang version in WORKSPACE to match MODULE.bazel
  WORKSPACE
Labels: backport-v3.10.x, backport-v3.11.x, backport-v3.12.x

#9741 v3.9.x use rules erlang 3.13.1
  .bazelrc
  MODULE.bazel
  WORKSPACE
  rabbitmq.bzl
Labels: bazel

#9751 Add missing dep for //deps/rabbitmq_aws:eunit
  deps/rabbitmq_aws/BUILD.bazel
Labels: bazel

#9750 bazel run gazelle
  deps/rabbit/BUILD.bazel
Labels: bazel

#9763 AMQP 1.0 client connection: implement format_status/1
  deps/amqp10_client/src/amqp10_client_connection.erl
Labels: backport-v3.11.x, backport-v3.12.x

#9768 Optimise rabbit_registry:binary_to_type/1
  deps/rabbit_common/src/rabbit_registry.erl
Labels: backport-v3.11.x, backport-v3.12.x

#9767 AMQP 1.0 Erlang client: integrate credentials_obfuscation
  deps/amqp10_client/BUILD.bazel
  deps/amqp10_client/Makefile
  deps/amqp10_client/src/amqp10_client.erl
  deps/amqp10_client/src/amqp10_client_connection.erl
Labels: bazel, make, backport-v3.11.x, backport-v3.12.x

#9790 Fix a file descriptor leak in an aux command handler
  deps/rabbit/src/rabbit_fifo.erl
Labels: backport-v3.11.x, backport-v3.12.x

#9785 Speed up shovel start
  deps/rabbitmq_shovel/src/rabbit_shovel_dyn_worker_sup_sup.erl
Labels: backport-v3.11.x, backport-v3.12.x

#9794 Fix quorum queue open files info
  deps/rabbit/src/rabbit_quorum_queue.erl
Labels: backport-v3.11.x, backport-v3.12.x

#9811 Skip some assertions in mixed version tests
  deps/rabbitmq_mqtt/BUILD.bazel
  deps/rabbitmq_mqtt/test/cluster_SUITE.erl
  deps/rabbitmq_mqtt/test/shared_SUITE.erl
Labels: bazel

#9769 Upgrade khepri_mnesia_migration from 0.1.1 to 0.2.1
  MODULE.bazel
  rabbitmq-components.mk
Labels: bazel, make

#9822 3.12.8 release notes
  release-notes/3.12.8.md
Labels: backport-v3.12.x

#9824 3.11.25 release notes
  release-notes/3.11.25.md
Labels: backport-v3.11.x, backport-v3.12.x

#9802 Khepri migration: match expected records
  deps/rabbit/app.bzl
  deps/rabbit/include/internal_user.hrl
  deps/rabbit/src/rabbit_db_exchange_m2k_converter.erl
  deps/rabbit/src/rabbit_db_maintenance_m2k_converter.erl
  deps/rabbit/src/rabbit_db_queue_m2k_converter.erl
  deps/rabbit/src/rabbit_db_user_m2k_converter.erl
  deps/rabbit/src/rabbit_db_vhost_m2k_converter.erl
Labels: bazel

#9835 Selenium: fix an issue in run-scripts
  deps/rabbitmq_management/selenium/package.json
  deps/rabbitmq_management/selenium/run-suites.sh
  deps/rabbitmq_management/selenium/test/oauth/with-sp-initiated/logout.js
  deps/rabbitmq_management/selenium/test/pageobjects/BasePage.js
  deps/rabbitmq_management/selenium/test/pageobjects/SSOHomePage.js
  deps/rabbitmq_management/selenium/test/utils.js
Labels: backport-v3.11.x, backport-v3.12.x
