Repository rabbitmq/rabbitmq-server, pull requests merged in 2023-06, with the labels that each got.

#8439 Add `bazel run rabbitmq-upgrade`
  BUILD.bazel
Labels: bazel, backport-v3.10.x, backport-v3.11.x, backport-v3.12.x

#8448 Bump CSV to 3.0.5 in erlang.mk
  deps/rabbitmq_cli/Makefile
Labels: make, backport-v3.11.x, backport-v3.12.x

#8454 Update 3.12.0 release notes
  release-notes/3.12.0.md
Labels: backport-v3.12.x

#8453 Handle missing delivery marker in CQ v1 index
  deps/rabbit/BUILD.bazel
  deps/rabbit/src/rabbit_queue_index.erl
  deps/rabbit/test/classic_queue_prop_SUITE.erl
Labels: bazel, backport-v3.10.x, backport-v3.11.x, backport-v3.12.x

#8462 Remove '\n' from Access refused stomp log.
  deps/rabbitmq_stomp/src/rabbit_stomp_processor.erl
  deps/rabbitmq_stomp/test/python_SUITE_data/src/connect_disconnect.py
  deps/rabbitmq_web_stomp/test/cowboy_websocket_SUITE.erl
Labels: rabbitmq-stomp, backport-v3.10.x, backport-v3.11.x, backport-v3.12.x

#8466 3.11.18 release notes
  release-notes/3.11.18.md
Labels: backport-v3.11.x, backport-v3.12.x

#8469 3.10.24 release notes
  release-notes/3.10.24.md
Labels: backport-v3.10.x, backport-v3.11.x, backport-v3.12.x

#8473 3.12.1 release notes
  release-notes/3.12.1.md
Labels: backport-v3.12.x

#8463 Bump stomp.py to v8.1.0.
  deps/rabbitmq_stomp/test/python_SUITE.erl
  deps/rabbitmq_stomp/test/python_SUITE_data/deps/pika/Makefile
  deps/rabbitmq_stomp/test/python_SUITE_data/deps/stomppy/Makefile
  deps/rabbitmq_stomp/test/python_SUITE_data/src/main_runner.py
  deps/rabbitmq_stomp/test/python_SUITE_data/src/test_runner.py
  deps/rabbitmq_stomp/test/python_SUITE_data/src/tls_connect_disconnect.py
  deps/rabbitmq_stomp/test/python_SUITE_data/src/tls_runner.py
Labels: rabbitmq-stomp, make, backport-v3.10.x, backport-v3.11.x, backport-v3.12.x

#8483 Fix /api/connections/username/{username} internal errors
  deps/rabbitmq_management/src/rabbit_mgmt_wm_connection_user_name.erl
Labels: backport-v3.11.x, backport-v3.12.x

#8488 Fix SASL external authentication in stream plugin
  deps/rabbitmq_stream/src/rabbit_stream_reader.erl
Labels: bug, backport-v3.10.x, backport-v3.11.x, backport-v3.12.x

#8499 Adopt otp 25.3.2.2
  MODULE.bazel
  WORKSPACE
Labels: bazel, backport-v3.10.x, backport-v3.11.x, backport-v3.12.x

#8513 Add a shorthand for the OAuth 2 authN/authZ backend
  deps/rabbit/priv/schema/rabbit.schema
  deps/rabbit/test/config_schema_SUITE_data/rabbit.snippets
Labels: backport-v3.10.x, backport-v3.11.x

#8523 Don't fail with a 500 when virtual host or user do not exist
  deps/rabbitmq_management/src/rabbit_mgmt_util.erl
  deps/rabbitmq_management/src/rabbit_mgmt_wm_limit.erl
  deps/rabbitmq_management/src/rabbit_mgmt_wm_user_limit.erl
Labels: backport-v3.12.x

#8520 Rename a couple of management UI tabs
  deps/rabbitmq_management/priv/www/js/global.js
  deps/rabbitmq_management/priv/www/js/main.js
  deps/rabbitmq_management/selenium/test/basic-auth/ac-administrator-without-vhost-permissions.js
  deps/rabbitmq_management/selenium/test/basic-auth/ac-management-without-vhost-permissions.js
  deps/rabbitmq_management/selenium/test/basic-auth/ac-monitoring-without-vhost-permissions.js
  deps/rabbitmq_management/selenium/test/pageobjects/BasePage.js
  deps/rabbitmq_stream_management/priv/www/js/stream.js
Labels: backport-v3.11.x, backport-v3.12.x

#8529 Remove the buildbuddy toolchain from the workspace
  WORKSPACE
Labels: backport-v3.10.x, backport-v3.11.x, backport-v3.12.x

#8542 HTTP API: introduce a number of endpoints for QQ replica management
  deps/rabbit/src/rabbit_quorum_queue.erl
  deps/rabbitmq_ct_helpers/include/rabbit_mgmt_test.hrl
  deps/rabbitmq_ct_helpers/src/rabbit_mgmt_test_util.erl
  deps/rabbitmq_management/app.bzl
  deps/rabbitmq_management/src/rabbit_mgmt_dispatcher.erl
  deps/rabbitmq_management/src/rabbit_mgmt_util.erl
  deps/rabbitmq_management/src/rabbit_mgmt_wm_quorum_queue_replicas_add_member.erl
  deps/rabbitmq_management/src/rabbit_mgmt_wm_quorum_queue_replicas_delete_member.erl
  deps/rabbitmq_management/src/rabbit_mgmt_wm_quorum_queue_replicas_grow.erl
  deps/rabbitmq_management/src/rabbit_mgmt_wm_quorum_queue_replicas_shrink.erl
  deps/rabbitmq_management/test/clustering_SUITE.erl
  moduleindex.yaml
Labels: bazel, backport-v3.11.x, backport-v3.12.x

#8506 Adopt otp 26.0.1
  MODULE.bazel
  WORKSPACE
Labels: bazel, backport-v3.11.x, backport-v3.12.x

#8548 Fixes #8547
  deps/rabbit/src/rabbit_access_control.erl
  deps/rabbitmq_auth_backend_oauth2/src/uaa_jwks.erl
  deps/rabbitmq_auth_backend_oauth2/src/uaa_jwt.erl
  deps/rabbitmq_auth_backend_oauth2/test/unit_SUITE.erl
  deps/rabbitmq_management/selenium/bin/suite_template
  deps/rabbitmq_management/selenium/package.json
  deps/rabbitmq_management/selenium/suites/oauth-with-keycloak.sh
  deps/rabbitmq_management/selenium/test/oauth/.env.docker.keycloak
  deps/rabbitmq_management/selenium/test/oauth/.env.local.keycloak
  deps/rabbitmq_management/selenium/test/oauth/enabled_plugins
  deps/rabbitmq_management/selenium/test/oauth/keycloak/ca_certificate.pem
  deps/rabbitmq_management/selenium/test/oauth/keycloak/server_localhost_certificate.pem
  deps/rabbitmq_management/selenium/test/oauth/keycloak/server_localhost_key.pem
  deps/rabbitmq_management/selenium/test/oauth/rabbitmq.conf
  deps/rabbitmq_management/selenium/test/oauth/rabbitmq.jwks.conf
  deps/rabbitmq_management/selenium/test/oauth/rabbitmq.uaa.conf
  deps/rabbitmq_management/selenium/test/utils.js
Labels: backport-v3.11.x, backport-v3.12.x

#8555 bazel {start,stop}-cluster: allow node index ranges for more control
  scripts/bazel/rabbitmq-run.sh
Labels: backport-v3.10.x, backport-v3.11.x, backport-v3.12.x

#8565 Use OpenSSL 3.1.1 for //packaging/docker-image:rabbitmq
  WORKSPACE
  packaging/docker-image/BUILD.bazel
  packaging/docker-image/build_install_openssl.sh
  packaging/docker-image/build_install_otp.sh
  packaging/docker-image/test_configs/openssl_ubuntu.yaml
Labels: bazel

#8579 Display node maintenance status in the UI
  deps/rabbitmq_management/priv/www/js/tmpl/node.ejs
  deps/rabbitmq_management/priv/www/js/tmpl/overview.ejs
  deps/rabbitmq_management/src/rabbit_mgmt_wm_node.erl
  deps/rabbitmq_management/src/rabbit_mgmt_wm_nodes.erl
Labels: backport-v3.11.x, backport-v3.12.x

#8584 Use 3.11.18 for the secondary umbrella
  bazel/bzlmod/secondary_umbrella.bzl
Labels: bazel, backport-v3.12.x

#8591 Quorum queues: handle_tick bugfix
  deps/rabbit/src/rabbit_fifo.erl
  deps/rabbit/src/rabbit_quorum_queue.erl
Labels: bug, backport-v3.11.x, backport-v3.12.x

#8595 Closes #8564
  deps/rabbit/src/rabbit_amqqueue.erl
Labels: backport-v3.10.x, backport-v3.11.x, backport-v3.12.x

#8597 Drop a particularly flaky CMQ test
  deps/rabbit/BUILD.bazel
  deps/rabbit/test/clustering_management_SUITE.erl
Labels: bazel, backport-v3.11.x, backport-v3.12.x

#8602 Ra 2.6.2
  MODULE.bazel
  rabbitmq-components.mk
Labels: bazel, make, backport-v3.11.x, backport-v3.12.x

#8606 Update 3.12.1 release notes
  release-notes/3.12.1.md
Labels: backport-v3.12.x

#8616 Osiris v1.6.0
  MODULE.bazel
  deps/rabbit/Makefile
Labels: bazel, make, backport-v3.11.x, backport-v3.12.x

#8615 Make the extension of :package-generic-unix configurable in bazel
  dist.bzl
Labels: bazel, backport-v3.10.x, backport-v3.11.x, backport-v3.12.x

#8627 3.12.1 release notes updates
  release-notes/3.12.1.md
Labels: backport-v3.12.x

#8630 Add log message during quorum queue recovery
  deps/rabbit/src/rabbit_quorum_queue.erl
Labels: backport-v3.11.x, backport-v3.12.x

#8629 Fix classic queue declaration crash
  deps/rabbit/src/rabbit_classic_queue.erl
Labels: bug, backport-v3.10.x, backport-v3.11.x, backport-v3.12.x

#8636 List #8629 and #8630 in 3.11.19 release notes
  release-notes/3.11.19.md
Labels: backport-v3.11.x, backport-v3.12.x

#8643 Test resilience
  deps/rabbit/app.bzl
  deps/rabbit/test/per_vhost_msg_store_SUITE.erl
  deps/rabbit/test/quorum_queue_SUITE.erl
  deps/rabbitmq_recent_history_exchange/app.bzl
  deps/rabbitmq_recent_history_exchange/test/system_SUITE.erl
Labels: bazel, backport-v3.11.x, backport-v3.12.x

#8647 bazel run gazelle
  deps/rabbitmq_mqtt/BUILD.bazel
Labels: bazel

#8664 Add support for LOCAL proxy header
  deps/rabbit/test/proxy_protocol_SUITE.erl
  deps/rabbit_common/src/rabbit_net.erl
  deps/rabbitmq_amqp1_0/test/proxy_protocol_SUITE.erl
  deps/rabbitmq_mqtt/test/proxy_protocol_SUITE.erl
  deps/rabbitmq_stomp/test/proxy_protocol_SUITE.erl
  deps/rabbitmq_web_mqtt/test/proxy_protocol_SUITE.erl
  deps/rabbitmq_web_stomp/test/proxy_protocol_SUITE.erl
Labels: backport-v3.11.x, backport-v3.12.x

#8653 Avoid secondary umbrella archive collisions in actions
  .github/workflows/test-mixed-versions.yaml
  bazel/bzlmod/secondary_umbrella.bzl
Labels: bazel, backport-v3.10.x, backport-v3.11.x, backport-v3.12.x

#8671 Update 3.12.1 release notes
  release-notes/3.12.1.md
Labels: backport-v3.12.x

#8673 Update 3.11.19 release notes
  release-notes/3.11.19.md
Labels: backport-v3.11.x, backport-v3.12.x

#8661 (Opt-in) Prometheus scraping endpoint authentication
  deps/rabbitmq_management/BUILD.bazel
  deps/rabbitmq_management/app.bzl
  deps/rabbitmq_management/src/rabbit_mgmt_util.erl
  deps/rabbitmq_management_agent/BUILD.bazel
  deps/rabbitmq_management_agent/app.bzl
  deps/rabbitmq_management_agent/include/rabbit_mgmt_records.hrl
  deps/rabbitmq_prometheus/app.bzl
  deps/rabbitmq_prometheus/priv/schema/rabbitmq_prometheus.schema
  deps/rabbitmq_prometheus/src/rabbit_prometheus_handler.erl
  deps/rabbitmq_prometheus/test/config_schema_SUITE_data/rabbitmq_prometheus.snippets
  deps/rabbitmq_prometheus/test/rabbit_prometheus_http_SUITE.erl
  deps/rabbitmq_web_dispatch/BUILD.bazel
  deps/rabbitmq_web_dispatch/app.bzl
  deps/rabbitmq_web_dispatch/include/rabbitmq_web_dispatch_records.hrl
  deps/rabbitmq_web_dispatch/src/rabbit_web_dispatch_access_control.erl
  moduleindex.yaml
Labels: bazel, backport-v3.11.x, backport-v3.12.x

#8685 Backport #8661 to v3.11.x
  deps/rabbitmq_management/BUILD.bazel
  deps/rabbitmq_management/app.bzl
  deps/rabbitmq_management/src/rabbit_mgmt_util.erl
  deps/rabbitmq_management_agent/BUILD.bazel
  deps/rabbitmq_management_agent/app.bzl
  deps/rabbitmq_management_agent/include/rabbit_mgmt_records.hrl
  deps/rabbitmq_prometheus/app.bzl
  deps/rabbitmq_prometheus/priv/schema/rabbitmq_prometheus.schema
  deps/rabbitmq_prometheus/src/rabbit_prometheus_handler.erl
  deps/rabbitmq_prometheus/test/config_schema_SUITE_data/rabbitmq_prometheus.snippets
  deps/rabbitmq_prometheus/test/rabbit_prometheus_http_SUITE.erl
  deps/rabbitmq_web_dispatch/BUILD.bazel
  deps/rabbitmq_web_dispatch/app.bzl
  deps/rabbitmq_web_dispatch/include/rabbitmq_web_dispatch_records.hrl
  deps/rabbitmq_web_dispatch/src/rabbit_web_dispatch_access_control.erl
  moduleindex.yaml
Labels: bazel

#8686 Include error reason in shovel log
  deps/rabbitmq_shovel/src/rabbit_shovel_worker.erl
Labels: backport-v3.11.x, backport-v3.12.x

#8697 Gracefully close shovel if destination exchange does not exist (#8692 with some cosmetic changes)
  deps/rabbitmq_shovel/src/rabbit_amqp091_shovel.erl
  deps/rabbitmq_shovel/src/rabbit_amqp10_shovel.erl
  deps/rabbitmq_shovel/test/dynamic_SUITE.erl
Labels: backport-v3.10.x, backport-v3.11.x, backport-v3.12.x

#8698 adopt OTP 26.0.2
  MODULE.bazel
  WORKSPACE
Labels: bazel, backport-v3.11.x, backport-v3.12.x

#8706 Revamp java test projects
  .github/dependabot.yaml
  deps/rabbitmq_amqp1_0/test/system_SUITE_data/java-tests/pom.xml
  deps/rabbitmq_amqp1_0/test/system_SUITE_data/java-tests/src/test/java/com/rabbitmq/amqp1_0/tests/jms/RoundTripTest.java
  deps/rabbitmq_amqp1_0/test/system_SUITE_data/java-tests/src/test/resources/logback-test.xml
  deps/rabbitmq_auth_backend_http/examples/rabbitmq_auth_backend_spring_boot/pom.xml
  deps/rabbitmq_auth_backend_http/examples/rabbitmq_auth_backend_spring_boot/src/test/java/com/rabbitmq/examples/AuthBackendHttpControllerTest.java
  deps/rabbitmq_auth_backend_http/examples/rabbitmq_auth_backend_spring_boot_kotlin/pom.xml
  deps/rabbitmq_mqtt/test/java_SUITE_data/pom.xml
  deps/rabbitmq_mqtt/test/java_SUITE_data/src/test/resources/logback-test.xml
  deps/rabbitmq_stream/test/rabbit_stream_SUITE_data/pom.xml
  deps/rabbitmq_stream_management/test/http_SUITE_data/pom.xml
Labels: backport-v3.11.x, backport-v3.12.x
