Repository rabbitmq/rabbitmq-server, pull requests merged in 2024-02, with the labels that each got.

#10458 CLI: allow building with Elixir 1.17
  deps/rabbitmq_cli/mix.exs
Labels: backport-v3.11.x, backport-v3.12.x

#10457 Check whether EPMD is running before starting it
  deps/rabbit_common/src/rabbit_nodes_common.erl
Labels: backport-v3.11.x, backport-v3.12.x

#10459 Resolve CLI elixirc warnings
  deps/rabbitmq_cli/BUILD.bazel
  deps/rabbitmq_cli/lib/rabbitmq/cli/core/command_modules.ex
  deps/rabbitmq_cli/lib/rabbitmq/cli/ctl/commands/add_user_command.ex
  deps/rabbitmq_cli/lib/rabbitmq/cli/ctl/commands/force_standalone_khepri_boot.ex
  deps/rabbitmq_cli/lib/rabbitmq/cli/ctl/commands/forget_cluster_node_command.ex
  deps/rabbitmq_cli/lib/rabbitmq/cli/ctl/commands/join_cluster_command.ex
  deps/rabbitmq_cli/lib/rabbitmq/cli/ctl/commands/rename_cluster_node_command.ex
  deps/rabbitmq_cli/lib/rabbitmq/cli/ctl/commands/update_cluster_nodes_command.ex
  deps/rabbitmq_cli/lib/rabbitmq/cli/diagnostics/commands/check_if_any_deprecated_features_are_used_command.ex
  deps/rabbitmq_cli/lib/rabbitmq/cli/diagnostics/commands/list_policies_that_match.ex
  deps/rabbitmq_cli/lib/rabbitmq/cli/diagnostics/commands/metadata_store_status_command.ex
  deps/rabbitmq_cli/lib/rabbitmq/cli/diagnostics/commands/remote_shell_command.ex
  deps/rabbitmq_cli/lib/rabbitmq/cli/streams/commands/coordinator_status_command.ex
  deps/rabbitmq_cli/rabbitmqctl_compile_warnings_as_errors.bzl
Labels: bazel, backport-v3.12.x

#10476 Rework consumer sample deletion when a channel is closed
  deps/rabbit/src/rabbit_channel.erl
  deps/rabbitmq_management_agent/src/rabbit_mgmt_metrics_gc.erl
Labels: backport-v3.12.x

#10508 Add man doc for the rabbitmq-streams restart_stream command.
  deps/rabbit/docs/rabbitmq-streams.8
Labels: backport-v3.12.x

#10512 Log message in case of stream publisher declaration failure
  deps/rabbitmq_stream/src/rabbit_stream_reader.erl
Labels: backport-v3.11.x, backport-v3.12.x

#10523 Ra 2.9.1
  MODULE.bazel
  rabbitmq-components.mk
Labels: bazel, make

#10520 Adopt otp 26.2.2
  MODULE.bazel
  WORKSPACE
Labels: bazel, backport-v3.12.x

#10528 Adopt otp 25.3.2.9
  MODULE.bazel
  WORKSPACE
Labels: bazel, backport-v3.11.x, backport-v3.12.x

#10537 Bump Khepri from 0.11.0 to 0.12.0
  MODULE.bazel
  rabbitmq-components.mk
Labels: bazel, make

#10546 bazel run gazelle with edits to reduce the noise around (the generated) OAuth 2 dependency lists
  deps/oauth2_client/BUILD.bazel
  deps/oauth2_client/app.bzl
  deps/rabbitmq_auth_backend_oauth2/BUILD.bazel
  deps/rabbitmq_auth_backend_oauth2/app.bzl
  deps/rabbitmq_cli/BUILD.bazel
  deps/rabbitmq_management/BUILD.bazel
  deps/rabbitmq_management/app.bzl
  deps/rabbitmq_shovel/BUILD.bazel
  moduleindex.yaml
Labels: bazel

#10547 rabbit_pbe: minor API improvements
  deps/rabbit_common/src/rabbit_pbe.erl
Labels: backport-v3.12.x

#10561 3.12.13 release notes
  release-notes/3.12.13.md
Labels: backport-v3.12.x

#10568 Fix AMQP 1.0 -> AMQP 0.9.1 durability conversion
  deps/rabbitmq_amqp1_0/src/rabbit_amqp1_0_message.erl
  deps/rabbitmq_amqp1_0/test/amqp10_client_SUITE.erl
Labels: bug, backport-v3.11.x

#10567 Parse 2 bytes encoded AMQP boolean to Erlang boolean
  deps/amqp10_common/src/amqp10_binary_parser.erl
  deps/amqp10_common/test/binary_generator_SUITE.erl
  deps/amqp10_common/test/binary_parser_SUITE.erl
  deps/rabbit/src/mc_amqp.erl
  deps/rabbit/test/mc_unit_SUITE.erl
  deps/rabbitmq_amqp1_0/src/rabbit_amqp1_0_message.erl
  deps/rabbitmq_amqp1_0/test/amqp10_client_SUITE.erl
  deps/rabbitmq_mqtt/src/mc_mqtt.erl
  deps/rabbitmq_mqtt/test/mc_mqtt_SUITE.erl
  deps/rabbitmq_mqtt/test/protocol_interop_SUITE.erl
Labels: bug

#10577 Add gazelle directive to stabilize bazel run gazelle
  deps/rabbitmq_auth_backend_oauth2/BUILD.bazel
  deps/rabbitmq_stream/app.bzl
Labels: bazel

#10582 Clean up some incorrect references to rabbitmq_oauth2_client
  deps/oauth2_client/BUILD.bazel
  moduleindex.yaml
Labels: bazel

#10584 only rules_erlang, looking_glass & osiris from BCR
  BAZEL.md
  BUILD.bazel
  MODULE.bazel
  bazel/BUILD.khepri
  bazel/BUILD.ra
  moduleindex.yaml
Labels: bazel

#10586 QQ: be more defensive when reserving file handles.
  deps/rabbit/src/rabbit_quorum_queue.erl
Labels: backport-v3.12.x

#10589 Bump Khepri from 0.12.0 to 0.12.1
  MODULE.bazel
  rabbitmq-components.mk
Labels: bazel, make

#10606 Use `MaxInterval` when free space is `NaN`
  deps/rabbit/src/rabbit_disk_monitor.erl
Labels: backport-v3.12.x

#10610 Use default sorting when `?sort=` in MGMT API
  deps/rabbitmq_management/src/rabbit_mgmt_util.erl
Labels: backport-v3.13.x

#10623 Fix AMQP 0.9.1 headers regression
  deps/rabbit/src/mc_amqpl.erl
  deps/rabbit/test/quorum_queue_SUITE.erl
Labels: backport-v3.13.x

#10633 ctl delete_queue: mention [--vhost <name>] explicitly in help output
  deps/rabbitmq_cli/lib/rabbitmq/cli/ctl/commands/delete_queue_command.ex
Labels: backport-v3.13.x

#10569 Configurable writer module
  MODULE.bazel
  deps/rabbit/Makefile
  deps/rabbit/src/rabbit_stream_coordinator.erl
Labels: bazel, make, backport-v3.13.x

#10638 Fix OTP float warnings
  deps/rabbit_common/src/rabbit_http_util.erl
Labels: backport-v3.13.x

#10644 bazel run gazelle
  deps/oauth2_client/BUILD.bazel
Labels: bazel
