Repository rabbitmq/rabbitmq-server, pull requests merged in 2024-03, with the labels that each got.

#10657 Label main as 4.0.0 in bazel build
  rabbitmq.bzl
Labels: bazel

#10665 rabbitmq.conf.example updates
  deps/rabbit/docs/rabbitmq.conf.example
Labels: backport-v3.13.x

#10664 QQ: add feature flag to control adding non-voting members.
  deps/rabbit/src/rabbit_core_ff.erl
  deps/rabbit/src/rabbit_quorum_queue.erl
  deps/rabbit/test/quorum_queue_SUITE.erl
Labels: backport-v3.13.x

#10674 Print startup time in millisecond instead of microsecond
  deps/rabbit/src/rabbit.erl
Labels: backport-v3.13.x

#10663 Add queue type setting for exchange federation
  deps/rabbitmq_federation/include/rabbit_federation.hrl
  deps/rabbitmq_federation/src/rabbit_federation_exchange_link.erl
  deps/rabbitmq_federation/src/rabbit_federation_parameters.erl
  deps/rabbitmq_federation/src/rabbit_federation_upstream.erl
  deps/rabbitmq_federation/test/exchange_SUITE.erl
  deps/rabbitmq_federation_management/priv/www/js/federation.js
  deps/rabbitmq_federation_management/priv/www/js/tmpl/federation-upstream.ejs
  deps/rabbitmq_federation_management/priv/www/js/tmpl/federation-upstreams.ejs
Labels: backport-v3.13.x

#10685 rabbit_stream_queue_SUITE: test reliability with khepri
  deps/rabbit/test/rabbit_stream_queue_SUITE.erl
Labels: backport-v3.13.x

#10689 Remove wrong and unncessary log statement
  deps/rabbitmq_auth_backend_oauth2/src/uaa_jwks.erl
Labels: backport-v3.13.x

#10704 CLI: update guide URLs to use the website new path structure
  deps/rabbitmq_cli/lib/rabbitmq/cli/core/doc_guide.ex
  deps/rabbitmq_federation/include/rabbit_federation.hrl
  deps/rabbitmq_mqtt/include/rabbit_mqtt.hrl
  deps/rabbitmq_shovel/include/rabbit_shovel.hrl
  deps/rabbitmq_stomp/include/rabbit_stomp.hrl
  deps/rabbitmq_stream/src/Elixir.RabbitMQ.CLI.Ctl.Commands.AddSuperStreamCommand.erl
  deps/rabbitmq_stream/src/Elixir.RabbitMQ.CLI.Ctl.Commands.DeleteSuperStreamCommand.erl
  deps/rabbitmq_stream/src/Elixir.RabbitMQ.CLI.Ctl.Commands.ListStreamConnectionsCommand.erl
  deps/rabbitmq_stream/src/Elixir.RabbitMQ.CLI.Ctl.Commands.ListStreamConsumerGroupsCommand.erl
  deps/rabbitmq_stream/src/Elixir.RabbitMQ.CLI.Ctl.Commands.ListStreamConsumersCommand.erl
  deps/rabbitmq_stream/src/Elixir.RabbitMQ.CLI.Ctl.Commands.ListStreamGroupConsumersCommand.erl
  deps/rabbitmq_stream/src/Elixir.RabbitMQ.CLI.Ctl.Commands.ListStreamPublishersCommand.erl
  deps/rabbitmq_stream/src/Elixir.RabbitMQ.CLI.Ctl.Commands.ListStreamTrackingCommand.erl
  deps/rabbitmq_stream_common/include/rabbit_stream.hrl
Labels: backport-v3.13.x

#10712 FIX #10535. Super Streams: check for duplicate partitions names
  deps/rabbitmq_stream/src/rabbit_stream_manager.erl
  deps/rabbitmq_stream/test/rabbit_stream_SUITE.erl
Labels: backport-v3.13.x

#10720 rabbit_env: Correctly pass `TakeFromRemoteNode` argument to `update_context/3`
  deps/rabbit_common/src/rabbit_env.erl
  deps/rabbit_common/test/rabbit_env_SUITE.erl
Labels: bug

#10730 Dedupe ?awaitMatch/4 in rabbit_assert.hrl
  deps/rabbitmq_ct_helpers/include/rabbit_assert.hrl
Labels: backport-v3.11.x, backport-v3.12.x, backport-v3.13.x

#10736 rules_pkg 0.9.1 -> 0.10.1
  MODULE.bazel
  WORKSPACE
Labels: bazel, backport-v3.11.x, backport-v3.12.x, backport-v3.13.x

#10738 Update Cowboy to 2.12.0
  MODULE.bazel
  rabbitmq-components.mk
Labels: bazel, make, backport-v3.13.x

#10735 Use the new save-always flag on the cache action
  .github/workflows/oci.yaml
  .github/workflows/rabbitmq_peer_discovery_aws.yaml
  .github/workflows/test-authnz.yaml
  .github/workflows/test-erlang-git.yaml
  .github/workflows/test-mixed-versions.yaml
  .github/workflows/test-selenium.yaml
  .github/workflows/test.yaml
Labels: backport-v3.12.x, backport-v3.13.x

#10734 Store management UI OIDC tokens in localStorage instead of sessionStorage
  deps/rabbitmq_management/priv/www/js/oidc-oauth/helper.js
Labels: backport-v3.13.x

#10721 Close #10345. Add prometheus_rabbitmq_federation_collector.
  deps/rabbitmq_federation/app.bzl
  deps/rabbitmq_federation/src/rabbit_federation_status.erl
  deps/rabbitmq_prometheus/BUILD.bazel
  deps/rabbitmq_prometheus/app.bzl
  deps/rabbitmq_prometheus/metrics.md
  deps/rabbitmq_prometheus/src/collectors/prometheus_rabbitmq_federation_collector.erl
  deps/rabbitmq_prometheus/src/rabbit_prometheus_dispatcher.erl
  deps/rabbitmq_prometheus/test/prometheus_rabbitmq_federation_collector_SUITE.erl
  deps/rabbitmq_prometheus/test/rabbitmq_prometheus_collector_test_proxy.erl
  moduleindex.yaml
Labels: bazel, backport-v3.13.x

#10754 Introduce per-channel consumers limit (by @illotum, AWS)
  deps/rabbit/priv/schema/rabbit.schema
  deps/rabbit/src/rabbit_channel.erl
  deps/rabbit/test/config_schema_SUITE_data/rabbit.snippets
  deps/rabbit/test/per_node_limit_SUITE.erl
Labels: bazel, make, backport-v3.12.x, backport-v3.13.x

#10757 Fixup rabbitmq_amqp1_0 BUILD.bazel
  deps/rabbitmq_amqp1_0/BUILD.bazel
Labels: bazel, backport-v3.13.x

#10768 Remove weird characters
  deps/rabbit/docs/rabbitmq.conf.example
Labels: backport-v3.13.x

#10799 fixed management ui popup auto close problem #10797
  deps/rabbitmq_management/priv/www/js/main.js
Labels: backport-v3.13.x

#10803 Commit the amqp framing generated sources
  MODULE.bazel
  deps/rabbit_common/.gitignore
  deps/rabbit_common/BUILD.bazel
  deps/rabbit_common/include/rabbit_framing.hrl
  deps/rabbit_common/src/rabbit_framing_amqp_0_8.erl
  deps/rabbit_common/src/rabbit_framing_amqp_0_9_1.erl
Labels: bazel, backport-v3.13.x

#10801 Use rules_erlang 3.15.0
  MODULE.bazel
  WORKSPACE
  bazel/elixir/elixir_toolchain.bzl
Labels: bazel, backport-v3.13.x

#10338 Bazel 7 fixes
  .bazelversion
  bazel/elixir/elixir_as_app.bzl
  deps/rabbitmq_cli/rabbitmqctl.bzl
Labels: bazel, backport-v3.13.x

#10813 Adopt otp 25.2.3
  MODULE.bazel
Labels: bazel, backport-v3.11.x, backport-v3.12.x

#10825 PR #10761 follow ups
  deps/rabbitmq_mqtt/include/rabbit_mqtt.hrl
  deps/rabbitmq_mqtt/test/command_SUITE.erl
  deps/rabbitmq_web_mqtt/src/Elixir.RabbitMQ.CLI.Ctl.Commands.ListWebMqttConnectionsCommand.erl
  deps/rabbitmq_web_mqtt/test/command_SUITE.erl
Labels: backport-v3.13.x

#10822 Osiris v1.8.1
  MODULE.bazel
  deps/rabbit/Makefile
Labels: bazel, make, backport-v3.11.x, backport-v3.12.x, backport-v3.13.x

#10837 chore: fix some typos
  deps/rabbit/src/rabbit_maintenance.erl
  release-notes/3.11.10.md
  release-notes/3.13.0.md
  release-notes/3.6.4.md
  release-notes/3.8.10.md
  release-notes/3.8.3.md
  release-notes/README-1.8.1.txt
  release-notes/README-3.4.0.txt
Labels: backport-v3.13.x

#10839 HTTP API: GET /api/queues/{vhost}/{name} now supports enable_queue_totals
  deps/rabbitmq_management/src/rabbit_mgmt_wm_queue.erl
  deps/rabbitmq_management/test/rabbit_mgmt_only_http_SUITE.erl
Labels: backport-v3.13.x

#10759 rabbit_peer_discovery: Pass inetrc config file to temporary hidden node
  deps/rabbit/src/rabbit_peer_discovery.erl
Labels: bug, backport-v3.13.x

#10862 Adopt otp 26.1.2
  WORKSPACE
Labels: backport-v3.12.x, backport-v3.13.x

#10849 Use rules_erlang 3.15.1
  .bazelrc
  .github/workflows/test-windows.yaml
  MODULE.bazel
  WORKSPACE
Labels: bazel, backport-v3.13.x

#10870 rabbitmq-plugins list: respect --silent and --quiet
  deps/rabbitmq_cli/lib/rabbitmq/cli/plugins/commands/list_command.ex
  deps/rabbitmq_cli/test/plugins/list_plugins_command_test.exs
Labels: backport-v3.13.x

#10880 Remove deprecated queue_explicit_gc_run_operation_threshold config
  deps/rabbit/BUILD.bazel
  deps/rabbit/Makefile
  deps/rabbit/test/backing_queue_SUITE.erl
Labels: bazel, make

#10875 Tests for rabbitmq-plugins list: --silent and --quiet options
  deps/rabbitmq_cli/lib/rabbitmq/cli/plugins/commands/list_command.ex
  deps/rabbitmq_cli/lib/rabbitmq/cli/plugins/plugins_helpers.ex
  deps/rabbitmq_cli/test/plugins/list_plugins_command_test.exs
Labels: backport-v3.13.x

#10884 3.13.1 release notes
  release-notes/3.13.1.md
Labels: backport-v3.13.x
