Repository rabbitmq/rabbitmq-server, pull requests merged in 2024-12, with the labels that each got.

#12889 By @bpint: Fixes an exception in AMQP 0-9-1 exception (error) generator when input data includes non-ASCII characters
  deps/rabbit_common/src/rabbit_binary_generator.erl
  deps/rabbit_common/test/unit_SUITE.erl
Labels: backport-v4.0.x

#12888 Fixes an exception in AMQP 0-9-1 exception (error) generator when input data includes non-ASCII characters
  deps/rabbit_common/src/rabbit_binary_generator.erl
  deps/rabbit_common/test/unit_SUITE.erl
Labels: backport-v4.0.x

#12894 CLI: Error on compiler warnings in tests
  deps/rabbitmq_cli/Makefile
  deps/rabbitmq_cli/lib/rabbitmq/cli/auto_complete.ex
  deps/rabbitmq_cli/test/diagnostics/check_if_any_deprecated_features_are_used_command_test.exs
  deps/rabbitmq_cli/test/diagnostics/check_if_cluster_has_classic_queue_mirroring_policy_command_test.exs
  deps/rabbitmq_cli/test/diagnostics/discover_peers_command_test.exs
  deps/rabbitmq_cli/test/rabbitmqctl_test.exs
Labels: make, backport-v4.0.x

#12904 Set a floor of zero for incoming-window
  deps/amqp10_client/src/amqp10_client_session.erl
  deps/rabbit/src/rabbit_amqp_session.erl
  deps/rabbit/test/amqp_client_SUITE.erl
Labels: bug, backport-v4.0.x

#12907 By @gomoripeti: Restore credit_flow between AMQP 0.9.1 channel/MQTT connection -> CQ processes
  deps/rabbit/BUILD.bazel
  deps/rabbit/Makefile
  deps/rabbit/src/rabbit_channel.erl
  deps/rabbit/src/rabbit_classic_queue.erl
  deps/rabbit/test/classic_queue_SUITE.erl
  deps/rabbit_common/src/rabbit_misc.erl
  deps/rabbitmq_mqtt/src/rabbit_mqtt_processor.erl
  deps/rabbitmq_mqtt/test/mqtt_shared_SUITE.erl
  deps/rabbitmq_web_mqtt/test/web_mqtt_shared_SUITE.erl
Labels: bazel, make, backport-v4.0.x

#12910 Backport #12907 to v4.0.x
  deps/rabbit/BUILD.bazel
  deps/rabbit/Makefile
  deps/rabbit/src/rabbit_channel.erl
  deps/rabbit/src/rabbit_classic_queue.erl
  deps/rabbit/test/classic_queue_SUITE.erl
  deps/rabbit_common/src/rabbit_misc.erl
  deps/rabbitmq_mqtt/src/rabbit_mqtt_processor.erl
  deps/rabbitmq_mqtt/test/mqtt_shared_SUITE.erl
  deps/rabbitmq_web_mqtt/test/web_mqtt_shared_SUITE.erl
Labels: bazel, make

#12921 By @noxdafox: Improve rabbit_backing_queue:is_duplicate behaviour (#12913), take 2
  deps/rabbit/src/rabbit_amqqueue_process.erl
  deps/rabbit/src/rabbit_backing_queue.erl
Labels: backport-v4.0.x

#12928 Allow building CLI with elixir 1.18.x
  deps/rabbitmq_cli/mix.exs
Labels: backport-v3.13.x, backport-v4.0.x

#12935 Fix dead lettering crash
  deps/rabbit/src/mc.erl
  deps/rabbit/test/dead_lettering_SUITE.erl
Labels: bug, backport-v4.0.x

#12936 Pin Bazel to v7.4.1
  .bazelversion
Labels: backport-v4.0.x

#12941 bazel run gazelle
  deps/rabbit/app.bzl
Labels: bazel

#12940 bazel run gazelle
  deps/rabbit/app.bzl
Labels: bazel

#12945 4.0.5 release notes
  release-notes/4.0.4.md
  release-notes/4.0.5.md
Labels: backport-v4.0.x

#12950 Quorum queues: ignore handle_tick with an old overview format
  deps/rabbit/src/rabbit_quorum_queue.erl
Labels: backport-v4.0.x

#12960 Remove actions/setup-dotnet
  .github/workflows/test-make-target.yaml
  .github/workflows/test-plugin-mixed.yaml
  .github/workflows/test-plugin.yaml
Labels: backport-v4.0.x

#12737 rabbitmq_ct_helpers: Change how Mnesia/Khepri is selected
  .github/workflows/test-make-target.yaml
  deps/rabbit/test/bindings_SUITE.erl
  deps/rabbit/test/clustering_management_SUITE.erl
  deps/rabbit/test/clustering_recovery_SUITE.erl
  deps/rabbitmq_ct_helpers/src/rabbit_ct_broker_helpers.erl
  deps/rabbitmq_jms_topic_exchange/test/rjms_topic_selector_SUITE.erl
  deps/rabbitmq_recent_history_exchange/test/system_SUITE.erl
Labels: bazel, make

#12980 Upgrade eetcd and gun
  deps/rabbitmq_peer_discovery_etcd/Makefile
  deps/rabbitmq_peer_discovery_etcd/priv/schema/rabbitmq_peer_discovery_etcd.schema
  deps/rabbitmq_peer_discovery_etcd/src/rabbitmq_peer_discovery_etcd_v3_client.erl
  release-notes/4.1.0.md
Labels: make

#12966 rabbit_feature_flags: Take callback definition from correct node
  deps/rabbit/src/rabbit_ff_controller.erl
  deps/rabbit/test/feature_flags_SUITE.erl
Labels: bug

#12969 Fix channel crash when publishing to a new stream
  deps/rabbit/src/rabbit_stream_queue.erl
Labels: backport-v4.0.x

#12992 Remove rabbit_common from MQTT dependencies
  deps/rabbitmq_mqtt/Makefile
  deps/rabbitmq_web_mqtt/Makefile
Labels: make, backport-v4.0.x

#12994 Upgrade eetcd to v0.5.0
  deps/rabbitmq_peer_discovery_etcd/Makefile
Labels: make

#13002 Speed up tests
  deps/rabbit/test/amqp_client_SUITE.erl
  deps/rabbitmq_mqtt/test/util.erl
Labels: backport-v4.0.x
