Repository rabbitmq/rabbitmq-server, pull requests merged in 2024-08, with the labels that each got.

#11884 Speed up AMQP connection and session (de)registration
  deps/rabbit/src/rabbit.erl
  deps/rabbit/src/rabbit_amqp1_0.erl
  deps/rabbit/src/rabbit_amqp_session.erl
  deps/rabbitmq_mqtt/src/rabbit_mqtt_sup.erl
Labels: backport-v4.0.x

#11892 Add dynamic and static promethues metric gauge
  deps/rabbitmq_prometheus/BUILD.bazel
  deps/rabbitmq_prometheus/Makefile
  deps/rabbitmq_prometheus/app.bzl
  deps/rabbitmq_prometheus/src/collectors/prometheus_rabbitmq_shovel_collector.erl
  deps/rabbitmq_prometheus/src/rabbit_prometheus_dispatcher.erl
  deps/rabbitmq_prometheus/test/prometheus_rabbitmq_shovel_collector_SUITE.erl
  deps/rabbitmq_shovel/src/rabbit_shovel_status.erl
  moduleindex.yaml
Labels: bazel, make, backport-v3.13.x, backport-v4.0.x

#11889 Add dynamic and static Shovels Promethues metric gauge
  deps/rabbitmq_prometheus/BUILD.bazel
  deps/rabbitmq_prometheus/Makefile
  deps/rabbitmq_prometheus/app.bzl
  deps/rabbitmq_prometheus/src/collectors/prometheus_rabbitmq_shovel_collector.erl
  deps/rabbitmq_prometheus/src/rabbit_prometheus_dispatcher.erl
  deps/rabbitmq_prometheus/test/prometheus_rabbitmq_shovel_collector_SUITE.erl
  deps/rabbitmq_shovel/src/rabbit_shovel_status.erl
  moduleindex.yaml
Labels: bazel, make

#11898 Classic peer discovery: node list warnings
  deps/rabbit/src/rabbit_peer_discovery_classic_config.erl
Labels: backport-v3.13.x, backport-v4.0.x

#11907 Bump Cuttlefish to 3.3.0
  MODULE.bazel
  erlang.mk
  rabbitmq-components.mk
Labels: bazel, make, backport-v3.13.x, backport-v4.0.x

#11910 Reuse timestamp in rabbit_message_interceptor
  deps/rabbit/src/rabbit_message_interceptor.erl
Labels: backport-v4.0.x

#11917 Reduce Khepri test flakes
  deps/rabbitmq_ct_helpers/BUILD.bazel
  deps/rabbitmq_ct_helpers/src/rabbit_ct_broker_helpers.erl
  deps/rabbitmq_mqtt/test/shared_SUITE.erl
Labels: bazel, backport-v3.13.x, backport-v4.0.x

#11925 Avoid returning leader info when leader is unknown
  deps/rabbit/src/rabbit_amqp_management.erl
Labels: bug, backport-v4.0.x

#11928 Bump Cuttlefish to 3.4.0
  MODULE.bazel
  rabbitmq-components.mk
Labels: bazel, make, backport-v3.13.x, backport-v4.0.x

#11933 QQ: refactor and improve leader detection code.
  deps/rabbit/src/rabbit_quorum_queue.erl
  deps/rabbit/test/cli_forget_cluster_node_SUITE.erl
Labels: backport-v4.0.x

#11941 Bump observer_cli to 1.7.5
  MODULE.bazel
  rabbitmq-components.mk
Labels: bazel, make, backport-v3.13.x, backport-v4.0.x

#11947 STOMP: add support for consumer priorities
  deps/rabbitmq_stomp/include/rabbit_stomp_headers.hrl
  deps/rabbitmq_stomp/src/rabbit_stomp_processor.erl
  deps/rabbitmq_stomp/test/system_SUITE.erl
Labels: backport-v4.0.x

#11953 Avoid persistent_term for credit config
  deps/rabbit/src/rabbit_amqp_session.erl
Labels: backport-v4.0.x

#11963 bazel run gazelle
  deps/rabbit/app.bzl
Labels: bazel

#11962 bazel run gazelle
  deps/rabbit/app.bzl
Labels: bazel

#11967 Add `cluster_upgrade_SUITE` to check mixed-version upgrades
  deps/rabbit/BUILD.bazel
  deps/rabbit/app.bzl
  deps/rabbit/test/cluster_upgrade_SUITE.erl
  deps/rabbitmq_ct_helpers/src/rabbit_ct_broker_helpers.erl
Labels: bazel, backport-v3.13.x, backport-v4.0.x

#11970 bazel run gazelle
  deps/rabbit/app.bzl
Labels: bazel

#11971 bazel run gazelle
  deps/rabbit/app.bzl
Labels: bazel

#11974 bazel run gazelle
  deps/rabbit/app.bzl
Labels: bazel

#11975 Log AMQP connection name and container-id
  deps/rabbit/src/rabbit_amqp_reader.erl
Labels: backport-v4.0.x

#11981 4.0.0-beta.4 release notes
  release-notes/4.0.0.md
Labels: backport-v4.0.x

#11979 Handle transient queue deletion in Khepri minority
  deps/rabbit/src/rabbit_amqqueue.erl
  deps/rabbit/src/rabbit_db.erl
  deps/rabbit/src/rabbit_db_queue.erl
  deps/rabbit/src/rabbit_khepri.erl
  deps/rabbit_common/src/rabbit_misc.erl
Labels: backport-v3.13.x, backport-v4.0.x

#11986 Restrict username and password in AMQPLAIN
  deps/rabbit/src/rabbit_auth_mechanism_amqplain.erl
Labels: backport-v3.13.x, backport-v4.0.x

#12000 Ra v2.13.6
  MODULE.bazel
  rabbitmq-components.mk
Labels: bazel, make, backport-v4.0.x

#11984 Support SASL mechanism EXTERNAL in Erlang AMQP 1.0 client
  deps/amqp10_client/src/amqp10_client.erl
  deps/amqp10_client/src/amqp10_client_connection.erl
  deps/rabbitmq_auth_mechanism_ssl/BUILD.bazel
  deps/rabbitmq_auth_mechanism_ssl/Makefile
  deps/rabbitmq_auth_mechanism_ssl/app.bzl
  deps/rabbitmq_auth_mechanism_ssl/src/rabbit_auth_mechanism_ssl.erl
  deps/rabbitmq_auth_mechanism_ssl/test/system_SUITE.erl
Labels: bazel, make, backport-v4.0.x

#12002 LDAP: optional sensitive value tagging
  deps/rabbitmq_auth_backend_ldap/priv/schema/rabbitmq_auth_backend_ldap.schema
  deps/rabbitmq_auth_backend_ldap/src/rabbit_auth_backend_ldap.erl
  deps/rabbitmq_auth_backend_ldap/test/config_schema_SUITE_data/rabbitmq_auth_backend_ldap.snippets
Labels: backport-v4.0.x

#12005 Initial man page updates for 4.0
  deps/rabbit/docs/.gitignore
  deps/rabbit/docs/README.md
  deps/rabbit/docs/postprocess_man_html.sh
  deps/rabbit/docs/rabbitmq-diagnostics.8
  deps/rabbit/docs/rabbitmq-echopid.8
  deps/rabbit/docs/rabbitmq-env.conf.5
  deps/rabbit/docs/rabbitmq-plugins.8
  deps/rabbit/docs/rabbitmq-queues.8
  deps/rabbit/docs/rabbitmq-server.8
  deps/rabbit/docs/rabbitmq-service.8
  deps/rabbit/docs/rabbitmq-streams.8
  deps/rabbit/docs/rabbitmq-upgrade.8
  deps/rabbit/docs/rabbitmqctl.8
Labels: backport-v3.13.x, backport-v4.0.x

#12014 rabbitmq-upgrade revive: handle more errors
  deps/rabbit/src/rabbit_maintenance.erl
Labels: backport-v3.13.x, backport-v4.0.x

#11999 Add SASL mechanism ANONYMOUS
  deps/amqp10_client/src/amqp10_client.erl
  deps/amqp10_client/test/system_SUITE.erl
  deps/rabbit/BUILD.bazel
  deps/rabbit/Makefile
  deps/rabbit/app.bzl
  deps/rabbit/docs/rabbitmq.conf.example
  deps/rabbit/priv/schema/rabbit.schema
  deps/rabbit/src/rabbit_amqp_reader.erl
  deps/rabbit/src/rabbit_auth_mechanism_anonymous.erl
  deps/rabbit/src/rabbit_auth_mechanism_plain.erl
  deps/rabbit/src/rabbit_reader.erl
  deps/rabbit/test/amqp_auth_SUITE.erl
  deps/rabbit/test/amqp_system_SUITE_data/fsharp-tests/Program.fs
  deps/rabbit/test/config_schema_SUITE_data/rabbit.snippets
  deps/rabbit/test/unit_access_control_SUITE.erl
  deps/rabbitmq_auth_mechanism_ssl/test/system_SUITE.erl
  deps/rabbitmq_mqtt/BUILD.bazel
  deps/rabbitmq_mqtt/Makefile
  deps/rabbitmq_mqtt/priv/schema/rabbitmq_mqtt.schema
  deps/rabbitmq_mqtt/src/rabbit_mqtt_processor.erl
  deps/rabbitmq_mqtt/src/rabbit_mqtt_util.erl
  deps/rabbitmq_mqtt/test/auth_SUITE.erl
  deps/rabbitmq_mqtt/test/config_schema_SUITE_data/rabbitmq_mqtt.snippets
  deps/rabbitmq_mqtt/test/rabbitmq_mqtt.app
  deps/rabbitmq_mqtt/test/util_SUITE.erl
  deps/rabbitmq_shovel/test/amqp10_inter_cluster_SUITE.erl
  deps/rabbitmq_stream/test/rabbit_stream_SUITE.erl
  moduleindex.yaml
  release-notes/4.0.0.md
Labels: bazel, make, backport-v4.0.x

#11980 Handle queue declaration failures in Khepri minority
  deps/rabbit/src/rabbit_amqqueue.erl
  deps/rabbit/src/rabbit_amqqueue_process.erl
  deps/rabbit/src/rabbit_db_queue.erl
  deps/rabbit/src/rabbit_quorum_queue.erl
  deps/rabbit/src/rabbit_stream_coordinator.erl
  deps/rabbit/src/rabbit_stream_queue.erl
  deps/rabbitmq_mqtt/src/rabbit_mqtt_qos0_queue.erl
Labels: backport-v3.13.x, backport-v4.0.x

#11964 QQ: checkpointing frequency improvements
  deps/rabbit/BUILD.bazel
  deps/rabbit/app.bzl
  deps/rabbit/src/rabbit_fifo.erl
  deps/rabbit/src/rabbit_fifo.hrl
  deps/rabbit/src/rabbit_quorum_queue.erl
  deps/rabbit/test/rabbit_fifo_SUITE.erl
  deps/rabbit/test/rabbit_fifo_int_SUITE.erl
Labels: bazel, backport-v4.0.x

#12024 bazel run gazelle
  deps/rabbit/BUILD.bazel
  deps/rabbit/app.bzl
Labels: bazel

#12025 bazel run gazelle
  deps/rabbit/BUILD.bazel
  deps/rabbit/app.bzl
Labels: bazel

#12027 Fix AMQP 1.0 SASL CR Demo
  deps/rabbit/src/rabbit_amqp_reader.erl
  deps/rabbit/src/rabbit_auth_mechanism_anonymous.erl
  deps/rabbit/src/rabbit_reader.erl
Labels: backport-v4.0.x

#11937 QQ: introduce a default delivery limit
  deps/rabbit/src/rabbit_fifo.erl
  deps/rabbit/src/rabbit_quorum_queue.erl
  deps/rabbitmq_management/priv/www/js/global.js
  deps/rabbitmq_management/priv/www/js/tmpl/queue.ejs
  release-notes/4.0.0.md
Labels: backport-v4.0.x, breaking-change

#12032 Maintain order of configured SASL mechanisms
  deps/rabbit/priv/schema/rabbit.schema
  deps/rabbit/test/config_schema_SUITE_data/rabbit.snippets
  deps/rabbitmq_ct_helpers/src/rabbit_ct_config_schema.erl
Labels: backport-v4.0.x

#12026 Fixes to rabbit_maintenance:revive/0
  deps/rabbit/src/rabbit_amqqueue.erl
  deps/rabbit/src/rabbit_maintenance.erl
  deps/rabbit/test/maintenance_mode_SUITE.erl
Labels: backport-v3.13.x, backport-v4.0.x

#12042 Update 4.0 release notes
  release-notes/4.0.0.md
Labels: backport-v4.0.x

#12041 Shovel HTTP API: actually implement GET /api/shovels/vhost/{vhost}/{name}
  deps/rabbitmq_management/src/rabbit_mgmt_wm_parameters.erl
  deps/rabbitmq_shovel_management/app.bzl
  deps/rabbitmq_shovel_management/src/rabbit_shovel_mgmt_shovel.erl
  deps/rabbitmq_shovel_management/src/rabbit_shovel_mgmt_shovels.erl
  deps/rabbitmq_shovel_management/test/http_SUITE.erl
  moduleindex.yaml
Labels: bazel, backport-v3.13.x, backport-v4.0.x

#12047 Shovel management: tests and simplification
  deps/rabbitmq_management/src/rabbit_mgmt_wm_definitions.erl
  deps/rabbitmq_management/src/rabbit_mgmt_wm_parameter.erl
  deps/rabbitmq_management/src/rabbit_mgmt_wm_parameters.erl
  deps/rabbitmq_shovel_management/src/rabbit_shovel_mgmt_shovel.erl
  deps/rabbitmq_shovel_management/test/http_SUITE.erl
Labels: backport-v3.13.x, backport-v4.0.x

#12050 Remove randomized_startup_delay_range config
  deps/rabbit/priv/schema/rabbit.schema
  deps/rabbit/test/config_schema_SUITE_data/rabbit.snippets
  release-notes/4.0.0.md
Labels: backport-v4.0.x

#11998 Make it hard to accidentally enable an experimental feature flag
  deps/rabbitmq_cli/lib/rabbitmq/cli/ctl/commands/enable_feature_flag_command.ex
  deps/rabbitmq_cli/test/ctl/enable_feature_flag_test.exs
  deps/rabbitmq_management/priv/www/js/tmpl/feature-flags.ejs
Labels: backport-v3.13.x, backport-v4.0.x

#12061 Rename quorum queue priority from "low" to "normal"
  deps/rabbit/src/rabbit_fifo.erl
  deps/rabbit/src/rabbit_fifo_q.erl
  deps/rabbit/src/rabbit_quorum_queue.erl
  deps/rabbit/test/rabbit_fifo_q_SUITE.erl
  deps/rabbitmq_management/priv/www/js/tmpl/queue.ejs
Labels: backport-v4.0.x

#12066 Return non-0 exit code when failing to enable an experimental feature flag
  deps/rabbitmq_cli/lib/rabbitmq/cli/ctl/commands/enable_feature_flag_command.ex
  deps/rabbitmq_cli/test/ctl/enable_feature_flag_test.exs
Labels: backport-v3.13.x, backport-v4.0.x

#12035 Management: Add segment count to stream queue page
  deps/rabbitmq_management/priv/www/js/global.js
  deps/rabbitmq_management/priv/www/js/tmpl/queue.ejs
Labels: backport-v4.0.x

#12070 Expose quorum queue status at GET /api/queues/quorum/{vhost}/{name}/status by @SimonUnge
  deps/rabbitmq_ct_helpers/src/rabbit_mgmt_test_util.erl
  deps/rabbitmq_management/app.bzl
  deps/rabbitmq_management/src/rabbit_mgmt_dispatcher.erl
  deps/rabbitmq_management/src/rabbit_mgmt_wm_quorum_queue_status.erl
  deps/rabbitmq_management/test/rabbit_mgmt_http_SUITE.erl
  moduleindex.yaml
Labels: bazel, backport-v3.13.x, backport-v4.0.x

#12073 Osiris v1.8.3
  MODULE.bazel
  deps/rabbit/Makefile
Labels: bazel, make, backport-v3.13.x, backport-v4.0.x

#12085 Don't return khepri status when khperi_db is disabled
  deps/rabbitmq_cli/lib/rabbitmq/cli/diagnostics/commands/metadata_store_status_command.ex
Labels: backport-v3.13.x, backport-v4.0.x

#12091 Run with default wal_sync_method
  deps/rabbit_common/mk/rabbitmq-run.mk
  scripts/bazel/rabbitmq-run.bat
  scripts/bazel/rabbitmq-run.sh
Labels: make, backport-v3.13.x, backport-v4.0.x

#12104 Prevent exchange logging crash
  deps/rabbit/src/rabbit_logger_exchange_h.erl
Labels: backport-v3.13.x, backport-v4.0.x

#12109 Default queue type (DQT): fall back to node-wide default when virtual host has no metadata set
  deps/rabbit/src/rabbit_amqqueue.erl
  deps/rabbit/src/rabbit_queue_type.erl
  deps/rabbit/test/quorum_queue_SUITE.erl
  deps/rabbitmq_amqp_client/test/management_SUITE.erl
  deps/rabbitmq_ct_helpers/src/rabbit_mgmt_test_util.erl
  deps/rabbitmq_management/test/rabbit_mgmt_http_SUITE.erl
  deps/rabbitmq_management/test/rabbit_mgmt_only_http_SUITE.erl
Labels: backport-v3.13.x, backport-v4.0.x

#12113 rabbitmq-upgrade await_quorum_plus_one improvements
  deps/rabbit/src/rabbit_upgrade_preparation.erl
  deps/rabbit/test/upgrade_preparation_SUITE.erl
  deps/rabbitmq_cli/lib/rabbitmq/cli/streams/commands/add_replica_command.ex
  deps/rabbitmq_management/test/rabbit_mgmt_http_health_checks_SUITE.erl
Labels: backport-v3.13.x, backport-v4.0.x

#12119 3.13.7 release notes
  release-notes/3.13.7.md
Labels: backport-v3.13.x, backport-v4.0.x

#12128 Incrase default rabbit.max_link_credit
  deps/rabbit/src/rabbit_amqp_session.erl
Labels: backport-v4.0.x

#12082 Return errors when a queue record fails to be removed
  deps/rabbit/src/rabbit_amqqueue.erl
  deps/rabbit/src/rabbit_amqqueue_process.erl
  deps/rabbit/src/rabbit_db_queue.erl
  deps/rabbit/src/rabbit_quorum_queue.erl
  deps/rabbit/src/rabbit_stream_queue.erl
  deps/rabbit/src/rabbit_vhost.erl
  deps/rabbit/test/cluster_minority_SUITE.erl
Labels: backport-v4.0.x

#12118 MQTT and Streams: handle connection shutdown via CLI command gracefully
  deps/rabbit/src/rabbit_connection_tracking.erl
  deps/rabbit/src/rabbit_networking.erl
  deps/rabbitmq_mqtt/src/rabbit_mqtt_reader.erl
  deps/rabbitmq_mqtt/test/shared_SUITE.erl
Labels: backport-v3.13.x, backport-v4.0.x

#12149 Minor optimisation: Hibernate 2 metrics gc processes
  deps/rabbit/src/rabbit_core_metrics_gc.erl
  deps/rabbitmq_stream/src/rabbit_stream_metrics_gc.erl
Labels: backport-v3.13.x, backport-v4.0.x

#12140 Remove some dead code and configuration options
  deps/rabbit/BUILD.bazel
  deps/rabbit/Makefile
  deps/rabbit/docs/rabbitmq.conf.example
  deps/rabbit/priv/schema/rabbit.schema
  deps/rabbit/test/config_schema_SUITE_data/rabbit.snippets
  deps/rabbitmq_cli/lib/rabbitmq/cli/ctl/commands/hipe_compile_command.ex
  deps/rabbitmq_prometheus/docker/docker-entrypoint.sh
  deps/rabbitmq_prometheus/docker/rabbitmq-dist-metrics.conf
  deps/rabbitmq_prometheus/docker/rabbitmq-dist-tls.conf
  deps/rabbitmq_prometheus/docker/rabbitmq-overview.conf
  packaging/docker-image/Dockerfile
Labels: bazel, make, backport-v4.0.x

#12153 Support unicode messages by exchange logging
  deps/rabbit/src/rabbit_logger_exchange_h.erl
  deps/rabbit/test/logging_SUITE.erl
Labels: backport-v3.13.x, backport-v4.0.x

#12161 Set the default vm_memory_high_watermark to 0.6
  deps/rabbit/BUILD.bazel
  deps/rabbit/Makefile
  deps/rabbit/docs/rabbitmq.conf.example
  deps/rabbit/priv/schema/rabbit.schema
  deps/rabbit/test/unit_vm_memory_monitor_SUITE.erl
  deps/rabbitmq_mqtt/test/shared_SUITE.erl
Labels: bazel, make, backport-v4.0.x

#11965 Support tokens without kid when using multiple oauth providers and/or resource servers
  deps/oauth2_client/BUILD.bazel
  deps/oauth2_client/include/oauth2_client.hrl
  deps/oauth2_client/src/oauth2_client.erl
  deps/oauth2_client/test/system_SUITE.erl
  deps/oauth2_client/test/unit_SUITE.erl
  deps/rabbitmq_auth_backend_oauth2/BUILD.bazel
  deps/rabbitmq_auth_backend_oauth2/app.bzl
  deps/rabbitmq_auth_backend_oauth2/priv/schema/rabbitmq_auth_backend_oauth2.schema
  deps/rabbitmq_auth_backend_oauth2/src/rabbit_oauth2_config.erl
  deps/rabbitmq_auth_backend_oauth2/src/rabbit_oauth2_schema.erl
  deps/rabbitmq_auth_backend_oauth2/src/uaa_jwt.erl
  deps/rabbitmq_auth_backend_oauth2/src/uaa_jwt_jwt.erl
  deps/rabbitmq_auth_backend_oauth2/test/config_schema_SUITE_data/rabbitmq_auth_backend_oauth2.snippets
  deps/rabbitmq_auth_backend_oauth2/test/jwks_SUITE.erl
  deps/rabbitmq_auth_backend_oauth2/test/rabbit_auth_backend_oauth2_test_util.erl
  deps/rabbitmq_auth_backend_oauth2/test/rabbit_oauth2_config_SUITE.erl
  deps/rabbitmq_auth_backend_oauth2/test/rabbit_oauth2_schema_SUITE.erl
  deps/rabbitmq_auth_backend_oauth2/test/rabbit_oauth2_schema_SUITE_data/certs/cacert.pem
  deps/rabbitmq_auth_backend_oauth2/test/rabbit_oauth2_schema_SUITE_data/certs/cert.pem
  deps/rabbitmq_auth_backend_oauth2/test/rabbit_oauth2_schema_SUITE_data/certs/key.pem
  deps/rabbitmq_auth_backend_oauth2/test/unit_SUITE.erl
Labels: bazel, backport-v3.13.x, backport-v4.0.x

#12172 Minor fix: GET/HEAD method on non existing shovel crash
  deps/rabbitmq_shovel_management/src/rabbit_shovel_mgmt_shovel.erl
Labels: backport-v3.13.x, backport-v4.0.x

#12179 bazel run gazelle
  deps/rabbitmq_auth_backend_oauth2/BUILD.bazel
  deps/rabbitmq_auth_backend_oauth2/app.bzl
  moduleindex.yaml
Labels: bazel

#12178 bazel run gazelle
  deps/rabbitmq_auth_backend_oauth2/BUILD.bazel
  deps/rabbitmq_auth_backend_oauth2/app.bzl
  moduleindex.yaml
Labels: bazel

#12177 bazel run gazelle
  deps/rabbitmq_auth_backend_oauth2/BUILD.bazel
  deps/rabbitmq_auth_backend_oauth2/app.bzl
  moduleindex.yaml
Labels: bazel

#12183 Remove queue-version CQ argument
  deps/rabbitmq_management/priv/www/js/global.js
  deps/rabbitmq_management/priv/www/js/tmpl/policies.ejs
  deps/rabbitmq_management/priv/www/js/tmpl/queues.ejs
Labels: backport-v4.0.x

#12182 Update .NET to 8.0
  .github/workflows/test-plugin-mixed.yaml
  deps/rabbit/test/amqp_system_SUITE_data/fsharp-tests/fsharp-tests.fsproj
Labels: backport-v3.13.x, backport-v4.0.x

#12186 Document request and connection timeout configs of the http auth backend
  deps/rabbitmq_auth_backend_http/README.md
Labels: backport-v3.13.x, backport-v4.0.x

#12163 rabbit_db_cluster: Reset feature flags immediately after a failure to join
  deps/rabbit/BUILD.bazel
  deps/rabbit/app.bzl
  deps/rabbit/src/rabbit_db_cluster.erl
  deps/rabbit/test/metadata_store_clustering_SUITE.erl
Labels: bazel
