Repository rabbitmq/rabbitmq-server, pull requests merged in 2024-09, with the labels that each got.

#11778 Make cleanups and ct-master introduction
  Makefile
  deps/amqp10_client/Makefile
  deps/amqp10_common/Makefile
  deps/amqp_client/Makefile
  deps/amqp_client/test/system_SUITE.erl
  deps/oauth2_client/Makefile
  deps/rabbit/.gitignore
  deps/rabbit/Makefile
  deps/rabbit/ct.test.spec
  deps/rabbit/test/cluster_limit_SUITE.erl
  deps/rabbit/test/deprecated_features_SUITE.erl
  deps/rabbit/test/feature_flags_SUITE.erl
  deps/rabbit/test/feature_flags_v2_SUITE.erl
  deps/rabbit/test/metadata_store_clustering_SUITE.erl
  deps/rabbit/test/per_vhost_connection_limit_SUITE.erl
  deps/rabbit/test/queue_parallel_SUITE.erl
  deps/rabbit/test/queue_type_SUITE.erl
  deps/rabbit/test/quorum_queue_member_reconciliation_SUITE.erl
  deps/rabbit/test/rabbit_ct_hook.erl
  deps/rabbit/test/rabbit_fifo_dlx_integration_SUITE.erl
  deps/rabbit/test/rabbit_stream_queue_SUITE.erl
  deps/rabbit/test/rabbitmq_4_0_deprecations_SUITE.erl
  deps/rabbit/test/unit_config_value_encryption_SUITE.erl
  deps/rabbit_common/Makefile
  deps/rabbit_common/mk/rabbitmq-components.hexpm.mk
  deps/rabbit_common/mk/rabbitmq-early-plugin.mk
  deps/rabbit_common/mk/rabbitmq-early-test.mk
  deps/rabbit_common/mk/rabbitmq-hexpm.mk
  deps/rabbit_common/mk/rabbitmq-plugin.mk
  deps/rabbit_common/mk/rabbitmq-test.mk
  deps/rabbit_common/mk/rabbitmq-tools.mk
  deps/rabbitmq_amqp1_0/Makefile
  deps/rabbitmq_amqp_client/Makefile
  deps/rabbitmq_aws/Makefile
  deps/rabbitmq_cli/Makefile
  deps/rabbitmq_codegen/Makefile
  deps/rabbitmq_ct_client_helpers/Makefile
  deps/rabbitmq_ct_helpers/Makefile
  deps/rabbitmq_ct_helpers/src/rabbit_ct_broker_helpers.erl
  deps/rabbitmq_prelaunch/src/rabbit_prelaunch_conf.erl
  deps/rabbitmq_stream_common/Makefile
  deps/trust_store_http/Makefile
  rabbitmq-components.mk
  rabbitmq.bzl
Labels: bazel, make

#12074 Cancel AMQP stream consumer when local stream member is deleted
  deps/rabbit/BUILD.bazel
  deps/rabbit/src/rabbit_stream_coordinator.erl
  deps/rabbit/src/rabbit_stream_queue.erl
  deps/rabbit/test/rabbit_stream_queue_SUITE.erl
Labels: bazel, backport-v3.13.x, backport-v4.0.x

#12197 bazel run gazelle
  deps/rabbit/BUILD.bazel
  deps/rabbit/app.bzl
Labels: bazel

#11702 Extract MQTT client_id from client certificate and propagate to authnz backends
  deps/rabbit/src/rabbit_ssl.erl
  deps/rabbitmq_ct_helpers/tools/tls-certs/openssl.cnf.in
  deps/rabbitmq_mqtt/BUILD.bazel
  deps/rabbitmq_mqtt/priv/schema/rabbitmq_mqtt.schema
  deps/rabbitmq_mqtt/src/rabbit_mqtt_processor.erl
  deps/rabbitmq_mqtt/test/auth_SUITE.erl
  deps/rabbitmq_mqtt/test/config_schema_SUITE_data/rabbitmq_mqtt.snippets
Labels: bazel, backport-v4.0.x

#12165 Run Selenium suites against a cluster of nodes
  .github/workflows/test-selenium.yaml
  deps/rabbitmq_management/selenium/bin/components/rabbitmq
  deps/rabbitmq_management/selenium/bin/components/selenium
  deps/rabbitmq_management/selenium/bin/gen-advanced-config
  deps/rabbitmq_management/selenium/bin/rabbit-compose.yml
  deps/rabbitmq_management/selenium/bin/suite_template
  deps/rabbitmq_management/selenium/package.json
  deps/rabbitmq_management/selenium/test/authnz-msg-protocols/amqp10.js
  deps/rabbitmq_management/selenium/test/authnz-msg-protocols/mqtt.js
  deps/rabbitmq_management/selenium/test/authnz-msg-protocols/rabbitmq.cluster.conf
  deps/rabbitmq_management/selenium/test/basic-auth/rabbitmq.cluster.conf
  deps/rabbitmq_management/selenium/test/basic-auth/rabbitmq.conf
  deps/rabbitmq_management/selenium/test/env.cluster
  deps/rabbitmq_management/selenium/test/multi-oauth/rabbitmq.cluster.conf
  deps/rabbitmq_management/selenium/test/oauth/keycloak/test-realm.json
  deps/rabbitmq_management/selenium/test/oauth/rabbitmq.cluster.conf
  deps/rabbitmq_management/selenium/test/oauth/with-sp-initiated/unauthorized.js
  deps/rabbitmq_management/selenium/test/utils.js
  deps/rabbitmq_management/selenium/test/vhosts/Makefile
Labels: make, backport-v4.0.x

#12148 Add prometheus tags "raft_cluster" to non-QQ raft metrics
  deps/rabbitmq_prometheus/src/collectors/prometheus_rabbitmq_core_metrics_collector.erl
Labels: backport-v3.13.x, backport-v4.0.x

#12215 Add connection duration to "closing AMQP connection..." msgs
  deps/rabbit/src/rabbit_reader.erl
Labels: backport-v4.0.x

#11672 Bump Ra from 2.13.6 to 2.14.0 + Khepri from 0.14.0 to 0.15.0
  MODULE.bazel
  deps/rabbit/src/rabbit_db_maintenance.erl
  deps/rabbit/src/rabbit_khepri.erl
  rabbitmq-components.mk
Labels: bazel, make

#12220 Use snake case instead of camel case
  deps/rabbit/src/rabbit_quorum_queue.erl
Labels: backport-v3.13.x, backport-v4.0.x

#11795 Unify Khepri paths API
  deps/rabbit/src/rabbit_db_binding.erl
  deps/rabbit/src/rabbit_db_binding_m2k_converter.erl
  deps/rabbit/src/rabbit_db_exchange.erl
  deps/rabbit/src/rabbit_db_exchange_m2k_converter.erl
  deps/rabbit/src/rabbit_db_maintenance.erl
  deps/rabbit/src/rabbit_db_maintenance_m2k_converter.erl
  deps/rabbit/src/rabbit_db_msup.erl
  deps/rabbit/src/rabbit_db_msup_m2k_converter.erl
  deps/rabbit/src/rabbit_db_queue.erl
  deps/rabbit/src/rabbit_db_queue_m2k_converter.erl
  deps/rabbit/src/rabbit_db_rtparams.erl
  deps/rabbit/src/rabbit_db_rtparams_m2k_converter.erl
  deps/rabbit/src/rabbit_db_user.erl
  deps/rabbit/src/rabbit_db_user_m2k_converter.erl
  deps/rabbit/src/rabbit_db_vhost.erl
  deps/rabbit/src/rabbit_db_vhost_m2k_converter.erl
  deps/rabbit/src/rabbit_khepri.erl
  deps/rabbit/src/rabbit_table.erl
  deps/rabbit/test/metadata_store_phase1_SUITE.erl
  deps/rabbitmq_consistent_hash_exchange/src/rabbit_db_ch_exchange.erl
  deps/rabbitmq_consistent_hash_exchange/src/rabbit_db_ch_exchange_m2k_converter.erl
  deps/rabbitmq_jms_topic_exchange/src/rabbit_db_jms_exchange.erl
  deps/rabbitmq_jms_topic_exchange/src/rabbit_db_jms_exchange_m2k_converter.erl
  deps/rabbitmq_recent_history_exchange/src/rabbit_db_rh_exchange.erl
  deps/rabbitmq_recent_history_exchange/src/rabbit_db_rh_exchange_m2k_converter.erl
  deps/rabbitmq_shovel/test/rolling_upgrade_SUITE.erl
Labels: bazel, make

#12236 Fix message resend bug in rabbit_stream_queue
  deps/rabbit/src/rabbit_stream_queue.erl
  deps/rabbit/test/amqp_client_SUITE.erl
Labels: bug, backport-v4.0.x

#12234 Support handle-max
  deps/rabbit/BUILD.bazel
  deps/rabbit/Makefile
  deps/rabbit/priv/schema/rabbit.schema
  deps/rabbit/src/rabbit_amqp_reader.erl
  deps/rabbit/src/rabbit_amqp_session.erl
  deps/rabbit/test/amqp_client_SUITE.erl
  deps/rabbit/test/amqp_credit_api_v2_SUITE.erl
  deps/rabbit/test/config_schema_SUITE_data/rabbit.snippets
Labels: bazel, make, backport-v4.0.x

#12248 Simplify session reply frames
  deps/rabbit/src/rabbit_amqp_session.erl
Labels: backport-v4.0.x

#12250 QQ: a delivery-limit of -1 disables the delivery limit.
  deps/rabbit/src/rabbit_fifo.erl
  deps/rabbit/src/rabbit_fifo.hrl
  deps/rabbit/src/rabbit_policies.erl
  deps/rabbit/src/rabbit_quorum_queue.erl
  deps/rabbit/test/quorum_queue_SUITE.erl
  deps/rabbit/test/rabbit_fifo_SUITE.erl
  deps/rabbit/test/unit_policy_validators_SUITE.erl
  deps/rabbit/test/unit_quorum_queue_SUITE.erl
  deps/rabbitmq_management/priv/www/js/global.js
  release-notes/4.0.0.md
Labels: backport-v4.0.x

#12264 make: Fix regressions following make plugins cleanup
  deps/amqp10_client/Makefile
  deps/rabbitmq_amqp_client/Makefile
  deps/rabbitmq_ct_helpers/Makefile
Labels: make

#12267 Management UI: remove disk read and write metrics from overview page.
  deps/rabbitmq_management/priv/www/js/charts.js
  deps/rabbitmq_management/priv/www/js/global.js
Labels: backport-v4.0.x

#12279 Handle Khepri timeouts when deleting MQTT QOS0 queues
  deps/rabbit/src/rabbit_amqqueue.erl
  deps/rabbit/src/rabbit_classic_queue.erl
  deps/rabbit/src/rabbit_quorum_queue.erl
  deps/rabbitmq_mqtt/src/rabbit_mqtt_qos0_queue.erl
Labels: backport-v3.13.x, backport-v4.0.x

#12280 rabbit_khepri: Retry fence in init/1 in cases of timeout
  deps/rabbit/src/rabbit_khepri.erl
Labels: backport-v4.0.x

#12270 Use openssl.cnf config when generating new CSR
  deps/rabbitmq_ct_helpers/tools/tls-certs/Makefile
Labels: make, backport-v3.13.x, backport-v4.0.x

#12276 Increase the timeout when batch deleting permissions
  deps/rabbit/src/rabbit_db_user.erl
  deps/rabbit/test/cluster_minority_SUITE.erl
Labels: backport-v4.0.x

#12286 Tweak wording around experimental feature flags (Khepri)
  deps/rabbit/src/rabbit_core_ff.erl
  deps/rabbitmq_management/priv/www/js/tmpl/feature-flags.ejs
Labels: backport-v4.0.x

#12294 More copywriting tweaks around the Khepri feature flag
  deps/rabbit/src/rabbit_core_ff.erl
  deps/rabbitmq_management/priv/www/js/tmpl/feature-flags.ejs
Labels: backport-v4.0.x

#12300 Update khepri to 0.16.0
  MODULE.bazel
  rabbitmq-components.mk
Labels: bazel, make

#12304 Revert "Log errors from `ranch:handshake`"
  deps/rabbit/src/rabbit_networking.erl
  deps/rabbit/src/rabbit_reader.erl
  deps/rabbitmq_mqtt/src/rabbit_mqtt_reader.erl
  deps/rabbitmq_stomp/src/rabbit_stomp_reader.erl
  deps/rabbitmq_stream/src/rabbit_stream_reader.erl
Labels: backport-v4.0.x

#12306 Fix formatter crash
  deps/rabbit/src/rabbit_upgrade_preparation.erl
Labels: backport-v3.13.x, backport-v4.0.x

#12303 forget_cluster_node: delete all local classic queues when using Khepri store
  deps/rabbit/src/rabbit_amqqueue.erl
  deps/rabbit/src/rabbit_khepri.erl
  deps/rabbit/test/cli_forget_cluster_node_SUITE.erl
Labels: backport-v4.0.x

#12310 QQ: unblock publishers when queue length policy is deleted
  deps/rabbit/src/rabbit_fifo.erl
  deps/rabbit/test/quorum_queue_SUITE.erl
Labels: backport-v3.13.x, backport-v4.0.x

#12317 Handle database timeouts in MQTT queue deletion
  deps/rabbit/src/rabbit_amqqueue.erl
  deps/rabbit/src/rabbit_classic_queue.erl
  deps/rabbit/src/rabbit_queue_type.erl
  deps/rabbit/src/rabbit_quorum_queue.erl
  deps/rabbit/src/rabbit_stream_coordinator.erl
  deps/rabbit/src/rabbit_stream_queue.erl
  deps/rabbitmq_mqtt/src/rabbit_mqtt_processor.erl
  deps/rabbitmq_mqtt/src/rabbit_mqtt_qos0_queue.erl
Labels: backport-v4.0.x

#12322 Khepri feature flag: add a documentation URL
  deps/rabbit/src/rabbit_core_ff.erl
Labels: backport-v4.0.x

#12325 cli enable_feature_flag: --experimental becomes --opt-in
  deps/rabbitmq_cli/lib/rabbitmq/cli/ctl/commands/enable_feature_flag_command.ex
  deps/rabbitmq_cli/test/ctl/enable_feature_flag_test.exs
Labels: backport-v4.0.x

#12327 Fix modified annotations
  deps/amqp10_client/src/amqp10_client_session.erl
  deps/amqp10_client/test/system_SUITE.erl
  deps/amqp10_common/src/amqp10_framing.erl
  deps/amqp10_common/test/prop_SUITE.erl
  deps/rabbit/src/rabbit_amqp_session.erl
  deps/rabbit/test/amqp_client_SUITE.erl
  deps/rabbit/test/amqp_system_SUITE_data/fsharp-tests/Program.fs
  deps/rabbit/test/mc_unit_SUITE.erl
  deps/rabbitmq_consistent_hash_exchange/test/rabbit_exchange_type_consistent_hash_SUITE.erl
  deps/rabbitmq_mqtt/test/mc_mqtt_SUITE.erl
  deps/rabbitmq_shovel/test/amqp10_dynamic_SUITE.erl
  release-notes/4.0.0.md
Labels: bug, backport-v4.0.x, breaking-change

#12352 Decrease default MQTT Maximum Packet Size
  deps/rabbitmq_mqtt/BUILD.bazel
  deps/rabbitmq_mqtt/Makefile
  deps/rabbitmq_mqtt/src/rabbit_mqtt.erl
  release-notes/4.1.0.md
Labels: bazel, make, breaking-change

#12348 Make rabbit_table:wait/2 silent when checking if cmq are used
  deps/rabbit/src/rabbit_mirror_queue_misc.erl
  deps/rabbit/src/rabbit_table.erl
Labels: backport-v4.0.x

#12358 QQ: fix off-by-one bug in release cursor effects.
  deps/rabbit/src/rabbit_fifo.erl
  deps/rabbit/test/rabbit_fifo_SUITE.erl
Labels: bug, backport-v4.0.x

#12357 Fix non-canonical and broken links
  deps/rabbit/BUILD.bazel
  deps/rabbit/INSTALL
  deps/rabbit/Makefile
  deps/rabbit/README.md
  deps/rabbit/SECURITY.md
  deps/rabbit/docs/README-for-packages
  deps/rabbit/docs/advanced.config.example
  deps/rabbit/docs/rabbitmq-diagnostics.8
  deps/rabbit/docs/rabbitmq-plugins.8
  deps/rabbit/docs/rabbitmq-queues.8
  deps/rabbit/docs/rabbitmq-server.8
  deps/rabbit/docs/rabbitmq-server.service.example
  deps/rabbit/docs/rabbitmq-service.8
  deps/rabbit/docs/rabbitmq-streams.8
  deps/rabbit/docs/rabbitmq-upgrade.8
  deps/rabbit/docs/rabbitmq.conf.example
  deps/rabbit/docs/rabbitmqctl.8
  deps/rabbit/priv/schema/rabbit.schema
  deps/rabbit/src/rabbit_core_ff.erl
  deps/rabbit/src/rabbit_health_check.erl
  deps/rabbit/src/rabbit_ssl.erl
  deps/rabbit/test/amqp_client_SUITE.erl
  deps/rabbit/test/dead_lettering_SUITE.erl
  deps/rabbit/test/policy_SUITE.erl
Labels: bazel, make

#12342 Emit histogram metric for received message sizes per protocol
  deps/rabbit/BUILD.bazel
  deps/rabbit/app.bzl
  deps/rabbit/src/rabbit_amqp_session.erl
  deps/rabbit/src/rabbit_channel.erl
  deps/rabbit/src/rabbit_global_counters.erl
  deps/rabbit/src/rabbit_msg_size_metrics.erl
  deps/rabbit/test/msg_size_metrics_SUITE.erl
  deps/rabbit/test/unit_msg_size_metrics_SUITE.erl
  deps/rabbitmq_mqtt/src/rabbit_mqtt.erl
  deps/rabbitmq_mqtt/src/rabbit_mqtt_processor.erl
  deps/rabbitmq_mqtt/test/shared_SUITE.erl
  deps/rabbitmq_prometheus/app.bzl
  deps/rabbitmq_prometheus/src/collectors/prometheus_rabbitmq_global_metrics_collector.erl
  deps/rabbitmq_prometheus/src/collectors/prometheus_rabbitmq_message_size_metrics_collector.erl
  deps/rabbitmq_prometheus/src/rabbit_prometheus_dispatcher.erl
  deps/rabbitmq_prometheus/test/rabbit_prometheus_http_SUITE.erl
  moduleindex.yaml
Labels: bazel

#12370 CI: Enable test.yaml on v4.0.x
  .github/workflows/templates/test.template.yaml
  .github/workflows/test.yaml
Labels: backport-v4.0.x

#12386 rabbitmqadmin v1: add default-queue-type to vhost declaration
  deps/rabbitmq_management/bin/rabbitmqadmin
Labels: backport-v3.13.x, backport-v4.0.x

#12394 Make it possible to override the license line in the startup banner
  deps/rabbit/src/rabbit.erl
Labels: backport-v3.13.x, backport-v4.0.x

#12390 Remove duplicate stats keys in quorum queues
  deps/rabbit/src/rabbit_quorum_queue.erl
Labels: backport-v3.13.x, backport-v4.0.x

#12391 Comply with §2.2.2 of Anonymous Terminus extension
  deps/amqp10_client/src/amqp10_client_session.erl
  deps/rabbit/src/rabbit_amqp_session.erl
  deps/rabbit/test/amqp_address_SUITE.erl
  deps/rabbit/test/amqp_auth_SUITE.erl
  deps/rabbit/test/amqp_client_SUITE.erl
Labels: backport-v4.0.x

#12393 Bump secondary umbrella to 4.0, re-enable Khepri mixed versions
  .github/workflows/test-plugin-mixed.yaml
  MODULE.bazel
  bazel/bzlmod/secondary_umbrella.bzl
  rabbitmq.bzl
Labels: bazel

#12405 Fix function_clause
  deps/rabbit/src/mc_compat.erl
  deps/rabbit/test/mc_unit_SUITE.erl
Labels: bug, backport-v4.0.x
