Repository rabbitmq/rabbitmq-server, pull requests merged in 2024-04, with the labels that each got.

#10896 Be more defensive when importing definitions where some virtual hosts do not have a default queue type
  deps/rabbit/src/rabbit_vhost.erl
Labels: backport-v3.12.x, backport-v3.13.x

#10891 Be more defensive when importing definitions where some virtual hosts do not have a default queue type
  deps/rabbit/src/rabbit_vhost.erl
Labels: backport-v3.12.x, backport-v3.13.x

#10869 Remove rules_docker in favor of rules_oci
  .bazelrc
  .github/workflows/oci.yaml
  .github/workflows/rabbitmq_peer_discovery_aws.yaml
  .github/workflows/test-authnz.yaml
  .github/workflows/test-erlang-git.yaml
  .github/workflows/test-mixed-versions.yaml
  .github/workflows/test-selenium.yaml
  .github/workflows/test.yaml
  BUILD.bazel
  MODULE.bazel
  WORKSPACE
  packaging/docker-image/10-defaults.conf
  packaging/docker-image/20-management_agent.disable_metrics_collector.conf
  packaging/docker-image/BUILD.bazel
  packaging/docker-image/Dockerfile
  packaging/docker-image/build_install_openssl.sh
  packaging/docker-image/build_install_otp.sh
  packaging/docker-image/docker-entrypoint.sh
  packaging/docker-image/install_rabbitmq.sh
  packaging/docker-image/test_configs/openssl_ubuntu.yaml
  packaging/docker-image/test_configs/otp_ubuntu.yaml
  packaging/docker-image/test_configs/rabbitmq_ubuntu.yaml
Labels: bazel, backport-v3.13.x

#10917 Require feature flag message_containers
  deps/rabbit/BUILD.bazel
  deps/rabbit/app.bzl
  deps/rabbit/src/mc_amqpl.erl
  deps/rabbit/src/rabbit_core_ff.erl
  deps/rabbit/test/amqp_client_SUITE.erl
  deps/rabbit/test/dead_lettering_SUITE.erl
  deps/rabbit/test/dynamic_ha_SUITE.erl
  deps/rabbit/test/dynamic_qq_SUITE.erl
  deps/rabbit/test/eager_sync_SUITE.erl
  deps/rabbit/test/mc_unit_SUITE.erl
  deps/rabbit/test/message_containers_SUITE.erl
  deps/rabbit/test/priority_queue_SUITE.erl
  deps/rabbit/test/queue_type_SUITE.erl
  deps/rabbit/test/quorum_queue_SUITE.erl
  deps/rabbit/test/rabbit_fifo_dlx_integration_SUITE.erl
  deps/rabbit/test/unit_classic_mirrored_queue_sync_throttling_SUITE.erl
  deps/rabbitmq_mqtt/src/rabbit_mqtt_processor.erl
  deps/rabbitmq_mqtt/test/ff_SUITE.erl
  rabbitmq.bzl
Labels: bazel

#10873 Introduce new AMQP 1.0 address format
  deps/amqp10_client/src/amqp10_client_session.erl
  deps/amqp10_client/test/system_SUITE.erl
  deps/rabbit/BUILD.bazel
  deps/rabbit/app.bzl
  deps/rabbit/src/mc.erl
  deps/rabbit/src/mc_amqp.erl
  deps/rabbit/src/rabbit.erl
  deps/rabbit/src/rabbit_amqp_management.erl
  deps/rabbit/src/rabbit_amqp_reader.erl
  deps/rabbit/src/rabbit_amqp_session.erl
  deps/rabbit/test/amqp_address_SUITE.erl
  deps/rabbit/test/amqp_auth_SUITE.erl
  deps/rabbit/test/amqp_client_SUITE.erl
  deps/rabbit/test/per_node_limit_SUITE.erl
  deps/rabbit_common/src/rabbit_routing_parser.erl
  deps/rabbitmq_amqp_client/test/management_SUITE.erl
  deps/rabbitmq_ct_helpers/src/rabbit_ct_helpers.erl
  deps/rabbitmq_mqtt/BUILD.bazel
  deps/rabbitmq_mqtt/Makefile
  deps/rabbitmq_mqtt/src/mc_mqtt.erl
  deps/rabbitmq_mqtt/test/mc_mqtt_SUITE.erl
  deps/rabbitmq_mqtt/test/protocol_interop_SUITE.erl
  deps/rabbitmq_shovel_management/test/http_SUITE.erl
  deps/rabbitmq_stomp/test/proxy_protocol_SUITE.erl
  deps/rabbitmq_stream/test/protocol_interop_SUITE.erl
Labels: bazel, make

#10930 bazel run gazelle
  deps/rabbit/BUILD.bazel
Labels: bazel

#10916 Make more TLS client options configurable for Kubernetes peer discovery
  deps/rabbitmq_peer_discovery_k8s/priv/schema/rabbitmq_peer_discovery_k8s.schema
  deps/rabbitmq_peer_discovery_k8s/src/rabbit_peer_discovery_k8s.erl
  deps/rabbitmq_peer_discovery_k8s/test/config_schema_SUITE_data/certs/cacert.pem
  deps/rabbitmq_peer_discovery_k8s/test/config_schema_SUITE_data/certs/cert.pem
  deps/rabbitmq_peer_discovery_k8s/test/config_schema_SUITE_data/certs/key.pem
  deps/rabbitmq_peer_discovery_k8s/test/config_schema_SUITE_data/namespace.txt
  deps/rabbitmq_peer_discovery_k8s/test/config_schema_SUITE_data/rabbitmq_peer_discovery_k8s.snippets
  deps/rabbitmq_peer_discovery_k8s/test/config_schema_SUITE_data/token.txt
Labels: backport-v3.13.x

#10931 Ensure queue data for `members`, etc is sorted upon input
  deps/rabbitmq_management_agent/src/rabbit_mgmt_format.erl
Labels: backport-v3.13.x

#10941 Always use GHCR when building the docker image
  .github/workflows/oci.yaml
  packaging/docker-image/BUILD.bazel
  packaging/docker-image/Dockerfile
Labels: bazel, backport-v3.13.x

#10819 rabbitmq-server: Propagate exit code
  deps/rabbit/scripts/rabbitmq-server
Labels: backport-v3.13.x

#10953 Avoid creation of binaries in AMQP 1.0 generator
  deps/amqp10_client/src/amqp10_client_session.erl
  deps/amqp10_common/app.bzl
  deps/amqp10_common/codegen.py
  deps/amqp10_common/src/amqp10_binary_generator.erl
  deps/amqp10_common/src/amqp10_framing.erl
  deps/amqp10_common/src/amqp10_util.erl
  deps/rabbit/src/rabbit_amqp_reader.erl
  deps/rabbit/src/rabbit_amqp_session.erl
  deps/rabbit/src/rabbit_amqp_writer.erl
  deps/rabbit/src/rabbit_fifo.erl
  deps/rabbit/src/rabbit_queue_consumers.erl
  deps/rabbit/src/rabbit_queue_type.erl
  deps/rabbit/src/rabbit_stream_queue.erl
  moduleindex.yaml
Labels: bazel

#10955 No need for `|| exit "$?"`
  deps/rabbit/scripts/rabbitmq-server
Labels: backport-v3.13.x

#10976 changed log line to allow for MaxConsumers being an integer not a string
  deps/rabbit/src/rabbit_channel.erl
Labels: backport-v3.13.x

#10908 Handle non-existent virtual host in several HTTP API endpoints
  deps/rabbitmq_management/src/rabbit_mgmt_wm_exchange_publish.erl
  deps/rabbitmq_management/src/rabbit_mgmt_wm_queue_actions.erl
  deps/rabbitmq_management/src/rabbit_mgmt_wm_queue_get.erl
Labels: backport-v3.13.x

#10961 GitHub Actions: Add GHCR login step to `test-{authnz,selenium}.yaml` workflows
  .github/workflows/oci.yaml
  .github/workflows/test-authnz.yaml
  .github/workflows/test-selenium.yaml
Labels: backport-v3.13.x

#10983 erlang_ls: Add `deps/*/` to include dirs
  erlang_ls.config
Labels: backport-v3.13.x

#10985 bazel: Remove committed files from //tools:symlink_deps_for_erlang_ls
  tools/erlang_ls.bzl
Labels: bazel, backport-v3.13.x

#10928 Prefer `erlang:monotonic_time/0` for elapsed time measurements
  deps/rabbit/src/rabbit_boot_steps.erl
  deps/rabbit/src/rabbit_deprecated_features.erl
  deps/rabbit/src/rabbit_feature_flags.erl
  deps/rabbit/src/rabbit_ff_registry_factory.erl
  deps/rabbitmq_ct_helpers/src/rabbit_ct_broker_helpers.erl
Labels: backport-v3.13.x

#10993 Adopt otp 25.3.2.11
  MODULE.bazel
  WORKSPACE
Labels: bazel, backport-v3.11.x, backport-v3.12.x

#10995 Fix mnesia deletion return value in recent history exchange cleanup
  deps/rabbitmq_recent_history_exchange/src/rabbit_db_rh_exchange.erl
  deps/rabbitmq_recent_history_exchange/test/system_SUITE.erl
Labels: backport-v3.13.x

#10999 Print more logs when stream connection fails to open
  deps/rabbitmq_stream/src/rabbit_stream_reader.erl
Labels: backport-v3.12.x, backport-v3.13.x

#10952 Remove duplicate code that built ssl options
  deps/oauth2_client/src/oauth2_client.erl
  deps/oauth2_client/test/system_SUITE.erl
  deps/oauth2_client/test/unit_SUITE.erl
  deps/rabbitmq_auth_backend_oauth2/priv/schema/rabbitmq_auth_backend_oauth2.schema
  deps/rabbitmq_auth_backend_oauth2/src/uaa_jwks.erl
  deps/rabbitmq_auth_backend_oauth2/test/jwks_SUITE.erl
Labels: backport-v3.13.x

#11005 Update startup banner link for the new website
  deps/rabbit/src/rabbit.erl
Labels: backport-v3.13.x

#11007 Update management UI footer links for the new website
  deps/rabbitmq_management/priv/www/js/tmpl/layout.ejs
Labels: backport-v3.13.x

#11012 Store MQTT messages as non-durable if QoS 0
  deps/rabbitmq_mqtt/src/mc_mqtt.erl
  deps/rabbitmq_mqtt/test/mc_mqtt_SUITE.erl
  deps/rabbitmq_mqtt/test/protocol_interop_SUITE.erl
Labels: backport-v3.13.x

#11014 Fix some dialyzer build system errors in make
  Makefile
  deps/amqp10_common/Makefile
  deps/amqp10_common/test/serial_number_SUITE.erl
  deps/oauth2_client/Makefile
  deps/rabbitmq_ct_client_helpers/Makefile
  deps/rabbitmq_ct_helpers/Makefile
  deps/rabbitmq_ct_helpers/WORKSPACE.bazel
  deps/rabbitmq_stream_common/Makefile
Labels: bazel, make, backport-v3.13.x

#11016 Fix make dialyze for deps/rabbit
  deps/rabbit/Makefile
Labels: make

#11019 Add dep_gen_batch_server to rabbitmq-components.mk
  deps/rabbitmq_prelaunch/Makefile
  rabbitmq-components.mk
Labels: make

#11022 bazel run gazelle
  deps/rabbit/app.bzl
Labels: bazel

#11023 Skip access check on absent will queue
  deps/rabbitmq_mqtt/src/rabbit_mqtt_processor.erl
  deps/rabbitmq_mqtt/test/auth_SUITE.erl
Labels: backport-v3.13.x

#11039 Fix deps for rabbit_common in make
  deps/rabbit_common/Makefile
Labels: make, backport-v3.13.x

#11042 Use make for OCI workflow
  .github/workflows/oci-base.yaml
  .github/workflows/oci-make.yaml
  .github/workflows/oci.yaml
  .github/workflows/rabbitmq_peer_discovery_aws.yaml
  packaging/base-image/.dockerignore
  packaging/base-image/BUILD.bazel
  packaging/base-image/Dockerfile
  packaging/docker-image/.gitignore
  packaging/docker-image/BUILD.bazel
  packaging/docker-image/Dockerfile
  packaging/docker-image/Makefile
Labels: bazel, make, backport-v3.13.x

#11044 Provide more descriptive type spec
  deps/rabbit/include/mc.hrl
  deps/rabbit/src/mc_amqp.erl
Labels: backport-v3.13.x

#11057 Set durable annotation for MQTT messages
  deps/rabbitmq_mqtt/src/mc_mqtt.erl
Labels: backport-v3.13.x

#11058 Fix failing auth test
  .github/workflows/test-authnz.yaml
  deps/rabbitmq_management/selenium/test/authnz-msg-protocols/mqtt.js
Labels: backport-v3.13.x

#11060 rabbitmq-diagnostics observer: fix accepting user input
  deps/rabbit/scripts/rabbitmq-diagnostics
  deps/rabbit/scripts/rabbitmqctl
Labels: backport-v3.13.x

#11054 Make the OCI workflows conditional on push access
  .github/workflows/oci-make.yaml
  .github/workflows/rabbitmq_peer_discovery_aws.yaml
  .github/workflows/test-authnz.yaml
  .github/workflows/test-selenium.yaml
Labels: backport-v3.13.x

#11070 Speed up 'rabbitmqctl stop_app'
  deps/rabbitmq_management_agent/src/rabbit_mgmt_db_handler.erl
Labels: backport-v3.13.x

#11097 Replicate x_jms_topic_table Mnesia table (backport #11087)
  deps/rabbit/src/rabbit_maintenance.erl
  deps/rabbit/src/rabbit_table.erl
  deps/rabbitmq_jms_topic_exchange/src/rabbit_jms_topic_exchange.erl
Labels: bug

#11102 Remove duplicate rabbitmq_auth_backend_http in plugins.mk
  plugins.mk
Labels: make

#11077 Notify of permission and parameter deletions when deleting a vhost
  deps/rabbit/src/rabbit_auth_backend_internal.erl
  deps/rabbit/src/rabbit_db_rtparams.erl
  deps/rabbit/src/rabbit_db_user.erl
  deps/rabbit/src/rabbit_khepri.erl
  deps/rabbit/src/rabbit_runtime_parameters.erl
  deps/rabbit/src/rabbit_vhost.erl
  deps/rabbit/src/rabbit_vhost_limit.erl
  deps/rabbit/test/vhost_SUITE.erl
  deps/rabbitmq_management/src/rabbit_mgmt_wm_vhost.erl
Labels: backport-v3.13.x

#11101 Cleanup shovels deleted from another node
  deps/rabbitmq_shovel/src/rabbit_shovel_dyn_worker_sup_sup.erl
  deps/rabbitmq_shovel/src/rabbit_shovel_worker.erl
  deps/rabbitmq_shovel/test/delete_shovel_command_SUITE.erl
Labels: backport-v3.13.x

#11113 Ra 2.10.0
  MODULE.bazel
  bazel/BUILD.ra
  moduleindex.yaml
  rabbitmq-components.mk
Labels: dependencies, bazel, make, backport-v3.13.x

#11116 List shovels on all nodes
  deps/rabbitmq_shovel/src/Elixir.RabbitMQ.CLI.Ctl.Commands.ShovelStatusCommand.erl
Labels: backport-v3.13.x

#11114 Fix make dialyze for a number of plugins
  deps/rabbit_common/mk/rabbitmq-early-test.mk
  deps/rabbitmq_auth_backend_oauth2/Makefile
  deps/rabbitmq_consistent_hash_exchange/Makefile
  deps/rabbitmq_management_agent/Makefile
  deps/rabbitmq_mqtt/Makefile
  deps/rabbitmq_prelaunch/Makefile
  deps/rabbitmq_recent_history_exchange/Makefile
  deps/rabbitmq_shovel/Makefile
  deps/rabbitmq_stomp/Makefile
  deps/rabbitmq_stream/Makefile
  deps/rabbitmq_web_mqtt/Makefile
  deps/rabbitmq_web_stomp/Makefile
Labels: make, backport-v3.13.x

#11065 Better handle QQ delete member operation when member already removed
  deps/rabbit/src/rabbit_quorum_queue.erl
  deps/rabbit/test/quorum_queue_SUITE.erl
Labels: make, backport-v3.13.x

#11124 Add rabbitmqctl to rabbitmq_federation PLT_APPS
  deps/rabbitmq_federation/Makefile
Labels: make, backport-v3.13.x

#11131 3.13.2 release notes
  release-notes/3.13.2.md
Labels: backport-v3.13.x
