Repository rabbitmq/rabbitmq-server, pull requests merged in 2024-07, with the labels that each got.

#11585 Management UI: Fix internal_server_error args for put vhost failures
  deps/rabbitmq_management/src/rabbit_mgmt_util.erl
  deps/rabbitmq_management/src/rabbit_mgmt_wm_vhost.erl
Labels: backport-v3.13.x

#11582 Various test improvements
  deps/rabbit/BUILD.bazel
  deps/rabbit/test/bindings_SUITE.erl
  deps/rabbit/test/clustering_management_SUITE.erl
  deps/rabbit/test/clustering_recovery_SUITE.erl
  deps/rabbit/test/per_user_connection_channel_limit_SUITE.erl
  deps/rabbit/test/per_user_connection_channel_tracking_SUITE.erl
  deps/rabbit/test/per_user_connection_tracking_SUITE.erl
  deps/rabbit/test/per_vhost_connection_limit_SUITE.erl
  deps/rabbit/test/per_vhost_connection_limit_partitions_SUITE.erl
  deps/rabbit/test/per_vhost_msg_store_SUITE.erl
  deps/rabbit/test/per_vhost_queue_limit_SUITE.erl
  deps/rabbit/test/policy_SUITE.erl
  deps/rabbit/test/publisher_confirms_parallel_SUITE.erl
  deps/rabbit/test/queue_type_SUITE.erl
  deps/rabbit/test/rabbit_stream_queue_SUITE.erl
Labels: bazel

#11600 bazel run gazelle
  deps/rabbit/app.bzl
Labels: bazel

#11605 3.13.4 release notes
  release-notes/3.13.4.md
Labels: backport-v3.13.x

#11609 Don't build ARM64 OCI
  .github/workflows/oci-make.yaml
Labels: backport-v3.13.x

#11614 rabbit_runtime_parameters: Remove dead 'value_global/2', 'value/4'
  deps/rabbit/src/rabbit_db_rtparams.erl
  deps/rabbit/src/rabbit_runtime_parameters.erl
Labels: backport-v3.13.x

#11604 Use different AMQP address format for v1 and v2
  deps/rabbit/app.bzl
  deps/rabbit/src/rabbit_amqp_management.erl
  deps/rabbit/src/rabbit_amqp_session.erl
  deps/rabbit/src/rabbit_uri.erl
  deps/rabbit/test/amqp_address_SUITE.erl
  deps/rabbit/test/amqp_auth_SUITE.erl
  deps/rabbitmq_amqp_client/app.bzl
  deps/rabbitmq_amqp_client/src/rabbitmq_amqp_address.erl
  deps/rabbitmq_mqtt/src/mc_mqtt.erl
  deps/rabbitmq_mqtt/test/mc_mqtt_SUITE.erl
  deps/rabbitmq_mqtt/test/protocol_interop_SUITE.erl
  moduleindex.yaml
Labels: bazel

#11616 Split management HTTP API tests to reduce interference
  deps/rabbitmq_management/BUILD.bazel
  deps/rabbitmq_management/test/rabbit_mgmt_http_SUITE.erl
Labels: bazel

#11620 Use GHA cache for OCI; reenable ARM
  .github/workflows/oci-make.yaml
Labels: backport-v3.13.x

#11619 rabbit_definitions: ensure federation-upstream-set parameters are exported
  deps/rabbit/src/rabbit_definitions.erl
  deps/rabbitmq_cli/lib/rabbitmq/cli/ctl/commands/export_definitions_command.ex
  deps/rabbitmq_federation/BUILD.bazel
  deps/rabbitmq_federation/app.bzl
  deps/rabbitmq_federation/test/definition_import_SUITE.erl
  deps/rabbitmq_federation/test/definition_import_SUITE_data/case1.json
Labels: bazel, backport-v3.13.x

#11608 3.13.x only: fix timestamp when recovering x-death header
  deps/rabbit/src/mc_amqpl.erl
  deps/rabbit/test/dead_lettering_SUITE.erl
  deps/rabbit/test/mc_unit_SUITE.erl
Labels: bug, backport-pending

#11623 OTP27 compatibility for v3.13.x specific stuff
  deps/amqp10_client/src/amqp10_msg.erl
  deps/rabbit/src/rabbit_msg_record.erl
  erlang.mk
Labels: make

#11624 Diable ARM64 OCI
  .github/workflows/oci-make.yaml
Labels: backport-v3.13.x

#11630 Upgrade AMQP address format in tests
  deps/rabbit/BUILD.bazel
  deps/rabbit/test/amqp_client_SUITE.erl
  deps/rabbit/test/amqp_credit_api_v2_SUITE.erl
Labels: bazel

#11641 Add inter cluster AMQP 1.0 shovel test
  deps/rabbitmq_shovel/BUILD.bazel
  deps/rabbitmq_shovel/Makefile
  deps/rabbitmq_shovel/app.bzl
  deps/rabbitmq_shovel/test/amqp10_inter_cluster_SUITE.erl
  deps/rabbitmq_shovel/test/shovel_test_utils.erl
Labels: bazel, make

#11643 Consistent Hash doc improvement
  deps/rabbitmq_consistent_hash_exchange/README.md
Labels: backport-v3.13.x

#11642 Require MQTT feature flags in 4.0
  deps/rabbitmq_mqtt/BUILD.bazel
  deps/rabbitmq_mqtt/Makefile
  deps/rabbitmq_mqtt/app.bzl
  deps/rabbitmq_mqtt/include/mqtt_machine.hrl
  deps/rabbitmq_mqtt/include/mqtt_machine_v0.hrl
  deps/rabbitmq_mqtt/src/Elixir.RabbitMQ.CLI.Ctl.Commands.DecommissionMqttNodeCommand.erl
  deps/rabbitmq_mqtt/src/mqtt_machine.erl
  deps/rabbitmq_mqtt/src/mqtt_machine_v0.erl
  deps/rabbitmq_mqtt/src/mqtt_node.erl
  deps/rabbitmq_mqtt/src/rabbit_mqtt.erl
  deps/rabbitmq_mqtt/src/rabbit_mqtt_collector.erl
  deps/rabbitmq_mqtt/src/rabbit_mqtt_ff.erl
  deps/rabbitmq_mqtt/src/rabbit_mqtt_processor.erl
  deps/rabbitmq_mqtt/src/rabbit_mqtt_qos0_queue.erl
  deps/rabbitmq_mqtt/src/rabbit_mqtt_reader.erl
  deps/rabbitmq_mqtt/test/auth_SUITE.erl
  deps/rabbitmq_mqtt/test/cluster_SUITE.erl
  deps/rabbitmq_mqtt/test/command_SUITE.erl
  deps/rabbitmq_mqtt/test/ff_SUITE.erl
  deps/rabbitmq_mqtt/test/java_SUITE.erl
  deps/rabbitmq_mqtt/test/mqtt_machine_SUITE.erl
  deps/rabbitmq_mqtt/test/protocol_interop_SUITE.erl
  deps/rabbitmq_mqtt/test/proxy_protocol_SUITE.erl
  deps/rabbitmq_mqtt/test/reader_SUITE.erl
  deps/rabbitmq_mqtt/test/retainer_SUITE.erl
  deps/rabbitmq_mqtt/test/shared_SUITE.erl
  deps/rabbitmq_mqtt/test/util.erl
  deps/rabbitmq_mqtt/test/v5_SUITE.erl
  deps/rabbitmq_web_mqtt/src/rabbit_web_mqtt_handler.erl
  deps/rabbitmq_web_mqtt/test/command_SUITE.erl
  moduleindex.yaml
Labels: bazel, make

#11654 Take `-setcookie` argument into account for peer args
  deps/rabbit/src/rabbit_peer_discovery.erl
Labels: backport-v3.13.x

#11665 Fix direct reply to crash when tracing is enabled
  deps/rabbit/src/rabbit_trace.erl
  deps/rabbit/test/amqpl_direct_reply_to_SUITE.erl
Labels: bug, backport-v3.13.x

#11663 Turn off mixed version tests against Khepri
  .github/workflows/test-plugin-mixed.yaml
  deps/rabbit/test/cluster_minority_SUITE.erl
  deps/rabbit/test/clustering_management_SUITE.erl
  deps/rabbit/test/clustering_recovery_SUITE.erl
  deps/rabbit/test/metadata_store_clustering_SUITE.erl
  deps/rabbitmq_consistent_hash_exchange/BUILD.bazel
  deps/rabbitmq_consistent_hash_exchange/test/rabbit_exchange_type_consistent_hash_SUITE.erl
Labels: bazel, make, backport-v3.13.x

#11668 Bump `khepri` to 0.14.0, `khepri_mnesia_migration` to 0.5.0
  MODULE.bazel
  bazel/BUILD.khepri
  deps/rabbit/src/rabbit_khepri.erl
  deps/rabbit/test/cluster_minority_SUITE.erl
  deps/rabbitmq_cli/lib/rabbitmq/cli/default_output.ex
  moduleindex.yaml
  rabbitmq-components.mk
Labels: bazel, make

#11667 rabbit_db_*: Wrap `ets` calls to projections in `whereis/1` checks
  deps/rabbit/src/rabbit_db_binding.erl
  deps/rabbit/src/rabbit_db_exchange.erl
  deps/rabbit/src/rabbit_db_queue.erl
  deps/rabbit/src/rabbit_db_rtparams.erl
  deps/rabbit/src/rabbit_db_topic_exchange.erl
  deps/rabbit/src/rabbit_db_user.erl
  deps/rabbit/src/rabbit_db_vhost.erl
Labels: backport-v4.0.x

#11676 Catch abrupt TCP closure when processing `queue_event`
  deps/rabbitmq_mqtt/src/rabbit_mqtt_reader.erl
Labels: backport-v4.0.x

#11686 Fix elixir warning on build
  Makefile
Labels: make, backport-v4.0.x

#11695 bazel run gazelle
  deps/rabbitmq_peer_discovery_consul/app.bzl
Labels: bazel

#11565 Deprecate queue-master-locator
  deps/rabbit/BUILD.bazel
  deps/rabbit/Makefile
  deps/rabbit/app.bzl
  deps/rabbit/priv/schema/rabbit.schema
  deps/rabbit/src/rabbit_classic_queue.erl
  deps/rabbit/src/rabbit_core_ff.erl
  deps/rabbit/src/rabbit_queue_location.erl
  deps/rabbit/src/rabbit_queue_location_client_local.erl
  deps/rabbit/src/rabbit_queue_location_min_masters.erl
  deps/rabbit/src/rabbit_queue_location_random.erl
  deps/rabbit/src/rabbit_queue_location_validator.erl
  deps/rabbit/src/rabbit_queue_master_location_misc.erl
  deps/rabbit/src/rabbit_queue_master_locator.erl
  deps/rabbit/test/classic_queue_SUITE.erl
  deps/rabbit/test/queue_master_location_SUITE.erl
  deps/rabbit/test/rabbitmq_4_0_deprecations_SUITE.erl
  deps/rabbit/test/unit_queue_location_SUITE.erl
  deps/rabbit_common/src/rabbit_registry.erl
  deps/rabbitmq_management/priv/www/js/global.js
  deps/rabbitmq_management/priv/www/js/tmpl/policies.ejs
  deps/rabbitmq_management/priv/www/js/tmpl/queues.ejs
  moduleindex.yaml
Labels: bazel, make, backport-v4.0.x

#11696 Simplify
  deps/rabbitmq_mqtt/src/rabbit_mqtt_reader.erl
Labels: backport-v3.13.x, backport-v4.0.x

#11701 Fix queue type consumer arguments
  deps/rabbit/src/rabbit_classic_queue.erl
  deps/rabbit/src/rabbit_stream_queue.erl
Labels: backport-v4.0.x

#11700 Use 'try'/'catch' rather than 'ets:whereis/1' for Khepri projections
  deps/rabbit/src/rabbit_db_binding.erl
  deps/rabbit/src/rabbit_db_exchange.erl
  deps/rabbit/src/rabbit_db_queue.erl
  deps/rabbit/src/rabbit_db_rtparams.erl
  deps/rabbit/src/rabbit_db_topic_exchange.erl
  deps/rabbit/src/rabbit_db_user.erl
  deps/rabbit/src/rabbit_db_vhost.erl
Labels: backport-v4.0.x

#11705 Support consumer priority in AMQP
  deps/amqp10_client/src/amqp10_client_types.erl
  deps/rabbit/src/rabbit_amqp_session.erl
  deps/rabbit/src/rabbit_fifo.hrl
  deps/rabbit/test/amqp_client_SUITE.erl
Labels: backport-v4.0.x

#11709 bazel run gazelle
  deps/rabbit/BUILD.bazel
  deps/rabbit/app.bzl
Labels: bazel

#11710 bazel run gazelle
  deps/rabbit/BUILD.bazel
  deps/rabbit/app.bzl
Labels: bazel

#11713 Initial (very brief) 4.0.0 release notes
  release-notes/4.0.0.md
Labels: backport-v4.0.x

#11715 mc: increase utf8 scanning limit for longstr conversions.
  deps/rabbit/src/mc_amqpl.erl
  deps/rabbit/test/mc_unit_SUITE.erl
Labels: backport-v3.13.x, backport-v4.0.x

#11423 OAuth 2, breaking change: upgrade oidc-client-ts library to a new major
  deps/rabbitmq_management/app.bzl
  deps/rabbitmq_management/priv/www/js/oidc-oauth/helper.js
  deps/rabbitmq_management/priv/www/js/oidc-oauth/oidc-client-ts.3.0.1.min.js
  deps/rabbitmq_management/priv/www/js/oidc-oauth/oidc-client-ts.3.0.1.min.js.map
  deps/rabbitmq_management/priv/www/js/oidc-oauth/oidc-client-ts.js.map
  deps/rabbitmq_management/selenium/full-suite-management-ui
  deps/rabbitmq_management/selenium/short-suite-management-ui
  deps/rabbitmq_management/selenium/test/oauth/with-sp-initiated/unauthorized.js
Labels: bazel, backport-v4.0.x

#11716 CMQ cleanup
  deps/rabbit/docs/rabbitmqctl.8
  deps/rabbit/docs/set_rabbitmq_policy.sh.example
  deps/rabbitmq_cli/lib/rabbitmq/cli/queues/commands/check_if_node_is_mirror_sync_critical_command.ex
Labels: backport-v4.0.x

#11720 Handle empty HTTP body in response from AWS JSON
  deps/rabbitmq_aws/src/rabbitmq_aws_json.erl
Labels: backport-v4.0.x

#11724 bazel run gazelle
  deps/rabbitmq_management/app.bzl
Labels: bazel

#11725 bazel run gazelle
  deps/rabbitmq_management/app.bzl
Labels: bazel

#11698 Ra 2.13.1
  MODULE.bazel
  rabbitmq-components.mk
Labels: bazel, make, backport-v4.0.x

#11732 fix typos
  release-notes/4.0.0.md
Labels: backport-v4.0.x

#11746 Prometheus: expose memory breakdown metrics
  deps/rabbitmq_prometheus/src/collectors/prometheus_rabbitmq_core_metrics_collector.erl
  deps/rabbitmq_prometheus/test/rabbit_prometheus_http_SUITE.erl
Labels: backport-v4.0.x

#11758 Ra 2.13.2
  MODULE.bazel
  rabbitmq-components.mk
Labels: bazel, make, backport-v3.13.x, backport-v4.0.x

#11763 Add stream replication port range in ini-style configuration
  deps/rabbit/priv/schema/rabbit.schema
  deps/rabbit/test/config_schema_SUITE_data/rabbit.snippets
Labels: usability, backport-v4.0.x

#11770 3.13.5 release notes
  release-notes/3.13.5.md
Labels: backport-v3.13.x, backport-v4.0.x

#11779 Bump Ra to 2.13.4
  MODULE.bazel
  rabbitmq-components.mk
Labels: bazel, make, backport-v3.13.x, backport-v4.0.x

#11685 Handle timeouts possible in Khepri minority in `rabbit_db_binding`
  deps/rabbit/src/rabbit_binding.erl
  deps/rabbit/src/rabbit_channel.erl
  deps/rabbit/src/rabbit_db_binding.erl
  deps/rabbit/src/rabbit_definitions.erl
  deps/rabbit/src/rabbit_khepri.erl
  deps/rabbit/test/cluster_minority_SUITE.erl
  deps/rabbitmq_stream/src/rabbit_stream_manager.erl
Labels: backport-v4.0.x

#11788 Move memory breakdown metrics to new endpoint
  deps/rabbitmq_prometheus/src/collectors/prometheus_rabbitmq_core_metrics_collector.erl
  deps/rabbitmq_prometheus/src/rabbit_prometheus_dispatcher.erl
  deps/rabbitmq_prometheus/src/rabbit_prometheus_handler.erl
  deps/rabbitmq_prometheus/test/rabbit_prometheus_http_SUITE.erl
Labels: backport-v4.0.x

#11794 Ra v2.13.5
  MODULE.bazel
  rabbitmq-components.mk
Labels: bazel, make, backport-v3.13.x, backport-v4.0.x

#11800 3.13.6 release notes
  release-notes/3.13.3.md
  release-notes/3.13.4.md
  release-notes/3.13.5.md
  release-notes/3.13.6.md
Labels: backport-v3.13.x, backport-v4.0.x

#11808 Fix crash in consistent hash exchange
  deps/rabbitmq_consistent_hash_exchange/README.md
  deps/rabbitmq_consistent_hash_exchange/src/rabbit_exchange_type_consistent_hash.erl
  deps/rabbitmq_consistent_hash_exchange/test/rabbit_exchange_type_consistent_hash_SUITE.erl
Labels: bug, backport-v3.13.x, backport-v4.0.x

#11813 Fix test flake
  deps/rabbit/test/amqpl_direct_reply_to_SUITE.erl
Labels: backport-v3.13.x, backport-v4.0.x

#11814 Fix rabbit_priority_queue:update_rates bug
  deps/rabbit/src/rabbit_priority_queue.erl
  deps/rabbit/test/priority_queue_SUITE.erl
Labels: backport-v4.0.x

#11809 QQ: use a dedicated function for queue recovery after Ra system restart.
  deps/rabbit/src/rabbit_quorum_queue.erl
  deps/rabbit/src/rabbit_ra_systems.erl
Labels: backport-v4.0.x

#11785 Handle timeouts possible in Khepri minority in `rabbit_db_exchange`
  deps/rabbit/src/rabbit_amqp_management.erl
  deps/rabbit/src/rabbit_channel.erl
  deps/rabbit/src/rabbit_db_exchange.erl
  deps/rabbit/src/rabbit_db_queue.erl
  deps/rabbit/src/rabbit_definitions.erl
  deps/rabbit/src/rabbit_exchange.erl
  deps/rabbit/src/rabbit_logger_exchange_h.erl
  deps/rabbit/src/rabbit_vhost.erl
  deps/rabbit/test/bindings_SUITE.erl
  deps/rabbit/test/cluster_minority_SUITE.erl
  deps/rabbit/test/exchanges_SUITE.erl
  deps/rabbit/test/routing_SUITE.erl
  deps/rabbit_common/src/rabbit_misc.erl
  deps/rabbitmq_cli/test/ctl/list_exchanges_command_test.exs
  deps/rabbitmq_event_exchange/src/rabbit_exchange_type_event.erl
  deps/rabbitmq_federation/test/unit_inbroker_SUITE.erl
  deps/rabbitmq_stream/src/rabbit_stream_manager.erl
Labels: backport-v4.0.x

#11793 Configure shovels to wait until all sources and destinations are declared
  deps/rabbitmq_shovel/app.bzl
  deps/rabbitmq_shovel/priv/schema/rabbitmq_shovel.schema
  deps/rabbitmq_shovel/src/rabbit_amqp091_shovel.erl
  deps/rabbitmq_shovel/src/rabbit_shovel_parameters.erl
  deps/rabbitmq_shovel/test/configuration_SUITE.erl
  deps/rabbitmq_shovel/test/dynamic_SUITE.erl
  deps/rabbitmq_shovel/test/shovel_test_utils.erl
Labels: rabbitmq-shovel, bazel, backport-v4.0.x

#11741 rabbit_khepri: Retry register_projections during boot
  deps/rabbit/src/rabbit_khepri.erl
  deps/rabbitmq_cli/lib/rabbitmq/cli/default_output.ex
Labels: backport-v4.0.x

#11706 Handle timeouts possible in Khepri minority in `rabbit_db_vhost`
  deps/rabbit/src/rabbit_db_vhost.erl
  deps/rabbit/src/rabbit_definitions.erl
  deps/rabbit/src/rabbit_vhost.erl
  deps/rabbitmq_management/src/rabbit_mgmt_wm_vhost.erl
Labels: backport-v4.0.x

#11664 rabbit_node_monitor: use a leader query for cluster members on node_added event
  deps/rabbit/BUILD.bazel
  deps/rabbit/app.bzl
  deps/rabbit/src/rabbit_db_cluster.erl
  deps/rabbit/src/rabbit_mnesia.erl
  deps/rabbit/src/rabbit_node_monitor.erl
  deps/rabbit/src/rabbit_nodes.erl
  deps/rabbit/test/clustering_events_SUITE.erl
Labels: bazel, backport-v4.0.x

#11839 bazel run gazelle
  deps/rabbit/BUILD.bazel
Labels: bazel

#11840 bazel run gazelle
  deps/rabbit/BUILD.bazel
Labels: bazel

#11843 Report frame_max as integer
  deps/rabbit/src/rabbit_amqp_reader.erl
  deps/rabbit/src/rabbit_amqp_writer.erl
Labels: backport-v4.0.x

#11846 Fix quorum queue credit reply crash in AMQP session
  deps/rabbit/src/rabbit_amqp_session.erl
  deps/rabbit/src/rabbit_fifo_client.erl
  deps/rabbit/test/amqp_client_SUITE.erl
Labels: bug, backport-v4.0.x

#11861 Make AMQP flow control configurable
  deps/rabbit/src/rabbit_amqp_session.erl
Labels: backport-v4.0.x

#11867 Disconnect MQTT client when its credential expires
  deps/rabbit/src/rabbit_amqp_reader.erl
  deps/rabbitmq_auth_backend_oauth2/BUILD.bazel
  deps/rabbitmq_auth_backend_oauth2/Makefile
  deps/rabbitmq_auth_backend_oauth2/test/system_SUITE.erl
  deps/rabbitmq_mqtt/src/rabbit_mqtt_processor.erl
  deps/rabbitmq_mqtt/src/rabbit_mqtt_reader.erl
  deps/rabbitmq_web_mqtt/src/rabbit_web_mqtt_handler.erl
Labels: bazel, make, backport-v3.13.x, backport-v4.0.x

#11870 Add test for AMQP 1.0 clients using OAuth token
  deps/rabbitmq_auth_backend_oauth2/BUILD.bazel
  deps/rabbitmq_auth_backend_oauth2/Makefile
  deps/rabbitmq_auth_backend_oauth2/test/system_SUITE.erl
Labels: bazel, make, backport-v4.0.x
