Repository rabbitmq/rabbitmq-server, pull requests merged in 2024-05, with the labels that each got.

#11137 Fix compatibility with openldap 2.5.x
  deps/rabbitmq_auth_backend_ldap/example/global.ldif
  deps/rabbitmq_auth_backend_ldap/example/memberof_init.ldif
  deps/rabbitmq_auth_backend_ldap/example/refint_2.ldif
  deps/rabbitmq_auth_backend_ldap/test/rabbit_ldap_seed.erl
  deps/rabbitmq_auth_backend_ldap/test/system_SUITE.erl
Labels: backport-v3.13.x

#11129 CI: Bump actions runner to Ubuntu 22.04
  .github/workflows/gazelle-scheduled.yaml
  .github/workflows/gazelle.yaml
  .github/workflows/perform-bazel-execution-comparison.yaml
  .github/workflows/rabbitmq_peer_discovery_aws.yaml
  .github/workflows/test-authnz.yaml
  .github/workflows/test-erlang-git.yaml
  .github/workflows/test-mixed-versions.yaml
  .github/workflows/test-selenium.yaml
  .github/workflows/test.yaml
  .github/workflows/update-elixir-patches.yaml
  .github/workflows/update-otp-patches.yaml
Labels: backport-v3.13.x

#11150 Avoid leaking nodes in rabbitmq_mqtt shared_SUITE
  deps/rabbitmq_mqtt/test/shared_SUITE.erl
Labels: backport-v3.13.x

#11152 Avoid oauth2_client being reported as a plugin
  deps/oauth2_client/BUILD.bazel
  deps/oauth2_client/Makefile
Labels: bazel, make, backport-v3.13.x

#11156 Adopt otp 25.3.2.12
  MODULE.bazel
  WORKSPACE
Labels: bazel, backport-v3.11.x, backport-v3.12.x

#11128 This should be logged at debug level
  deps/rabbit/src/rabbit_vhost.erl
Labels: backport-v3.13.x

#10964 4.x: change AMQP on disk message format & speed up the AMQP parser
  deps/amqp10_client/src/amqp10_client_frame_reader.erl
  deps/amqp10_client/src/amqp10_client_session.erl
  deps/amqp10_client/src/amqp10_msg.erl
  deps/amqp10_client/test/mock_server.erl
  deps/amqp10_client/test/system_SUITE.erl
  deps/amqp10_common/.gitignore
  deps/amqp10_common/BUILD.bazel
  deps/amqp10_common/Makefile
  deps/amqp10_common/app.bzl
  deps/amqp10_common/rebar.config
  deps/amqp10_common/src/amqp10_binary_generator.erl
  deps/amqp10_common/src/amqp10_binary_parser.erl
  deps/amqp10_common/src/amqp10_framing.erl
  deps/amqp10_common/test/binary_generator_SUITE.erl
  deps/amqp10_common/test/binary_parser_SUITE.erl
  deps/amqp10_common/test/prop_SUITE.erl
  deps/rabbit/BUILD.bazel
  deps/rabbit/app.bzl
  deps/rabbit/src/mc.erl
  deps/rabbit/src/mc_amqp.erl
  deps/rabbit/src/mc_amqpl.erl
  deps/rabbit/src/rabbit_amqp_reader.erl
  deps/rabbit/src/rabbit_amqp_session.erl
  deps/rabbit/src/rabbit_core_ff.erl
  deps/rabbit/src/rabbit_msg_record.erl
  deps/rabbit/src/rabbit_stream_queue.erl
  deps/rabbit/test/amqp_client_SUITE.erl
  deps/rabbit/test/mc_unit_SUITE.erl
  deps/rabbit/test/rabbit_message_interceptor_SUITE.erl
  deps/rabbit/test/rabbit_msg_record_SUITE.erl
  deps/rabbitmq_consistent_hash_exchange/BUILD.bazel
  deps/rabbitmq_consistent_hash_exchange/Makefile
  deps/rabbitmq_consistent_hash_exchange/test/rabbit_exchange_type_consistent_hash_SUITE.erl
  deps/rabbitmq_mqtt/BUILD.bazel
  deps/rabbitmq_mqtt/src/mc_mqtt.erl
  deps/rabbitmq_mqtt/src/rabbit_mqtt_qos0_queue.erl
  deps/rabbitmq_mqtt/test/mc_mqtt_SUITE.erl
  deps/rabbitmq_mqtt/test/protocol_interop_SUITE.erl
  moduleindex.yaml
Labels: bazel, make

#11163 Added global default queue type config
  deps/rabbit/priv/schema/rabbit.schema
  deps/rabbit/src/rabbit_queue_type.erl
Labels: backport-v3.13.x

#11167 3.12.14 release notes
  release-notes/3.12.14.md
Labels: backport-v3.13.x

#10645 Add token helper functions to oauth2-client module
  deps/oauth2_client/BUILD.bazel
  deps/oauth2_client/Makefile
  deps/oauth2_client/app.bzl
  deps/oauth2_client/include/oauth2_client.hrl
  deps/oauth2_client/src/jwt_helper.erl
  deps/oauth2_client/src/oauth2_client.erl
  deps/oauth2_client/test/oauth2_client_test_util.erl
  deps/oauth2_client/test/oauth_http_mock.erl
  deps/oauth2_client/test/system_SUITE.erl
  deps/oauth2_client/test/unit_SUITE.erl
  deps/rabbitmq_management/selenium/test/basic-auth/enabled_plugins
Labels: bazel, make, backport-v3.13.x

#11177 jose dependency belongs to rabbitmq-components.mk
  deps/rabbitmq_auth_backend_oauth2/Makefile
  rabbitmq-components.mk
Labels: make, backport-v3.13.x

#11180 Backport #11177, take 2
  deps/rabbitmq_auth_backend_oauth2/Makefile
  rabbitmq-components.mk
Labels: make

#11185 Use looking_glass 0.2.2
  MODULE.bazel
Labels: bazel, backport-v3.12.x, backport-v3.13.x

#11193 Be more defensive when determining if a policy has CMQ keys
  deps/rabbit/src/rabbit_mirror_queue_misc.erl
Labels: backport-v3.13.x

#11197 3.13: correctly format disabled plugins in 'rabbitmq-plugins list'
  deps/rabbitmq_cli/lib/rabbitmq/cli/formatters/plugins.ex
  deps/rabbitmq_cli/test/plugins/plugins_formatter_test.exs
Labels: backport-v3.13.x

#11199 Make: move seshat dep definition to rabbitmq-components.mk
  deps/rabbit/Makefile
  rabbitmq-components.mk
Labels: make, backport-v3.13.x

#11214 Declaring an exchange with an invalid type is a precondition failure
  deps/rabbit/src/rabbit_exchange.erl
Labels: backport-v3.12.x, backport-v3.13.x

#11121 4.x: Use compressed mem tables and set a wal max entries default for quorum queues
  MODULE.bazel
  deps/rabbit/src/rabbit_ra_systems.erl
  rabbitmq-components.mk
Labels: bazel, make

#11174 Fix dead lettering
  deps/rabbit/BUILD.bazel
  deps/rabbit/app.bzl
  deps/rabbit/include/mc.hrl
  deps/rabbit/src/mc.erl
  deps/rabbit/src/mc_amqp.erl
  deps/rabbit/src/mc_amqpl.erl
  deps/rabbit/src/mc_compat.erl
  deps/rabbit/src/rabbit_core_ff.erl
  deps/rabbit/src/rabbit_dead_letter.erl
  deps/rabbit/src/rabbit_fifo_dlx_worker.erl
  deps/rabbit/test/amqp_client_SUITE.erl
  deps/rabbit/test/dead_lettering_SUITE.erl
  deps/rabbit/test/mc_unit_SUITE.erl
  deps/rabbit/test/message_containers_deaths_v2_SUITE.erl
Labels: bazel, backport-v3.13.x

#10656 4.x: remove availability of CQv1
  deps/rabbit/BUILD.bazel
  deps/rabbit/priv/schema/rabbit.schema
  deps/rabbit/src/rabbit_amqqueue_process.erl
  deps/rabbit/src/rabbit_classic_queue_index_v2.erl
  deps/rabbit/src/rabbit_queue_index.erl
  deps/rabbit/src/rabbit_variable_queue.erl
  deps/rabbit/test/backing_queue_SUITE.erl
  deps/rabbit/test/classic_queue_prop_SUITE.erl
  deps/rabbit/test/priority_queue_SUITE.erl
  deps/rabbit/test/unicode_SUITE.erl
  deps/rabbitmq_management/test/rabbit_mgmt_http_SUITE.erl
  deps/rabbitmq_mqtt/test/shared_SUITE.erl
  deps/rabbitmq_mqtt/test/v5_SUITE.erl
Labels: bazel

#11226 Fix a management UI issue with a page refresh after logging out
  deps/rabbitmq_management/priv/www/js/dispatcher.js
  deps/rabbitmq_management/priv/www/js/oidc-oauth/helper.js
  deps/rabbitmq_management/selenium/test/basic-auth/logout.js
  deps/rabbitmq_management/selenium/test/pageobjects/BasePage.js
Labels: backport-v3.13.x

#11230 Remove BCC from x-death routing-keys
  deps/rabbit/src/mc.erl
  deps/rabbit/src/mc_amqpl.erl
  deps/rabbit/test/dead_lettering_SUITE.erl
Labels: backport-v3.13.x

#11234 Fix a flake in amqp_client_SUITE
  deps/rabbit/test/amqp_client_SUITE.erl
Labels: backport-v3.12.x, backport-v3.13.x

#11243 Initial 3.13.3 release notes
  release-notes/3.13.3.md
Labels: backport-v3.13.x

#11252 Adopt otp 26.2.5
  MODULE.bazel
  WORKSPACE
Labels: bazel, backport-v3.12.x, backport-v3.13.x

#11250 Add configuration for ELP language server
  .elp.toml
Labels: backport-v3.13.x

#11254 Use the latest OTP in the dev OCIs
  packaging/docker-image/Dockerfile
Labels: backport-v3.13.x

#11258 Setup erlang for the gazelle workflow
  .github/workflows/gazelle-scheduled.yaml
  .github/workflows/gazelle.yaml
Labels: backport-v3.13.x

#11259 bazel run gazelle
  deps/oauth2_client/BUILD.bazel
  deps/oauth2_client/app.bzl
  deps/rabbitmq_peer_discovery_consul/app.bzl
  moduleindex.yaml
Labels: bazel

#11251 Wrap maybe function in quotes, so it is treated as an atom
  deps/rabbit_common/src/rabbit_heartbeat.erl
  deps/rabbit_common/src/rabbit_types.erl
Labels: backport-v3.13.x

#11270 rabbit_vhost: log a warning when a virtual host process stops (or fails)
  deps/rabbit/src/rabbit_vhost.erl
Labels: backport-v3.13.x

#11280 rabbit_direct: log cosmetics
  deps/rabbit/src/rabbit_direct.erl
Labels: backport-v3.13.x

#11279 Introduce rabbit_vhost_sup_sup:start_on_all_nodes/2
  deps/rabbit/src/rabbit_vhost_sup_sup.erl
Labels: backport-v3.13.x

#11285 Adopt elixir 1.15.8
  MODULE.bazel
Labels: bazel, backport-v3.11.x, backport-v3.12.x, backport-v3.13.x

#11288 CQ: Fix entry missing from cache leading to crash on read
  deps/rabbit/src/rabbit_msg_store.erl
Labels: backport-v3.13.x

#11222 Enforce/honor per-vhost queue limit for all protocols
  deps/rabbit/src/rabbit_channel.erl
  deps/rabbit/src/rabbit_queue_type.erl
Labels: backport-v3.13.x

#11297 Reduce inefficiency introduced in b636f41
  deps/rabbit_common/mk/rabbitmq-early-test.mk
Labels: make, backport-v3.13.x

#11212 cluster wide queue limit - main
  deps/rabbit/BUILD.bazel
  deps/rabbit/app.bzl
  deps/rabbit/priv/schema/rabbit.schema
  deps/rabbit/src/rabbit_queue_type.erl
  deps/rabbit/test/cluster_limit_SUITE.erl
Labels: bazel

#11196 A way to configure a cluster wide queue limit
  deps/rabbit/BUILD.bazel
  deps/rabbit/app.bzl
  deps/rabbit/priv/schema/rabbit.schema
  deps/rabbit/src/rabbit_queue_type.erl
  deps/rabbit/test/cluster_limit_SUITE.erl
Labels: bazel, make

#11310 rabbitmq-early-test.mk: Use same Dialyzer options as in Bazel
  deps/rabbit_common/mk/rabbitmq-early-test.mk
Labels: make

#11322 Make rabbit_misc:which_applications/0 more resilient
  deps/rabbit_common/src/rabbit_misc.erl
Labels: backport-v3.12.x, backport-v3.13.x

#11245 Prometheus: add segment file count to queue_metrics and expose
  deps/rabbit/src/rabbit_osiris_metrics.erl
  deps/rabbit/src/rabbit_stream_queue.erl
  deps/rabbitmq_prometheus/src/collectors/prometheus_rabbitmq_core_metrics_collector.erl
Labels: backport-v3.13.x

#11301 Remove duplicated checks of vhost queue limit
  deps/rabbit/src/rabbit_amqp_management.erl
  deps/rabbit/src/rabbit_amqp_session.erl
  deps/rabbit/src/rabbit_amqqueue.erl
  deps/rabbit/src/rabbit_channel.erl
  deps/rabbit/src/rabbit_queue_type.erl
  deps/rabbit/test/amqp_auth_SUITE.erl
  deps/rabbitmq_mqtt/src/rabbit_mqtt_processor.erl
  deps/rabbitmq_stream/src/rabbit_stream_manager.erl
Labels: backport-v3.13.x

#11332 Another round of 3.13.3 release notes updates
  release-notes/3.13.3.md
Labels: backport-v3.13.x

#11339 Interpret x-death header from AMQP 0.9.1 client
  deps/rabbit/BUILD.bazel
  deps/rabbit/app.bzl
  deps/rabbit/include/mc.hrl
  deps/rabbit/src/mc.erl
  deps/rabbit/src/mc_amqp.erl
  deps/rabbit/src/mc_amqpl.erl
  deps/rabbit/src/rabbit_dead_letter.erl
  deps/rabbit/src/rabbit_fifo_dlx_worker.erl
  deps/rabbit/test/dead_lettering_SUITE.erl
  deps/rabbit/test/mc_unit_SUITE.erl
  deps/rabbit/test/per_node_limit_SUITE.erl
  deps/rabbit/test/unit_classic_mirrored_queue_sync_throttling_SUITE.erl
  deps/rabbitmq_mqtt/src/mc_mqtt.erl
Labels: bazel
