Repository rabbitmq/rabbitmq-server, pull requests merged in 2024-10, with the labels that each got.

#9729 Relax feature flag compat check during join cluster
  deps/rabbit/src/rabbit_db_cluster.erl
  deps/rabbit/src/rabbit_feature_flags.erl
  deps/rabbit/src/rabbit_ff_controller.erl
  deps/rabbit/src/rabbit_khepri.erl
  deps/rabbit/src/rabbit_mnesia.erl
  deps/rabbit/test/feature_flags_v2_SUITE.erl
Labels: bazel

#12418 Add a rabbit.license_line default
  deps/rabbit/BUILD.bazel
  deps/rabbit/Makefile
Labels: bazel, make, backport-v3.13.x, backport-v4.0.x

#12437 By @ayanda-D: make sure (non-replicated) CQs (classic queues) emit leader and members metrics, just like replicated QQs
  .github/workflows/templates/test-mixed-versions.template.yaml
  .github/workflows/templates/test.template.yaml
  deps/rabbit/src/rabbit_amqqueue_process.erl
Labels: backport-v4.0.x

#12457 Remove multiple mentions of global prefetch from management UI, CLI, man pages
  deps/rabbit/docs/rabbitmqctl.8
  deps/rabbit/src/rabbit_channel.erl
  deps/rabbitmq_cli/lib/rabbitmq/cli/ctl/commands/list_channels_command.ex
  deps/rabbitmq_management/priv/www/js/global.js
  deps/rabbitmq_management/priv/www/js/tmpl/channel.ejs
  deps/rabbitmq_management/priv/www/js/tmpl/channels-list.ejs
  deps/rabbitmq_prometheus/src/collectors/prometheus_rabbitmq_core_metrics_collector.erl
Labels: backport-v4.0.x

#12458 By @gomoripeti: Don't start invalid but enabled plugins at startup
  deps/rabbit/src/rabbit_plugins.erl
Labels: backport-v4.0.x

#12425 Fix the exit status when parallel-ct is used
  deps/rabbit/Makefile
  deps/rabbitmq_ct_helpers/src/ct_master_fork.erl
  deps/rabbitmq_ct_helpers/src/cth_parallel_ct_detect_failure.erl
  deps/rabbitmq_mqtt/Makefile
Labels: make

#12442 QQ: fix bug with discards using a consumer_id()
  deps/rabbit/src/rabbit_fifo.erl
  deps/rabbit/test/quorum_queue_SUITE.erl
  deps/rabbit/test/rabbit_fifo_SUITE.erl
Labels: bug, backport-v4.0.x

#12415 Support AMQP filter expressions
  deps/amqp10_client/src/amqp10_client_session.erl
  deps/amqp10_client/src/amqp10_msg.erl
  deps/amqp10_common/app.bzl
  deps/amqp10_common/include/amqp10_filtex.hrl
  deps/rabbit/BUILD.bazel
  deps/rabbit/Makefile
  deps/rabbit/app.bzl
  deps/rabbit/ct.test.spec
  deps/rabbit/src/mc.erl
  deps/rabbit/src/mc_amqp.erl
  deps/rabbit/src/rabbit_amqp_filtex.erl
  deps/rabbit/src/rabbit_amqp_reader.erl
  deps/rabbit/src/rabbit_amqp_session.erl
  deps/rabbit/src/rabbit_amqp_util.erl
  deps/rabbit/src/rabbit_queue_type.erl
  deps/rabbit/src/rabbit_quorum_queue.erl
  deps/rabbit/src/rabbit_stream_queue.erl
  deps/rabbit/test/amqp_address_SUITE.erl
  deps/rabbit/test/amqp_auth_SUITE.erl
  deps/rabbit/test/amqp_client_SUITE.erl
  deps/rabbit/test/amqp_filtex_SUITE.erl
  deps/rabbit/test/amqp_utils.erl
  deps/rabbitmq_stream/test/protocol_interop_SUITE.erl
  moduleindex.yaml
Labels: bazel, make

#12474 4.0.x: Dependency CSV updated from 3.2.0 to 3.2.1
  MODULE.bazel
  deps/rabbitmq_cli/Makefile
Labels: bazel, make

#12475 4.0.x, by @Ayanda-D: stop QQ replicas when a QQ is forced to shrink to a single replica
  deps/rabbit/src/rabbit_quorum_queue.erl
  deps/rabbit/test/quorum_queue_SUITE.erl
Labels: backport-v3.13.x

#12473 4.1, by @SimonUnge: Dependency CSV updated from 3.2.0 to 3.2.1
  MODULE.bazel
  deps/rabbitmq_cli/Makefile
Labels: bazel, make, backport-v3.13.x, backport-v4.0.x

#12468 4.1, by @Ayanda-D: stop QQ replicas when a QQ is forced to shrink to a single replica
  deps/rabbit/src/rabbit_quorum_queue.erl
  deps/rabbit/test/quorum_queue_SUITE.erl
Labels: backport-v4.0.x

#12478 4.0.x: update thoas to 1.2.1
  MODULE.bazel
  bazel/BUILD.thoas
  rabbitmq-components.mk
Labels: bazel, make, backport-v3.13.x

#12479 4.1: update Recon to 2.5.6
  MODULE.bazel
  bazel/BUILD.recon
  rabbitmq-components.mk
Labels: bazel, make

#12487 bazel run gazelle
  deps/rabbit/BUILD.bazel
  deps/rabbitmq_ct_helpers/app.bzl
  moduleindex.yaml
Labels: bazel

#12484 4.0.x: upgrade Redbug to 2.1.0
  MODULE.bazel
  bazel/BUILD.redbug
  rabbitmq-components.mk
Labels: bazel, make, backport-v3.13.x

#12498 bazel run gazelle
  deps/rabbitmq_auth_backend_oauth2/BUILD.bazel
  deps/rabbitmq_auth_backend_oauth2/app.bzl
  deps/rabbitmq_management/BUILD.bazel
  deps/rabbitmq_management/app.bzl
  moduleindex.yaml
Labels: bazel

#12439 OAuth 2: support scope aliases in rabbitmq.conf
  deps/rabbitmq_auth_backend_oauth2/priv/schema/rabbitmq_auth_backend_oauth2.schema
  deps/rabbitmq_auth_backend_oauth2/src/rabbit_oauth2_schema.erl
  deps/rabbitmq_auth_backend_oauth2/test/config_schema_SUITE_data/rabbitmq_auth_backend_oauth2.snippets
  deps/rabbitmq_auth_backend_oauth2/test/rabbit_oauth2_schema_SUITE.erl
Labels: rabbitmq-auth-backend-oauth2, bazel

#12399 Deprecate two OAuth2 settings: auth_oauth2.jwks_url and management.metadata_url
  deps/oauth2_client/src/oauth2_client.erl
  deps/oauth2_client/test/system_SUITE.erl
  deps/rabbitmq_auth_backend_oauth2/README.md
  deps/rabbitmq_auth_backend_oauth2/priv/schema/rabbitmq_auth_backend_oauth2.schema
  deps/rabbitmq_auth_backend_oauth2/src/uaa_jwt.erl
  deps/rabbitmq_auth_backend_oauth2/test/config_schema_SUITE_data/rabbitmq_auth_backend_oauth2.snippets
  deps/rabbitmq_auth_backend_oauth2/test/jwks_SUITE.erl
  deps/rabbitmq_auth_backend_oauth2/test/rabbit_oauth2_provider_SUITE.erl
  deps/rabbitmq_auth_backend_oauth2/test/unit_SUITE.erl
  deps/rabbitmq_management/priv/schema/rabbitmq_management.schema
  deps/rabbitmq_management/src/rabbit_mgmt_wm_auth.erl
  deps/rabbitmq_management/test/rabbit_mgmt_wm_auth_SUITE.erl
Labels: rabbitmq-auth-backend-oauth2, bazel, make

#12501 Tests: wait until stats are published, not just collected on the agent
  deps/rabbitmq_management/test/clustering_SUITE.erl
  deps/rabbitmq_management/test/clustering_prop_SUITE.erl
Labels: backport-v4.0.x

#12506 Track requeue history
  deps/amqp10_client/src/amqp10_client_session.erl
  deps/rabbit/src/mc.erl
  deps/rabbit/src/mc_util.erl
  deps/rabbit/src/rabbit_amqp_session.erl
  deps/rabbit/test/amqp_client_SUITE.erl
  deps/rabbitmq_amqp_client/src/rabbitmq_amqp_client.erl
Labels: bug, backport-v4.0.x

#12208 Adjust vheap sizes for message handling processes in OTP 27
  deps/rabbit/app.bzl
  deps/rabbit/src/rabbit_amqp_session.erl
  deps/rabbit/src/rabbit_channel.erl
  deps/rabbit/src/rabbit_process_flag.erl
  deps/rabbit/src/rabbit_ra_systems.erl
  deps/rabbit_common/src/code_version.erl
  moduleindex.yaml
Labels: bazel, backport-v4.0.x

#12503 Return error if stream publisher/consumer reference is longer than 255 characters
  deps/rabbitmq_stream/src/rabbit_stream_reader.erl
  deps/rabbitmq_stream/test/rabbit_stream_SUITE.erl
Labels: backport-v4.0.x

#12511 Use inner module function to increment stream protocol counter
  deps/rabbitmq_stream/src/rabbit_stream_reader.erl
Labels: backport-v4.0.x

#12521 QQ: improve `rabbit_quorum_queue:status/2` efficiency by allowing it to use `ra:key_metrics/1`
  deps/rabbit/src/rabbit_quorum_queue.erl
Labels: bug, backport-v4.0.x

#12502 4.1/main: Make CI: Fix and enhance ct_master
  deps/rabbit/Makefile
  deps/rabbitmq_ct_helpers/app.bzl
  deps/rabbitmq_ct_helpers/src/ct_master_event_fork.erl
  deps/rabbitmq_ct_helpers/src/ct_master_fork.erl
  deps/rabbitmq_ct_helpers/src/ct_master_logs_fork.erl
  deps/rabbitmq_ct_helpers/src/cth_parallel_ct_detect_failure.erl
  deps/rabbitmq_ct_helpers/src/rabbit_ct_broker_helpers.erl
  deps/rabbitmq_ct_helpers/src/rabbit_ct_helpers.erl
  deps/rabbitmq_mqtt/Makefile
  moduleindex.yaml
Labels: bazel, make

#12523 Provide clear error message for reserved annotation keys
  .github/workflows/test-make-target.yaml
  .github/workflows/test-plugin.yaml
  deps/amqp10_common/src/amqp10_framing.erl
  deps/rabbit/src/rabbit_amqp_session.erl
  deps/rabbit/test/amqp_client_SUITE.erl
  deps/rabbit/test/amqp_system_SUITE_data/fsharp-tests/global.json
Labels: backport-v4.0.x

#12530 Fix error message
  deps/rabbit/test/amqp_system_SUITE.erl
Labels: backport-v4.0.x

#12535 Make CI: Check that CI knows about all CT_SUITES in CI
  .github/workflows/test-make.yaml
  deps/rabbit/Makefile
  deps/rabbitmq_mqtt/Makefile
Labels: make

#12456 Grafana: add a runtime/Erlang/BEAM dashboard
  deps/rabbitmq_prometheus/docker/grafana/dashboards/Erlang-BEAM.json
  deps/rabbitmq_prometheus/docker/grafana/dashboards/Erlang-Distribution.json
  deps/rabbitmq_prometheus/docker/grafana/dashboards/Erlang-Distributions-Compare.json
  deps/rabbitmq_prometheus/docker/grafana/dashboards/Erlang-Memory-Allocators.json
  deps/rabbitmq_prometheus/docker/grafana/dashboards/RabbitMQ-Overview.json
  deps/rabbitmq_prometheus/docker/grafana/dashboards/RabbitMQ-Quorum-Queues-Raft.json
  deps/rabbitmq_prometheus/docker/grafana/dashboards/RabbitMQ-Stream.json
Labels: backport-v4.0.x

#12543 Fix module mentioned in target group size description
  deps/rabbit/src/rabbit_quorum_queue.erl
Labels: backport-v4.0.x

#12553 Check topic permissions of CC and BCC headers
  deps/rabbit/app.bzl
  deps/rabbit/src/rabbit_channel.erl
  deps/rabbit/test/topic_permission_SUITE.erl
Labels: bazel, backport-v4.0.x

#12566 Bump observer_cli to 1.8.0
  MODULE.bazel
  rabbitmq-components.mk
Labels: bazel, make, backport-v4.0.x

#12569 bazel run gazelle
  deps/amqp10_client/BUILD.bazel
Labels: bazel

#12550 Ensure init-slapd.sh passes `shellcheck`
  deps/rabbitmq_auth_backend_ldap/test/system_SUITE_data/init-slapd.sh
Labels: backport-v4.0.x

#12571 Convert array from AMQP 1.0 to AMQP 0.9.1
  deps/amqp10_client/src/amqp10_msg.erl
  deps/rabbit/src/mc_amqpl.erl
  deps/rabbit/test/amqp_client_SUITE.erl
  deps/rabbit/test/mc_unit_SUITE.erl
Labels: bug

#12577 QQ periodic membership reconciliation: correctly return a `ra:members/2` error in case of a timeout
  deps/rabbit/src/rabbit_quorum_queue_periodic_membership_reconciliation.erl
Labels: backport-v4.0.x

#12574 Bump IBM MQ image used for interoperability testing to 9.4.0
  .github/workflows/ibm-mq-make.yaml
Labels: backport-v4.0.x

#12559 Support x-cc message annotation
  deps/rabbit/BUILD.bazel
  deps/rabbit/app.bzl
  deps/rabbit/src/mc.erl
  deps/rabbit/src/mc_amqp.erl
  deps/rabbit/src/mc_amqpl.erl
  deps/rabbit/src/mc_compat.erl
  deps/rabbit/src/mc_util.erl
  deps/rabbit/src/rabbit_amqp_session.erl
  deps/rabbit/src/rabbit_stream_queue.erl
  deps/rabbit/test/amqp_address_SUITE.erl
  deps/rabbit/test/amqp_client_SUITE.erl
  deps/rabbit/test/dead_lettering_SUITE.erl
  deps/rabbit/test/mc_unit_SUITE.erl
  deps/rabbit/test/topic_permission_SUITE.erl
  deps/rabbitmq_mqtt/src/mc_mqtt.erl
  deps/rabbitmq_mqtt/test/mc_mqtt_SUITE.erl
  release-notes/4.1.0.md
Labels: bazel

#12581 Delete test access_failure
  deps/rabbit/test/amqp_system_SUITE.erl
  deps/rabbit/test/amqp_system_SUITE_data/fsharp-tests/Program.fs
Labels: backport-v4.0.x

#12558 Make CI: Mixed version testing
  .github/workflows/test-make-target.yaml
  .github/workflows/test-make-tests.yaml
  .github/workflows/test-make.yaml
  .github/workflows/test-mixed-versions.yaml
  deps/rabbit/test/cluster_upgrade_SUITE.erl
  deps/rabbit/test/feature_flags_SUITE.erl
  deps/rabbit_common/mk/rabbitmq-dist.mk
  deps/rabbit_common/mk/rabbitmq-run.mk
  deps/rabbitmq_ct_helpers/src/rabbit_ct_broker_helpers.erl
  deps/rabbitmq_ct_helpers/src/rabbit_ct_helpers.erl
Labels: make

#12592 Use fmt_string in this error message
  deps/rabbitmq_management/priv/www/js/tmpl/overview.ejs
Labels: backport-v4.0.x

#12601 4.0.3 release notes
  release-notes/4.0.3.md
Labels: backport-v4.0.x

#12606 Add AMQP 1.0 event exchange test
  deps/rabbitmq_event_exchange/Makefile
  deps/rabbitmq_event_exchange/test/system_SUITE.erl
Labels: make

#12610 Fix rabbitmq_federation queue_SUITE flake
  deps/rabbitmq_federation/test/federation_status_command_SUITE.erl
  deps/rabbitmq_federation/test/queue_SUITE.erl
  deps/rabbitmq_federation/test/rabbit_federation_test_util.erl
  deps/rabbitmq_federation/test/restart_federation_link_command_SUITE.erl
Labels: backport-v3.13.x, backport-v4.0.x

#12604 MQTT, x.509 certificate-based authentication: use the correct key name for the TLS SAN type configuration parameter
  deps/rabbitmq_ct_helpers/tools/tls-certs/openssl.cnf.in
  deps/rabbitmq_mqtt/BUILD.bazel
  deps/rabbitmq_mqtt/src/rabbit_mqtt_processor.erl
  deps/rabbitmq_mqtt/test/auth_SUITE.erl
Labels: rabbitmq-mqtt, bazel, backport-v4.0.x

#12616 Make (rabbitmq-run.mk): abort restart-cluster if something goes wrong
  deps/rabbit_common/mk/rabbitmq-run.mk
Labels: make, backport-v3.13.x, backport-v4.0.x

#12624 Fixes for CI flakes
  deps/rabbit/test/metrics_SUITE.erl
  deps/rabbitmq_federation_prometheus/test/prometheus_rabbitmq_federation_collector_SUITE.erl
Labels: backport-v3.13.x, backport-v4.0.x

#12629 Reduce AWS peer discovery workflow run rate
  .github/workflows/rabbitmq_peer_discovery_aws.yaml
Labels: backport-v3.13.x, backport-v4.0.x
