Repository rabbitmq/rabbitmq-server, pull requests merged in 2024-01, with the labels that each got.

#10257 Add -noinput via `rabbitmq-env`
  deps/rabbit/scripts/rabbitmq-diagnostics
  deps/rabbit/scripts/rabbitmq-diagnostics.bat
  deps/rabbit/scripts/rabbitmq-env
  deps/rabbit/scripts/rabbitmq-plugins
  deps/rabbit/scripts/rabbitmq-queues
  deps/rabbit/scripts/rabbitmq-streams
  deps/rabbit/scripts/rabbitmq-upgrade
  deps/rabbit/scripts/rabbitmqctl
  deps/rabbit/scripts/vmware-rabbitmq
  deps/rabbitmq_cli/mix.exs
Labels: backport-v3.12.x

#10268 Ensure `-noinput` is applied correctly
  deps/rabbit/scripts/rabbitmq-diagnostics
  deps/rabbit/scripts/rabbitmqctl
Labels: backport-v3.12.x

#10271 Return error atom according to specification
  deps/rabbitmq_stream/src/rabbit_stream_manager.erl
Labels: bug, backport-v3.11.x, backport-v3.12.x

#10269 Ra v2.7.1
  MODULE.bazel
  rabbitmq-components.mk
Labels: bazel, make

#10284 3.12.12 release notes
  release-notes/3.12.12.md
Labels: backport-v3.12.x

#10297 Adopt OTP 26.2.1
  .bazelrc
  .github/workflows/oci.yaml
  .github/workflows/rabbitmq_peer_discovery_aws.yaml
  MODULE.bazel
  WORKSPACE
  bazel/platforms/BUILD.bazel
  packaging/docker-image/BUILD.bazel
Labels: bazel

#10229 [#8557/CLI] Removed ANSI escape codes from JSON output
  deps/rabbitmq_cli/lib/rabbitmq/cli/ctl/commands/cluster_status_command.ex
  deps/rabbitmq_cli/lib/rabbitmq/cli/diagnostics/commands/erlang_cookie_sources_command.ex
Labels: backport-v3.12.x

#10305 Fix undef internal call in supervisor2
  deps/rabbit_common/src/supervisor2.erl
Labels: backport-v3.12.x

#10303 #2634 - if ASCII disabled, remove escape codes
  deps/rabbitmq_cli/lib/rabbitmq/cli/core/ansi.ex
Labels: backport-v3.12.x

#10337 Revert "Default to classic queues v2"
  deps/rabbit/BUILD.bazel
  deps/rabbit/Makefile
  deps/rabbit/priv/schema/rabbit.schema
  deps/rabbit/src/rabbit_amqqueue_process.erl
  deps/rabbit/src/rabbit_variable_queue.erl
  deps/rabbitmq_management/test/rabbit_mgmt_http_SUITE.erl
  release-notes/3.13.0.md
Labels: bazel, make

#10357 rabbitmq-components.mk: Declare `dep_rabbitmq_prelaunch`
  rabbitmq-components.mk
Labels: make

#10339 Reduce per message disk overhead
  deps/rabbit/include/mc.hrl
  deps/rabbit/src/mc.erl
  deps/rabbit/src/mc_amqp.erl
  deps/rabbit/src/mc_amqpl.erl
  deps/rabbit/src/mc_compat.erl
  deps/rabbit/src/rabbit_channel.erl
  deps/rabbit/src/rabbit_dead_letter.erl
  deps/rabbit/src/rabbit_exchange.erl
  deps/rabbit/src/rabbit_exchange_type_direct.erl
  deps/rabbit/src/rabbit_exchange_type_topic.erl
  deps/rabbit/src/rabbit_fifo_dlx_worker.erl
  deps/rabbit/src/rabbit_logger_exchange_h.erl
  deps/rabbit/src/rabbit_message_interceptor.erl
  deps/rabbit/src/rabbit_quorum_queue.erl
  deps/rabbit/src/rabbit_stream_queue.erl
  deps/rabbit/src/rabbit_trace.erl
  deps/rabbit/src/rabbit_variable_queue.erl
  deps/rabbit/test/mc_unit_SUITE.erl
  deps/rabbitmq_consistent_hash_exchange/src/rabbit_exchange_type_consistent_hash.erl
  deps/rabbitmq_jms_topic_exchange/src/rabbit_jms_topic_exchange.erl
  deps/rabbitmq_mqtt/BUILD.bazel
  deps/rabbitmq_mqtt/app.bzl
  deps/rabbitmq_mqtt/src/mc_mqtt.erl
  deps/rabbitmq_mqtt/src/rabbit_mqtt_processor.erl
  deps/rabbitmq_mqtt/test/mc_mqtt_SUITE.erl
  deps/rabbitmq_sharding/src/rabbit_sharding_exchange_type_modulus_hash.erl
Labels: bazel

#10353 Do not contact disconnected nodes in rabbit_nodes:list_running/0
  deps/rabbit/src/rabbit_mnesia_rename.erl
  deps/rabbit/src/rabbit_node_monitor.erl
  deps/rabbit/src/rabbit_nodes.erl
  deps/rabbit/test/clustering_management_SUITE.erl
Labels: backport-v3.12.x

#10375 Catch ETS exception when system is still starting
  deps/rabbitmq_stream/src/rabbit_stream.erl
Labels: streams

#10369 Make 'rabbitmqctl rename_cluster_node' and 'rabbitmqctl update_cluster_nodes ' no-ops
  deps/rabbit/BUILD.bazel
  deps/rabbit/app.bzl
  deps/rabbit/docs/rabbitmqctl.8
  deps/rabbit/src/rabbit_db_cluster.erl
  deps/rabbit/src/rabbit_mnesia.erl
  deps/rabbit/src/rabbit_mnesia_rename.erl
  deps/rabbit/src/rabbit_prelaunch_cluster.erl
  deps/rabbit/test/cluster_rename_SUITE.erl
  deps/rabbit/test/clustering_management_SUITE.erl
  deps/rabbit/test/per_vhost_connection_limit_SUITE.erl
  deps/rabbitmq_cli/lib/rabbitmq/cli/ctl/commands/node_health_check_command.ex
  deps/rabbitmq_cli/lib/rabbitmq/cli/ctl/commands/rename_cluster_node_command.ex
  deps/rabbitmq_cli/lib/rabbitmq/cli/ctl/commands/update_cluster_nodes_command.ex
  deps/rabbitmq_cli/mix.exs
  deps/rabbitmq_cli/test/ctl/rename_cluster_node_command_test.exs
  deps/rabbitmq_cli/test/ctl/update_cluster_nodes_command_test.exs
  deps/rabbitmq_peer_discovery_aws/test/integration_SUITE.erl
  moduleindex.yaml
Labels: bazel

#10385 HTTP auth example dotnetcore: Update to .NET 8
  deps/rabbitmq_auth_backend_http/examples/README.md
  deps/rabbitmq_auth_backend_http/examples/rabbitmq_auth_backend_webapi_dotnetcore/RabbitMqAuthBackendHttp.csproj
  deps/rabbitmq_auth_backend_http/examples/rabbitmq_auth_backend_webapi_dotnetcore/Requests/ResourceAuthRequest.cs
  deps/rabbitmq_auth_backend_http/examples/rabbitmq_auth_backend_webapi_dotnetcore/Requests/TopicAuthRequest.cs
  deps/rabbitmq_auth_backend_http/examples/rabbitmq_auth_backend_webapi_dotnetcore/Requests/UserAuthRequest.cs
  deps/rabbitmq_auth_backend_http/examples/rabbitmq_auth_backend_webapi_dotnetcore/Requests/VhostAuthRequest.cs
Labels: backport-v3.12.x

#10364 Reduce flakiness of certain Common Test suites
  deps/rabbit/src/rabbit_quorum_queue.erl
  deps/rabbit/src/rabbit_quorum_queue_periodic_membership_reconciliation.erl
  deps/rabbit/src/rabbit_stream_coordinator.erl
  deps/rabbit/src/rabbit_stream_queue.erl
  deps/rabbit/test/message_containers_SUITE.erl
  deps/rabbit/test/quorum_queue_SUITE.erl
  deps/rabbit/test/rabbit_stream_queue_SUITE.erl
  deps/rabbitmq_cli/lib/rabbitmq/cli/ctl/commands/wait_command.ex
  deps/rabbitmq_mqtt/test/protocol_interop_SUITE.erl
Labels: backport-v3.12.x

#10409 Catch ETS error in stream management queries
  deps/rabbitmq_stream_management/src/rabbit_stream_mgmt_db.erl
Labels: streams

#10417 An alternative to #10415, closes #10330
  deps/rabbitmq_management/app.bzl
  deps/rabbitmq_management/priv/www/api/index.html
  deps/rabbitmq_management/src/rabbit_mgmt_nodes.erl
  deps/rabbitmq_management/src/rabbit_mgmt_wm_node.erl
  deps/rabbitmq_management/src/rabbit_mgmt_wm_node_memory.erl
  deps/rabbitmq_management/src/rabbit_mgmt_wm_node_memory_ets.erl
  deps/rabbitmq_management/test/rabbit_mgmt_http_SUITE.erl
  moduleindex.yaml
Labels: bazel, backport-v3.12.x

#10331 Stream coordinator: fixes to automatic membership changes.
  deps/rabbit/BUILD.bazel
  deps/rabbit/src/rabbit_amqqueue.erl
  deps/rabbit/src/rabbit_db_cluster.erl
  deps/rabbit/src/rabbit_queue_type_util.erl
  deps/rabbit/src/rabbit_quorum_queue.erl
  deps/rabbit/src/rabbit_stream_coordinator.erl
  deps/rabbit/src/rabbit_stream_coordinator.hrl
  deps/rabbit/src/rabbit_stream_queue.erl
  deps/rabbit/test/message_containers_SUITE.erl
  deps/rabbit/test/queue_type_SUITE.erl
  deps/rabbit/test/queue_utils.erl
  deps/rabbit/test/rabbit_stream_queue_SUITE.erl
  deps/rabbitmq_amqp1_0/test/amqp10_client_SUITE.erl
  deps/rabbitmq_cli/lib/rabbitmq/cli/ctl/commands/forget_cluster_node_command.ex
  deps/rabbitmq_cli/lib/rabbitmq/cli/streams/commands/coordinator_status_command.ex
  deps/rabbitmq_stream/test/rabbit_stream_SUITE.erl
Labels: bazel

#10424 Minor: Fix error handling in rabbit_quorum_queue:status/2
  deps/rabbit/src/rabbit_quorum_queue.erl
Labels: backport-v3.12.x

#10428 Fix MQTT test flake
  deps/rabbitmq_mqtt/test/reader_SUITE.erl
Labels: backport-v3.12.x

#10437 Update Cowboy to 2.11
  MODULE.bazel
  rabbitmq-components.mk
Labels: bazel, make, backport-v3.12.x

#10443 Use local Khepri queries only
  MODULE.bazel
  deps/rabbit/src/rabbit_db_maintenance.erl
  deps/rabbit/src/rabbit_khepri.erl
  deps/rabbit/src/rabbit_maintenance.erl
  rabbitmq-components.mk
Labels: bazel, make
