Repository rabbitmq/rabbitmq-server, pull requests merged in 2024-11, with the labels that each got.

#12634 bazel run gazelle
  deps/rabbitmq_auth_backend_oauth2/app.bzl
Labels: bazel

#12636 QQ: handle case where a stale read request results in member crash.
  deps/rabbit/src/rabbit_fifo.erl
  deps/rabbit/test/quorum_queue_SUITE.erl
Labels: bug, backport-v4.0.x

#12640 QQs: periodically apply policies if there's a discrepancy between the current and desired policy-driven state
  deps/rabbit/src/rabbit_fifo.erl
  deps/rabbit/src/rabbit_quorum_queue.erl
  deps/rabbit/test/quorum_queue_SUITE.erl
Labels: bazel, make

#12642 test: wait for links and metrics in prometheus_rabbitmq_federation_collector_SUITE
  deps/rabbitmq_federation_prometheus/test/prometheus_rabbitmq_federation_collector_SUITE.erl
Labels: backport-v3.13.x, backport-v4.0.x

#12646 metrics_SUITE: wait for tables in proper test
  deps/rabbit/test/metrics_SUITE.erl
Labels: backport-v3.13.x, backport-v4.0.x

#12654 Selenium suite workflow: updates for 2024
  .github/workflows/test-authnz.yaml
Labels: backport-v4.0.x

#12655 Selenium management UI suite workflow: updates for 2024
  .github/workflows/test-management-ui.yaml
Labels: backport-v4.0.x

#12661 bazel run gazelle
  deps/rabbit/app.bzl
Labels: bazel

#12666 By @LoisSotoLopez: Exclude policy_repair QQ test on mixed versions
  deps/rabbit/test/quorum_queue_SUITE.erl
Labels: backport-v4.0.x

#12671 Fixes for test flakes
  deps/rabbitmq_cli/test/ctl/set_disk_free_limit_command_test.exs
  deps/rabbitmq_management/test/clustering_prop_SUITE.erl
Labels: backport-v3.13.x, backport-v4.0.x

#12677 Management UI: arranged and reorganized vertical bars on the queue/stream declaration form
  deps/rabbitmq_management/priv/www/js/tmpl/queues.ejs
Labels: backport-v4.0.x

#12684 Remove gen_server behaviour from stream manager
  deps/rabbitmq_stream/src/rabbit_stream_manager.erl
  deps/rabbitmq_stream/src/rabbit_stream_reader.erl
  deps/rabbitmq_stream/src/rabbit_stream_sup.erl
Labels: performance, backport-v4.0.x

#12670 Show session and link details for AMQP 1.0 connection
  deps/rabbit/src/rabbit_amqp_reader.erl
  deps/rabbit/src/rabbit_amqp_session.erl
  deps/rabbit/src/rabbit_connection_tracking.erl
  deps/rabbitmq_management/Makefile
  deps/rabbitmq_management/app.bzl
  deps/rabbitmq_management/priv/www/js/dispatcher.js
  deps/rabbitmq_management/priv/www/js/global.js
  deps/rabbitmq_management/priv/www/js/tmpl/connection.ejs
  deps/rabbitmq_management/priv/www/js/tmpl/sessions-list.ejs
  deps/rabbitmq_management/src/rabbit_mgmt_dispatcher.erl
  deps/rabbitmq_management/src/rabbit_mgmt_wm_connection_sessions.erl
  deps/rabbitmq_management/test/rabbit_mgmt_http_SUITE.erl
  moduleindex.yaml
  release-notes/4.1.0.md
Labels: bazel, make

#12687 Fix MQTT test flake
  deps/rabbitmq_mqtt/test/mqtt_shared_SUITE.erl
Labels: backport-v4.0.x

#12689 Fix MQTT test flake management_plugin_connection
  deps/rabbitmq_mqtt/test/mqtt_shared_SUITE.erl
Labels: backport-v4.0.x

#12686 Use infinity timout for RA local query in stream coordinator
  deps/rabbit/src/rabbit_stream_coordinator.erl
  deps/rabbit/src/rabbit_stream_sac_coordinator.erl
Labels: usability, backport-v4.0.x

#12694 Fix flake will_delay_session_takeover
  deps/rabbitmq_mqtt/test/v5_SUITE.erl
Labels: backport-v4.0.x

#12696 HTTP API: reduce body size limit for the endpoint used to bind queues/streams/exchanges
  deps/rabbitmq_amqp1_0/BUILD.bazel
  deps/rabbitmq_ct_client_helpers/BUILD.bazel
  deps/rabbitmq_ct_helpers/BUILD.bazel
  deps/rabbitmq_management/src/rabbit_mgmt_util.erl
  deps/rabbitmq_management/src/rabbit_mgmt_wm_bindings.erl
  deps/rabbitmq_management/src/rabbit_mgmt_wm_definitions.erl
Labels: bazel, backport-v4.0.x

#12659 Make it possible to set some cluster metadata besides the name using tags
  deps/rabbit/priv/schema/rabbit.schema
  deps/rabbit/src/rabbit.erl
  deps/rabbitmq_cli/lib/rabbitmq/cli/ctl/commands/cluster_status_command.ex
  deps/rabbitmq_management/src/rabbit_mgmt_wm_overview.erl
  deps/rabbitmq_management/test/rabbit_mgmt_http_SUITE.erl
Labels: backport-v4.0.x

#12702 Make it possible to set some node-specific metadata using tags
  deps/rabbit/priv/schema/rabbit.schema
  deps/rabbit/src/rabbit.erl
  deps/rabbitmq_cli/lib/rabbitmq/cli/ctl/commands/status_command.ex
  deps/rabbitmq_management/src/rabbit_mgmt_wm_overview.erl
  deps/rabbitmq_management/test/rabbit_mgmt_http_SUITE.erl
Labels: backport-v4.0.x

#12704 Osiris v1.8.4
  MODULE.bazel
  rabbitmq-components.mk
Labels: bazel, make, backport-v4.0.x

#12710 4.1: Avoid an exception when an AMQP 0-9-1-originating message with expiration set is converted for an MQTT consumer
  deps/rabbitmq_mqtt/src/mc_mqtt.erl
  deps/rabbitmq_mqtt/test/mc_mqtt_SUITE.erl
  deps/rabbitmq_mqtt/test/protocol_interop_SUITE.erl
Labels: bug, backport-v4.0.x

#12721 CQ: Fix flakes in the store file scan test
  deps/rabbit/test/backing_queue_SUITE.erl
Labels: backport-v4.0.x

#12720 Grafana Dashboards: Fix Query Errors and Improve Instance Filtering in Erlang Distribution and BEAM Dashboards
  deps/rabbitmq_prometheus/docker/grafana/dashboards/Erlang-BEAM.json
  deps/rabbitmq_prometheus/docker/grafana/dashboards/Erlang-Distribution.json
Labels: backport-v4.0.x

#12722 Fix flakes
  deps/rabbit/test/amqp_client_SUITE.erl
  deps/rabbit/test/amqpl_consumer_ack_SUITE.erl
  deps/rabbit/test/per_node_limit_SUITE.erl
  deps/rabbitmq_management/test/clustering_SUITE.erl
  deps/rabbitmq_management/test/clustering_prop_SUITE.erl
  deps/rabbitmq_mqtt/test/mqtt_shared_SUITE.erl
Labels: backport-v4.0.x

#12714 Support publishing AMQP 1.0 to Event Exchange
  deps/rabbit/src/mc_amqpl.erl
  deps/rabbit/src/mc_util.erl
  deps/rabbit/test/mc_unit_SUITE.erl
  deps/rabbitmq_event_exchange/Makefile
  deps/rabbitmq_event_exchange/README.md
  deps/rabbitmq_event_exchange/priv/schema/rabbitmq_event_exchange.schema
  deps/rabbitmq_event_exchange/src/rabbit_exchange_type_event.erl
  deps/rabbitmq_event_exchange/test/config_schema_SUITE_data/rabbitmq_event_exchange.snippets
  deps/rabbitmq_event_exchange/test/system_SUITE.erl
  release-notes/4.1.0.md
Labels: make

#12727 By @Ayanda-D: Ensure only alive leaders and followers when fetching QQ replica states
  deps/rabbit/src/rabbit_quorum_queue.erl
  deps/rabbit/test/quorum_queue_SUITE.erl
  deps/rabbit/test/unit_quorum_queue_SUITE.erl
Labels: backport-v4.0.x

#12744 crashing_queues_SUITE: squash a compiler warning
  deps/rabbit/test/crashing_queues_SUITE.erl
Labels: backport-v4.0.x

#12748 Bump khepri_mnesia_migration from 0.7.0 to 0.7.1
  MODULE.bazel
  rabbitmq-components.mk
Labels: bazel, make

#12752 By @Hathoute: consider additional_scopes_key when multiple OAuth 2 backends are used
  deps/rabbitmq_auth_backend_oauth2/src/rabbit_oauth2_schema.erl
  deps/rabbitmq_auth_backend_oauth2/test/config_schema_SUITE_data/rabbitmq_auth_backend_oauth2.snippets
  deps/rabbitmq_auth_backend_oauth2/test/rabbit_oauth2_schema_SUITE.erl
Labels: backport-v4.0.x

#12759 Minor update in README of recent history exchange
  deps/rabbitmq_recent_history_exchange/README.md
Labels: backport-v4.0.x

#12769 Update COMMUNITY_SUPPORT.md
  COMMUNITY_SUPPORT.md
Labels: backport-v4.0.x

#12773 bazel run gazelle
  deps/rabbitmq_ct_helpers/BUILD.bazel
  deps/rabbitmq_ct_helpers/app.bzl
  moduleindex.yaml
Labels: bazel

#12780 bazel run gazelle
  deps/rabbitmq_management/app.bzl
  moduleindex.yaml
Labels: bazel

#12723 Use preprocessor macros for building Khepri path patterns
  deps/rabbit/app.bzl
  deps/rabbit/include/khepri.hrl
  deps/rabbit/include/rabbit_khepri.hrl
  deps/rabbit/src/rabbit_db_binding.erl
  deps/rabbit/src/rabbit_db_exchange.erl
  deps/rabbit/src/rabbit_db_maintenance.erl
  deps/rabbit/src/rabbit_db_msup.erl
  deps/rabbit/src/rabbit_db_queue.erl
  deps/rabbit/src/rabbit_db_rtparams.erl
  deps/rabbit/src/rabbit_db_user.erl
  deps/rabbit/src/rabbit_db_vhost.erl
  deps/rabbit/src/rabbit_khepri.erl
Labels: bazel, backport-v4.0.x

#12785 Update osiris to v1.8.5
  MODULE.bazel
  rabbitmq-components.mk
Labels: streams, bazel, make, backport-v4.0.x

#12790 bazel run gazelle
  deps/rabbit/app.bzl
Labels: bazel

#12795 Drop release_series_support_status from GET /api/overview and 'rabbitmq-diagnostics status'
  deps/rabbitmq_cli/lib/rabbitmq/cli/ctl/commands/status_command.ex
  deps/rabbitmq_management/src/rabbit_mgmt_wm_overview.erl
Labels: backport-v4.0.x

#12797 GET /api/overview: format cluster and node tag lists as maps
  deps/rabbitmq_management/src/rabbit_mgmt_wm_overview.erl
Labels: backport-v4.0.x

#12799 rabbit_vhosts: Don't reconcile vhosts if `rabbit` is stopped
  deps/rabbit/src/rabbit_vhosts.erl
  deps/rabbit/test/quorum_queue_member_reconciliation_SUITE.erl
Labels: backport-v4.0.x

#12775 Fixes for test flakes
  deps/oauth2_client/test/system_SUITE.erl
  deps/rabbit/test/amqp_client_SUITE.erl
  deps/rabbit/test/amqp_filtex_SUITE.erl
  deps/rabbitmq_ct_helpers/src/rabbit_ct_helpers.erl
  deps/rabbitmq_management/test/clustering_SUITE.erl
  deps/rabbitmq_management/test/clustering_prop_SUITE.erl
  deps/rabbitmq_mqtt/test/auth_SUITE.erl
  deps/rabbitmq_mqtt/test/mqtt_shared_SUITE.erl
  deps/rabbitmq_mqtt/test/v5_SUITE.erl
  selenium/test/basic-auth/ac-management.js
Labels: backport-v4.0.x

#12812 bazel run gazelle
  deps/rabbitmq_management/app.bzl
  moduleindex.yaml
Labels: bazel

#12820 v4.0.x: Expose max offset lag of stream consumers via Prometheus
  deps/amqp10_common/src/serial_number.erl
  deps/rabbitmq_ct_helpers/BUILD.bazel
  deps/rabbitmq_ct_helpers/Makefile
  deps/rabbitmq_ct_helpers/app.bzl
  deps/rabbitmq_ct_helpers/src/stream_test_utils.erl
  deps/rabbitmq_prometheus/BUILD.bazel
  deps/rabbitmq_prometheus/Makefile
  deps/rabbitmq_prometheus/src/collectors/prometheus_rabbitmq_core_metrics_collector.erl
  deps/rabbitmq_prometheus/test/rabbit_prometheus_http_SUITE.erl
  deps/rabbitmq_stream/test/protocol_interop_SUITE.erl
  moduleindex.yaml
Labels: bazel, make

#12825 Require Java 11 in stream Java client projects
  deps/rabbitmq_stream/test/rabbit_stream_SUITE_data/pom.xml
  deps/rabbitmq_stream_management/test/http_SUITE_data/pom.xml
Labels: backport-v3.13.x, backport-v4.0.x

#12824 bazel run gazelle
  deps/rabbitmq_prometheus/BUILD.bazel
Labels: bazel

#12818 OAuth 2: JWT token refresh should preserve user identity displayed in the UI
  deps/rabbitmq_auth_backend_oauth2/src/rabbit_auth_backend_oauth2.erl
  deps/rabbitmq_auth_backend_oauth2/test/jwks_SUITE.erl
  deps/rabbitmq_auth_backend_oauth2/test/system_SUITE.erl
Labels: backport-v4.0.x

#12786 Selenium suites: replace Java AMQP 1.0 client with a JavaScript one
  selenium/Dockerfile
  selenium/amqp10-roundtriptest/pom.xml
  selenium/amqp10-roundtriptest/run
  selenium/amqp10-roundtriptest/src/main/java/com/rabbitmq/amqp1_0/RoundTripTest.java
  selenium/package.json
  selenium/test/amqp.js
  selenium/test/authnz-msg-protocols/amqp10.js
  selenium/test/connections/amqp10/sessions-for-monitoring-user.js
Labels: backport-v4.0.x

#12821 Definition export: inject default queue type into virtual host metadata
  deps/rabbit/src/rabbit_definitions.erl
  deps/rabbit/src/rabbit_queue_type.erl
  deps/rabbit/src/rabbit_vhost.erl
  deps/rabbit/src/vhost.erl
  deps/rabbitmq_cli/lib/rabbitmq/cli/ctl/commands/export_definitions_command.ex
  deps/rabbitmq_cli/lib/rabbitmq/cli/ctl/commands/list_vhosts_command.ex
  deps/rabbitmq_ct_helpers/src/rabbit_ct_broker_helpers.erl
  deps/rabbitmq_management/src/rabbit_mgmt_wm_definitions.erl
  deps/rabbitmq_management/src/rabbit_mgmt_wm_overview.erl
  deps/rabbitmq_management/src/rabbit_mgmt_wm_vhosts.erl
  deps/rabbitmq_management/test/rabbit_mgmt_http_SUITE.erl
Labels: backport-v4.0.x

#12840 Fix transient queue detection
  deps/rabbit/src/rabbit_amqqueue.erl
  deps/rabbit/src/rabbit_db_queue.erl
Labels: backport-v4.0.x

#12842 bazel run gazelle
  deps/amqp10_client/app.bzl
Labels: bazel

#12845 Fix selenium issues on v4.0.x
  selenium/.gitignore
  selenium/bin/components/devkeycloak
  selenium/bin/components/keycloak
  selenium/bin/components/prodkeycloak
  selenium/bin/components/rabbitmq
  selenium/bin/components/uaa
  selenium/bin/suite_template
  selenium/full-suite-management-ui
  selenium/package.json
  selenium/run-suites.sh
  selenium/suites/authnz-mgt/basic-auth-behind-proxy.sh
  selenium/suites/authnz-mgt/oauth-idp-initiated-with-uaa-and-prefix-via-proxy.sh
  selenium/suites/authnz-mgt/oauth-idp-initiated-with-uaa-via-proxy.sh
  selenium/test/amqp.js
  selenium/test/authnz-msg-protocols/env.auth-oauth-dev.docker
  selenium/test/authnz-msg-protocols/env.auth-oauth-dev.local
  selenium/test/authnz-msg-protocols/env.auth-oauth-prod.docker
  selenium/test/authnz-msg-protocols/env.auth-oauth-prod.local
  selenium/test/authnz-msg-protocols/env.docker.devkeycloak
  selenium/test/authnz-msg-protocols/env.docker.prodkeycloak
  selenium/test/authnz-msg-protocols/env.local.devkeycloak
  selenium/test/authnz-msg-protocols/env.local.prodkeycloak
  selenium/test/basic-auth/certs/ca_rabbitmq_certificate.pem
  selenium/test/basic-auth/certs/client_rabbitmq.jks
  selenium/test/basic-auth/certs/client_rabbitmq.p12
  selenium/test/basic-auth/certs/client_rabbitmq_certificate.pem
  selenium/test/basic-auth/certs/client_rabbitmq_key.pem
  selenium/test/basic-auth/certs/server_rabbitmq.jks
  selenium/test/basic-auth/certs/server_rabbitmq.p12
  selenium/test/basic-auth/certs/server_rabbitmq_certificate.pem
  selenium/test/basic-auth/certs/server_rabbitmq_key.pem
  selenium/test/basic-auth/certs/truststore.jks
  selenium/test/multi-oauth/env.docker.devkeycloak
  selenium/test/multi-oauth/env.docker.prodkeycloak
  selenium/test/multi-oauth/env.local.devkeycloak
  selenium/test/multi-oauth/env.local.prodkeycloak
  selenium/test/multi-oauth/rabbitmq.tls.conf
  selenium/test/oauth/certs/ca_certificate.pem
  selenium/test/oauth/certs/server_rabbitmq_certificate.pem
  selenium/test/oauth/certs/server_rabbitmq_key.pem
  selenium/test/oauth/env.docker.keycloak
  selenium/test/oauth/env.local.keycloak
  selenium/test/oauth/keycloak/ca_certificate.pem
  selenium/test/oauth/keycloak/server_keycloak_certificate.pem
  selenium/test/oauth/keycloak/server_keycloak_key.pem
  selenium/test/oauth/rabbitmq.tls.conf
Labels: bazel, make

#12849 Fix selenium suites in v4.0.x
  selenium/test/multi-oauth/env.docker.devkeycloak
  selenium/test/multi-oauth/env.docker.prodkeycloak
Labels: bazel, make

#12837 rabbit_quorum_queue: Wait for member add in `add_member/4`
  deps/rabbit/src/rabbit_quorum_queue.erl
Labels: backport-v4.0.x

#12846 Pin Horus to 0.3.1 temporarily
  MODULE.bazel
  deps/rabbit/Makefile
Labels: bazel, make

#12860 rabbitmq_cli: Improve test node start
  deps/rabbitmq_cli/Makefile
Labels: make

#12866 bazel run gazelle
  deps/rabbit/BUILD.bazel
  deps/rabbit/app.bzl
  deps/rabbitmq_mqtt/app.bzl
  deps/rabbitmq_web_mqtt/app.bzl
Labels: bazel
