Repository rabbitmq/rabbitmq-server, pull requests merged in 2025-02, with the labels that each got.

#13187 Bump Khepri cluster formation timeout to the standard 5 minutes
  deps/rabbit/src/rabbit_khepri.erl
Labels: backport-v4.0.x

#13190 Ra 2.16.1
  MODULE.bazel
  rabbitmq-components.mk
Labels: bazel, make

#13202 Add tests for different JMS message types
  deps/rabbit/Makefile
  deps/rabbit/ct.test.spec
  deps/rabbit/test/amqp_client_SUITE.erl
  deps/rabbit/test/amqp_dotnet_SUITE.erl
  deps/rabbit/test/amqp_dotnet_SUITE_data/console/Program.cs
  deps/rabbit/test/amqp_dotnet_SUITE_data/console/README.md
  deps/rabbit/test/amqp_dotnet_SUITE_data/console/standalone.csproj
  deps/rabbit/test/amqp_dotnet_SUITE_data/fsharp-tests/Program.fs
  deps/rabbit/test/amqp_dotnet_SUITE_data/fsharp-tests/fsharp-tests.fsproj
  deps/rabbit/test/amqp_dotnet_SUITE_data/fsharp-tests/global.json
  deps/rabbit/test/amqp_jms_SUITE.erl
  deps/rabbit/test/amqp_jms_SUITE_data/.gitignore
  deps/rabbit/test/amqp_jms_SUITE_data/.mvn/wrapper/maven-wrapper.properties
  deps/rabbit/test/amqp_jms_SUITE_data/mvnw
  deps/rabbit/test/amqp_jms_SUITE_data/mvnw.cmd
  deps/rabbit/test/amqp_jms_SUITE_data/pom.xml
  deps/rabbit/test/amqp_jms_SUITE_data/src/test/java/com/rabbitmq/amqp/tests/jms/JmsTest.java
  deps/rabbit/test/amqp_jms_SUITE_data/src/test/resources/logback-test.xml
  deps/rabbit/test/amqp_system_SUITE_data/java-tests/src/test/java/com/rabbitmq/amqp1_0/tests/jms/RoundTripTest.java
  deps/rabbit/test/amqp_utils.erl
Labels: make

#13050 k8s peer discovery v2
  deps/rabbit/src/rabbit_peer_discovery.erl
  deps/rabbit_common/src/rabbit_peer_discovery_backend.erl
  deps/rabbitmq_peer_discovery_k8s/Makefile
  deps/rabbitmq_peer_discovery_k8s/README.md
  deps/rabbitmq_peer_discovery_k8s/app.bzl
  deps/rabbitmq_peer_discovery_k8s/include/rabbit_peer_discovery_k8s.hrl
  deps/rabbitmq_peer_discovery_k8s/priv/schema/rabbitmq_peer_discovery_k8s.schema
  deps/rabbitmq_peer_discovery_k8s/src/rabbit_peer_discovery_k8s.erl
  deps/rabbitmq_peer_discovery_k8s/src/rabbitmq_peer_discovery_k8s.erl
  deps/rabbitmq_peer_discovery_k8s/src/rabbitmq_peer_discovery_k8s_app.erl
  deps/rabbitmq_peer_discovery_k8s/src/rabbitmq_peer_discovery_k8s_node_monitor.erl
  deps/rabbitmq_peer_discovery_k8s/src/rabbitmq_peer_discovery_k8s_sup.erl
  deps/rabbitmq_peer_discovery_k8s/test/config_schema_SUITE_data/rabbitmq_peer_discovery_k8s.snippets
  deps/rabbitmq_peer_discovery_k8s/test/rabbitmq_peer_discovery_k8s_SUITE.erl
Labels: bazel, make

#13206 bazel run gazelle
  deps/rabbit/app.bzl
  deps/rabbitmq_peer_discovery_k8s/BUILD.bazel
  deps/rabbitmq_peer_discovery_k8s/app.bzl
  moduleindex.yaml
Labels: bazel

#13211 Set cluster_name to "localhost" when running with make
  deps/rabbit_common/mk/rabbitmq-run.mk
Labels: make, backport-v4.0.x

#13210 Peer discovery: disable consul health check helper when registration is disabled
  deps/rabbit/src/rabbit_peer_discovery.erl
  deps/rabbitmq_peer_discovery_consul/src/rabbitmq_peer_discovery_consul_health_check_helper.erl
Labels: backport-v4.0.x

#13219 Bump observer_cli to 1.8.2
  MODULE.bazel
  rabbitmq-components.mk
Labels: bazel, make, backport-v4.0.x

#13218 Add rabbitmq_endpoint label to rabbitmq_identity_info
  deps/rabbitmq_prometheus/src/collectors/prometheus_rabbitmq_core_metrics_collector.erl
Labels: backport-v4.1.x

#13180 Fix flake on rabbitmq_mqtt auth_SUITE
  deps/rabbitmq_mqtt/test/auth_SUITE.erl
  selenium/package.json
  selenium/test/pageobjects/BasePage.js
Labels: backport-v4.0.x, backport-v4.1.x

#13244 'ctl delete_shovel': adapt to rabbit_shovel_dyn_worker_sup_sup public API changes
  deps/rabbitmq_shovel/src/Elixir.RabbitMQ.CLI.Ctl.Commands.DeleteShovelCommand.erl
Labels: backport-v4.0.x, backport-v4.1.x

#13198 Show consumer count column on Mgmt UI Channels page
  deps/rabbitmq_management/priv/www/js/global.js
  deps/rabbitmq_management/priv/www/js/tmpl/channels-list.ejs
Labels: backport-v4.0.x, backport-v4.1.x

#13260 bazel run gazelle
  deps/rabbitmq_auth_backend_cache/app.bzl
  moduleindex.yaml
Labels: bazel

#13261 bazel run gazelle
  deps/rabbitmq_auth_backend_cache/app.bzl
  moduleindex.yaml
Labels: bazel

#13324 Use JUnit extension to configure JMS tests
  deps/rabbit/test/amqp_jms_SUITE.erl
  deps/rabbit/test/amqp_jms_SUITE_data/pom.xml
  deps/rabbit/test/amqp_jms_SUITE_data/src/test/java/com/rabbitmq/amqp/tests/jms/Cli.java
  deps/rabbit/test/amqp_jms_SUITE_data/src/test/java/com/rabbitmq/amqp/tests/jms/JmsConnectionTest.java
  deps/rabbit/test/amqp_jms_SUITE_data/src/test/java/com/rabbitmq/amqp/tests/jms/JmsTemporaryQueueTest.java
  deps/rabbit/test/amqp_jms_SUITE_data/src/test/java/com/rabbitmq/amqp/tests/jms/JmsTest.java
  deps/rabbit/test/amqp_jms_SUITE_data/src/test/java/com/rabbitmq/amqp/tests/jms/JmsTestInfrastructureExtension.java
  deps/rabbit/test/amqp_jms_SUITE_data/src/test/java/com/rabbitmq/amqp/tests/jms/TestUtils.java
  deps/rabbit/test/amqp_jms_SUITE_data/src/test/resources/logback-test.xml
Labels: backport-v4.1.x

#13331 Trap exit in AMQP 1.0 client proc
  deps/amqp10_client/src/amqp10_client_frame_reader.erl
Labels: backport-v4.1.x

#13329 Increase the TCP ports range used by `parallel-ct-set-*`
  deps/rabbit/Makefile
Labels: make

#13325 Follow-up: finish 'rabbitmqctl clear_auth_backend_cache' plus add tests
  deps/rabbitmq_auth_backend_cache/src/rabbit_auth_backend_cache.erl
  deps/rabbitmq_auth_backend_cache/src/rabbit_auth_cache.erl
  deps/rabbitmq_auth_backend_cache/src/rabbit_auth_cache_dict.erl
  deps/rabbitmq_auth_backend_cache/src/rabbit_auth_cache_ets.erl
  deps/rabbitmq_auth_backend_cache/src/rabbit_auth_cache_ets_segmented.erl
  deps/rabbitmq_auth_backend_cache/src/rabbit_auth_cache_ets_segmented_stateless.erl
  deps/rabbitmq_auth_backend_cache/test/rabbit_auth_cache_SUITE.erl
  deps/rabbitmq_auth_backend_cache/test/rabbit_auth_clear_cache_command_SUITE.erl
Labels: backport-v4.0.x, backport-v4.1.x

#13307 Mc: introduce new function in mc_amqp to init mc from stream data
  deps/rabbit/src/mc_amqp.erl
  deps/rabbit/src/rabbit_stream_queue.erl
Labels: backport-v4.0.x, backport-v4.1.x

#13328 Ra v2.16.2
  MODULE.bazel
  rabbitmq-components.mk
Labels: bazel, make, backport-v4.1.x

#13326 Ra v2.15.2
  MODULE.bazel
  rabbitmq-components.mk
Labels: bazel, make

#13343 bazel run gazelle
  deps/rabbitmq_auth_backend_cache/app.bzl
Labels: bazel

#13342 bazel run gazelle
  deps/rabbitmq_auth_backend_cache/app.bzl
Labels: bazel

#13353 Update queue-messages and queue-message-body-bytes tooltips
  deps/rabbitmq_management/priv/www/js/global.js
  deps/rabbitmq_management/priv/www/js/tmpl/queue.ejs
Labels: backport-v4.0.x, backport-v4.1.x

#13351 CLI: Don't use regex as module attributes
  deps/rabbitmq_cli/lib/rabbitmq/cli/core/command_modules.ex
  deps/rabbitmq_cli/lib/rabbitmq/cli/core/os_pid.ex
Labels: backport-v4.0.x, backport-v4.1.x

#13242 Update Cowboy
  deps/rabbitmq_mqtt/Makefile
  rabbitmq-components.mk
Labels: make

#13364 Recover "received timestamp" when reading from stream
  deps/rabbit/src/mc.erl
  deps/rabbit/src/mc_amqp.erl
  deps/rabbit/test/mc_unit_SUITE.erl
Labels: backport-v4.1.x

#13365 Delete rabbit_uri
  deps/rabbit/Makefile
  deps/rabbit/src/rabbit_amqp_management.erl
  deps/rabbit/src/rabbit_amqp_session.erl
  deps/rabbit/src/rabbit_uri.erl
  deps/rabbitmq_mqtt/src/mc_mqtt.erl
Labels: make, backport-v4.1.x

#13360 Remove set_stream_retention_policy command
  deps/rabbit/docs/rabbitmq-streams.8
  deps/rabbit/src/rabbit_stream_queue.erl
  deps/rabbitmq_cli/lib/rabbitmq/cli/streams/commands/set_stream_retention_policy_command.ex
  deps/rabbitmq_cli/test/streams/set_stream_retention_policy_command_test.exs
Labels: breaking-change, backport-v4.1.x

#13358 Deprecate set_stream_retention_policy command
  deps/rabbit/docs/rabbitmq-streams.8
  deps/rabbit/src/rabbit_stream_queue.erl
  deps/rabbitmq_cli/lib/rabbitmq/cli/streams/commands/set_stream_retention_policy_command.ex
  deps/rabbitmq_cli/test/streams/set_stream_retention_policy_command_test.exs
Labels: bug

#13370 bazel run gazelle
  deps/rabbit/BUILD.bazel
  deps/rabbit/app.bzl
  deps/rabbitmq_mqtt/BUILD.bazel
  moduleindex.yaml
Labels: bazel

#13382 rabbit_backing_queue: pass mc:state() to discard callback
  deps/rabbit/src/rabbit_backing_queue.erl
Labels: backport-v4.1.x

#13385 Adding a "source-bundle" target to the Makefile
  Makefile
Labels: make, backport-v4.0.x, backport-v4.1.x

#13411 Send all received WebSocket frames to app
  deps/rabbitmq_ct_client_helpers/src/rfc6455_client.erl
Labels: bug, backport-v4.1.x

#13380 Tests: add rabbitmq_diagnostics to test helpers
  deps/rabbitmq_ct_helpers/src/rabbit_ct_broker_helpers.erl
  deps/rabbitmq_ct_helpers/src/rabbit_ct_helpers.erl
Labels: backport-v4.0.x, backport-v4.1.x

#13408 Do not propagate `none` password to http backend
  deps/rabbitmq_auth_backend_http/src/rabbit_auth_backend_http.erl
  deps/rabbitmq_auth_backend_http/test/auth_SUITE.erl
  deps/rabbitmq_auth_backend_http/test/auth_http_mock.erl
  deps/rabbitmq_mqtt/test/auth_SUITE.erl
  selenium/full-suite-authnz-messaging
  selenium/suites/authnz-messaging/auth-http-backend-with-mtls.sh
  selenium/suites/authnz-messaging/auth-http-backend.sh
  selenium/test/amqp.js
  selenium/test/authnz-msg-protocols/amqp10.js
  selenium/test/authnz-msg-protocols/mqtt.js
Labels: backport-v4.1.x

#13430 Fix CQ shared store files not deleted with large messages
  deps/rabbit/src/rabbit_msg_store.erl
Labels: backport-v4.0.x, backport-v4.1.x

#13363 Add dynamic socket buffer functionality to rabbit_reader
  deps/rabbit/include/rabbit_amqp_reader.hrl
  deps/rabbit/src/rabbit_amqp_reader.erl
  deps/rabbit/src/rabbit_networking.erl
  deps/rabbit/src/rabbit_reader.erl
Labels: backport-v4.1.x

#13435 Handle mc_amqp 3.13 `msg` record in 4.x
  deps/rabbit/src/mc_amqp.erl
Labels: backport-v4.0.x, backport-v4.1.x
