Repository rabbitmq/rabbitmq-server, pull requests merged in 2025-03, with the labels that each got.

#13442 Bump Prometheus Version
  deps/rabbitmq_prometheus/docker/docker-compose-metrics.yml
Labels: backport-v4.0.x, backport-v4.1.x

#13445 Osiris 1.8.6
  MODULE.bazel
  rabbitmq-components.mk
  release-notes/4.1.0.md
Labels: bazel, make, backport-v4.0.x, backport-v4.1.x

#13465 By @aaron-seo: Optionally allow separate configuration of auth_backends for all HTTP-based plugins (protocols, APIs)
  deps/rabbit/src/rabbit_access_control.erl
  deps/rabbitmq_web_dispatch/priv/schema/rabbitmq_web_dispatch.schema
  deps/rabbitmq_web_dispatch/src/rabbit_web_dispatch_access_control.erl
  deps/rabbitmq_web_dispatch/test/config_schema_SUITE.erl
  deps/rabbitmq_web_dispatch/test/config_schema_SUITE_data/rabbitmq_web_dispatch.snippets
Labels: backport-v4.0.x, backport-v4.1.x

#13409 amqp_client_SUITE: Fix frequent test failures
  .github/workflows/test-make-tests.yaml
  deps/amqp10_client/src/amqp10_client_connection.erl
  deps/rabbit/Makefile
  deps/rabbit/test/amqp_client_SUITE.erl
Labels: make

#13471 (Updated) Adding a "source-bundle" target to the Makefile
  Makefile
Labels: make

#13480 Fix flake in test case session_upgrade_v3_v5_qos1
  deps/rabbitmq_mqtt/test/v5_SUITE.erl
Labels: backport-v4.0.x, backport-v4.1.x

#13487 By @Ayanda-D: new CLI health check that detects QQs without an elected reachable leader #13433
  deps/rabbit/src/amqqueue.erl
  deps/rabbit/src/rabbit_db_queue.erl
  deps/rabbit/src/rabbit_quorum_queue.erl
  deps/rabbit/test/quorum_queue_SUITE.erl
  deps/rabbit/test/rabbit_db_queue_SUITE.erl
  deps/rabbitmq_cli/lib/rabbitmq/cli/core/output.ex
  deps/rabbitmq_cli/lib/rabbitmq/cli/diagnostics/commands/check_for_quorum_queues_without_an_elected_leader_command.ex
  deps/rabbitmq_cli/test/diagnostics/check_for_quorum_queues_without_an_elected_leader_command_test.exs
Labels: backport-v4.0.x, backport-v4.1.x

#13425 Fix log collection in Selenium workflows
  .github/workflows/test-management-ui-for-pr.yaml
  .github/workflows/test-management-ui.yaml
Labels: backport-v4.1.x

#13495 Update support link.
  deps/rabbitmq_management/priv/www/js/tmpl/layout.ejs
Labels: backport-v4.0.x, backport-v4.1.x

#13493 Add missing selenium function
  selenium/bin/suite_template
  selenium/suites/authnz-mgt/multi-oauth-with-basic-auth-when-idps-down.sh
  selenium/test/oauth/with-idp-down/landing.js
  selenium/test/pageobjects/BasePage.js
  selenium/test/pageobjects/SSOHomePage.js
Labels: backport-v4.0.x, backport-v4.1.x

#13476 Improve oauth2 idp-initiated login
  deps/rabbitmq_management/include/rabbit_mgmt.hrl
  deps/rabbitmq_management/src/rabbit_mgmt_login.erl
  deps/rabbitmq_management/src/rabbit_mgmt_oauth_bootstrap.erl
  selenium/bin/components/fakeportal
Labels: backport-v4.0.x, backport-v4.1.x

#13485 Minor improvement: Remove observer_cli from CLI escritps
  deps/rabbitmq_cli/Makefile
  deps/rabbitmq_cli/lib/rabbitmq/cli/diagnostics/commands/observer_command.ex
  deps/rabbitmq_cli/mix.exs
Labels: make, backport-v4.0.x, backport-v4.1.x

#13513 Ra 2.16.3 - bug fixes.
  rabbitmq-components.mk
Labels: make, backport-v4.1.x

#13518 rabbitmq-components.mk: Update meck from 0.9.2 to 1.0.0
  rabbitmq-components.mk
Labels: make

#13525 By @ikavgo: introduce a deletion protection marker for queues
  deps/rabbit/Makefile
  deps/rabbit/src/amqqueue.erl
  deps/rabbit/src/rabbit_amqqueue.erl
  deps/rabbit/test/rabbit_amqqueue_SUITE.erl
Labels: make, backport-v4.1.x

#13528 By @ikavgo: add a --force option to 'rabbitmqctl delete_queue'
  deps/rabbitmq_cli/lib/rabbitmq/cli/core/users.ex
  deps/rabbitmq_cli/lib/rabbitmq/cli/ctl/commands/delete_queue_command.ex
  deps/rabbitmq_cli/test/ctl/delete_queue_command_test.exs
  deps/rabbitmq_cli/test/test_helper.exs
Labels: backport-v4.1.x

#13530 Ra 2.15.3 - bug fixes
  MODULE.bazel
  rabbitmq-components.mk
Labels: bazel, make

#13542 Increase initial AMQP 0-9-1 connection frame size limit
  deps/rabbit_common/include/rabbit_framing.hrl
Labels: backport-v4.0.x, backport-v4.1.x

#13549 Increase FRAME-MIN-SIZE in AMQP 0-9-1 code generation file
  deps/rabbitmq_codegen/amqp-rabbitmq-0.9.1.json
Labels: backport-v4.0.x, backport-v4.1.x

#13552 Use Erlang 27 in CI for tests
  .github/workflows/test-authnz.yaml
  .github/workflows/test-make.yaml
  .github/workflows/test-management-ui-for-pr.yaml
  .github/workflows/test-management-ui.yaml
Labels: backport-v4.1.x

#13554 Commit generated code after FRAME-MIN-SIZE change
  deps/rabbit_common/src/rabbit_framing_amqp_0_8.erl
  deps/rabbit_common/src/rabbit_framing_amqp_0_9_1.erl
  deps/rabbitmq_codegen/amqp-rabbitmq-0.8.json
Labels: backport-v4.0.x, backport-v4.1.x

#13559 Log clearer message if TLS client connects to AMQP port
  deps/rabbit/src/rabbit_reader.erl
Labels: backport-v4.1.x

#12922 Native Elixir support in Erlang.mk (SEE DESCRIPTION BEFORE MERGE)
  Makefile
  deps/amqp10_client/Makefile
  deps/oauth2_client/Makefile
  deps/rabbit/Makefile
  deps/rabbit/src/rabbit_variable_queue.erl
  deps/rabbit_common/mk/rabbitmq-build.mk
  deps/rabbit_common/mk/rabbitmq-dist.mk
  deps/rabbit_common/mk/rabbitmq-early-plugin.mk
  deps/rabbitmq_auth_backend_cache/Makefile
  deps/rabbitmq_auth_backend_oauth2/Makefile
  deps/rabbitmq_aws/Makefile
  deps/rabbitmq_cli/Makefile
  deps/rabbitmq_cli/lib/rabbitmq/cli/formatters/csv.ex
  deps/rabbitmq_cli/lib/rabbitmqctl.ex
  deps/rabbitmq_cli/mix.exs
  deps/rabbitmq_cli/test/test_helper.exs
  deps/rabbitmq_consistent_hash_exchange/Makefile
  deps/rabbitmq_ct_helpers/Makefile
  deps/rabbitmq_ct_helpers/src/rabbit_ct_helpers.erl
  deps/rabbitmq_federation/Makefile
  deps/rabbitmq_federation_prometheus/Makefile
  deps/rabbitmq_management_agent/Makefile
  deps/rabbitmq_mqtt/Makefile
  deps/rabbitmq_peer_discovery_consul/Makefile
  deps/rabbitmq_peer_discovery_etcd/Makefile
  deps/rabbitmq_peer_discovery_k8s/Makefile
  deps/rabbitmq_prometheus/Makefile
  deps/rabbitmq_shovel/Makefile
  deps/rabbitmq_shovel_prometheus/Makefile
  deps/rabbitmq_stomp/Makefile
  deps/rabbitmq_stream/Makefile
  deps/rabbitmq_stream_management/Makefile
  deps/rabbitmq_web_mqtt/Makefile
  erlang.mk
  mk/rabbitmq-mix.mk
  packaging/generic-unix/Makefile
Labels: make

#13563 Improve log message for non-AMQP clients on AMQP port
  deps/rabbit/src/rabbit_reader.erl
Labels: backport-v4.1.x

#13567 By @efimov90: a dark theme for the management UI
  deps/rabbitmq_management/priv/www/css/dark.css
  deps/rabbitmq_management/priv/www/css/light.css
  deps/rabbitmq_management/priv/www/css/main.css
  deps/rabbitmq_management/priv/www/img/auto.svg
  deps/rabbitmq_management/priv/www/img/dark.svg
  deps/rabbitmq_management/priv/www/img/light.svg
  deps/rabbitmq_management/priv/www/index.html
  deps/rabbitmq_management/priv/www/js/theme-switcher.js
  deps/rabbitmq_management/priv/www/js/tmpl/layout.ejs
Labels: backport-v4.1.x

#13565 Extend rabbit_amqqueue_SUITE and add amqqueue:make_internal/{1,2} type specs
  deps/rabbit/src/amqqueue.erl
  deps/rabbit/test/rabbit_amqqueue_SUITE.erl
Labels: backport-v4.1.x

#13574 Auto widen session incoming-window in AMQP 1.0 client
  deps/amqp10_client/src/amqp10_client.erl
  deps/amqp10_client/src/amqp10_client_session.erl
  deps/rabbit/test/amqp_client_SUITE.erl
  deps/rabbitmq_amqp_client/test/management_SUITE.erl
Labels: bug, backport-v4.0.x, backport-v4.1.x

#13571 New HTTP API health check endpoints
  deps/rabbitmq_management/src/rabbit_mgmt_dispatcher.erl
  deps/rabbitmq_management/src/rabbit_mgmt_wm_health_check_quorum_queues_without_elected_leaders.erl
  deps/rabbitmq_management/src/rabbit_mgmt_wm_health_check_quorum_queues_without_elected_leaders_across_all_vhosts.erl
  deps/rabbitmq_management/test/rabbit_mgmt_http_health_checks_SUITE.erl
Labels: backport-v4.1.x

#13580 Update Erlang.mk (MERGE IF GREEN)
  erlang.mk
Labels: make

#13588 Pull from socket up to 10 times in stream test utils
  deps/rabbitmq_ct_helpers/src/stream_test_utils.erl
  deps/rabbitmq_prometheus/test/rabbit_prometheus_http_SUITE.erl
  deps/rabbitmq_stream/test/rabbit_stream_SUITE.erl
Labels: backport-v4.0.x, backport-v4.1.x

#13607 Bump Cuttlefish to 3.5.0
  rabbitmq-components.mk
Labels: make, backport-v4.0.x, backport-v4.1.x

#13604 Switch is_<queue_type> to using queue.type field in Management UI
  deps/rabbit/src/rabbit_classic_queue.erl
  deps/rabbit/src/rabbit_quorum_queue.erl
  deps/rabbit/src/rabbit_stream_queue.erl
  deps/rabbit/test/quorum_queue_SUITE.erl
  deps/rabbit/test/rabbit_stream_queue_SUITE.erl
  deps/rabbitmq_management/priv/www/js/main.js
Labels: backport-v4.1.x

#13612 Fix the errors logged by Cowboy caused by double reply in a few endpoints
  deps/rabbitmq_management/src/rabbit_mgmt_util.erl
  deps/rabbitmq_management/src/rabbit_mgmt_wm_exchange_publish.erl
  deps/rabbitmq_management/src/rabbit_mgmt_wm_queue_actions.erl
  deps/rabbitmq_management/src/rabbit_mgmt_wm_queue_get.erl
Labels: backport-v4.0.x, backport-v4.1.x

#13603 Remove redundant rabbit_queue_type APIs
  deps/rabbit/src/rabbit_amqp_management.erl
  deps/rabbit/src/rabbit_queue_type.erl
  deps/rabbit/src/rabbit_vhost.erl
Labels: backport-v4.1.x

#13587 QQ: Revise checkpointing logic to take more frequent checkpoints for large message workloads
  deps/rabbit/src/rabbit_fifo.erl
  deps/rabbit/src/rabbit_fifo.hrl
  deps/rabbit/src/rabbit_quorum_queue.erl
  deps/rabbit/test/quorum_queue_SUITE.erl
Labels: backport-v4.0.x, backport-v4.1.x

#13623 Fix the CLI's main module on Windows
  deps/rabbit/scripts/rabbitmq-diagnostics.bat
  deps/rabbit/scripts/rabbitmq-plugins.bat
  deps/rabbit/scripts/rabbitmq-queues.bat
  deps/rabbit/scripts/rabbitmq-streams.bat
  deps/rabbit/scripts/rabbitmq-upgrade.bat
  deps/rabbit/scripts/rabbitmqctl.bat
  deps/rabbit/scripts/vmware-rabbitmq.bat
Labels: backport-v4.1.x

#13620 Shovel: keep track of forwarded message count (a new metric)
  deps/rabbitmq_shovel/src/Elixir.RabbitMQ.CLI.Ctl.Commands.DeleteShovelCommand.erl
  deps/rabbitmq_shovel/src/Elixir.RabbitMQ.CLI.Ctl.Commands.RestartShovelCommand.erl
  deps/rabbitmq_shovel/src/rabbit_amqp091_shovel.erl
  deps/rabbitmq_shovel/src/rabbit_shovel_behaviour.erl
  deps/rabbitmq_shovel/src/rabbit_shovel_status.erl
  deps/rabbitmq_shovel/src/rabbit_shovel_worker.erl
  deps/rabbitmq_shovel/test/amqp10_SUITE.erl
  deps/rabbitmq_shovel/test/configuration_SUITE.erl
  deps/rabbitmq_shovel/test/dynamic_SUITE.erl
  deps/rabbitmq_shovel/test/shovel_status_command_SUITE.erl
  deps/rabbitmq_shovel/test/shovel_test_utils.erl
  deps/rabbitmq_shovel_management/src/rabbit_shovel_mgmt_util.erl
  deps/rabbitmq_shovel_prometheus/src/rabbit_shovel_prometheus_collector.erl
  deps/rabbitmq_shovel_prometheus/test/prometheus_rabbitmq_shovel_collector_SUITE.erl
Labels: backport-v4.1.x

#13629 Use case-insensitive `lists:member`
  deps/rabbitmq_auth_backend_ldap/src/rabbit_auth_backend_ldap.erl
Labels: backport-v4.0.x, backport-v4.1.x

#13634 New Shovel management UI metrics
  deps/rabbitmq_shovel_management/priv/www/js/shovel.js
  deps/rabbitmq_shovel_management/priv/www/js/tmpl/shovels.ejs
  deps/rabbitmq_shovel_management/src/rabbit_shovel_mgmt_util.erl
Labels: backport-v4.1.x

#13636 Bump timeout in RabbitMQ AMQP 1.0 Erlang client
  deps/rabbit/test/amqp_client_SUITE.erl
  deps/rabbitmq_amqp_client/src/rabbitmq_amqp_client.erl
Labels: backport-v4.1.x

#13583 Emit queue_info metric
  deps/rabbitmq_prometheus/src/collectors/prometheus_rabbitmq_core_metrics_collector.erl
  deps/rabbitmq_prometheus/test/rabbit_prometheus_http_SUITE.erl
Labels: backport-v4.1.x

#13638 Ra 2.16.5 - bug fixes and minor improvements
  deps/rabbit/src/rabbit_quorum_queue.erl
  deps/rabbitmq_management/test/rabbit_mgmt_only_http_SUITE.erl
  rabbitmq-components.mk
Labels: make, backport-v4.1.x

#13646 queue info metric: guard against whereis returning `undefined`
  deps/rabbitmq_prometheus/src/collectors/prometheus_rabbitmq_core_metrics_collector.erl
Labels: backport-v4.1.x

#13649 [skip ci] fix debug log formatting
  deps/rabbit/src/rabbit_quorum_queue.erl
Labels: backport-v4.1.x

#13657 Re-evaluate stream SAC group after connection down event
  deps/rabbit/src/rabbit_stream_sac_coordinator.erl
  deps/rabbit/test/rabbit_stream_sac_coordinator_SUITE.erl
  deps/rabbitmq_stream/src/rabbit_stream_reader.erl
Labels: bug, backport-v4.0.x, backport-v4.1.x
