Repository rabbitmq/rabbitmq-server, pull requests merged in 2025-01, with the labels that each got.

#13010 Update doc link
  deps/rabbit/src/rabbit_amqp_session.erl
Labels: backport-v4.0.x

#13015 4.1.0: Introduce a way to protect a virtual host from deletion
  deps/rabbit/src/rabbit_db_vhost.erl
  deps/rabbit/src/rabbit_definitions.erl
  deps/rabbit/src/rabbit_vhost.erl
  deps/rabbit/src/vhost.erl
  deps/rabbit/test/definition_import_SUITE.erl
  deps/rabbit/test/definition_import_SUITE_data/case22.json
  deps/rabbitmq_cli/lib/rabbitmq/cli/ctl/commands/cluster_status_command.ex
  deps/rabbitmq_cli/lib/rabbitmq/cli/ctl/commands/decode_command.ex
  deps/rabbitmq_cli/lib/rabbitmq/cli/ctl/commands/decrypt_conf_value_command.ex
  deps/rabbitmq_cli/lib/rabbitmq/cli/ctl/commands/delete_vhost_command.ex
  deps/rabbitmq_cli/lib/rabbitmq/cli/ctl/commands/disable_vhost_deletion_protection_command.ex
  deps/rabbitmq_cli/lib/rabbitmq/cli/ctl/commands/enable_feature_flag_command.ex
  deps/rabbitmq_cli/lib/rabbitmq/cli/ctl/commands/enable_vhost_deletion_protection_command.ex
  deps/rabbitmq_cli/lib/rabbitmq/cli/ctl/commands/encode_command.ex
  deps/rabbitmq_cli/lib/rabbitmq/cli/ctl/commands/encrypt_conf_value_command.ex
  deps/rabbitmq_cli/lib/rabbitmq/cli/ctl/commands/list_vhosts_command.ex
  deps/rabbitmq_cli/lib/rabbitmq/cli/ctl/commands/status_command.ex
  deps/rabbitmq_cli/lib/rabbitmq/cli/ctl/commands/update_vhost_metadata_command.ex
  deps/rabbitmq_cli/lib/rabbitmq/cli/diagnostics/commands/check_if_any_deprecated_features_are_used_command.ex
  deps/rabbitmq_cli/lib/rabbitmq/cli/diagnostics/commands/metadata_store_status_command.ex
  deps/rabbitmq_cli/lib/rabbitmq/cli/queues/commands/check_if_node_is_mirror_sync_critical_command.ex
  deps/rabbitmq_cli/test/core/json_stream_test.exs
  deps/rabbitmq_cli/test/ctl/disable_vhost_deletion_protection_command_test.exs
  deps/rabbitmq_cli/test/ctl/enable_feature_flag_test.exs
  deps/rabbitmq_cli/test/ctl/enable_vhost_deletion_protection_command_test.exs
  deps/rabbitmq_cli/test/ctl/force_boot_command_test.exs
  deps/rabbitmq_cli/test/ctl/force_reset_command_test.exs
  deps/rabbitmq_cli/test/ctl/reset_command_test.exs
  deps/rabbitmq_cli/test/ctl/set_disk_free_limit_command_test.exs
  deps/rabbitmq_cli/test/ctl/update_vhost_metadata_command_test.exs
  deps/rabbitmq_cli/test/diagnostics/schema_info_command_test.exs
  deps/rabbitmq_ct_helpers/src/rabbit_ct_broker_helpers.erl
  deps/rabbitmq_ct_helpers/src/rabbit_mgmt_test_util.erl
  deps/rabbitmq_management/priv/www/api/index.html
  deps/rabbitmq_management/priv/www/js/tmpl/vhost.ejs
  deps/rabbitmq_management/src/rabbit_mgmt_dispatcher.erl
  deps/rabbitmq_management/src/rabbit_mgmt_util.erl
  deps/rabbitmq_management/src/rabbit_mgmt_wm_vhost.erl
  deps/rabbitmq_management/src/rabbit_mgmt_wm_vhost_deletion_protection.erl
  deps/rabbitmq_management/src/rabbit_mgmt_wm_vhosts.erl
  deps/rabbitmq_management/test/clustering_prop_SUITE.erl
  deps/rabbitmq_management/test/rabbit_mgmt_http_SUITE.erl
  deps/rabbitmq_management/test/rabbit_mgmt_http_health_checks_SUITE.erl
  deps/rabbitmq_management/test/rabbit_mgmt_http_vhost_deletion_protection_SUITE.erl
Labels: backport-v4.0.x

#13018 bazel run gazelle
  deps/rabbitmq_management/app.bzl
  moduleindex.yaml
Labels: bazel

#13019 bazel run gazelle
  deps/rabbitmq_management/app.bzl
  moduleindex.yaml
Labels: bazel

#13052 HTTP API: make GET /api/aliveness-test a no-op
  deps/rabbitmq_management/src/rabbit_mgmt_wm_aliveness_test.erl
Labels: backport-v4.0.x

#13063 Stream queue: consumers are active by default
  deps/rabbit/src/rabbit_stream_queue.erl
Labels: backport-v4.0.x

#13067 Allow InitialCredit/MoreCreditAfter of zero
  deps/rabbit/src/rabbit.erl
Labels: backport-v4.0.x

#13049 Ignore CLI info calls during stream connection initialization
  deps/rabbitmq_stream/src/rabbit_stream_reader.erl
Labels: bug, backport-v4.0.x

#13083 QQ: improve fifo client log message on leader change
  deps/rabbit/src/rabbit_fifo_client.erl
Labels: backport-v4.0.x

#13087 Fix return value of `rabbit_priority_queue:delete_crashed/1`
  deps/rabbit/src/rabbit_priority_queue.erl
Labels: backport-v4.0.x

#13090 HTTP API: format empty consumer.channel_details as an empty object
  deps/rabbitmq_management_agent/src/rabbit_mgmt_format.erl
Labels: backport-v4.0.x

#13069 Remove deprecated/unused/old startup checks
  deps/rabbit/BUILD.bazel
  deps/rabbit/Makefile
  deps/rabbit/app.bzl
  deps/rabbit/ct.test.spec
  deps/rabbit/src/rabbit.erl
  deps/rabbit/src/rabbit_variable_queue.erl
  deps/rabbit/test/msg_store_SUITE.erl
Labels: bazel, make, backport-v4.0.x

#13092 Emit cancellation event only when stream consumer is cancelled
  deps/rabbit/src/rabbit_stream_queue.erl
  deps/rabbitmq_stream/src/rabbit_stream_metrics.erl
  deps/rabbitmq_stream/src/rabbit_stream_reader.erl
Labels: backport-v4.0.x

#13105 Emit internal events on stream consume and cancel
  deps/rabbit/src/rabbit_stream_queue.erl
  deps/rabbit/test/rabbit_list_test_event_handler.erl
  deps/rabbit/test/rabbit_stream_queue_SUITE.erl
  deps/rabbitmq_stream/src/rabbit_stream_metrics.erl
  deps/rabbitmq_stream/src/rabbit_stream_reader.erl
  deps/rabbitmq_stream/test/rabbit_list_test_event_handler.erl
  deps/rabbitmq_stream/test/rabbit_stream_SUITE.erl
  deps/rabbitmq_stream/test/rabbit_stream_reader_SUITE.erl
Labels: bug, backport-v4.0.x

#13119 Fix wait-for-confirms sequence in stream test utils
  deps/rabbitmq_ct_helpers/src/stream_test_utils.erl
  deps/rabbitmq_prometheus/test/rabbit_prometheus_http_SUITE.erl
  deps/rabbitmq_stream/test/protocol_interop_SUITE.erl
  deps/rabbitmq_stream/test/rabbit_stream_SUITE.erl
Labels: backport-v4.0.x

#13122 bazel run gazelle
  deps/rabbit/BUILD.bazel
  deps/rabbit/app.bzl
  deps/rabbitmq_stream/BUILD.bazel
  deps/rabbitmq_stream/app.bzl
Labels: bazel

#13121 bazel run gazelle
  deps/rabbit/BUILD.bazel
  deps/rabbit/app.bzl
  deps/rabbitmq_stream/BUILD.bazel
  deps/rabbitmq_stream/app.bzl
Labels: bazel

#13095 QQ: resend pending commands when new leader detected on applied notif…
  deps/rabbit/src/rabbit_fifo_client.erl
  deps/rabbit/test/rabbit_fifo_int_SUITE.erl
Labels: backport-v4.0.x

#13127 Ra 2.15.1
  MODULE.bazel
  rabbitmq-components.mk
Labels: bazel, make, backport-v4.0.x

#13133 Test helpers: add `** killed` to the default find crashes ignore list
  deps/rabbitmq_ct_helpers/src/rabbit_ct_broker_helpers.erl
Labels: backport-v4.0.x

#13146 Return 404 in AMQP management queue purge for non-existing queue
  deps/rabbit/src/rabbit_amqp_management.erl
  deps/rabbitmq_amqp_client/test/management_SUITE.erl
Labels: usability, backport-v4.0.x

#13149 Log incorrectly claims the limit is per node,
  deps/rabbit/src/rabbit_runtime_parameters.erl
Labels: backport-v4.0.x

#13154 Log incorrectly claims the limit is per node, but the component count…
  deps/rabbit/src/rabbit_runtime_parameters.erl
  deps/rabbit/test/runtime_parameters_SUITE.erl
Labels: backport-v4.0.x

#13115 Support exchange federation with MQTT 5.0 subscribers
  deps/rabbit/src/rabbit_core_ff.erl
  deps/rabbitmq_mqtt/Makefile
  deps/rabbitmq_mqtt/src/rabbit_mqtt_processor.erl
  deps/rabbitmq_mqtt/test/feature_flag_SUITE.erl
  deps/rabbitmq_mqtt/test/federation_SUITE.erl
Labels: make

#13156 bazel run gazelle
  deps/rabbitmq_mqtt/app.bzl
Labels: bazel

#13164 bazel run gazelle
  deps/amqp10_client/BUILD.bazel
  deps/amqp10_client/app.bzl
  deps/rabbit/app.bzl
  deps/rabbitmq_ct_client_helpers/app.bzl
  deps/rabbitmq_web_mqtt/BUILD.bazel
  deps/rabbitmq_web_mqtt/app.bzl
  deps/rabbitmq_web_stomp/BUILD.bazel
  deps/rabbitmq_web_stomp/app.bzl
  moduleindex.yaml
Labels: bazel

#12713 Ra v2.16.0
  MODULE.bazel
  bazel/BUILD.ra
  deps/rabbit/src/rabbit_channel.erl
  deps/rabbit/src/rabbit_fifo.erl
  deps/rabbit/src/rabbit_fifo_client.erl
  deps/rabbit/src/rabbit_fifo_dlx.erl
  deps/rabbit/src/rabbit_queue_type_util.erl
  deps/rabbit/src/rabbit_quorum_queue.erl
  deps/rabbit/src/rabbit_stream_coordinator.erl
  deps/rabbit/test/quorum_queue_SUITE.erl
  deps/rabbit/test/rabbit_fifo_SUITE.erl
  deps/rabbit/test/rabbit_fifo_int_SUITE.erl
  deps/rabbitmq_management/priv/www/js/tmpl/channel.ejs
  rabbitmq-components.mk
Labels: bazel, make

#13166 QQ: make sure there are no duplicates on the list of nodes
  deps/rabbit/src/rabbit_quorum_queue.erl
Labels: backport-v4.0.x

#13170 bazel run gazelle
  deps/rabbitmq_management/BUILD.bazel
  deps/rabbitmq_management/app.bzl
  deps/rabbitmq_mqtt/BUILD.bazel
  moduleindex.yaml
Labels: bazel

#13177 Better metric description
  deps/rabbitmq_prometheus/src/collectors/prometheus_rabbitmq_core_metrics_collector.erl
Labels: backport-v4.0.x

#13176 bazel run gazelle
  deps/rabbitmq_management/app.bzl
  moduleindex.yaml
Labels: bazel

#13185 Switch AWS peer discovery test from Bazel to make
  .github/workflows/oci-make.yaml
  .github/workflows/peer-discovery-aws.yaml
  deps/rabbitmq_mqtt/test/packet_prop_SUITE.erl
  erlang.mk
Labels: make, backport-v4.0.x
