Repository rabbitmq/rabbitmq-server, pull requests merged in 2025-06, with the labels that each got.

#13941 Oauth2: Support variable expansion when checking resource access
  .github/workflows/test-authnz.yaml
  .github/workflows/test-management-ui-for-pr.yaml
  deps/rabbitmq_auth_backend_oauth2/src/rabbit_auth_backend_oauth2.erl
  deps/rabbitmq_auth_backend_oauth2/src/rabbit_oauth2_scope.erl
  deps/rabbitmq_auth_backend_oauth2/test/rabbit_auth_backend_oauth2_test_util.erl
  deps/rabbitmq_auth_backend_oauth2/test/system_SUITE.erl
  deps/rabbitmq_auth_backend_oauth2/test/unit_SUITE.erl
Labels: rabbitmq-auth-backend-oauth2, backport-v4.1.x

#13996 MQTT: disconnect consumer when queue is deleted
  deps/rabbitmq_mqtt/src/rabbit_mqtt_processor.erl
  deps/rabbitmq_mqtt/src/rabbit_mqtt_qos0_queue.erl
  deps/rabbitmq_mqtt/src/rabbit_mqtt_reader.erl
  deps/rabbitmq_mqtt/test/mqtt_shared_SUITE.erl
  deps/rabbitmq_web_mqtt/test/web_mqtt_shared_SUITE.erl
Labels: backport-v4.1.x

#14017 Adjust triggers for Selenium workflow
  .github/workflows/test-management-ui-for-pr.yaml
Labels: backport-v4.1.x

#13981 Management UI: fix MQTT qos0 queue [type] rendering
  deps/rabbitmq_management/priv/www/js/main.js
  selenium/full-suite-management-ui
  selenium/short-suite-management-ui
  selenium/suites/mgt/mqtt-connections.sh
  selenium/test/basic-auth/enabled_plugins
  selenium/test/connections/mqtt/list-connections.js
  selenium/test/exchanges/management.js
  selenium/test/mqtt.js
  selenium/test/queuesAndStreams/view-mqtt-qos0.js
  selenium/test/queuesAndStreams/view-qq-consumers.js
  selenium/test/utils.js
Labels: bug, rabbitmq-management

#14023 Wrap TLS options password into a function in more places
  deps/rabbit/src/rabbit_ssl.erl
  deps/rabbit/test/unit_rabbit_ssl_SUITE.erl
  deps/rabbit_common/src/rabbit_ssl_options.erl
  deps/rabbitmq_management/src/rabbit_mgmt_app.erl
  deps/rabbitmq_management/test/listener_config_SUITE.erl
  deps/rabbitmq_prometheus/src/rabbit_prometheus_app.erl
  deps/rabbitmq_web_dispatch/src/rabbit_web_dispatch_sup.erl
Labels: backport-v4.1.x

#14057 CT broker helpers: use rabbitmq-plugins from the given node with a secondary umbrella
  deps/rabbitmq_ct_helpers/src/rabbit_ct_broker_helpers.erl
Labels: backport-v4.1.x

#14060 Avoid using the size/1 BIF
  deps/amqp10_client/src/amqp10_client_frame_reader.erl
  deps/amqp10_client/src/amqp10_client_session.erl
  deps/amqp10_common/src/amqp10_binary_generator.erl
  deps/rabbit/src/rabbit_amqp_filtex.erl
  deps/rabbit/src/rabbit_amqp_reader.erl
  deps/rabbit/src/rabbit_queue_index.erl
Labels: backport-v4.1.x

#14066 Fix `export` module attribute
  deps/rabbitmq_amqp_client/src/rabbitmq_amqp_address.erl
Labels: backport-v4.1.x

#14088 Avoid list allocation
  deps/rabbit/src/rabbit_fifo.erl
Labels: backport-v4.1.x

#14081 Delete symlinks to `erlang.mk` and `rabbitmq-components.mk`
  deps/amqp10_client/Makefile
  deps/amqp10_client/erlang.mk
  deps/amqp10_client/rabbitmq-components.mk
  deps/amqp10_common/Makefile
  deps/amqp10_common/erlang.mk
  deps/amqp10_common/rabbitmq-components.mk
  deps/amqp_client/Makefile
  deps/amqp_client/erlang.mk
  deps/amqp_client/rabbitmq-components.mk
  deps/rabbit_common/Makefile
  deps/rabbit_common/erlang.mk
  deps/rabbit_common/rabbitmq-components.mk
Labels: make, backport-v4.1.x

#14097 Federation: update makefile to avoid dialyzer compilation errors
  deps/rabbitmq_federation/Makefile
Labels: make, backport-v4.1.x

#14106 Miscellaneous minor improvements in stream SAC coordinator
  deps/rabbit/src/rabbit_stream_coordinator.erl
  deps/rabbit/src/rabbit_stream_sac_coordinator.erl
  deps/rabbit/test/rabbit_stream_sac_coordinator_SUITE.erl
Labels: enhancement, backport-v4.1.x

#14109 Use module machine version for stream coordinator status
  deps/rabbit/src/rabbit_stream_coordinator.erl
Labels: bug, backport-v4.1.x

#14111 Bump ActiveMQ to v6.1.7
  deps/amqp10_client/Makefile
Labels: make, backport-v4.1.x

#14143 Close stream consumer log after stream is deleted or unavailable
  deps/rabbitmq_stream/src/rabbit_stream_reader.erl
Labels: bug, backport-v4.1.x

#14114 Improve Erlang/OTP 28 compatibility, use OTP 28 in the pipelines
  .github/workflows/oci-make.yaml
  .github/workflows/peer-discovery-aws.yaml
  .github/workflows/test-authnz.yaml
  .github/workflows/test-make-target.yaml
  .github/workflows/test-make-type-check.yaml
  .github/workflows/test-make.yaml
  .github/workflows/test-management-ui-for-pr.yaml
  .github/workflows/test-management-ui.yaml
  deps/rabbit/src/rabbit_networking.erl
  deps/rabbit/src/rabbit_reader.erl
  deps/rabbit/test/per_user_connection_tracking_SUITE.erl
  deps/rabbit/test/quorum_queue_SUITE.erl
  deps/rabbit/test/rabbit_fifo_prop_SUITE.erl
  deps/rabbit_common/Makefile
  deps/rabbit_common/src/rabbit_cert_info.erl
  deps/rabbit_common/src/rabbit_net.erl
  deps/rabbit_common/src/rabbit_routing_parser.erl
  deps/rabbitmq_cli/Makefile
  deps/rabbitmq_cli/test/ctl/set_permissions_command_test.exs
  deps/rabbitmq_cli/test/ctl/set_permissions_globally_command_test.exs
  deps/rabbitmq_cli/test/plugins/disable_plugins_command_test.exs
  deps/rabbitmq_ct_client_helpers/Makefile
  deps/rabbitmq_ct_client_helpers/src/rfc6455_client.erl
  deps/rabbitmq_management_agent/src/exometer_slide.erl
  deps/rabbitmq_stomp/Makefile
  deps/rabbitmq_stream/Makefile
  deps/rabbitmq_web_mqtt/Makefile
  erlang.mk
Labels: make

#14147 Display AMQP filters in Management UI
  deps/amqp10_client/include/amqp10_client.hrl
  deps/amqp10_client/src/amqp10_client.erl
  deps/amqp10_client/src/amqp10_client_connection.erl
  deps/amqp10_client/src/amqp10_client_frame_reader.erl
  deps/amqp10_client/src/amqp10_client_internal.hrl
  deps/amqp10_client/src/amqp10_client_session.erl
  deps/amqp10_client/test/mock_server.erl
  deps/amqp10_common/include/amqp10_filter.hrl
  deps/amqp10_common/include/amqp10_filtex.hrl
  deps/rabbit/Makefile
  deps/rabbit/src/mc.erl
  deps/rabbit/src/rabbit_amqp_filter.erl
  deps/rabbit/src/rabbit_amqp_filter_jms.erl
  deps/rabbit/src/rabbit_amqp_filter_prop.erl
  deps/rabbit/src/rabbit_amqp_session.erl
  deps/rabbit/src/rabbit_amqp_util.erl
  deps/rabbit/src/rabbit_jms_ast.erl
  deps/rabbit/src/rabbit_jms_selector_lexer.erl
  deps/rabbit/src/rabbit_jms_selector_lexer.xrl
  deps/rabbit/src/rabbit_jms_selector_parser.erl
  deps/rabbit/src/rabbit_jms_selector_parser.yrl
  deps/rabbit/src/rabbit_queue_type.erl
  deps/rabbit/src/rabbit_stream_queue.erl
  deps/rabbit/test/amqp_filter_prop_SUITE.erl
  deps/rabbit/test/amqp_filter_sql_SUITE.erl
  deps/rabbit/test/amqp_jms_unit_SUITE.erl
  deps/rabbitmq_management/priv/www/js/global.js
  deps/rabbitmq_management/priv/www/js/tmpl/sessions-list.ejs
  deps/rabbitmq_management/test/rabbit_mgmt_http_SUITE.erl
  deps/rabbitmq_stream/test/protocol_interop_SUITE.erl
  release-notes/4.2.0.md
Labels: make

#14150 cluster_minority_SUITE: Fix race in `remove_node_when_seed_node_is_leader`
  deps/rabbit/test/cluster_minority_SUITE.erl
Labels: backport-v4.1.x
