Repository rabbitmq/rabbitmq-server, pull requests merged in 2025-10, with the labels that each got.

#14573 Keep exclusive/auto-delete queues with Khepri + network partition
  deps/rabbit/src/rabbit_amqqueue.erl
  deps/rabbit/src/rabbit_amqqueue_process.erl
  deps/rabbit/src/rabbit_db_queue.erl
  deps/rabbit/src/rabbit_khepri.erl
  deps/rabbit/src/rabbit_mnesia.erl
  deps/rabbit/src/rabbit_node_monitor.erl
  deps/rabbit/test/bindings_SUITE.erl
  deps/rabbit/test/clustering_recovery_SUITE.erl
  deps/rabbit/test/rabbit_db_queue_SUITE.erl
Labels: backport-v4.2.x

#14653 Update Cowboy to 2.14.1
  rabbitmq-components.mk
Labels: make, backport-v4.2.x

#14662 Local shovel: ensure no more messages are published with delete-after
  deps/rabbitmq_shovel/src/rabbit_local_shovel.erl
Labels: bug, backport-v4.2.x

#14655 Remove all usage of `cacerts` from configuration schemas
  deps/rabbit/priv/schema/rabbit.schema
  deps/rabbitmq_auth_backend_http/priv/schema/rabbitmq_auth_backend_http.schema
  deps/rabbitmq_auth_backend_ldap/priv/schema/rabbitmq_auth_backend_ldap.schema
  deps/rabbitmq_management/priv/schema/rabbitmq_management.schema
  deps/rabbitmq_management_agent/src/rabbit_mgmt_format.erl
  deps/rabbitmq_peer_discovery_consul/priv/schema/rabbitmq_peer_discovery_consul.schema
  deps/rabbitmq_peer_discovery_etcd/priv/schema/rabbitmq_peer_discovery_etcd.schema
  deps/rabbitmq_prometheus/test/config_schema_SUITE_data/schema/rabbitmq_management.schema
  deps/rabbitmq_trust_store/priv/schema/rabbitmq_trust_store.schema
Labels: breaking-change, backport-v4.2.x

#14669 clustering_recovery_SUITE: Run on its own in CI
  .github/workflows/test-make-tests.yaml
  deps/rabbit/Makefile
Labels: make

#14660 amqp_client: Emit 'connection.blocked' in direct connections
  deps/amqp_client/src/amqp_gen_connection.erl
  deps/rabbit/src/rabbit_direct.erl
  deps/rabbitmq_shovel/test/amqp091_alarm_SUITE.erl
  deps/rabbitmq_shovel/test/amqp091_dynamic_SUITE.erl
  deps/rabbitmq_shovel/test/shovel_test_utils.erl
Labels: backport-v4.2.x
