Repository rabbitmq/rabbitmq-server, pull requests merged in 2025-09, with the labels that each got.

#14438 Fix issue where leader is not returned after stream declaration
  deps/rabbit/src/rabbit_stream_queue.erl
  deps/rabbit/test/amqp_client_SUITE.erl
Labels: backport-v4.1.x

#14450 Local shovels: fix handling of acks/nacks
  deps/rabbitmq_shovel/src/rabbit_local_shovel.erl
  deps/rabbitmq_shovel/src/rabbit_shovel_confirms.erl
  deps/rabbitmq_shovel/test/local_dynamic_cluster_SUITE.erl
Labels: backport-v4.2.x

#14499 make: Remove the parallel-ct target
  deps/rabbit/Makefile
  deps/rabbit/ct.test.spec
Labels: make, backport-v4.1.x, backport-v4.2.x

#14493 rabbit_fifo: Expose each smallest raft index in `overview/1`
  deps/rabbit/src/rabbit_fifo.erl
Labels: backport-v4.1.x, backport-v4.2.x

#14458 QQ: exclude delivery_limit from policy repair comparison.
  deps/rabbit/src/rabbit_quorum_queue.erl
Labels: backport-v4.1.x, backport-v4.2.x

#14507 Speed up Direct Reply-To
  deps/rabbit/src/rabbit_channel.erl
  deps/rabbit/src/rabbit_direct_reply_to.erl
  deps/rabbit/src/rabbit_nodes.erl
Labels: backport-v4.1.x, backport-v4.2.x

#14511 Additional JSON CLI formatter fix
  deps/rabbitmq_cli/lib/rabbitmq/cli/formatters/json.ex
  deps/rabbitmq_cli/test/json_formatting_test.exs
Labels: backport-v4.1.x, backport-v4.2.x

#14474 Support Direct Reply-To for AMQP 1.0
  .github/workflows/test-make-tests.yaml
  deps/amqp10_client/src/amqp10_client_session.erl
  deps/rabbit/Makefile
  deps/rabbit/src/mc_amqpl.erl
  deps/rabbit/src/pid_recomposition.erl
  deps/rabbit/src/rabbit.erl
  deps/rabbit/src/rabbit_amqp_management.erl
  deps/rabbit/src/rabbit_amqp_session.erl
  deps/rabbit/src/rabbit_channel.erl
  deps/rabbit/src/rabbit_classic_queue.erl
  deps/rabbit/src/rabbit_core_ff.erl
  deps/rabbit/src/rabbit_db_queue.erl
  deps/rabbit/src/rabbit_db_topic_exchange.erl
  deps/rabbit/src/rabbit_direct_reply_to.erl
  deps/rabbit/src/rabbit_exchange.erl
  deps/rabbit/src/rabbit_global_counters.erl
  deps/rabbit/src/rabbit_pid_codec.erl
  deps/rabbit/src/rabbit_queue_type.erl
  deps/rabbit/src/rabbit_quorum_queue.erl
  deps/rabbit/src/rabbit_stream_queue.erl
  deps/rabbit/src/rabbit_trace.erl
  deps/rabbit/src/rabbit_volatile_queue.erl
  deps/rabbit/test/amqp_auth_SUITE.erl
  deps/rabbit/test/amqp_client_SUITE.erl
  deps/rabbit/test/amqp_utils.erl
  deps/rabbit/test/direct_reply_to_amqp_SUITE.erl
  deps/rabbit/test/direct_reply_to_amqpl_SUITE.erl
  deps/rabbit/test/mc_unit_SUITE.erl
  deps/rabbit/test/queue_type_SUITE.erl
  deps/rabbit/test/rabbit_direct_reply_to_prop_SUITE.erl
  deps/rabbit_common/src/delegate.erl
  deps/rabbitmq_amqp_client/src/rabbitmq_amqp_address.erl
  deps/rabbitmq_mqtt/src/rabbit_mqtt_qos0_queue.erl
  deps/rabbitmq_shovel/test/amqp10_static_SUITE.erl
  deps/rabbitmq_shovel/test/local_static_SUITE.erl
Labels: make, backport-v4.2.x

#14569 Amqp10 shovel: retry with insufficient_credit error
  deps/rabbitmq_shovel/src/rabbit_amqp10_shovel.erl
Labels: backport-v4.2.x

#14189 Integrate Osiris reader optimizations for streams
  deps/rabbit/Makefile
  deps/rabbit/priv/schema/rabbit.schema
  deps/rabbit/src/rabbit_stream_queue.erl
  deps/rabbit/test/config_schema_SUITE_data/rabbit.snippets
  deps/rabbitmq_stream/src/rabbit_stream_reader.erl
  deps/rabbitmq_stream/test/rabbit_stream_SUITE.erl
  rabbitmq-components.mk
Labels: dependencies, streams, make, backport-v4.2.x

#14595 AWS plugin: enable Cuttlefish schema tests
  deps/rabbitmq_aws/Makefile
  deps/rabbitmq_aws/test/config_schema_SUITE.erl
  deps/rabbitmq_aws/test/config_schema_SUITE_data/rabbitmq_aws.snippets
Labels: make, backport-v4.2.x

#14559 Bump up version of ldap docker image used in selenium tests
  selenium/bin/components/mock-auth-backend-ldap
Labels: backport-v4.2.x

#14589 Quorum queues: fix resend issues after network partition
  deps/rabbit/src/rabbit_fifo.erl
  deps/rabbit/src/rabbit_fifo_client.erl
  deps/rabbit/test/quorum_queue_SUITE.erl
  deps/rabbit/test/rabbit_fifo_int_SUITE.erl
Labels: backport-v4.2.x

#14570 Reduce ETS copy overhead when delivering to target queues
  deps/rabbit/src/amqqueue.erl
  deps/rabbit/src/rabbit_amqp_session.erl
  deps/rabbit/src/rabbit_amqqueue.erl
  deps/rabbit/src/rabbit_channel.erl
  deps/rabbit/src/rabbit_classic_queue.erl
  deps/rabbit/src/rabbit_db_queue.erl
  deps/rabbit/src/rabbit_dead_letter.erl
  deps/rabbit/src/rabbit_fifo_dlx_worker.erl
  deps/rabbit/src/rabbit_khepri.erl
  deps/rabbit/src/rabbit_queue_type.erl
  deps/rabbit/src/rabbit_quorum_queue.erl
  deps/rabbit/src/rabbit_stream_coordinator.erl
  deps/rabbit/src/rabbit_stream_queue.erl
  deps/rabbit/src/rabbit_volatile_queue.erl
  deps/rabbit/test/rabbit_db_queue_SUITE.erl
  deps/rabbitmq_management/test/clustering_SUITE.erl
  deps/rabbitmq_mqtt/src/rabbit_mqtt_processor.erl
  deps/rabbitmq_mqtt/src/rabbit_mqtt_qos0_queue.erl
  deps/rabbitmq_recent_history_exchange/src/rabbit_exchange_type_recent_history.erl
  deps/rabbitmq_shovel/src/rabbit_local_shovel.erl
Labels: backport-v4.2.x

#14610 Remove `update/2` callback from `rabbit_queue_type`
  deps/rabbit/src/rabbit_classic_queue.erl
  deps/rabbit/src/rabbit_queue_type.erl
  deps/rabbit/src/rabbit_quorum_queue.erl
  deps/rabbit/src/rabbit_stream_queue.erl
  deps/rabbit/src/rabbit_volatile_queue.erl
  deps/rabbitmq_mqtt/src/rabbit_mqtt_qos0_queue.erl
Labels: backport-v4.2.x

#14577 Add `NON_DETERMINISTIC` make variable
  deps/rabbit/Makefile
  deps/rabbit_common/mk/rabbitmq-build.mk
Labels: make

#14616 AMQP1.0 client: Support HTTP/2 Websocket
  deps/amqp10_client/src/amqp10_client_socket.erl
Labels: backport-v4.2.x
