Repository rabbitmq/rabbitmq-server, pull requests merged in 2025-04, with the labels that each got.

#13643 Allow a previously reset node to rejoin its original cluster
  deps/rabbit/src/rabbit_db_cluster.erl
  deps/rabbit/src/rabbit_mnesia.erl
Labels: backport-v4.0.x, backport-v4.1.x

#13673 Added 'unlimited' config setting for peer_discovery_retry_limit
  deps/rabbit/priv/schema/rabbit.schema
  deps/rabbit/test/config_schema_SUITE_data/rabbit.snippets
Labels: backport-v4.0.x, backport-v4.1.x

#13674 Ignore stream connections in unexpected states
  deps/rabbitmq_stream/src/rabbit_stream_reader.erl
Labels: backport-v4.0.x, backport-v4.1.x

#13686 Update khepri_mnesia_migration from 0.7.1 to 0.7.2
  deps/rabbit/test/quorum_queue_SUITE.erl
  rabbitmq-components.mk
Labels: make

#13705 Update Ra from 2.16.6 to 2.16.7
  rabbitmq-components.mk
Labels: make, backport-v4.1.x

#13701 Avoid crash when reporting federation status
  deps/rabbitmq_federation_management/src/rabbit_federation_mgmt.erl
Labels: backport-v4.0.x, backport-v4.1.x

#13685 Upstream changes from Tanzu RabbitMQ's Selenium suite
  selenium/bin/components/devkeycloak-proxy
  selenium/bin/components/forward-proxy
  selenium/bin/components/keycloak
  selenium/bin/components/prodkeycloak-proxy
  selenium/bin/components/rabbitmq
  selenium/bin/suite_template
  selenium/test/basic-auth/ac-management.js
  selenium/test/basic-auth/unauthorized.js
  selenium/test/oauth/env.docker.keycloak
  selenium/test/oauth/env.keycloak-oauth-provider
  selenium/test/oauth/env.local.keycloak
  selenium/test/oauth/imports/users.json
  selenium/test/oauth/rabbitmq.keycloak-mgt-oauth-provider.conf
  selenium/test/oauth/rabbitmq.keycloak-oauth-provider.conf
  selenium/test/oauth/rabbitmq.keycloak-verify-none-oauth-provider.conf
  selenium/test/oauth/rabbitmq.uaa-mgt-oauth-provider.conf
  selenium/test/oauth/rabbitmq.uaa-oauth-provider.conf
  selenium/test/oauth/with-sp-initiated/redirection-after-login.js
  selenium/test/oauth/with-sp-initiated/unauthorized.js
  selenium/test/pageobjects/BasePage.js
  selenium/test/utils.js
Labels: backport-v4.1.x

#13703 QQ: handle tick tweaks
  deps/rabbit/src/rabbit_quorum_queue.erl
Labels: backport-v4.1.x

#13698 Add new option require_auth_for_api_desc_page to mgmt
  deps/rabbitmq_management/Makefile
  deps/rabbitmq_management/priv/schema/rabbitmq_management.schema
  deps/rabbitmq_management/src/rabbit_mgmt_wm_static.erl
  deps/rabbitmq_management/test/config_schema_SUITE_data/rabbitmq_management.snippets
Labels: make, backport-v4.0.x, backport-v4.1.x

#12753 Bump Khepri to 0.17.0
  .github/workflows/test-make-target.yaml
  deps/rabbit/src/rabbit_db_binding.erl
  deps/rabbit/src/rabbit_db_exchange.erl
  deps/rabbit/src/rabbit_db_msup.erl
  deps/rabbit/src/rabbit_db_queue.erl
  deps/rabbit/src/rabbit_db_rtparams.erl
  deps/rabbit/src/rabbit_db_user.erl
  deps/rabbit/src/rabbit_db_vhost.erl
  deps/rabbit/src/rabbit_khepri.erl
  deps/rabbit/test/cluster_minority_SUITE.erl
  deps/rabbit/test/clustering_management_SUITE.erl
  deps/rabbit/test/peer_discovery_classic_config_SUITE.erl
  deps/rabbit/test/quorum_queue_SUITE.erl
  deps/rabbit/test/rabbit_stream_queue_SUITE.erl
  deps/rabbitmq_consistent_hash_exchange/src/rabbit_db_ch_exchange.erl
  deps/rabbitmq_ct_helpers/src/rabbit_ct_broker_helpers.erl
  deps/rabbitmq_federation/test/exchange_SUITE.erl
  deps/rabbitmq_jms_topic_exchange/src/rabbit_db_jms_exchange.erl
  deps/rabbitmq_mqtt/test/mqtt_shared_SUITE.erl
  deps/rabbitmq_recent_history_exchange/src/rabbit_db_rh_exchange.erl
  deps/rabbitmq_shovel/test/rolling_upgrade_SUITE.erl
  rabbitmq-components.mk
Labels: make

#13727 Fix concurrent AMQP queue declarations
  deps/rabbit/src/rabbit_amqp_management.erl
  deps/rabbitmq_amqp_client/test/management_SUITE.erl
Labels: bug, backport-v4.0.x, backport-v4.1.x

#13723 Remove log level tests
  deps/rabbit/src/rabbit_prelaunch_logging.erl
Labels: backport-v4.0.x, backport-v4.1.x

#13726 Osiris v1.8.7
  rabbitmq-components.mk
Labels: make, backport-v4.0.x, backport-v4.1.x

#13735 Ra 2.16.8
  rabbitmq-components.mk
Labels: make, backport-v4.1.x

#13756 [skip-ci] Additional Prometheus-related release notes
  release-notes/4.1.0.md
Labels: backport-v4.1.x

#13765 [skip ci] Grafana: update dashboards for RabbitMQ 4.1.x
  deps/rabbitmq_prometheus/docker/grafana/dashboards/Erlang-Distribution.json
  deps/rabbitmq_prometheus/docker/grafana/dashboards/Erlang-Distributions-Compare.json
  deps/rabbitmq_prometheus/docker/grafana/dashboards/Erlang-Memory-Allocators.json
  deps/rabbitmq_prometheus/docker/grafana/dashboards/RabbitMQ-Overview.json
  deps/rabbitmq_prometheus/docker/grafana/dashboards/RabbitMQ-Quorum-Queues-Raft.json
  deps/rabbitmq_prometheus/docker/grafana/dashboards/RabbitMQ-Stream.json
Labels: backport-v4.1.x

#13771 CQ: Fix rare eof crash of message store with fanout
  deps/rabbit/src/rabbit_msg_store.erl
  deps/rabbit/test/backing_queue_SUITE.erl
Labels: backport-v4.1.x

#12682 Khepri: Mark `khepri_db` feature flag as stable
  deps/rabbit/src/rabbit_core_ff.erl
  deps/rabbit/test/rabbitmq_4_0_deprecations_SUITE.erl
  deps/rabbitmq_cli/test/ctl/force_reset_command_test.exs
Labels: bazel, make

#13787 Add queues and streams page and test suite
  deps/rabbitmq_management/priv/www/js/tmpl/queue.ejs
  deps/rabbitmq_management/priv/www/js/tmpl/queues.ejs
  selenium/full-suite-management-ui
  selenium/short-suite-management-ui
  selenium/suites/mgt/queuesAndStreams.sh
  selenium/test/pageobjects/BasePage.js
  selenium/test/pageobjects/QueuePage.js
  selenium/test/pageobjects/QueuesAndStreamsPage.js
  selenium/test/pageobjects/StreamPage.js
  selenium/test/queuesAndStreams/add-classic.js
  selenium/test/queuesAndStreams/add-quorum.js
  selenium/test/queuesAndStreams/add-stream.js
  selenium/test/queuesAndStreams/list.js
  selenium/test/utils.js
Labels: backport-v4.1.x

#13818 By @aaron-seo: Adds a new auth backend that only accepts loopback connections
  .gitignore
  Makefile
  deps/rabbit/src/rabbit_auth_mechanism_plain.erl
  deps/rabbitmq_auth_backend_http/src/rabbit_auth_backend_http.erl
  deps/rabbitmq_auth_backend_internal_loopback/.gitignore
  deps/rabbitmq_auth_backend_internal_loopback/CODE_OF_CONDUCT.md
  deps/rabbitmq_auth_backend_internal_loopback/CONTRIBUTING.md
  deps/rabbitmq_auth_backend_internal_loopback/LICENSE
  deps/rabbitmq_auth_backend_internal_loopback/LICENSE-MPL-RabbitMQ
  deps/rabbitmq_auth_backend_internal_loopback/Makefile
  deps/rabbitmq_auth_backend_internal_loopback/README.md
  deps/rabbitmq_auth_backend_internal_loopback/schema/rabbitmq_auth_backend_internal_loopback.schema
  deps/rabbitmq_auth_backend_internal_loopback/src/rabbit_auth_backend_internal_loopback.erl
  deps/rabbitmq_auth_backend_internal_loopback/src/rabbit_auth_backend_internal_loopback_app.erl
  deps/rabbitmq_auth_backend_internal_loopback/test/rabbit_auth_backend_internal_loopback_SUITE.erl
  deps/rabbitmq_web_dispatch/priv/schema/rabbitmq_web_dispatch.schema
  deps/rabbitmq_web_dispatch/src/rabbit_web_dispatch_access_control.erl
  plugins.mk
  rabbitmq-components.mk
Labels: make, backport-v4.1.x

#13822 Remove unused Javascript functions
  deps/rabbitmq_management/priv/www/js/main.js
Labels: backport-v4.1.x
