Repository rabbitmq/rabbitmq-server, pull requests merged in 2025-05, with the labels that each got.

#13838 Test management ui selection of vhost's tags columns
  deps/rabbitmq_management/priv/www/js/tmpl/popup.ejs
  deps/rabbitmq_management/priv/www/js/tmpl/vhosts.ejs
  selenium/.node-xmlhttprequest-sync-88011
  selenium/test/exchanges/management.js
  selenium/test/mgt-api.js
  selenium/test/pageobjects/BasePage.js
  selenium/test/pageobjects/VhostsAdminTab.js
  selenium/test/queuesAndStreams/list.js
  selenium/test/utils.js
  selenium/test/vhosts/admin-vhosts.js
Labels: backport-v4.1.x

#13837 Modify default queue type injection logic
  deps/rabbit/src/rabbit_definitions.erl
  deps/rabbit/src/rabbit_vhost.erl
  deps/rabbit/src/vhost.erl
  deps/rabbit/test/vhost_SUITE.erl
  deps/rabbitmq_management/src/rabbit_mgmt_wm_definitions.erl
  deps/rabbitmq_management/test/rabbit_mgmt_http_SUITE.erl
Labels: backport-v4.1.x

#13850 STOMP: queue type tests - add queue.type assertions
  deps/rabbitmq_stomp/Makefile
  deps/rabbitmq_stomp/test/python_SUITE.erl
  deps/rabbitmq_stomp/test/python_SUITE_data/src/requirements.txt
  deps/rabbitmq_stomp/test/python_SUITE_data/src/x_queue_type_quorum.py
  deps/rabbitmq_stomp/test/python_SUITE_data/src/x_queue_type_stream.py
Labels: make, backport-v4.1.x

#13858 STOMP: confirm utf-8 handling
  deps/rabbitmq_stomp/test/frame_SUITE.erl
  deps/rabbitmq_stomp/test/python_SUITE_data/src/parsing.py
Labels: backport-v4.1.x

#13857 Fix partition index conflict in stream SAC coordinator
  deps/rabbit/src/rabbit_stream_sac_coordinator.erl
  deps/rabbit/test/rabbit_stream_sac_coordinator_SUITE.erl
  deps/rabbitmq_stream/src/rabbit_stream_reader.erl
  deps/rabbitmq_stream/test/rabbit_stream_SUITE.erl
Labels: backport-v4.1.x

#13848 Add several functions to mgt-api.js for wsr testing with selenium
  selenium/.node-xmlhttprequest-sync-88011
  selenium/bin/components/other-rabbitmq
  selenium/bin/components/rabbitmq
  selenium/bin/suite_template
  selenium/fakeportal/proxy.js
  selenium/test/amqp.js
  selenium/test/authnz-msg-protocols/amqp10.js
  selenium/test/authnz-msg-protocols/mqtt.js
  selenium/test/exchanges/management.js
  selenium/test/mgt-api.js
  selenium/test/oauth/with-idp-initiated/happy-login.js
  selenium/test/oauth/with-sp-initiated/happy-login.js
  selenium/test/oauth/with-sp-initiated/landing.js
  selenium/test/oauth/with-sp-initiated/logout.js
  selenium/test/oauth/with-sp-initiated/token-refresh.js
  selenium/test/oauth/with-sp-initiated/unauthorized.js
  selenium/test/pageobjects/BasePage.js
  selenium/test/pageobjects/LimitsAdminTab.js
  selenium/test/pageobjects/LoginPage.js
  selenium/test/pageobjects/QueuePage.js
  selenium/test/pageobjects/QueuesAndStreamsPage.js
  selenium/test/pageobjects/SSOHomePage.js
  selenium/test/pageobjects/StreamPage.js
  selenium/test/utils.js
Labels: backport-v4.1.x

#13861 Move `file_handle_cache` and `vm_memory_monitor` back to `rabbit`
  deps/rabbit/include/rabbit_memory.hrl
  deps/rabbit/src/file_handle_cache.erl
  deps/rabbit/src/vm_memory_monitor.erl
  deps/rabbit/test/unit_vm_memory_monitor_SUITE.erl
  deps/rabbit_common/Makefile
  deps/rabbit_common/test/unit_SUITE.erl
Labels: make, backport-v4.1.x

#13856 Make empty CQ init faster in case of clean shutdown
  deps/rabbit/src/rabbit_classic_queue_index_v2.erl
  deps/rabbit/src/rabbit_variable_queue.erl
  deps/rabbit/test/backing_queue_SUITE.erl
Labels: backport-v4.1.x

#13871 Allow multiple protocols in protocol listener health check
  deps/rabbitmq_management/priv/www/api/index.html
  deps/rabbitmq_management/src/rabbit_mgmt_dispatcher.erl
  deps/rabbitmq_management/src/rabbit_mgmt_wm_health_check_protocol_listener.erl
  deps/rabbitmq_management/test/rabbit_mgmt_http_health_checks_SUITE.erl
Labels: backport-v4.1.x

#13872 Add an 'is-in-service' health check wrapping `rabbit:is_serving/0`
  deps/rabbitmq_management/priv/www/api/index.html
  deps/rabbitmq_management/src/rabbit_mgmt_dispatcher.erl
  deps/rabbitmq_management/src/rabbit_mgmt_wm_health_check_is_in_service.erl
  deps/rabbitmq_management/test/rabbit_mgmt_http_health_checks_SUITE.erl
Labels: backport-v4.1.x

#13868 Fix selenium issues when running two rabbitmq
  selenium/bin/components/rabbitmq
  selenium/bin/suite_template
  selenium/fakeportal/proxy.js
  selenium/suites/mgt/mgt-only-exchanges.sh
  selenium/test/basic-auth/env.disable-metrics
  selenium/test/exchanges/management.js
  selenium/test/mgt-only/enabled_plugins
  selenium/test/mgt-only/imports/users.json
  selenium/test/mgt-only/logging.conf
  selenium/test/mgt-only/rabbitmq.conf
  selenium/test/multi-oauth/rabbitmq.enable-basic-auth.conf
  selenium/test/oauth/rabbitmq.load-user-definitions.conf
  selenium/test/pageobjects/BasePage.js
  selenium/test/pageobjects/VhostsAdminTab.js
  selenium/test/vhosts/admin-vhosts.js
Labels: backport-v4.1.x

#13879 Add health checks for testing readiness to serve clients
  deps/rabbitmq_management/priv/www/api/index.html
  deps/rabbitmq_management/src/rabbit_mgmt_dispatcher.erl
  deps/rabbitmq_management/src/rabbit_mgmt_wm_health_check_below_node_connection_limit.erl
  deps/rabbitmq_management/src/rabbit_mgmt_wm_health_check_ready_to_serve_clients.erl
  deps/rabbitmq_management/test/rabbit_mgmt_http_health_checks_SUITE.erl
Labels: backport-v4.1.x

#13878 Wait until page is fully loaded
  selenium/test/vhosts/admin-vhosts.js
Labels: backport-v4.1.x

#13888 Remove connection counts and limits from API health checks
  deps/rabbitmq_management/src/rabbit_mgmt_wm_health_check_below_node_connection_limit.erl
  deps/rabbitmq_management/src/rabbit_mgmt_wm_health_check_ready_to_serve_clients.erl
  deps/rabbitmq_management/test/rabbit_mgmt_http_health_checks_SUITE.erl
Labels: backport-v4.1.x

#13898 Improve memory use of `rabbit_mgmt_gc`
  deps/rabbitmq_management_agent/src/rabbit_mgmt_gc.erl
Labels: backport-v4.1.x

#13899 Allow non-deterministic builds
  deps/rabbit_common/mk/rabbitmq-build.mk
Labels: make, backport-v4.1.x

#13913 Bump Ra to 2.16.9
  rabbitmq-components.mk
Labels: make, backport-v4.1.x

#13916 OTP28: re:split change; street-address macro
  deps/rabbit_common/src/rabbit_cert_info.erl
  deps/rabbitmq_auth_backend_oauth2/Makefile
  deps/rabbitmq_mqtt/src/rabbit_mqtt_processor.erl
Labels: make, backport-v4.1.x

#13918 Follow AMQP spec for durable field
  deps/amqp10_client/src/amqp10_msg.erl
  deps/rabbit/src/mc_amqp.erl
  deps/rabbit/test/amqp_client_SUITE.erl
  release-notes/4.2.0.md
Labels: breaking-change

#13920 Add a proptest checking `ra_indexes` indices
  deps/rabbit/src/rabbit_fifo_index.erl
  deps/rabbit/test/rabbit_fifo_prop_SUITE.erl
Labels: backport-v4.1.x

#13925 Bump up chrome driver
  selenium/README.md
  selenium/package.json
  selenium/test/connections/amqp10/sessions-for-monitoring-user.js
  selenium/test/pageobjects/ConnectionPage.js
Labels: backport-v4.1.x

#13931 Fix selenium issue closing popup warning dialog since recent upgrade
  selenium/test/pageobjects/BasePage.js
  selenium/test/utils.js
Labels: backport-v4.1.x

#13932 Add tests for rabbit_classic_queue_index_v2:bounds/2
  deps/rabbit/src/rabbit_classic_queue_index_v2.erl
  deps/rabbit/test/backing_queue_SUITE.erl
Labels: backport-v4.1.x

#13548 For 4.1.x, by @aaron-seo: introduce a command that would force QQs to take a checkpoint and truncate its segments
  deps/rabbit/src/rabbit_quorum_queue.erl
  deps/rabbit/test/quorum_queue_SUITE.erl
  deps/rabbitmq_cli/lib/rabbitmq/cli/queues/commands/force_checkpoint_command.ex
  deps/rabbitmq_cli/test/queues/force_checkpoint_command_test.exs
Labels: backport-v4.1.x

#13947 Run rabbit_ct_hook before cth_styledout so that removing default logger handler works
  deps/rabbit/Makefile
  deps/rabbit/test/amqp_utils.erl
  deps/rabbit/test/peer_discovery_tmp_hidden_node_SUITE.erl
  deps/rabbit/test/policy_SUITE.erl
  deps/rabbit_common/mk/rabbitmq-early-plugin.mk
  deps/rabbitmq_ct_helpers/src/ct_master_fork.erl
  deps/rabbitmq_ct_helpers/src/rabbit_control_helper.erl
  deps/rabbitmq_ct_helpers/src/rabbit_ct_broker_helpers.erl
  deps/rabbitmq_ct_helpers/src/rabbit_ct_hook.erl
  deps/rabbitmq_management/Makefile
  deps/rabbitmq_mqtt/Makefile
Labels: make

#13963 Selenium: minor refactoring
  .github/workflows/test-authnz.yaml
  .github/workflows/test-management-ui-for-pr.yaml
  .github/workflows/test-management-ui.yaml
  selenium/bin/suite_template
  selenium/run-suites.sh
  selenium/test/connections/amqp10/sessions-for-monitoring-user.js
  selenium/test/exchanges/management.js
  selenium/test/queuesAndStreams/list.js
  selenium/test/queuesAndStreams/view-qq-consumers.js
  selenium/test/utils.js
  selenium/test/vhosts/admin-vhosts.js
Labels: backport-v4.1.x
