Repository rabbitmq/rabbitmq-server, pull requests merged in 2025-08, with the labels that each got.

#14321 Introduce a few new rabbit_plugins and rabbit_nodes functions
  deps/rabbit/src/rabbit_nodes.erl
  deps/rabbit/src/rabbit_plugins.erl
  deps/rabbit/test/unit_plugin_directories_SUITE.erl
Labels: backport-v4.1.x

#14304 Add a configurable limit for number of exchanges
  deps/rabbit/priv/schema/rabbit.schema
  deps/rabbit/src/rabbit_db_exchange.erl
  deps/rabbit/src/rabbit_exchange.erl
  deps/rabbit/test/cluster_limit_SUITE.erl
Labels: backport-v4.1.x

#14310 Collection of test fixes (2025Q2, batch 2)
  .github/workflows/test-make-target.yaml
  deps/rabbit/src/rabbit_vhosts.erl
  deps/rabbit/test/amqp_client_SUITE.erl
  deps/rabbit/test/amqp_filter_sql_SUITE.erl
  deps/rabbit/test/amqp_jms_SUITE.erl
  deps/rabbit/test/amqp_utils.erl
  deps/rabbit/test/feature_flags_v2_SUITE.erl
  deps/rabbit/test/per_user_connection_channel_tracking_SUITE.erl
  deps/rabbit/test/per_user_connection_tracking_SUITE.erl
  deps/rabbit/test/proxy_protocol_SUITE.erl
  deps/rabbit/test/rabbit_fifo_dlx_integration_SUITE.erl
  deps/rabbitmq_auth_backend_oauth2/test/jwks_SUITE.erl
  deps/rabbitmq_cli/.gitignore
  deps/rabbitmq_cli/Makefile
  deps/rabbitmq_consistent_hash_exchange/test/rabbit_exchange_type_consistent_hash_SUITE.erl
  deps/rabbitmq_mqtt/test/auth_SUITE.erl
  deps/rabbitmq_mqtt/test/cluster_SUITE.erl
  deps/rabbitmq_mqtt/test/mqtt_shared_SUITE.erl
  deps/rabbitmq_prometheus/test/rabbit_prometheus_http_SUITE.erl
  deps/rabbitmq_shovel/test/amqp10_inter_cluster_SUITE.erl
  deps/rabbitmq_stomp/test/python_SUITE_data/src/base.py
  deps/rabbitmq_stomp/test/python_SUITE_data/src/requirements.txt
  deps/rabbitmq_stomp/test/python_SUITE_data/src/test_runner.py
  deps/rabbitmq_stomp/test/python_SUITE_data/src/x_queue_name.py
  deps/rabbitmq_stream/test/rabbit_stream_partitions_SUITE.erl
  deps/rabbitmq_stream_management/test/http_SUITE_data/Makefile
Labels: make

#14344 Use advertised TLS host setting in metadata frame
  deps/rabbitmq_stream/src/rabbit_stream.erl
  deps/rabbitmq_stream/src/rabbit_stream_reader.erl
  deps/rabbitmq_stream/src/rabbit_stream_utils.hrl
  deps/rabbitmq_stream/test/rabbit_stream_SUITE.erl
Labels: bug, backport-v4.1.x

#14359 rabbit_access_control: Check configured auth backends are enabled at boot time
  deps/rabbit/src/rabbit.erl
  deps/rabbit/src/rabbit_access_control.erl
  deps/rabbit/src/rabbit_plugins.erl
  deps/rabbit/test/rabbit_access_control_SUITE.erl
  deps/rabbit/test/rabbit_access_control_SUITE_data/my_auth_plugin/Makefile
  deps/rabbit/test/rabbit_access_control_SUITE_data/my_auth_plugin/src/my_auth_plugin.erl
Labels: make

#14399 Make rabbit_ct_broker_helpers:configure_metadata_store/1 handle relative feature flag op lists
  deps/rabbitmq_ct_helpers/src/rabbit_ct_broker_helpers.erl
Labels: backport-v4.1.x

#14410 Add RABBITMQ_MAX_OPEN_FILES variable to the startup script
  deps/rabbit/scripts/rabbitmq-server
Labels: backport-v4.1.x

#14415 Shovel amqp1.0: fix delete after validation
  deps/rabbitmq_shovel/src/rabbit_shovel_parameters.erl
  deps/rabbitmq_shovel/test/amqp10_dynamic_SUITE.erl
Labels: backport-v4.1.x

#14444 Ensure that file modified time is set correctly
  Makefile
Labels: make
