Repository rabbitmq/rabbitmq-server, pull requests merged in 2025-07, with the labels that each got.

#14172 Add activate consumer and list tracking to rabbitmq-streams man page
  deps/rabbit/docs/rabbitmq-streams.8
Labels: doc, backport-v4.1.x

#14178 CQ: Retry opening write file when writing messages
  deps/rabbit/src/rabbit_classic_queue_index_v2.erl
  deps/rabbit/src/rabbit_classic_queue_store_v2.erl
  deps/rabbit/src/rabbit_file.erl
Labels: backport-v4.1.x

#14198 Polish stream Java test projects
  deps/rabbitmq_stream/test/rabbit_stream_SUITE_data/pom.xml
  deps/rabbitmq_stream/test/rabbit_stream_SUITE_data/src/test/java/com/rabbitmq/stream/ClusterSizeTest.java
  deps/rabbitmq_stream/test/rabbit_stream_SUITE_data/src/test/java/com/rabbitmq/stream/FailureTest.java
  deps/rabbitmq_stream/test/rabbit_stream_SUITE_data/src/test/java/com/rabbitmq/stream/Host.java
  deps/rabbitmq_stream/test/rabbit_stream_SUITE_data/src/test/java/com/rabbitmq/stream/LeaderLocatorTest.java
  deps/rabbitmq_stream/test/rabbit_stream_SUITE_data/src/test/java/com/rabbitmq/stream/StreamTest.java
  deps/rabbitmq_stream/test/rabbit_stream_SUITE_data/src/test/java/com/rabbitmq/stream/TestUtils.java
  deps/rabbitmq_stream_management/test/http_SUITE_data/pom.xml
  deps/rabbitmq_stream_management/test/http_SUITE_data/src/test/java/com/rabbitmq/stream/HttpTest.java
  deps/rabbitmq_stream_management/test/http_SUITE_data/src/test/java/com/rabbitmq/stream/TestUtils.java
Labels: backport-v4.1.x

#14210 Minor: Don't use Mnesia in rabbitmq_mqtt/test/processor_SUITE
  deps/rabbitmq_mqtt/src/rabbit_mqtt_processor.erl
  deps/rabbitmq_mqtt/test/processor_SUITE.erl
Labels: backport-v4.1.x

#14235 Fix flake in stream plugin test suite
  deps/rabbitmq_stream/test/rabbit_stream_partitions_SUITE.erl
Labels: backport-v4.1.x

#14240 Increase timeouts and improve error logging in stream test
  deps/rabbitmq_ct_helpers/src/stream_test_utils.erl
  deps/rabbitmq_stream/src/rabbit_stream_reader.erl
  deps/rabbitmq_stream/test/rabbit_stream_SUITE.erl
  deps/rabbitmq_stream/test/rabbit_stream_SUITE_data/src/test/java/com/rabbitmq/stream/FailureTest.java
  deps/rabbitmq_stream/test/rabbit_stream_SUITE_data/src/test/resources/logback-test.xml
Labels: backport-v4.1.x

#14252 Ra v2.16.12
  rabbitmq-components.mk
Labels: make, backport-v4.1.x

#14190 Very minor: Remove outdated comment from rabbit_msg_store
  deps/rabbit/src/rabbit_msg_store.erl
Labels: backport-v4.1.x

#14265 Remove awkward IO.inspect/1 in rabbitmqctl status command
  deps/rabbitmq_cli/lib/rabbitmq/cli/ctl/commands/status_command.ex
Labels: backport-v4.1.x

#14270 Introduce rabbit_ct_helpers:await_condition_* helpers which ignore exceptions
  deps/rabbitmq_ct_helpers/src/rabbit_ct_helpers.erl
Labels: backport-v4.1.x

#14278 rabbitmqctl shovel_status: handle metrics
  deps/rabbitmq_shovel/src/Elixir.RabbitMQ.CLI.Ctl.Commands.ShovelStatusCommand.erl
  deps/rabbitmq_shovel/test/shovel_status_command_SUITE.erl
Labels: bug, backport-v4.1.x

#14317 Fix channel number reuse
  deps/rabbit/src/rabbit_amqp_reader.erl
  deps/rabbit/src/rabbit_amqp_session.erl
Labels: bug, backport-v4.1.x
